### ISSUE TITLE
[androidtv] googletv.GoogleTVMessageParser GoogleTV Error Message

### ISSUE THREAD

**Issue by MichaelHeimann** [openhab/openhab-addons#15153] opened 2023-06-28 15:55 UTC
## Expected Behavior
Not Spam Logs.
Connect to shield successfully

## Current Behavior
I'm getting 11 Messages in the openhab.log every second (!) like this:

`2023-06-28 17:34:04.913 [WARN ] [tocol.googletv.GoogleTVMessageParser] - dd406711 - GoogleTV Error Message: 1a5d080312590a5708fe0412520a08534d2d4739393855120773616d73756e671801220231332a19636f6d2e676f6f676c652e616e64726f69642e766964656f73321c342e33392e3538342e3532393538383538332e372d72656c65617365`

I've reinstalled the addon from marketplace or manual via latest jar and it first shows this:

```
2023-06-28 17:34:04.776 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Login Successful to SHIELD
2023-06-28 17:34:04.833 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Message Parser Caught Exception
java.lang.ArrayIndexOutOfBoundsException: Index 124 out of bounds for length 124
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVMessageParser.handleMessage(ShieldTVMessageParser.java:132) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.finishReaderMessage(ShieldTVConnectionManager.java:738) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.readerThreadJob(ShieldTVConnectionManager.java:777) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

and then the spam of the error messages begins.

Also: this is from events.log:

```
2023-06-28 17:49:26.665 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'androidtv:shieldtv:dd406711' changed from OFFLINE: GoogleTV: Initializing | ShieldTV: ONLINE to OFFLINE: GoogleTV: reconnecting | ShieldTV: ONLINE
2023-06-28 17:49:26.702 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'androidtv:shieldtv:dd406711' changed from OFFLINE: GoogleTV: reconnecting | ShieldTV: ONLINE to OFFLINE: GoogleTV: Initializing | ShieldTV: ONLINE
```

## Possible Solution
ratelimit the same log message.
Fix the underlying issue would also be appreciated ;)

## Steps to Reproduce (for Bugs)
I can't say exactly. Could be a shield hardware restart I did a few days ago.

## Context
I'm trying to shutdown my tv when the shield is turned off due to CEC being incompetent. Doesn't work anymore for some days. Need to actually touch my tv-remote. duh.
Since androidtv does app autoupdates this could be due to an shield update.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
Openhab 3.4.4
org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-d1cc1c7.jar

* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
Shield Thing sais: remoteServerVersion 5.2.473254133
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
```
runtimeInfo:
  version: 3.4.4
  buildString: Release Build
locale: de-DE
systemInfo:
  configFolder: /etc/openhab
  userdataFolder: /var/lib/openhab
  logFolder: /var/log/openhab
  javaVersion: 11.0.19
  javaVendor: Ubuntu
  osName: Linux
  osVersion: 5.15.0-76-generic
  osArchitecture: amd64
  availableProcessors: 2
  freeMemory: 31307680
  totalMemory: 283115520
  startLevel: 100
bindings:
  - androidtv
  - deconz
  - exec
  - homeconnect
  - hue
  - lgwebos
  - minecraft
  - mqtt
  - network
  - snmp
  - wled
  - yamahamusiccast
  - yamahareceiver
clientInfo:
  device:
    ios: false
    android: false
    androidChrome: false
    desktop: true
    iphone: false
    ipod: false
    ipad: false
    edge: false
    ie: false
    firefox: false
    macos: false
    windows: false
    cordova: false
    phonegap: false
    electron: false
    nwjs: false
    webView: false
    webview: false
    standalone: false
    pixelRatio: 1
    prefersColorScheme: dark
  isSecureContext: false
  locationbarVisible: true
  menubarVisible: true
  navigator:
    cookieEnabled: true
    deviceMemory: N/A
    hardwareConcurrency: 16
    language: en-US
    languages:
      - en-US
      - de
      - en
    onLine: true
    platform: Linux x86_64
  screen:
    width: 5120
    height: 1440
    colorDepth: 24
  support:
    touch: false
    pointerEvents: true
    observer: true
    passiveListener: true
    gestures: false
    intersectionObserver: true
  themeOptions:
    dark: dark
    filled: true
    pageTransitionAnimation: default
    bars: light
    homeNavbar: default
    homeBackground: default
    expandableCardAnimation: default
  userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
    Gecko) Chrome/114.0.0.0 Safari/537.36
timestamp: 2023-06-28T15:53:25.901Z
```

**Comment by jlaur** [comment] 2023-06-28 17:10
@morph166955 - FYI.

**Comment by morph166955** [comment] 2023-06-28 19:12
Unfortunately, I think we have two issues here.   

The first issue being with GoogleTVMessageParser looks like a failed login.  It concerns me that you're getting this because we just upgraded to resolve this issue.  

Can you confirm what version of AndroidTV you have running on your shield as well as the versions of:

Google Play Movies & TV (aka com.google.android.videos)
Android TV Remote Service (aka com.google.android.tv.remote.service)

The second issue being with the ShieldTVMessageParser.  That's a really weird place to throw an exception.  Can you put the binding into trace logging and send me the logs from just before that exception?  It should say something along the lines of "{} - Received ShieldTV message from: {} - Message: {}" where the {} are replaced with the message info.  Also, are you running ipv6 by chance?

**Comment by morph166955** [comment] 2023-06-29 01:39
Google updated the client to 4.39.644.  This shouldn't impact the shield, but in the small chance that it does I am pushing #15154 to updated the login string anyway.  

Test jar is available at: https://github.com/morph166955/openhab-addons/releases/download/androidtv-beta/org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-f63eec4.jar

**Comment by morph166955** [comment] 2023-06-30 12:58
No worries. Trace logging will be very helpful for me to see what's happening at least on the shield issue. Please make sure to update the jar for the google issue, it may fix it.

**Comment by MichaelHeimann** [comment] 2023-06-30 13:02
> Google updated the client to 4.39.644. This shouldn't impact the shield, but in the small chance that it does I am pushing #15154 to updated the login string anyway.
> 
> Test jar is available at: https://github.com/morph166955/openhab-addons/releases/download/androidtv-beta/org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-f63eec4.jar
> 
> This should maybe hopefully fix the GoogleTVMessageParser error. This shouldn't do anything to the ShieldTV one.

Hmm, that one doesn't work at all, it seems:

```
2023-06-30 15:00:24.890 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-f63eec4.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.androidtv [289]
  Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.5.0)(!(version>=2.0.0)))"

	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.17.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445) ~[org.eclipse.osgi-3.17.200.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.7.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.7.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.7.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.7.4]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.7.4]
```

**Comment by MichaelHeimann** [comment] 2023-06-30 13:09
Reauthenticating didn't change it. But it's much easier with the new cli mode, thanks for that!

Will find out how to enable trace logging now and come back with the log...

**Comment by MichaelHeimann** [comment] 2023-06-30 13:17
> No worries. Trace logging will be very helpful for me to see what's happening at least on the shield issue. Please make sure to update the jar for the google issue, it may fix it.

Here's the log.

And you asked if I'm running IPv6 - yes I am. Although it shows legacy IPs in the trace ...

```
2023-06-30 15:14:29.573 [TRACE] [tocol.googletv.GoogleTVMessageParser] - dd406711 - Received GoogleTV message - Length: 93 Message: 0a5b08fd0412560a11534849454c4420416e64726f696420545612064e56494449411801220231312a24636f6d2e676f6f676c652e616e64726f69642e74762e72656d6f74652e73657276696365320d352e322e343733323534313333
2023-06-30 15:14:29.573 [DEBUG] [tocol.googletv.GoogleTVMessageParser] - dd406711 - 0a5b08fd041256 "SHIELD Android TV" "NVIDIA" 11 com.google.android.tv.remote.service 5.2.473254133
2023-06-30 15:14:29.573 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - Raw GoogleTV command decodes as: 590a5708fe0412520a08534d2d4739393855120773616d73756e671801220231332a19636f6d2e676f6f676c652e616e64726f69642e766964656f73321c342e33392e3538342e3532393538383538332e372d72656c65617365
2023-06-30 15:14:29.576 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - readerThreadJob message length 95
2023-06-30 15:14:29.577 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - GoogleTV Message: 95 5f1a5d080312590a5708fe0412520a08534d2d4739393855120773616d73756e671801220231332a19636f6d2e676f6f676c652e616e64726f69642e766964656f73321c342e33392e3538342e3532393538383538332e372d72656c65617365
2023-06-30 15:14:29.578 [TRACE] [tocol.googletv.GoogleTVMessageParser] - dd406711 - Received GoogleTV message - Length: 95 Message: 1a5d080312590a5708fe0412520a08534d2d4739393855120773616d73756e671801220231332a19636f6d2e676f6f676c652e616e64726f69642e766964656f73321c342e33392e3538342e3532393538383538332e372d72656c65617365
2023-06-30 15:14:29.578 [WARN ] [tocol.googletv.GoogleTVMessageParser] - dd406711 - GoogleTV Error Message: 1a5d080312590a5708fe0412520a08534d2d4739393855120773616d73756e671801220231332a19636f6d2e676f6f676c652e616e64726f69642e766964656f73321c342e33392e3538342e3532393538383538332e372d72656c65617365
2023-06-30 15:14:29.580 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - readerThreadJob received ffffffff.  Disconnecting hard.
2023-06-30 15:14:29.580 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Attempting to reconnect to the GoogleTV
2023-06-30 15:14:29.580 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Disconnecting GoogleTV
2023-06-30 15:14:29.581 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Command sender thread exiting 6466
2023-06-30 15:14:29.583 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Opening GoogleTV SSL connection to 10.250.10.33:6466 NORMAL
2023-06-30 15:14:29.613 [DEBUG] [l.googletv.GoogleTVConnectionManager] - Assuming server certificate is valid
2023-06-30 15:14:29.613 [TRACE] [l.googletv.GoogleTVConnectionManager] - Subject DN: CN=atvremote/sif/sif/SHIELD Android TV/00:04:4B:FA:FE:C3
2023-06-30 15:14:29.614 [TRACE] [l.googletv.GoogleTVConnectionManager] - Issuer DN: CN=atvremote/sif/sif/SHIELD Android TV/00:04:4B:FA:FE:C3
2023-06-30 15:14:29.615 [TRACE] [l.googletv.GoogleTVConnectionManager] - Serial number: 1665975951699
2023-06-30 15:14:29.615 [DEBUG] [l.googletv.GoogleTVConnectionManager] - Returning empty certificate for getAcceptedIssuers
2023-06-30 15:14:29.618 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Connection to 10.250.10.33:6466 NORMAL successful
2023-06-30 15:14:29.619 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - Starting Reader Thread for 10.250.10.33:6466
2023-06-30 15:14:29.620 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - Starting Sender Thread for 10.250.10.33:6466
2023-06-30 15:14:29.621 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Message reader thread started 6466
2023-06-30 15:14:29.621 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - Checking for PIN MODE for 10.250.10.33:6466 NORMAL
2023-06-30 15:14:29.621 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - Not PIN Mode 10.250.10.33:6466 NORMAL
2023-06-30 15:14:29.622 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Message reader thread exiting 6466
2023-06-30 15:14:29.621 [DEBUG] [l.googletv.GoogleTVConnectionManager] - dd406711 - Command sender thread started 6466
2023-06-30 15:14:29.660 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - readerThreadJob message length 93
2023-06-30 15:14:29.662 [TRACE] [l.googletv.GoogleTVConnectionManager] - dd406711 - GoogleTV Message: 93 5d0a5b08fd0412560a11534849454c4420416e64726f696420545612064e56494449411801220231312a24636f6d2e676f6f676c652e616e64726f69642e74762e72656d6f74652e73657276696365320d352e322e343733323534313333
2023-06-30 15:14:29.662 [TRACE] [tocol.googletv.GoogleTVMessageParser] - dd406711 - Received GoogleTV message - Length: 93 Message: 0a5b08fd0412560a11534849454c4420416e64726f696420545612064e56494449411801220231312a24636f6d2e676f6f676c652e616e64726f69642e74762e72656d6f74652e73657276696365320d352e322e343733323534313333

```

**Comment by morph166955** [comment] 2023-06-30 13:33
Thanks!  Do you have the trace for the shieldtv exception?

**Comment by MichaelHeimann** [comment] 2023-06-30 15:06
Not shure which parts you need so I've created a [tracefile](https://heimann.cloud/owncloud/index.php/s/E39pwGyiPgoSjd4) just before uninstalling the addon and reinstalling it again. So everything should be in there.

**Comment by morph166955** [comment] 2023-06-30 15:22
Awesome.  I can see the issue with the shieldtv side.  This is the offending line (saving for my notes):

```
2023-06-30 16:56:06.072 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Received ShieldTV message from: SHIELD - Message: 080b123808b51012330a06534849454c44189b462210363035333834333264643430363731312a0b61726d656162692d7637612a0761726d65616269180b
2023-06-30 16:56:06.073 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Longer Hostname Reply
2023-06-30 16:56:06.089 [INFO ] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Message Parser Caught Exception
java.lang.ArrayIndexOutOfBoundsException: Index 124 out of bounds for length 124
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVMessageParser.handleMessage(ShieldTVMessageParser.java:132) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.finishReaderMessage(ShieldTVConnectionManager.java:738) ~[?:?]
	at org.openhab.binding.androidtv.internal.protocol.shieldtv.ShieldTVConnectionManager.readerThreadJob(ShieldTVConnectionManager.java:777) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

The structure that I've always observied is:
080b 12 5b08b510 12 TOTALLEN? 0a LEN Hostname 12 LEN IPADDR Padding? 22 LEN DeviceID 2a LEN arm64-v8a 2a LEN armeabi-v7a 2a LEN armeabi 180b

Yours in comparison
080b 12 3808b510 12 33 0a 06 534849454c44 18 9b46 22 10 36303533383433326464343036373131 2a 0b 61726d656162692d763761 2a 07 61726d65616269 180b

The difference here being that we normally see "12 LEN IPADDR Padding?" but we're getting "18 9b46" which is unexpected.

I can submit a PR to resolve that piece.

As for the googletv side, I'll try to see what's going on with that jar.  Several PRs were just merged in so I may respin one for the marketplace anyway which would include this.

**Comment by morph166955** [comment] 2023-06-30 19:24
I've uploaded a new jar to the marketplace (01b82f7) which in theory fixes both issues.  If you could please update and let me know what you see that would be appreciated.  You may have to clear the cache out if you are still getting that same ogsi error, someone noted on the forum they had to do this.

https://github.com/morph166955/openhab-addons/releases/download/androidtv-beta/org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-01b82f7.jar

**Comment by MichaelHeimann** [comment] 2023-06-30 21:30
Hmm. I've reinstalled from the marketplace and no change.

Is this the expected version?

```
openhab> list -s | grep androidtv
292 │ Active │  80 │ 4.0.0.202306301807     │ org.openhab.binding.androidtv
```

Also [here](https://heimann.cloud/owncloud/index.php/s/fEp45kWwQ4QTtBn) is the trace after the install.

**Comment by morph166955** [comment] 2023-06-30 22:01
Yes, that is the correct version. The good news is that the shieldtv problem is resolved. 

```
2023-06-30 23:19:38.654 [TRACE] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Longer Hostname Reply
2023-06-30 23:19:38.656 [DEBUG] [tocol.shieldtv.ShieldTVMessageParser] - dd406711 - Hostname: SHIELD - ipAddress:  - deviceId: 60538432dd406711 - arch: armeabi-v7a,armeabi
```

That said, obviously the googletv isn't. I'll have to think on this. I can't reproduce it here unfortunately so I can't test locally and work through.

**Comment by morph166955** [comment] 2023-06-30 23:06
Just to confirm, was this a new install or did this work at some point and it then failed?

**Comment by MichaelHeimann** [comment] 2023-07-01 09:59
It did initially work.
I just noticed that yes, my usecase works with the latest jar, too. Openhab detects the shield getting on or off and I can turn the tv on or off based on that.

Tv remote ready to catch dust again. Thanks!

**Comment by morph166955** [comment] 2023-07-01 13:55
Gotcha. I have a thought on a test we can run but it will need a few tweaks to the code. From what you pasted above it looks like you're running native on Ubuntu right?  No docker or anything?

**Comment by MichaelHeimann** [comment] 2023-07-01 18:39
Jup. Ubuntu in a VM.

**Comment by morph166955** [comment] 2023-07-01 18:45
Awesome. Does the googletv app work on your phone?  Specifically can you connect, do the pin code, and then use the remote?

**Comment by morph166955** [comment] 2023-07-01 23:12
Ok, I've had some success adjusting the code to do this test.  It's going to take some more time on my side to make this work more cleanly.  Effectively, there is a part of the code which allows the binding to act as a man in the middle and watch the communications between a phone and the device.  Unfortunately, as I'm generally the only user, there are some manual certificate things that have to be done which are not that intuitive or easy.  I'm attempting to build that into the code so it's a little easier.  I hope to have that some time in the next few days.  Once done, if you can run the test on your side and send me the log, I should be able to see what the app is doing that is working compared to what we're doing that's not.  Then we can just write a patch on our side.

**Comment by MichaelHeimann** [comment] 2023-07-02 22:07
> Awesome. Does the googletv app work on your phone? Specifically can you connect, do the pin code, and then use the remote?

Yes, I just checked. it does work.

**Comment by morph166955** [comment] 2023-07-02 22:34
Awesome. Then this may work. I'll get back to you in a few days once I get some of this hashed and a new jar built.

**Comment by morph166955** [comment] 2023-07-03 21:05
Ok, I have a test jar which may help us figure this out.  This is going to be a little complicated, but not horrible.  I was able to automate the hard parts and include them in this jar.  I am expecting you to see a few exceptions thrown, that's normal, don't panic.

1) AVAHI
On Ubuntu there is a service called AVAHI which sends out the mdns messages that the app uses to populate the list of devices to connect to.  

First we have to create the host record.  Find /etc/avahi/hosts.  Add a line that says:

`(your OH IP)       shim.local`

Then there is a folder at /etc/avahi/services.  Create a file called googletv.service and populate it with this:


```
<?xml version="1.0"?>
<service-group>
    <name>Shim</name>
    <service>
        <type>_androidtvremote2._tcp</type>
        <host-name>shim.local</host-name>
        <port>6466</port>
        <txt-record>bt=1C:69:7A:AA:AA:46</txt-record>
</service>
</service-group>
```

2) start OH and put the binding into trace 

3) Configure a text based thing.  You should need 2 configuration items.  The ip address, and then add shim=true.  Example:
Thing androidtv:googletv:shim [ ipAddress="10.0.0.10", shim=true ]

4) Open the GoogleTV app on your phone.  If everything has worked so far you should see a device called Shim.  Attempt to connect to it.  You will see a bunch of messages in the log.  If we're lucky, you should see a pin request on your tv.

5) THIS IS THE TRICKY PART.  BEFORE putting the PIN into your phone, we need to load it into the binding so it can be modified for use.  The pin will be changed by the binding.  On the CLI, enter 
"openhab:androidtv androidtv:googletv:shim pincode (pin you see on screen)" <-- This will NOT make the pin go away on the screen.  In this mode we are caching the good pin so it can be used later.

6) This generates two log entries that will look like...

```
2023-07-03 15:44:46.502 [TRACE] [rnal.protocol.googletv.GoogleTVUtils] - validatePIN [78, -107, -79] 78 [-107, -79] [78, -107, -79] 4e95b1 4e4b173529f8698e6bff5e8077e2975885cb9589c6ea15016db3b13cf2f9b199
2023-07-03 15:44:46.503 [TRACE] [rnal.protocol.googletv.GoogleTVUtils] - validatePIN [78, -107, -79] 25 [-107, -79] [25, -107, -79] 1995b1 192d7d080e816c648fe961ba753c632a5c68c03d9862f6f1b6771a62906ee61d
```

The top line should include the pin you see on the screen (4e95b1 in my case).  The bottom line now includes your new pin.  The first two characters change, the other 4 stay the same.  Enter the new pin on your phone and hit pair.

7) If this all worked, you should now be able to control your device through your phone AND you should be seeing a ton of messages on your log.  You are now intercepting the traffic between your device and your phone.  If you got this far, grab EVERYTHING from top to bottom (yes it will be significant, every byte counts though here) and send it over.

THANK YOU!

https://github.com/morph166955/openhab-addons/releases/download/androidtv-beta/org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-70c779a.jar

**Comment by MichaelHeimann** [comment] 2023-07-04 16:35
Ok, I've got some questions:

In the xml, can I just use the MAC you posted or is that the id of the proxy device?

And then, in the openhab thing, what IP should go in there? The one of openhab? The one of the shield?

And just a note: openhab is in another subnet (server-vlan) than the shield or my phone, but mdns is forwarded in between the subnets, so it will mdns/see each other. I thought I should mention that.

Thanks,
Michael

**Comment by morph166955** [comment] 2023-07-04 16:37
The XML you can copy paste, the MAC can be left alone. You just need to put the IP of the device in the hosts file.

The IP on the thing is the IP of your shield.

I think that's OK, never tried it though.

**Comment by morph166955** [comment] 2023-07-04 19:44
One other note. To make it cleaner I didn't pull all of the pending PRs in (minus the cli) so you may see the shield bug in the logs still/again on that jar.

**Comment by morph166955** [comment] 2023-07-05 19:31
@MichaelHeimann checking in to see if you have had any success.  Not to put any time pressure, but with 4.0.0 about to go GA I really want to make sure we get a patch for this in ASAP so it makes it into the release.

**Comment by morph166955** [comment] 2023-07-06 17:59
The recent marketplace drop also now includes the updates to make this work...

https://github.com/morph166955/openhab-addons/releases/download/androidtv-beta/org.openhab.binding.androidtv-3.2.0-4.0.0-SNAPSHOT-d23b28a.jar

**Comment by morph166955** [comment] 2023-07-09 19:49
@MichaelHeimann checking in on this. We're days out from the 4.0.0 code lock, I'd really like to try to figure this out and submit a PR prior to that if we can.  Thanks!

**Comment by morph166955** [comment] 2023-07-16 23:49
I've pushed a PR to take the thing offline semi-permanently when this kind of error happens to avoid a flood scenario.  This does not fix this issue, it simply puts a stop gap in place to prevent floods.

**Comment by morph166955** [comment] 2023-07-19 14:03
This is not closed.  There is still the underlying protocol failure.  The PR only fixed the log flooding.

**Comment by morph166955** [comment] 2023-07-31 18:20
@MichaelHeimann checking in to see if you still have this issue and if you were able to pull the data above.  We've had another report of this bug, trying to get to root cause as I can't replicate it here.

**Comment by MichaelHeimann** [comment] 2023-07-31 22:38
@morph166955 sorry, I'm just deep in work and couldn't test my shield the last few days. It's getting better so I can give feedback the second half of this week.

**Comment by morph166955** [comment] 2023-07-31 23:47
Very much appreciated!

**Comment by morph166955** [comment] 2023-08-18 18:46
@MichaelHeimann Any luck?  I was able to get a debug from another user with this issue, and I've found what I think could be the offending flag.  Unfortunately, when I compare it to your outputs so far there is a small difference so I would still want to see what you are seeing to make sure the fix is accurate.

**Comment by morph166955** [comment] 2023-08-23 14:01
Test jar with possible fix - https://github.com/morph166955/openhab-addons/releases/download/androidtv-beta/org.openhab.binding.androidtv-4.1.0-SNAPSHOT-fixlogin2.jar

**Closed** 2023-09-10 06:55 UTC
Labels: awaiting feedback
