### ISSUE TITLE
[tapocontrol] Tapo Things offline since firmware update

### ISSUE THREAD

**Issue by dukeplay** [openhab/openhab-addons#15585] opened 2023-09-13 05:46 UTC
The P100 smart socket from device version 2.0, the L530 bulb and perhaps others have received a firmware update. Since then they have been offline in Openhab (COMMUNICATION_ERROR unknown api error (-1)). 

The P100 now has a firmware version 1.2.1 and the bulb l530 1.3.0.

![Tapo_P100](https://github.com/openhab/openhab-addons/assets/92566951/06221cf0-8e46-4d3a-9e4d-27007f093424)

**Comment by Goliath23** [comment] 2023-09-16 04:20
I second that. All Tapo Plugs offline, stopped working a few days ago.

**Comment by cee-dee** [comment] 2023-09-21 17:28
I can confirm that P100 plugs with version1.2.1 Build 230804 Rel. 190922 are not operational anymore. I cannot check the version of the operational ones because it requries a firmware update in the app. I'm eager to assist, e.g. provide logs or similar things.

**Comment by wildcs** [comment] 2023-10-09 18:24
Tapo changed the protocol for some devices because of security reasons.
I had to rewrite the whole communication and uploaded a beta to my compiled-addons repository.
You can read anything here in the [Binding-Support-Thread](https://community.openhab.org/t/tapocontrol-control-tapo-smart-wifi-devices-with-openhab/118389/297?u=bigdesaster)

**Comment by wildcs** [comment] 2023-10-12 16:17
Fixed with pr https://github.com/openhab/openhab-addons/pull/15725
Until pr is merged you can manually install jar from my [oh-compile-addons](https://github.com/wildcs/oh3_compiled-addons/tree/tapocontrol)

**Comment by dukeplay** [comment] 2023-10-15 09:02
Thank you very much for the great work.

**Closed** 2023-10-15 09:02 UTC
