### ISSUE TITLE
[telegram] errors on startup, binding only working after refreshing rules

### ISSUE THREAD

**Issue by cybermcm** [openhab/openhab-addons#10145] opened 2021-02-14 09:14 UTC
## Expected Behavior
Telegram binding working in rules

## Current Behavior
after restarting OpenHab multiple log file entries appear in openhab.log:
```
The field Tmp_eventRules.telegramAction refers to the missing type Object
```

## Possible Solution
workaround: After restarting Openhab I have to edit a rule to reload it. After this the Telegram binding is working

## Steps to Reproduce (for Bugs)
happens after every reboot

## Context
community forum:
[Link](https://community.openhab.org/t/error-when-system-started-in-getactions-method-of-telegram-binding/111496/4)

## Your Environment
* Version used: openHAB 3.0.1 with Telegram binding 3.0.1
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian current version with Docker

**Comment by mkosken** [comment] 2021-02-15 21:04
I get the same error and all the rules that contains TelegramActions can't run. They just give me the following error

[ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'machineStates-4' failed: null in machineStates

The errors goes away after reloading of the rule and everything works as it should until next reboot. All my rules are file based

**Comment by eric1905** [comment] 2021-03-05 18:23
I would also be glad if this will be fixed. I can confirm the modification of the rule works but I do not want to do this after every reboot

**Comment by cybermcm** [comment] 2021-03-05 18:33
simple workaround so far: use a crontab task to move files from rules directory to another directory and back… simple but effective…

**Comment by sagittarius0815** [comment] 2021-03-06 11:22
@cybermcm  workaround works, but it's not a solution.
It seems to be not only a Telegram actions problem, but a common action problem.
I have the same behavior with MQTT binding.

`val mqttActions = getActions("mqtt","mqtt:broker:exxxxxxxx5")
`
mqtt actions are not working after openheb3 restart.
But after a rules file modification the actions are working.

**Comment by cybermcm** [comment] 2021-03-06 11:29
I can't say anything about MQTT and rule files because I do not use it via rules. But if it is a common issue then there is hope that this will be fixed soon...

**Comment by Skinah** [comment] 2021-03-13 23:38
If this is happening with multiple bindings then it is probably a core isssue and this is in the wrong repo and won’t get seen by the right people. I don’t have any issues here using telegram binding from inside rules files and V3.x

**Comment by cybermcm** [comment] 2021-03-14 07:46
@Skinah If your binding works then we should compare our environment.
I'm using a Raspberry Pi with docker image (tag latest), Telegram being called by
`val telegramAction = getActions("telegram","telegram:telegramBot:xxxxxxxxxx")`
Is your setup similar?

**Comment by Skinah** [comment] 2021-03-30 02:11
Mine is flawless and I constantly reboot while testing new bindings in development, not seen this even once. I am not using docker as I use Armbian loaded on a oDROID N2+ and openHAB installed via APT. Using 3.1 milestone 2 currently but have used all the previous builds and not seen it.

**Comment by cybermcm** [comment] 2021-03-30 05:51
@Skinah: OK so if your environment is working there are a few options (possible issues):
1. docker related
2. maybe related to 32vs64 bit, I'm still using 32bit not sure what is your setup
3. mentioned in the forum ([Link](https://community.openhab.org/t/new-telegram-binding-tester-and-feedback-welcome/54806/379)) that the Telegram action "var telegramAction = getAction..." should be placed just before the send message and not on top of the rule file (didn't try this but will do)

**Comment by Skinah** [comment] 2021-03-30 23:12
2. I'm using 32bit (Hardware Float) Zulu java. I doubt it is java related.
3. To copy the code from your link, I am using it like this so not through a variable...
```
getActions(“telegram”,“telegram:telegramBot:FS6”).sendTelegram(“Test”)
```

I am using rule text files and note I have never tried the sendTelegram as above, I only use the ones to send photos and videos.

Good luck in narrowing it down.

**Comment by cybermcm** [comment] 2021-03-31 04:57
@Skinah: Thank you for your answer. You clarified that you don't use a variable. This is consistent with a forum [entry](https://community.openhab.org/t/new-telegram-binding-tester-and-feedback-welcome/54806/383?u=cybermcm) posted by eric1905 who has the same problem, but he uses this as a workaround for now.
I still think this is a bug, the official [binding](https://www.openhab.org/addons/bindings/telegram/) page explains the variable approach.
Hopefully a dev will take a look into it.

**Comment by Skinah** [comment] 2021-03-31 07:27
My gut feeling is this may be a bug in the core and not in the binding. You should not assume it is in the binding, and it needs to be narrowed down before someone blindly starts looking for an issue in the wrong place, so suggest you....

1. Try and confirm the work around solves it on your system.
2. Look to see if the same thing happens with any of the other bindings, if so it will be the core.
3. Check/search the issues on the github for the openHAB core.

I just looked above and someone has already mentioned that the same thing is happening with the mqtt binding, so it is looking very much like this is in the wrong place and an issue should be raised against the core AFTER first checking if there is already one.

**Comment by cybermcm** [comment] 2021-03-31 18:15
I can just verify 1): changing to something like
`getActions("telegram","telegram:telegramBot:FS6").sendTelegram("Test")`
instead of 
`val telegramAction = getActions("telegram","telegram:telegramBot:xxxxxxxxxx")`
solves the problem!

I'm afraid I can't test any more because work is eating up my time completely for the moment. Would be great if someone can cover 2) and 3)...

**Comment by mkosken** [comment] 2021-04-03 19:20
The same workaround that cybermcm verified above works for me as well. Regarding 2) same issue with different bindings, i got the same error  with mqtt binding and I can confirm that the same workaround fixad the issue with that binding as well. So, as Skinah suspected this seems more like a bug in the core and not in the binding. I did a really quick search in the core for already open issues, but didn't find any

**Comment by Skinah** [comment] 2021-08-18 08:35
Thanks for the feedback. Since this is not related to a particular binding and most likely it was a core issue. I will close this issue as there have been no recent reports of this on the forum so its probably fixed, if not it should be reported as a core issue.

**Closed by Skinah** 2021-08-18 08:35 UTC

**Comment by Skinah** [comment] 2021-08-30 12:50
Then if it is still happening, it needs to be opened as an issue under CORE and not ADDONS.
