### ISSUE TITLE
[hdpowerview] Add support for top down / bottom up blinds

### ISSUE THREAD

**Issue by stevegroom** [openhab/openhab-addons#4836] opened 2019-02-08 17:27 UTC
## Expected Behavior

PowerView top down / bottom up blinds have two position channels per blind. 

## Current Behavior
The current binding only reports the standard bottom position. 

## Possible Solution

I have a new Hunter Douglas topdown / bottom up blind. Using postman I can see the data returned includes the top and bottom rail positions :

``` json
{
    "shadeIds": [
        16876
    ],
    "shadeData": [
        {
            "id": 16876,
            "type": 8,
            "batteryStatus": 3,
            "batteryStrength": 144,
            "firmware": {
                "revision": 1,
                "subRevision": 8,
                "build": 1944
            },
            "name": "TGFuZGluZyBXaW5kb3c=",
            "signalStrength": 4,
            "roomId": 1532,
            "groupId": 35409,
            "positions": {
                "posKind2": 2,
                "position2": 33748,
                "posKind1": 1,
                "position1": 13144
            },
            "motor": {
                "revision": 0,
                "subRevision": 0,
                "build": 267
            }
        }
    ]
}
```

The blind reports posKind1 and posKind2 representing the upper and lower bars that move independently. When I capture all the channels and store them in InfluxDB only one value is stored (along with channel vane that is not used).

At the same time I would like to log battery strength rather than the LowBattery alert.

## Context
The current binding works in that I can position the blinds via scenes, but I would like direct control from OH. 

## Your Environment
OH 2.4 Stable on RPi B3+ Openhabian.

**Comment by berland** [comment] 2020-01-25 18:11
(duplicate of #4351)

**Comment by mstroeve** [comment] 2020-02-02 13:30
duplicate of #4351 please close this one.

**Closed** 2020-02-02 18:15 UTC
