### ISSUE TITLE
[Javascript Transformation] support NULL/null/UNDEF as NumberValue

### ISSUE THREAD

**Issue by radoslavv** [openhab/openhab-addons#7622] opened 2020-05-13 01:21 UTC
## Your Environment

* Version used: openHAB 2.5.3 Release Build, transformation-javascript - 2.5.3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): openjdk version "11.0.6" 2020-01-14 (build 11.0.6+10-post-Raspbian-1deb10u1)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): RPi4, Raspbian GNU/Linux 10 (buster), Linux 4.19.97-v7l+ armv7l

For processing of MQTT zero payload messages (interpreted as unpublish):

    [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'

or other specific payload value (having similar meaning, and already discussed on community portal), there is needed to allow for `NumericValue` to accept `NULL` and/or `UNDEF`:

    [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload 'null' not supported by type 'NumberValue'
    [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload 'NULL' not supported by type 'NumberValue'
    [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload 'UNDEF' not supported by type ''NumberValue'

where default unitialized value in `Value.java` is `UNDEF`:

    public abstract class Value {
        protected State state = UnDefType.UNDEF;
    ...

and also reset to `UNDEF` is supported (but not used, and this might be used in the `NULL` implementation):

    public final void resetState() {
        state = UnDefType.UNDEF;
    }

easy way of testing (w/o script):

    mosquitto_pub -t '02/SGP30/CO2_ppm' -m 'null'
    mosquitto_pub -t '02/SGP30/CO2_ppm' -m 'NULL'
    mosquitto_pub -t '02/SGP30/CO2_ppm' -m 'UNDEF'

so that this will be possible to handle zero payload (or other specific payload) in transformation JavaScript:

    (function(mqtt_payload) {
        if (mqtt_payload === '') {
            return( null );
            /*
            return( 'NULL' );
            return( Java.type("org.eclipse.smarthome.core.types.UnDefType").NULL );
            return( Java.type("org.eclipse.smarthome.core.types.UnDefType").UNDEF );
            */
        }
        else return( mqtt_payload );
    })(input)

could be tested using command:

    mosquitto_pub -t '02/SGP30/CO2_ppm' -m ''

Also would be great to transfer to script not only `input` value, but also `topic name`.

**Comment by Rossko57** [comment] 2020-05-13 21:31
Comment; bindings should never set Item state NULL.
UNDEF is certainly possible; it is already used by some bindings to indicate e.g. failed or corrupt communication, or an incalculable number.

The use case here is a bit different - setting UNDEF in response to a perfectly legitimate and well-formed message.  But, it would be done by a user-defined transform, just like it could from a rule.  Users can freely set UNDEF state from rules as well, so it would be difficult to argue that is should _only_ be used to indicate a problem.

If this feature were implemented, it should apply to any state channel type, and be available from any suitable transformation e.g. MAP
Note: there is nothing currently stopping any  existing transformation from returning a string "UNDEF" - this feature request is really for MQTT binding.  Transformation always returns strings by design.  It is up to the binding to take "special action" upon recognizing string "UNDEF".
(Other bindings supporting transformations could also act like this, but I would guess need their own enhancement requests.)

**Comment by id628** [comment] 2021-06-06 14:26
Since this issue doesn't seem to be addressed in over a year, is there a workaround to keep my logs from filling with thousands of warning messages? Can it be handled with a transform maybe?


```
2021-06-05 09:45:08.120 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:46:12.670 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:46:47.999 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:48:37.842 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:50:27.666 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:52:37.433 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:55:07.132 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 09:58:46.652 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 10:04:35.878 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 10:10:51.900 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 10:10:54.448 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '' not supported by type 'OnOffValue': No enum constant org.openhab.core.library.types.OnOffType.
2021-06-05 10:10:56.465 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '' not supported by type 'OnOffValue': No enum constant org.openhab.core.library.types.OnOffType.
2021-06-05 10:13:57.818 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 10:14:04.841 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 10:17:33.976 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
2021-06-05 10:20:59.759 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Incoming payload '' not supported by type 'NumberValue'
```

**Comment by Rossko57** [comment] 2021-06-08 00:35
Sure.  Use a chained REGEX transform to avoid attempting to process payloads with empty fields.

**Comment by id628** [comment] 2021-06-10 14:48
@radoslavv Since this issue seems to be with the MQTT Binding, rather than with Transforms, is it possible to change the title of the Issue?

**Comment by hmerk** [comment] 2022-07-04 19:37
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.

**Closed by hmerk** 2022-07-04 19:37 UTC
