### ISSUE TITLE
[swagger-codegen] IllegalArgumentException TadoModeTerminationCondition: declares multiple JSON fields named 'type'

### ISSUE THREAD

**Issue by dandjo** [openhab/openhab-addons#16779] opened 2024-05-20 15:53 UTC
## Current Behavior
An error occurs when initializing or interacting with the tado addon in version 4.2.0 M3.

```
2024-05-20 16:16:58.863 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalArgumentException: Class org.openhab.binding.tado.internal.api.model.TadoModeTerminationCondition declares multiple JSON fields named 'type'; conflict is caused by fields org.openhab.binding.tado.internal.api.model.TadoMo
deTerminationCondition#type and org.openhab.binding.tado.internal.api.model.OverlayTerminationCondition#type
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:302) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[?:?]
        at com.google.gson.Gson.getDelegateAdapter(Gson.java:652) ~[?:?]
        at org.openhab.binding.tado.internal.api.RuntimeTypeAdapterFactory.create(RuntimeTypeAdapterFactory.java:60) ~[?:?]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[?:?]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:160) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:294) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:130) ~[?:?]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1226) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1047) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:1014) ~[?:?]
        at org.openhab.binding.tado.internal.api.client.HomeApi.showZoneState(HomeApi.java:529) ~[?:?]
        at org.openhab.binding.tado.internal.handler.TadoZoneHandler.getZoneState(TadoZoneHandler.java:129) ~[?:?]
        at org.openhab.binding.tado.internal.handler.TadoZoneHandler.updateZoneState(TadoZoneHandler.java:325) ~[?:?]
        at org.openhab.binding.tado.internal.handler.TadoZoneHandler$1.run(TadoZoneHandler.java:420) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

## Environment
* Version used: openHAB 4.2.0-M3, Add-on 4.2.0-M3
* Operating System and version: Ubuntu server, 5.15.0-1055-raspi, openhabian

**Comment by dandjo** [comment] 2024-05-20 16:00
Here are additional information from my things and items used:

Tado Home Thing
```yaml
UID: tado:home:daniel
label: Tado Home
thingTypeUID: tado:home
configuration:
  password: xxxXXXxxxXXX
  username: john.doe@email.not
channels:
  - id: homePresence
    channelTypeUID: tado:homePresence
    label: At Home
    description: ON if at home, OFF if away
    configuration: {}

```

Tado Air Conditioning Thing
```yaml
UID: tado:zone:daniel:2
label: Tado Air Conditioning
thingTypeUID: tado:zone
configuration:
  hvacChangeDebounce: 5
  fallbackTimerDuration: 30
  id: 2
  refreshInterval: 30
bridgeUID: tado:home:daniel
channels:
  - id: currentTemperature
    channelTypeUID: tado:currentTemperature
    label: Temperature
    description: Current temperature
    configuration: {}
  - id: hvacMode
    channelTypeUID: tado:hvacMode
    label: HVAC Mode
    description: Mode of the device (OFF, HEAT, COOL, DRY, FAN, AUTO - if supported)
    configuration: {}
  - id: targetTemperature
    channelTypeUID: tado:targetTemperature
    label: Target Temperature
    description: Thermostat temperature setpoint
    configuration: {}
  - id: fanspeed
    channelTypeUID: tado:fanspeed
    label: Fan Speed
    description: AC fan speed (only if supported by AC)
    configuration: {}
  - id: swing
    channelTypeUID: tado:swing
    label: Swing
    description: State of AC swing (only if supported by AC)
    configuration: {}
  - id: overlayExpiry
    channelTypeUID: tado:overlayExpiry
    label: Overlay End Time
    description: Time until when the overlay is active. Null if no overlay is set or
      overlay type is manual.
    configuration: {}
  - id: timerDuration
    channelTypeUID: tado:timerDuration
    label: Timer Duration
    description: Total duration of a timer
    configuration: {}
  - id: operationMode
    channelTypeUID: tado:operationMode
    label: Zone Operation Mode
    description: Active operation mode (schedule, manual, timer or until next change)
    configuration: {}
  - id: acPower
    channelTypeUID: tado:acPower
    label: AirCon Power State
    description: Indicates if the air-conditioning is Off or On
    configuration: {}
  - id: openWindowDetected
    channelTypeUID: tado:openWindowDetected
    label: Open Window Detected
    description: Indicates if an open window has been detected
    configuration: {}
  - id: humidity
    channelTypeUID: system:atmospheric-humidity
    label: Humidity
    description: Current humidity in %
    configuration: {}
```

Tado Aircon Power State Item (example for all other)
```yaml
label: Tado AirCon Power State
type: Switch
category: switch
groupNames:
  - tado
tags:
  - Point
```

**Comment by lolodomo** [comment] 2024-05-25 09:55
Was it working in milestone 2 ?
As the only change regarding Tado in milestone 3 was reverted by #16793 , can you please tell us if your problem persists in the current daily snapshot ?

**Comment by andrewfg** [comment] 2024-05-25 10:45
> Was it working in milestone 2 ?

@lolodomo I am still on M2 and it is working just fine.

**Comment by lolodomo** [comment] 2024-05-25 10:53
So as the only change in M3 was reverted, we can expect the issue to be now resolved ?
Can you check again with the last snapshot ?

**Comment by andrewfg** [comment] 2024-05-25 12:22
> Can you check again with the last snapshot ?

Ok. Probably tomorrow..

**Comment by dandjo** [comment] 2024-05-25 20:53
Confirming, with snapshot 4.2.0~S4095 the error is gone, so the issue seems to be resolved with #16793.

**Comment by dandjo** [comment] 2024-05-25 20:56
For future versions it would probably be a better strategy to adapt the Tado addon to the newer Swagger version.

**Comment by lolodomo** [comment] 2024-05-26 07:21
Closing as issue is no more present.

**Comment by andrewfg** [comment] 2024-05-26 12:35
> it would probably be a better strategy to adapt the Tado addon to the newer Swagger version

@lolodomo / @dandjo even though this issue has been closed I am keeping the above suggestion in my mind. The problem is that it is not so easy to fix. The problem is that the Tado Cloud API does actually use JSON payloads with fields named 'type' and it seems the latest version of Swagger correctly parses the Tado YAML and generates DTOs for the API payloads with API related fields named 'type' annotated with '@SerializedName("type") but it apparently generates a extra field with the same '@SerializedName("type") annotation. I am not sure why that would happen with the new Swagger version. There may hopefully be a compatibility switch to turn off that new behaviour (i.e. make the new Swagger version behave like the older version), but I would need to study Swagger in my spare time. In the meantime the way to make Swagger behave like the older version is to -- well -- use the older version..

**Comment by andrewfg** [comment] 2024-05-31 14:21
I am reopening this issue because I think I have identified the cause of the problem, yet personally lack the skills to solve it, where other OH users (e.g. @dfrommi ) who may be able to fix it.

The issue is described [here](https://github.com/swagger-api/swagger-codegen/issues/12409). In short the Swagger Codegen (used to build the Tado binding) v2.3.1 does NOT generate duplicate fields in child DTOs whereas v2.4.41 DOES generate such duplicate fields. From deep googling I think there is some Swagger Codegen setting property called ['supportsInheritance`](https://github.com/swagger-api/swagger-codegen/blob/d51e61d6d385661d54c4c0767aaf4df3959feb5c/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L103) that may influence the creation of such duplicate fields in child classes.

However I lack the Swagger skills to know a) if the above hypothesis is correct, or b) how to fix it.

**Comment by dfrommi** [comment] 2024-05-31 14:39
There's always the option to stop using the generator. 
Just copy the generated code that works and commit it, then remove the generator-step. From then on, maintain the DTOs manually. 

I've initially created the generator to simplify API integration in OH in general and without introducing extra dependencies. But as far as I know, it's still only used in the tado integration and never found a wider acceptance. 

So I would suggest, get rid of the unicorn. 
As I'm not using OH anymore for a long time now, I will also not spend time keeping the generator up to date. So this step makes most likely a lot of sense, regardless of the issue. 

Hopefully my point of view helped at least a little bit.

**Comment by andrewfg** [comment] 2024-05-31 14:59
=> get rid of the unicorn.

@holgerfriedrich @lolodomo => WDYT?  The YAML has not changed since years, so the CodeGen produced DTOs will have not changed either (even though Swagger CodeGen recreates them on every CI build). So I can easily do the copy paste of the existing files from `/target/generated-code/src/main/java/...` to `src/main/java/..`  .. Personally I can't see any down sides, but WDYT?

**Comment by andrewfg** [comment] 2024-05-31 17:47
@holgerfriedrich I suppose the "only" risk is if the Swagger Codegen v2.3.1 is no longer downloadable and we know that later versions don't work. I am inclined to static copy the java files into OH so that we have everything in house.

**Closed** 2024-06-14 19:02 UTC
