### ISSUE TITLE
[broadlink] Not able to use the Binding under OH 4.0.2 to learn codes

### ISSUE THREAD

**Issue by scheuerer** [openhab/openhab-addons#15748] opened 2023-10-13 11:27 UTC
Hello,

now some more information.
I habe installed the offcial binding in an 4.0.2 installation and have added the Thing for my RM4 mini.
After that i was bringing the binding into trace mode.

An switching on and off the learning switch make now the following entry in the log file:

```
2023-10-13 13:18:26.458 [DEBUG] [.discovery.BroadlinkDiscoveryService] - Using source address /192.168.1.184 for sending out broadcast request.
2023-10-13 13:18:56.492 [DEBUG] [.discovery.BroadlinkDiscoveryService] - Discovery service found 0 broadlink devices.
2023-10-13 13:19:09.638 [DEBUG] [nternal.handler.BroadlinkBaseHandler] - Authenticating with broadlink device Broadlink RM4...
2023-10-13 13:19:09.676 [DEBUG] [nal.handler.RMUniversalRemoteHandler] - Thing broadlinkthermostat:rmuniversaldevice:3ebc1a6880 entered learning mode
2023-10-13 13:19:09.600 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Broadlink_RM4_Learning_Mode' received command ON
2023-10-13 13:19:09.602 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Broadlink_RM4_Learning_Mode' predicted to become ON
2023-10-13 13:19:09.604 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Broadlink_RM4_Learning_Mode' changed from OFF to ON
2023-10-13 13:19:56.500 [DEBUG] [.discovery.BroadlinkDiscoveryService] - Using source address /192.168.1.184 for sending out broadcast request.
2023-10-13 13:20:21.249 [DEBUG] [nternal.handler.BroadlinkBaseHandler] - Authenticating with broadlink device Broadlink RM4...
2023-10-13 13:20:21.228 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Broadlink_RM4_Learning_Mode' received command OFF
2023-10-13 13:20:21.230 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Broadlink_RM4_Learning_Mode' predicted to become OFF
2023-10-13 13:20:21.233 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Broadlink_RM4_Learning_Mode' changed from ON to OFF
```

As you can see, nothing happend after I have send a commonad from the remote to the RM4 mini…
Has someone out there any idea how to move forward?

**Comment by lsiepel** [comment] 2024-08-12 15:54
There is no broadlink binding part of openHAB. What binding and version is this about? Is this still happening in 4.2.1?

**Comment by lsiepel** [comment] 2024-09-28 19:21
Duplicate of https://github.com/openhab/openhab-addons/issues/15626

**Closed by lsiepel** 2024-09-28 19:21 UTC
