### ISSUE TITLE
[systeminfo] memory#availableHeap reports wrong values

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#13709] opened 2022-11-13 10:58 UTC
OH 3.4.0.M4
After having used the UI configuration for the systeminfo thing, the reported value for available heap is much to low.
Before with M3 (and textual config), the values have been around 50 - 120 MB, now it is ~ 2.1E-16 MB.

This happens on my both machines where I've upgraded and changed the kind of configuration.

![grafik](https://user-images.githubusercontent.com/37875289/201518214-052c4c20-3d1f-419a-a0f8-88e497f4b5e4.png)

**Comment by mherwege** [comment] 2022-11-15 20:40
@UrsusS Did you try removing the state description? The value should show in Bytes by default. I tested on a RPi 4 with Java OpenJDK 11.0.16 and it works correctly for me.
What operating system and linux version did you test with?
The code retrieving this was not touched in the most recent PR's to this binding.

**Comment by UrsusS** [comment] 2022-11-18 18:55
The item was defined as:
`Number:DataAmount       num_Server_Heap_Available                 "Verfügbarer Heap Speicher [%d MB]"         <none>          (gSystemInfo, gRestoreOnStartup, gLog, gDel1M)    {channel="systeminfo:computer:kopf:memory#availableHeap"}`
changing it to 
`Number:DataAmount       num_Server_Heap_Available                 ""         <none>          (gSystemInfo, gRestoreOnStartup, gLog, gDel1M)    {channel="systeminfo:computer:kopf:memory#availableHeap"}`
gives a very high number in Byte.

  version: 3.4.0.M4
  javaVersion: 11.0.16
  javaVendor: Raspbian
  osName: Linux
  osVersion: 5.15.76-v7l+

**Comment by mherwege** [comment] 2022-11-20 16:43
Does the value in Bytes correspond to the available heap? I know it is a high value. This code has not changed. The only thing I can see is that there have been quite a few changes to units in core.
Did you try %.0f MB as a state description?
@J-N-K Is there a chance that conversion from Bytes to MBytes using a state description broke in one way or the other with M4?

**Comment by UrsusS** [comment] 2022-11-22 20:35
Hard to say if these values correspond to the available heap. The value isn't constant, it is highly fluctuating.
%.0f MB didn't solve it, I just get 0 MB

**Comment by mherwege** [comment] 2022-11-28 17:09
I tested once more, and the issue is not with the binding, but with the unit conversion from B to MB. This is outside of the binding. I defined a Number:DataAmount item linked to this channel. If you use %0.f %unit% as a state description, it correctly shows the available heap in bytes. You can use the used heap % channel and see it go up/down with the available heap. But replacing that with %0.f MB does indeed show 0 MB as a result. So the unit conversion does not work.
I then tried creating a Number:DataAmount item, not linked to any channel and manually set a value. I tried changing the state description, but it never did the conversion correctly.
@lolodomo, @J-N-K do you have any view on this?

**Comment by lolodomo** [comment] 2022-12-12 19:22
The issue should be fixed with OH 3.4 milestone 6. can you confirm @UrsusS ?

**Comment by lolodomo** [comment] 2022-12-17 09:23
@UrsusS : please reopen in case it is not fixed.

**Closed by lolodomo** 2022-12-17 09:23 UTC
