### ISSUE TITLE
[senechome] Values freezes while channel link says "online"

### ISSUE THREAD

**Issue by DanielGlaas** [openhab/openhab-addons#12900] opened 2022-06-06 22:07 UTC
## Expected Behavior
I'm very satisfied with using openHAB, I use it to record the data of my solar energy production. I have a SENEC system and the binding works very vell and provides all data I need!
I expect that the data is continously recorded and persistently stored.

## Current Behavior
Very sporadically, it occures that the values are not updated anymore. The channel link and the Thing state are always online and neither the logs nor `journalctl` provide any kind of error report to me.
I attached two pictures which show that the value of the battery consumption is frozen for nearly three hours.
![energy frozen](https://user-images.githubusercontent.com/58786395/172254833-605ec10f-1aad-4466-b5ab-c4874eeb4ca8.png)
![channel online](https://user-images.githubusercontent.com/58786395/172254826-ca062cf3-f429-434c-9e2a-a33ab42066b3.png)
The pictures contain German text, I hope this does not matter.

## Workaround
A restart of openhab via `sudo systemctl restart openhab.service` solves the problem and the values are acquired correctly afterwards.
However, I need to take notice of this behaviour manually and trigger the restart by hand.

## Steps to Reproduce (for Bugs)
This behaviour is not reproducible.

Please note:
I have other channels which provide such dynamic data, and there I don't have frozen data at the same time. So this seems to be an issue with the SENEC addon for me.
Using the website of the SENEC system in parallel also displays updated values, so this issue is also not located in the SENEC system itself.

## Your Environment

* Version used: openHAB version 3.2.0
* Environment name and version: the used browser to display the data does not matter
* Operating System and version: raspberrypi 4, os buster

**Comment by DanielGlaas** [comment] 2022-06-06 22:11
Some additional information:
If I run openhab with the official docker image and the exactly same configuration, then this error appears much more often.

**Comment by fbphysik** [comment] 2023-03-06 06:38
> ## Workaround
> 
> A restart of openhab via `sudo systemctl restart openhab.service` solves the problem and the values are acquired correctly afterwards. However, I need to take notice of this behaviour manually and trigger the restart by hand.

Same problem here:

- OpenHAB 3.4.2 running on a laptop with Debian Bullseye
- Senec V3 hybrid duo

Disabling the senec thing in the UI and enabling it again works for me as a workaround, no need to restart openhab service.

**Comment by ssedlmaier** [comment] 2024-03-31 13:53
Has there been any update to this?
I have the same issue and just increased the log level to dig a bit deeper. Any hints would be appreciated.
If I can locate the issue I will prepare a PR as well.

**Comment by ssedlmaier** [comment] 2024-04-01 18:23
I created a potential fix for this. I will check this locally for a few days and open a PR if the problem is really solved.

**Closed** 2024-04-04 16:25 UTC
