### ISSUE TITLE
[bosesoundtouch] Things don't receive state updates and configurations from the speakers anymore

### ISSUE THREAD

**Issue by paeddib** [openhab/openhab-addons#14059] opened 2022-12-24 12:55 UTC
I have bose soundtouch speakers 10 and 20. After updating openhab to version 3.4.0, the items do not receive any state updates and configurations from the speakers anymore. Also, it is not possible to switch to a speaker preset number.

## Expected Behavior
Items receive states and configurations from the speakers. Power on/off, Presets, etc...

## Current Behavior
Generally, a soundtouch thing does not get any updates from the speakers, but the speakers do receive most of the commands from openhab.

That leads to a behaviour, that if a speaker is turning on with an openhab switch item, the 
item immediately switches back to "OFF" and will never has an "ON"-state.

If the speaker preset is changed in openhab, nothing happens on the speakers. The log shows  a warning message

[WARN ] [bosesoundtouch.internal.CommandExecutor] - null: No preset found at id: 3

## Possible Solution
I think the changes from version 3.3.0 to 3.4.0 breaks receiving states and configurations from the speakers. This leads to the described behaviour.

## Steps to Reproduce (for Bugs)
1. Turn on a speaker with a switch item => The item immediately turns back to off, the speaker turns on.
2. Turn on a speaker=> The openhab switch item does not receive power ON state.
3. Change speaker preset with openhab => Speaker does not change preset.

## Your Environment
* Version used: openHAB 3.4.0;  add-on version 3.4.0

**Comment by lolodomo** [comment] 2022-12-24 13:10
The only change I can find during this year is this one PR #13842.
@lsiepel : can your change be the source of the issue ?

**Comment by lsiepel** [comment] 2022-12-24 13:19
Hope not, but might be. @paeddib Can you send me a debug log ?

**Comment by paeddib** [comment] 2022-12-24 14:01
[openhab.log](https://github.com/openhab/openhab-addons/files/10298705/openhab.log)

@lsiepel  Let me know, if you need more informations

**Comment by lsiepel** [comment] 2022-12-24 22:57
I might have found something that could be the cause. I made a new jar that reverts some part of the previous PR. A JAR file can be downloaded here. Could you give it a try? Please add debug logging if it does not help. This jar is compatible with 3.4.0  
Remove the 3.4.0 binding add this to the addons folder and it should be picked up within seconds.
https://1drv.ms/u/s!AnMcxmvEeupwjplD0WsAcS4oPCnagg?e=wqqNOo

**Comment by paeddib** [comment] 2022-12-25 09:41
It is now possible to power on/off the speakers from openhab.  Also the thing receives the power state from the speakers. But the switch in openhab still jumps immediately back to OFF after slide it to ON. The switch changes to ON after receiving the state update from the speakers about a second later(see events_PowerOn.log).
[events_PowerOn.log](https://github.com/openhab/openhab-addons/files/10299683/events_PowerOn.log)
[openhab_PowerOn.log](https://github.com/openhab/openhab-addons/files/10299684/openhab_PowerOn.log)

It is still not possible to change the preset from openhab. Get still the same warning 
[WARN ] [bosesoundtouch.internal.CommandExecutor] - null: No preset found at id: 3

If volume or the preset are changed on speakers, the thing does not update the items (see logs)
[openhab_ChangeVolumeOnSpeakers.log](https://github.com/openhab/openhab-addons/files/10299690/openhab_ChangeVolumeOnSpeakers.log)
[openhab_ChangingPresetOnSpeakers.log](https://github.com/openhab/openhab-addons/files/10299691/openhab_ChangingPresetOnSpeakers.log)

**Comment by lsiepel** [comment] 2022-12-25 12:00
By replacing the deprecated XML parser with SAXParserFactory, the NamespaceAwareness was not set. With this verison that fixed big aprt of the communication problems. I cannot (yet) reproduce the remaining issue you are having.

As i might not come up with a quick resolution, we might need to revert the PR. 

Could you put the BoseSoundTouch binding in trace mode to a seperate file and send that file  after a stop/start + volume change from the bose binding?
file:
userdata\etc\log4j2.xml

add appender
```
		<!-- PlugwiseHA -->		
                <RollingRandomAccessFile append="true" fileName="${sys:openhab.logdir}/bosesoundtouch.log" filePattern="${sys:openhab.logdir}/bosesoundtouch.log.%i" immediateFlush="true" name="BOSESOUNDTOUCH">
                        <PatternLayout>
                                <Pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%-50.50c] - %m%n</Pattern>
                        </PatternLayout>
                        <Policies>
								<OnStartupTriggeringPolicy/>
                                <SizeBasedTriggeringPolicy size="16 MB"/>
                        </Policies>
                        <DefaultRolloverStrategy max="8"/>
                </RollingRandomAccessFile>
	<!-- PlugwiseHA -->
```
and logger:
```
		<Logger additivity="false" level="TRACE" name="org.openhab.binding.bosesounctouch">
				<AppenderRef ref="BOSESOUNDTOUCH"/>
		</Logger>
```

**Comment by paeddib** [comment] 2022-12-25 13:14
Below two separat logs for the two actions on the speaker
[bosesoundtouch_VolumeUp.log](https://github.com/openhab/openhab-addons/files/10299993/bosesoundtouch_VolumeUp.log)
[bosesoundtouch_PowerOnOff.log](https://github.com/openhab/openhab-addons/files/10299994/bosesoundtouch_PowerOnOff.log)

Complete log
[bosesoundtouch.log](https://github.com/openhab/openhab-addons/files/10300001/bosesoundtouch.log)

**Comment by lsiepel** [comment] 2022-12-25 21:05
I think i fixed more, but the work is not done yet. Could you check if this version improves your experience?
https://1drv.ms/u/s!AnMcxmvEeupwjplD0WsAcS4oPCnagg?e=wqqNOo 

Really big thanks for supplying all the logs, that make it much easier to fix. I have lkearned a lot about unit testing in java today, so i hope i can add tests to the next PR to pr4event such issues as this to happen at all.

**Comment by paeddib** [comment] 2022-12-25 21:50
Hello Isiepel, thanks for your help. I appreciate your effort very much!

Here are the new logs. Power On/Off from openhab. Preset change and volume up actions on speakers.
[bosesoundtouch_PowerOnOff.log](https://github.com/openhab/openhab-addons/files/10300666/bosesoundtouch_PowerOnOff.log)
[bosesoundtouch_ChangingPresetFrom4To5.log](https://github.com/openhab/openhab-addons/files/10300667/bosesoundtouch_ChangingPresetFrom4To5.log)
[bosesoundtouch_VolumeUp.log](https://github.com/openhab/openhab-addons/files/10300668/bosesoundtouch_VolumeUp.log)


Complete log. Changed binding around 22:29:28
[bosesoundtouch.log](https://github.com/openhab/openhab-addons/files/10300669/bosesoundtouch.log)

**Comment by lsiepel** [comment] 2022-12-25 21:59
Can you also let me know what issues remain? I’ll proceed tomorrow.

**Comment by lsiepel** [comment] 2022-12-26 15:51
Looked at it again, can't see any obvious bug. As i'm not able to do testing myself (borrowed a soundtouch 10 temporary from a friend) it's hard to fix. A volume change on the device and a event.log and besoundtouch.log around that time would help.
Does the soundtouch e20 device stay online? does it get any properties like firmware version etc?
Do you get any channel values?  Does etting a value work ? Or receiving any setting?

**Comment by paeddib** [comment] 2022-12-26 21:00
I am currently on holiday. I will check it when I get back home. Probably on Sunday. Sorry

**Comment by paeddib** [comment] 2022-12-27 10:02
I had a small window to test the last fix again. Sorry, I must not have loaded your last fix correctly. I have now tested the whole thing with version 3.4.1.202212260033.  It now seems like almost everything is working again. I have successfully checked most of the channels. 

The presets are still not working. The channel is always set to "0" when a preset is changed on the speaker. When the preset is changed from Openhab, the same message still appears as at the beginning.
[bosesoundtouch_PresetChangeFrom4To5.log](https://github.com/openhab/openhab-addons/files/10307357/bosesoundtouch_PresetChangeFrom4To5.log)

It seems that the binding did not initialize the preset correctly.
I get the following XML when I call the path http://IpAddressSpeaker:8090/presets
[presets.txt](https://github.com/openhab/openhab-addons/files/10307399/presets.txt)


Also the bass channel is not updated. If it is changed on the speaker, the value remains "NULL".
[bosesoundtouch_BassChange.log](https://github.com/openhab/openhab-addons/files/10307361/bosesoundtouch_BassChange.log)

**Comment by jlaur** [comment] 2022-12-28 10:14
@lsiepel - will you be able to look into @paeddib's last comment? As last resort, we can revert #13842, but of course it would preferable to get the issues fixed before the hotfix.

**Comment by lsiepel** [comment] 2022-12-28 10:48
Thanks for the heads up, I did not mis it, just have not found the time to get another version out. I think we are almost there. So I prefer not to revert.
Will come back to this tonight or tomorrow. I made my changes to 4.0.0.
I think we should also patch 3.4.0 to get this in 3.4.1 if that is released. How does that workflow go? Does a maintainer cherry pick?

**Comment by jlaur** [comment] 2022-12-28 10:54
@lsiepel - yes, I agree, since it's a regression in 3.4 which seems to have broken the binding, we should include it in the hotfix, that's why I was hunting you. 😁 Let's agree to revert only if the issue is not fixed before we'll release the hotfix. There is no due date yet. And yes, a maintainer will cherry-pick the commit into the 3.4.x branch. FYI @kaikreuzer

**Comment by lsiepel** [comment] 2022-12-28 20:02
Finished another version to test. Als added some tests. I think it improved again. Please let me know your results. The presets is different then the regular channels.

**Comment by Struppie** [comment] 2022-12-29 13:46
Hi @lsiepel ,
I'm also using the Bose SoundTouch binding and gave your latest build (add-on) from yesterday a try.
Result are very good! All reported problems for 3.4.0 release build seem to be fixed!
Switch on/off works fine, switching presets works fine, sending key-code works fine, changing volume works fine and playing information is also update => perfect results from my side. Many thanks for taking care!! :)

**Comment by lsiepel** [comment] 2022-12-29 13:57
Thanks! Now we are set to get this merged i guess!

**Closed** 2022-12-30 12:58 UTC
