### ISSUE TITLE
[miio] Dreame D9 - Add multimap support

### ISSUE THREAD

**Issue by SHU-red** [openhab/openhab-addons#13596] opened 2022-10-24 11:03 UTC
## Your Environment

* Version used: Proxmox(LXCUbuntu22(Docker(openHAB 3.4.0.M3 alpine)))

## Feature Request
Since a longer period of time, the Xiaomi Home App and my Dreame D9 provide the feature of multimaps

I took a look into the current miio-binding documentation and did not see channels pointing to this function

Also my device has none

Im not very deep into how this works but it could be the case, that the vacuum robot is providing these functions in its api and only the miio-binding could be updated?

I'd like to use this function

**Comment by marcelrv** [comment] 2022-11-14 13:55
Would be a great enhancement.
Suggest to add to bountysource to hopefully have someone contribute this, as from my side it will be challenging (time & no access to a similar device) to add this functionality.

**Comment by marcelrv** [comment] 2022-11-15 14:52
Note: Possible duplicate of #13365

**Comment by lsiepel** [comment] 2024-07-23 14:19
Closed as this seems to be a duplicate of #13365

**Closed by lsiepel** 2024-07-23 14:19 UTC
Labels: help wanted
