### ISSUE TITLE
[RFXCOM] - Send RAW request

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab-addons#10274] opened 2021-03-03 00:35 UTC
I would like to send a RAW command using RFXCOM to my unsupported vapouriser. The easiest way to allow this and help anyone else needing an odd command sent seems to be to expand the binding to allow raw packet sending, as it only seems to support receiving only. The RFXCOM Windows App supports RAW and can send the ON command. With the help of RFXCOM support and the RFXCOM Windows App I found the packet below which works from the Windows App. 
The full packet needs 0 and 5 at the beginning followed by

     239 870 785 313 217 861 783 315 220 862 787 310 775 316 212 877 214 865 788 313 774 312 780 307 785 315 209 872 222 868 218 876 214 870 222 871 217 873 214 872 219 862 792 312 775 313 221 869 216 870 223 863 790 309 213 868 784 313 215 874 218 865 785 314 214 6041

According to RFXCOM support 5 is the number of times the packet is repeated

Mapping a string item to the 'RAW Packet with header' channel provides

     0A0301D330567806290448

From the ON Command

**Comment by Jamstah** [comment] 2021-06-14 10:58
Duplicate of #6769

**Closed by Jamstah** 2021-06-14 10:58 UTC
Labels: duplicate
