### ISSUE TITLE
[modbus] 2.5.12 Paper UI Things menu weird

### ISSUE THREAD

**Issue by Rossko57** [openhab/openhab-addons#10309] opened 2021-03-10 20:12 UTC
(Add-ons v2 archive closed for new business.)

Using OH 2.5.12, attempting to add Modbus generic Thing via PaperUI
PaperUI > Configuration > Things > Add+
Displays list of available Things by binding.
Modbus binding absent from this list, but there is one entry for a modbus extension - HeliosEasyControls.
Clicking through that to HeliosEasyControls "Search" page , and then further clicking "add manually", does lead to a list of generic Modbus Thing types and other extension Thing types.

Ideally we should display a single generic Modbus entry on the high-level list and allow click-through to the longer generic Thing types and extension Thing types.

This affects the UI but is I think controlled by binding supplied properties.

**Comment by Rossko57** [comment] 2021-03-13 01:10
Hmm, I think this is a repeat of https://github.com/openhab/openhab-addons/issues/8973

**Comment by ssalonen** [comment] 2021-05-08 05:09
Closing as duplicate of #8973

**Closed by ssalonen** 2021-05-08 05:09 UTC
Labels: duplicate
