### ISSUE TITLE
[hueemulation] HueApp asks for updating the bridge

### ISSUE THREAD

**Issue by CroMarmot1** [openhab/openhab-addons#10485] opened 2021-04-07 11:22 UTC
## Expected Behavior
The emulated bridge should be connected to the Hue app and configurable.

## Current Behavior
Only an update message appears and the emulated bridge cannot be configured. So that no devices can be controlled.

## Possible Solution
Update swversion and/or fwversion for HueEmulation

## Steps to Reproduce (for Bugs)
1. Install add-on "Hue Emulation" and App "Hue".
2. Start the Hue-App, search for the emulated bridge.
3. Activate "Device Pairing" at Hue Emulation.
4. Check the Hue-App.

## Context
It is not possible to connect the "Bridge" with the HueApp, because the update message does not disappear.

* Version used: openHAB 3.0.1, Hue Emulation 3.0.1
* Environment name and version: Chrome (GUI), iOS 14.4 (Hue App)
* Operating System and version: RPi with latest "openHABian" SD image (openHABian v1.6.4)

**Comment by lolodomo** [comment] 2021-04-08 11:44
This is a duplicate of #7191

**Closed by lolodomo** 2021-04-08 11:44 UTC
