### ISSUE TITLE
[network] Include ping and arping in official docker images to avoid unreliable ping

### ISSUE THREAD

**Issue by dafzor** [openhab/openhab-addons#8349] opened 2020-08-26 19:23 UTC
When using " network:pingdevice" against a Windows 10 19041.450 PC with latest patches, if the firewall is active with the IMCP Ping inbound rule active, ping tool will be able to ping the PC, but java ping will fail making the device remain offline.

## Expected Behavior
network:pingdevice should be able to ping the PC correctly.

## Current Behavior
network:pingdevice will fail if windows firewall is active with IMCP inbound allowed.

![image](https://user-images.githubusercontent.com/1612206/91347155-c0653880-e7d9-11ea-9f64-b35716c777e1.png)
(gray is no firewall, black shows when firewall is enabled)

This might have been introduced with a recent windows or openHAB update as it was previously working correctly.

## Possible Solution
Installing ping and arping inside the container image and restarting openhab resolves the issue.

## Steps to Reproduce (for Bugs)
1. Have a windows 10 2004 PC with latest patches
2. Have openHAB running on arm docker host
2. enable firewall on windows with default settings and allow core network diagnostics
3. validate ping works by pinging from docker host
4. verify that openHAB does not see device as online
5. disable windows firewall
6. openHAB ping should now work as expected

## Context
It makes it impossible to create rules that depend on computer shutting down.

## Your Environment
* Version used: openHAB 2.5.8
* OS: armbian 10
* Docker: Docker version 19.03.12, build 48a6621
* Hardware: orangePI PC Plus
* network: host has 2 IP assigned to itself (2nd ip is for another container, i did test with the second IP removed with same results)

**Comment by bodiroga** [comment] 2020-08-27 19:10
Hi @dafzor!

Thanks for your feedback, but, although I'm not a network expert, shouldn't this be reported on the openhab-docker repo? Here you have a link to the issue tracker: https://github.com/openhab/openhab-docker/issues.

**Comment by dafzor** [comment] 2020-08-27 19:16
Hi @bodiroga 

The bug is in the network:pingdevice binding, so that's why I reported it here. I'll "cross-report" it on the docker repo as well.

**Comment by bodiroga** [comment] 2020-08-27 21:38
> The bug is in the network:pingdevice binding, so that's why I reported it here.

Yeah, sure, but the binding doesn't install any network tool, that is something that the OS must have and the binding will make use of it. That's why I think that it belongs to the openhab-docker repo. Anyway, I have seen that you have created the issue there and @wborn has already answered you :wink:

**Comment by Hilbrand** [comment] 2020-08-29 06:30
There haven't been much changes to the network  binding so its not likely the binding is the cause it fails now. As this issue reports a problem and solution that can't be solved in this repo and it has been reported in the correct repo I'll close it here.

**Closed by Hilbrand** 2020-08-29 06:30 UTC
