### ISSUE TITLE
PR-Addon builds failing on integration tests for feed binding

### ISSUE THREAD

**Issue by hmerk** [openhab/openhab-addons#8820] opened 2020-10-21 08:45 UTC
As the title already says, the itests for feed binding seem to be unstable and cause a couple of broken PR-Addon builds.

**Comment by daMihe** [comment] 2020-10-24 05:26
Is there someone already debugging this?

The Question is what changed since 2.x, there the integration tests were quite stable. Now i've watched a build one fundamental change is multithreading which is nice for building but may cause race conditions in integration tests. They are also run concurrently:
![image](https://user-images.githubusercontent.com/1167599/97068674-0ec06900-15ca-11eb-87e7-2470fa92206c.png)

Has someone already looked into it? Are integration tests done in separate environments?

**Comment by wborn** [comment] 2020-10-24 09:06
> The Question is what changed since 2.x, there the integration tests were quite stable. 

The main difference it that Jenkins is now configured to do a parallel build (`-T 1C`). That has reduce build times from 3 hours to just 1 hour. So that puts more load on the system while building and makes timing sensitive tests more likely to fail. So the tests that now fail more commonly, would previously fail occasionally. :wink: 

You can usually reproduce and fix these errors locally by running them while putting some load on your own system.

**Comment by daMihe** [comment] 2020-10-24 10:48
Yes, this allows to use all cores - if i add `-T 8` on my machine (having real 4 cores) i also see many normal tests failing. This is logical if a test requires some timing. Integration tests get usually run against a more or less full environment (here a running OpenHAB instance). In conclusion of multiple OH integration tests in parallel also multiple OH instances have to be started in parallel. This ensures that one integration test is not influencing another by just modifying the same instance.

Currently i'm digging a bit inside the maven tooling and am trying to find something out about the integration test environment. Do you have any further documentation or a hint about this?

Maybe i'm completely wrong, but the kind how the issue is looking is worth a bit attention also that i also had problems with integration tests. Unplanned concurrent execution may cause diffuse issues.

**Comment by wborn** [comment] 2020-10-24 11:19
> Do you have any further documentation or a hint about this?

There is of course the [Integration tests](https://www.openhab.org/docs/developer/tests.html#integration-tests) openHAB documentation. There is also some [Testing](https://bnd.bndtools.org/chapters/310-testing.html) documentation of bnd that launches the test environment. Basically what it does is start all bundles as defined in `itest.bndrun` and then run the JUnit 5 tests.

Usually you can fix the timing issues by making a few small changes so it waits for an assertion to become true instead of failing the test if it isn't immediately true. There's a `waitForAssert` method that you can usually use to fix it, e.g. similar to [openhab-core#1191](https://github.com/openhab/openhab-core/pull/1191/files).

Bnd will launch the itests using their own Java process. So there aren't many issues except for timing and resources conflicts (e.g. if itests use the same TCP port). The feed test for instance already runs on an available port based on the environment variable prepared by the build-helper-maven-plugin (see [pom.xml](https://github.com/openhab/openhab-addons/blob/f5bf17875d12a28b00f8c19a2a588f8f53bf53b8/itests/org.openhab.binding.feed.tests/pom.xml#L46-L65)).

**Comment by wborn** [comment] 2020-12-29 15:20
As there is no specific stacktrace, let's hope it is fixed by https://github.com/openhab/openhab-addons/pull/9565.

**Closed by wborn** 2020-12-29 15:20 UTC
Labels: test
