### ISSUE TITLE
[transform.map] Setting a Switch item value to NULL, shall look for `-=` in a `transform/.map` file, not for `NULL=`.

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-addons#13777] opened 2022-11-23 16:35 UTC
I have a switch in an `.items` file:
```
Switch r2 "2 Реле [MAP(switch.map):%s]" <kitchen> {channel="mqtt:topic:r2:r2"}
```
The file transforms/switch.map contains:
```
ON=Включено
OFF=Изключено
-=-
```
If the `-=-` is missing, there is an exception:
```
2022-11-23 17:29:07.415 [ERROR] [ui.internal.items.ItemUIRegistryImpl] - transformation throws exception [transformation=org.openhab.transform.map.internal.MapTransformationService@7890fe, value=-]                                                                           
org.openhab.core.transform.TransformationException: Target value not found in map for '-'                                               
        at org.openhab.transform.map.internal.MapTransformationService.transform(MapTransformationService.java:93) ~[?:?] 
        at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.transform(ItemUIRegistryImpl.java:551) ~[?:?]
        at org.openhab.core.ui.internal.items.ItemUIRegistryImpl.getLabel(ItemUIRegistryImpl.java:459) ~[?:?]      
        at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.constructSitemapEventForWidget(PageChangeListener.java:236) ~[?:?]                                                                                                                                      
        at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.constructSitemapEvents(PageChangeListener.java:225) ~[?:?]
        at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.constructAndSendEvents(PageChangeListener.java:172) ~[?:?]      
        at org.openhab.core.io.rest.sitemap.internal.PageChangeListener.stateChanged(PageChangeListener.java:186) ~[?:?]                
        at org.openhab.core.items.GenericItem.lambda$1(GenericItem.java:259) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]                             
        at java.lang.Thread.run(Thread.java:829) [?:?]                                                                                  
```

In a `.sitemap` file I have
```
Switch item=r2 
```

My understanding is that a Switch can have only three states: ON, OFF and UNDEFINED⇔NULL.  When the value was never set, Main UI shows at `http://…:8080/settings/items/` NULL for the UNDEFINED value.

Once the value for the switch is set and the device is disconnected, in openhab-JS and I call one of these two options:
```JavaScript
let {NULL} = require("@runtime")

items.getItem("name_it").postUpdate('NULL')
items.getItem("name_it").postUpdate(NULL)
```
the value NULL is searched in transforms/switch.map. But switch.map has no `NULL=`.

The point is, if the `.items` file contains no ` [MAP(switch.map):%s]`, but sitemap has `Switch item=r2 label="2 Реле [MAP(switch.map):%s]"`, then transform/switch.map does not need to contain `NULL=` line.

The problem report is that after sending `items.getItem("name_it").postUpdate("NULL")` to an item with label `"2 Реле [MAP(switch.map):%s]"`, the lookup value in switch.map should be `-=`, but it is `NULL=`.

Currently it is unclear for which state `-=` stands for.  It is neither for `NULL`, nor for `UNDEFINED`.

I use openHAB 3.3.

**Comment by J-N-K** [comment] 2022-11-25 18:18
This is an issue of the MAP transformation, moved to openhab-addons.

**Comment by lolodomo** [comment] 2022-11-29 07:31
Is the file switch.map your file? 
Because I agree that the entry in the map file should be NULL. 
UNDER is also a possible item state.

**Comment by dilyanpalauzov** [comment] 2022-11-29 07:45
> Is the file switch.map your file?
Yes, I have it under /etc/openhab/transforms.

**Comment by lolodomo** [comment] 2022-11-29 11:14
So why did you set this mapping rather than with NULL?

**Comment by dilyanpalauzov** [comment] 2022-11-29 11:44
The system throws the aforementioned exception if `-=-` is missing.

**Comment by lolodomo** [comment] 2024-05-04 07:15
"-" is what sitemap UIs map to when a state is NULL or UNDEF.
It should be the same whether the MAP is in item or sitemap. So no need normally to have NULL and UNDEF entries in the map file.

The problem is that Main UI has a different approach. You will need a NULL and an UNDEF entry in your map file.

I am going to confirm that by testing again.

I don't imagine a specific fix in the MAP transformation because it concerns all transformations. It looks to me like a problem in core framework with two different ways to provide the input to the transformation when a state is NULL or UNDEF.

**Comment by lolodomo** [comment] 2024-05-04 08:41
My items:
```
Switch TestSwitch1 "Switch1 [MAP(en.map):%s]"
Switch TestSwitch2
```
The part of my sitemap:
```
    Frame label="MAP & NULL state" {
        Default item=TestSwitch1
        Default item=TestSwitch2 label="Switch2 [MAP(en.map):%s]"
    }
```
en.map contains a map for "-" but none for NULL or UNDEF:
```
CLOSED=closed
OPEN=open
ON=< On >
OFF=< Off >
__ON__=<<< On >>>
__OFF__=<<< Off >>>
undefined=unknown
-=NULL or UNDEF
```

When I open only Basic UI, I have no warning logged and the result is as expected:
![image](https://github.com/openhab/openhab-addons/assets/10186704/5ba62d42-2a40-4cc4-9602-a8b42f565487)

Now, as soon as I open Main UI, I got this warning:
```
10:28:31.031 [WARN ] [rest.core.item.EnrichedItemDTOMapper] - Failed transforming the state 'NULL' on item 'TestSwitch1' with pattern 'MAP(en.map):%s': Target value not found in map for 'NULL'
```
The warning is repeated when opening the list of items or when opening the page of this item.

Main UI is calling a REST API that calls the transformation with the state "NULL".

As you can notice, the way to call transformation is done differently by Main UI and sitemap UI, sitemap UI is first converting NULL/UNDEF states into "-" before calling the transformation, Main UI does not.

As a workaround until we find a proper fix, to avoid warnings whatever the used UI, the solution for MAP transformation is to add entries for "NULL" and "UNDEF" in addition to "-". For my tests, I used:
```
-=NULL or UNDEF
NULL=This is NULL
UNDEF=This is UNDEF
```

@J-N-K : please move this issue in core.

**Comment by lolodomo** [comment] 2024-05-04 08:52
The "problem" is in the method `considerTransformation` I am already updating in my work in progress PR openhab/openhab-core#4203
But something has to be decided what to do when the state is NULL/UNDEF, should we call the transformation or not ?
The behaviour is not fully consistent when the item state is of type UndefType:

1. `EnrichedItemDTOMapper` is calling the transformation with "NULL" or "UNDEF"
2. `SseItemStatesEventBuilder` is not calling the transformation
3. `ItemUIRegistryImpl` is calling the transformation with "-"

**Comment by lolodomo** [comment] 2024-05-04 09:08
I believe:

1. The transformation should be called, it allows a user to replace "NULL" or "UNDEF" by any label he prefers. So `getDisplayState` in class `SseItemStatesEventBuilder ` has to be changed in my opinion.
2. Do we replace "NULL" and "UNDEF" by "-" before calling the transformation or not ? Doing it let a chance to the user to define a different behaviour for NULL and UNDEF in the transformation. I would be in favour of this solution even if it means users will have to change their transformations if they use sitemap UIs.

WDYT ?

**Comment by lolodomo** [comment] 2024-05-04 09:18
@openhab/core-maintainers for feedback on my analysis and my proposal.

**Comment by lolodomo** [comment] 2024-05-04 12:39
Note that what is done by sitemap UI is a little more than a simple replacement of NULL/UNDEF by "-":
https://github.com/openhab/openhab-core/blob/4dfbfb4995820089fbb92aaa64db09437d7e55ac/bundles/org.openhab.core.ui/src/main/java/org/openhab/core/ui/internal/items/ItemUIRegistryImpl.java#L598

**Comment by lolodomo** [comment] 2024-05-06 13:39
Proposed changes are now implemented in PR openhab/openhab-core#4703

**Comment by lolodomo** [comment] 2024-06-29 09:59
With the last changes in 4.2, if an item state is NULL, searched entry in MAP file will be NULL.
Same principle for UNDEF state, UNDEF entry is searched.
Defining an entry for "-" has no interest if the purpose is to catch NULL or UNDEF. There is now no conversion to "-" before calling the transformation.
If you don't want to add a MAP entry for NULL and UNDEF in your MAP file, you have also the option to define a default value in your MAP file. Look at the documentation of the MAP transformation. And if no default value is set, sitemap UIs will display "-" as state for NULL and UNDEF states.

I close this issue.

**Closed by lolodomo** 2024-06-29 09:59 UTC

**Comment by jlaur** [comment] 2024-06-29 10:22
@lolodomo - for a `String` item type, is it possible to map "NULL"/"UNDEF" dfferently than NULL/UNDEF?

**Comment by dilyanpalauzov** [comment] 2024-06-29 10:37
If my reading is correct, that the former `-=…` in transform files must be replaced with `NULL=…`, `UNDEF=…`, then this change should be spelled explicitly in the upgrade notes for 4.2.

**Comment by lolodomo** [comment] 2024-06-29 10:53
> If my reading is correct, that the former `-=…` in transform files must be replaced with `NULL=…`, `UNDEF=…`, then this change should be spelled explicitly in the upgrade notes for 4.2.

Yes, it would be better to mention it even if most of users are probably already using a default value in their MAP files, either
`=any text you would like as default`
or
`=_source_`

"-" as entry was only used by sitemap UIs, not Main UI.

**Comment by lolodomo** [comment] 2024-06-29 10:59
> @lolodomo - for a `String` item type, is it possible to map "NULL"/"UNDEF" dfferently than NULL/UNDEF?

Yes man ;) that is exactly what allows the changes. Look at the example in the merged PR.

**Comment by lsiepel** [comment] 2024-06-29 10:59
> If my reading is correct, that the former `-=…` in transform files must be replaced with `NULL=…`, `UNDEF=…`, then this change should be spelled explicitly in the upgrade notes for 4.2.

Upgrade notice should go here: https://github.com/openhab/openhab-distro/blob/main/distributions/openhab/src/main/resources/bin/update.lst

**Comment by lolodomo** [comment] 2024-06-29 11:29
PR created but needs to be rebased.
