### ISSUE TITLE
[evcc] problems with EVCC binding after upgrade to 3.4.1

### ISSUE THREAD

**Issue by mj6517** [openhab/openhab-addons#14231] opened 2023-01-15 23:14 UTC
Hello,

after the upgrade to 3.4.1 the evcc binding only works to a very limited extent. Control of charging settings from openHAB is no longer possible.
I have installed openHAB and evcc on the same rasperry using openHABian. The binding has worked very perfect since October 2022. but now I only see some read-only power-data from evcc.

## Expected Behavior
if I change items in openHAB, the changes should be applied synchronously to evcc and vice versa

## Current Behavior
it is not possible to change the items in openHAB. The charging settings are also shown wrong in openHAB.

## Possible Solution
maybe a problem with write-permission?

## Steps to Reproduce (for Bugs)
The charging settings is can not be changed. They show wrong values and can not be changed

```
Setpoint item=evcc_xx_loadpoint0_targetSoC minValue=5 maxValue=100 step=5
Setpoint item=evcc_xx_loadpoint0_minCurrent minValue=6 maxValue=96 step=2
Setpoint item=evcc_xx_loadpoint0_maxCurrent minValue=6 maxValue=96 step=2
Setpoint item=evcc_xx_loadpoint0_minSoC minValue=0 maxValue=100 step=5
Setpoint item=evcc_xx_loadpoint0_phases minValue=1 maxValue=3 step=2
```

## Context
I can use evcc only with evcc gui. My openHAB sitemap and openHAB rules do not work any longer.

## Your Environment

openHAB 3.4.1 - Release Build
Release = Raspbian GNU/Linux 11 (bullseye)
Kernel = Linux 5.15.84-v7+
Platform = Raspberry Pi 3 Model B Plus Rev 1.3
evcc v0.111.1

**Comment by florian-h05** [comment] 2023-01-16 22:43
openHAB 3.4.1 changed nothing in the evcc Binding.
Have you updated evcc?

**Comment by mj6517** [comment] 2023-01-16 23:34
I have installed evcc via   openHABian Configuration Tool  <sudo openhabian-config>.  When I do a "Upgrade System" in  openHABian Configuration Tool the evcc is also always updated. So yes, I also updated evcc. With the last update it was updated to evcc v0.111.1
Log file is added.
[openhab_DEBUG.log](https://github.com/openhab/openhab-addons/files/10429967/openhab_DEBUG.log)

**Comment by mj6517** [comment] 2023-01-16 23:43
the evcc GUI works. In openHAB the read-only data is shown, correctly but it is not possible to change anything.
![IMG_0054](https://user-images.githubusercontent.com/112985548/212780933-3e3f3bf9-bd3c-4542-8292-bd85c7ac282b.PNG)
![IMG_0055](https://user-images.githubusercontent.com/112985548/212780946-1db4e852-5147-4536-975e-a6e3972dd282.PNG)
![IMG_0057](https://user-images.githubusercontent.com/112985548/212780978-73c735f6-2e20-46b1-9eda-3866ed99c43c.PNG)

![IMG_0056](https://user-images.githubusercontent.com/112985548/212780967-c817f7c3-7092-4b41-bca2-3789356a9de2.PNG)

**Comment by florian-h05** [comment] 2023-01-17 06:02
Thanks for the info.
Have you tried to change something from openHAB while collecting the log? I guess no, because your log file doesn’t include command handling logs. Can you please give me a log while trying to change settings?

**Comment by mj6517** [comment] 2023-01-17 06:11
it's strange, I tried to change charging settings in openhab, but that didn't do anything. The values are somehow "fixed". EVCC worked fine the whole time, there charging was active and I could change charging mode in evcc directly.
I want to mention that everything else in openhab works fine (KNX, Shelly, Modbus, Openweathermap, Z-Wave ...)

**Comment by mj6517** [comment] 2023-01-17 06:29
sorry ... now the logfile has some entries. No vehicle is plugged in, so I could change easily. The actions in openhHAB didn't have any effect in evcc. The other way round it somehow works, if I change charging settings in evcc it is reflected in opneHAB.
[openhab_DEBUG2.log](https://github.com/openhab/openhab-addons/files/10431984/openhab_DEBUG2.log)

**Comment by florian-h05** [comment] 2023-01-17 07:01
State updates work fine, that doesn‘t wonder me. 
I am however wondering why the commands fail. The log tells that the binding receives the commands, but it however doesn‘t handle it. Because of the log messages, I guess the problem is in one of these two lines:

https://github.com/openhab/openhab-addons/blob/80094b5e9d293dfb73c81377325da13172d6baaf/bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java#L84-L92

I will check if I can reproduce - if not, I will extend the logging at these points and provide you an artifact with extended logging to get an idea what‘s the prooblem.

**Comment by florian-h05** [comment] 2023-01-18 16:50
I can reproduce, it is no problem with the openHAB code, evcc has just changed their API (again). I have opened a PR with the fix, I will also provide it in the marketplace so you can use it without having to wait for the next openHAB release.

**Comment by florian-h05** [comment] 2023-01-18 17:05
See https://github.com/florian-h05/openhab-addons/releases/tag/evcc-0.6 for the fix release.

**Comment by mj6517** [comment] 2023-01-18 21:25
Thank you. I have implemented the fix via console using  bundle:update .... described here: https://www.openhab.org/docs/administration/bundles.html
To be on the save side, I've also rebooted.

I'm afraid, at least in my environment it is now possible again to change the mode in both ways. Unfortunately, it still doesn't work to change Minimum SoC and Target SoC. Behaviour is like before. In openhab they are "fixed" to "0", no change possible. The Battery SoC shows also 0% which is wrong. Maybe you could have another look? 
Maybe it's bug on evcc side?

**Comment by mj6517** [comment] 2023-01-22 22:17
https://github.com/openhab/openhab-addons/pull/14245 has solved this issue. Thank you

**Comment by jlaur** [comment] 2023-01-23 07:38
> https://github.com/openhab/openhab-addons/pull/14245 has solved this issue. Thank you

This issue will be closed automatically when the pull request is merged. Until then I have reopened it.

**Closed** 2023-01-23 20:17 UTC
