### ISSUE TITLE
[hueemulation] setting Dimmer items to "xx%" works, but Alexa claims there is a problem: "... appears to be malfunctioning"

### ISSUE THREAD

**Issue by cherub-i** [openhab/openhab-addons#6690] opened 2019-12-27 12:47 UTC
## Expected Behavior
When commanding a dimmer item via Alexa (e.g.: "Alexa, set Test to 50%"), the item should change its brightness and **Alexa should not report any problems**.

## Current Behavior
Voice command "Alexa, set Test to 50%", Test changes brightsness to 50% accordingly, but still Alexa responds "Test appears to be malfunctioning".
Voice command "Alexa, set Test to 0%", Test goes off accordingly, but still Alexa responds "This value is outside the range of the device".

## Steps to Reproduce
My test setup:
- a dummy Dimmer item ```Dimmer DTest "Test"  (GDebug) ["Lighting"]```
- this item can be controlled via Alexa via voice
- I can verify via the JSON from the API (http://192.168.2.200/api/testuser/lights/69), that the ```bri```-value changes according to voice
```
{
  "state": {
    "bri": 206,
    "ct": 500,
    "on": true,
    "reachable": true,
    "mode": "homeautomation",
    "alert": "none"
  },
  "type": "Color temperature light",
  "modelid": "LTW001",
  "uniqueid": "02c09d5c-3116-4074-9720-0b2ba01cbf3f-69",
  "manufacturername": "Philips",
  "swversion": "66012040",
  "friendsOfHue": true,
  "colorGamut": "2200K-6500K",
  "hascolor": false,
  "name": "Test",
  "config": {
    "archetype": "classicbulb",
    "function": "functional",
    "direction": "omnidirectional"
  },
  "capabilities": {
    "certified": true,
    "streaming": {
      "renderer": false,
      "proxy": false
    },
    "control": {}
  }
}
```
- I can also see the change in the slider representation in the HTML sitemap

The following is a list of voice commands // the log statement // the JSON // the response from Alexa (sorry for the German, as it is pretty straight forward, I didn't bother to translate):
- "Alexa, schalte Test ein" //  log: DTest changed from 0 to 100 // JSON: "bri":254 // no error from Alexa
- "Alexa, Test auf 50%" // log: DTest changed from 100 to 50 // JSON: "bri":127 // "Test scheint nicht richtig zu funktionieren" 
- "Alexa, Test auf 51%" // log: DTest changed from 50 to 51 // JSON: "bri":130 // no error from Alexa
- "Alexa, Test auf 52%" // log: DTest changed from 51 to 52 // JSON: "bri":132 // "Test scheint nicht richtig zu funktionieren"
- "Alexa, schalte Test ein" //  log: DTest changed from 0 to 100 // JSON: "bri":254 // no error from Alexa
- "Alexa, Test auf 51%" // log: DTest changed from 50 to 51 // JSON: "bri":130 // no error from Alexa
- "Alexa, Test auf 0%" // log: DTest changed from 51 to 0 // JSON: "bri":0 // "Der Wert liegt außerhalb des Bereichs für das Gerät Test"
- "Alexa, Test auf 1%" // log: DTest changed from 0 to 2 // JSON: "bri":5 // "Test scheint nicht richtig zu funktionieren"

What do I take from that?
- all commands make the item itself do what it should
- but most of the time, Alexa claims that something went wrong
- many "set Test to xx%" values result in Alexa claiming: "... appears to be malfunctioning" (*note: this may not be the correct English translation, I am only sure about the german voice output*)
-- **but some values (51%, also 74% - probably others too) do not result in such an error output**
- when setting the value to 0%, Alexa claims: "this value is outside the range of the device" (*again: this may not be the correct English translation*)

As some numbers work and others don't, I suspect that the problem could be connected to some rounding issues, but that is for someone else to really inspect and find out - my coding skills are way to bad to do it myself.

## Your Environment
OH 2.5 release version, running in a docker container on port 80,  “Optional Discovery Web Port” in the Hue Emulation setttings is set to 80.

**Comment by cherub-i** [comment] 2019-12-27 12:48
This is my first issue here. Please do tell me, if I need to do something differently to do this in way, that it is helpful for everyone involved.

**Comment by MikeJMajor** [comment] 2020-01-24 22:51
When I monitor the HTTP traffic between an echo and OH I see the following:

1. Echo sends PUT request to OH with new brightness value
2. OH responds with success and returns the new brightness level
3. Echo seems to send up to three GET requests to retrieve the state of the bulb.

On my system the first response to the GET always seems to be the old value of the brightness because this is derived from the real state of the OH item which has not yet updated to the new brightness. 
When I get the error the next two responses to the GET requests return the new value off by 1, e.g. setting brightness to 50% sends 128 in the PUT request, but gets 127 back in the GET response.

So I'm guessing Alexa responds with the error when after three status requests the bulb state does not match what it expects.

I'm sure the conversion between hue values and OH values has always had the problem of being off by one, but Alexa checking the status and complaining when it doesn't match is probably new behaviour.

**Comment by MikeJMajor** [comment] 2020-01-25 09:08
The issue is that OH stores a brightness as a value 0 to 100, but hue uses 0 to 254. It's not possible to convert from a hue range to an OH range and back to a hue range and always get the original number.

The only fix I can think of for this issue would be to cache the last state received on the rest API and use this combined with the real state of the OH item to determine the value to send back. E.g. if the rest brightness is 128, but OH says 127 then since 128 and 127 represent the same OH value of 50 then we would send back 128. If the OH value doesn't match, e.g. it gives 200 then assume it's been changed outside of the hue emulation and send back 200.

@davidgraeff does this seem a reasonable change to make?

**Comment by cherub-i** [comment] 2020-01-31 08:07
@MikeJMajor thank you for picking this up providing a fix - I see that your PR is already underway.
I had an idea how to approach the issue other than with a cache. It is not thought through, but I wanted to toss it out to you anyway: what about introducing a kind of mapping table between values from 0..100 and a fixed corresponding value from 0..255?
If one could use this instead of the real mathematical conversion in all the relevant places, then it  should eliminate the deviations which lead to Alexa's complaints.

**Comment by rancor187** [comment] 2020-05-31 10:48
Hi there and thank you for the fix.

Unfortunately for me I use ROLLERSHUTTER items instead of DIMMER items and I still encounter the issue, but only when I want to send my rollershutters downwards.
I am on **OH 2.5.4** and this is one of the candidates:

`Rollershutter		 	Proxy_JA3_R2_Level_RS			"Rollo Bathroom [%s]"											["Lighting"]`

Once these items where added as devices in the Alexa App I started to test voice commands:

> **Alexa Rollo Bathroom 25%**	- Works just fine
**Alexa Rollo Bathroom 33**	- Works just fine
**Alexa Rollo Bathroom Down**	- Does the job, but Alexa: "'Rollo Bathroom' doesn't seem to work properly"
**Alexa Rollo Bathroom Off**	- Does the job, but Alexa: "'Rollo Bathroom' doesn't seem to work properly"
**Alexa Rollo Bathroom Up**	- Works just fine

_This is a rough translation from the German response of Alexa and the voice commands._


Is there anything that I could do about it?
Thank you.

**Comment by mstormi** [comment] 2020-06-26 13:27
I have a similar problem , Alexa to complain although it properly executes the command. 

events.log confirms :
`2020-06-26 14:46:21.333 [ome.event.ItemCommandEvent] - Item 'mobil_Iris2' received command 0,100,0`

Here's a HTTP dump of a color change command:
```
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
15:21:14.438991 IP alexa.fritz.box.39944 > openhab.http: Flags [P.], seq 1749487542:1749487736, ack 3883733751, win 913, options [nop,nop,TS val 2238154 ecr 2184185787], length 194: HTTP: PUT /api/c8b3021d-e6bb-4ce2-b4f3-                6f4f230385bf/lights/89/state HTTP/1.1
E...)v@.@.*....-...(...PhG...}.............
."&..0..PUT /api/c8b3021d-e6bb-4ce2-b4f3-6f4f230385bf/lights/89/state HTTP/1.1
Host: 192.168.178.40
Accept: */*
Content-Type: application/json
Content-Length: 33

{"on":true,"hue":46421,"sat":127}
15:21:14.461329 IP openhab.http > alexa.fritz.box.39944: Flags [P.], seq 1:656, ack 194, win 508, options [nop,nop,TS val 2184185819 ecr 2238154], length 655: HTTP: HTTP/1.1 200 OK
E.....@.@......(...-.P...}..hG.x.....\.....
.0..."&.HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Fri, 26 Jun 2020 13:21:14 GMT
Content-Type: application/json
Content-Length: 126
Connection: keep-alive
Access-Control-Allow-Origin: http://localhost:8080/rest,http://openhabianpi:8080/rest
Access-Control-Allow_Credentials: true
Access-Control-Allow-Headers: Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE,PATCH

[{"success":{"/lights/89/state/hue":46421}},{"success":{"/lights/89/state/on":true}},{"success":{"/lights/89/state/sat":127}}]
15:21:14.573738 IP alexa.fritz.box.39946 > openhab.http: Flags [P.], seq 2611470708:2611470843, ack 940295630, win 913, options [nop,nop,TS val 2238187 ecr 2184185929], length 135: HTTP: GET /api/c8b3021d-e6bb-4ce2-b4f3-6                f4f230385bf/lights/89 HTTP/1.1
E.....@.@......-...(.
.P...t8.......n......
."&..0.IGET /api/c8b3021d-e6bb-4ce2-b4f3-6f4f230385bf/lights/89 HTTP/1.1
Host: 192.168.178.40
Accept: */*
Content-Type: application/json


15:21:14.625841 IP openhab.http > alexa.fritz.box.39946: Flags [P.], seq 1:1196, ack 135, win 509, options [nop,nop,TS val 2184185983 ecr 2238187], length 1195: HTTP: HTTP/1.1 200 OK
E....Z@.@.c....(...-.P.
8............x.....
.0..."&.HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Fri, 26 Jun 2020 13:21:14 GMT
Content-Type: application/json
Content-Length: 666
Connection: keep-alive
Access-Control-Allow-Origin: http://localhost:8080/rest,http://openhabianpi:8080/rest
Access-Control-Allow_Credentials: true
Access-Control-Allow-Headers: Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range
Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE,PATCH

{"state":{"hue":0,"sat":0,"xy":[0.0,0.0],"effect":"none","transitiontime":0,"colormode":"ct","bri":254,"ct":500,"on":true,"reachable":true,"mode":"homeautomation","alert":"none"},"type":"Extended Color light","modelid":"L                CT010","uniqueid":"08cc1e02-8a39-496d-9010-e707126ce0f3-89","manufacturername":"Philips","swversion":"1.15.2_r19181","swconfigid":"F921C859","productid":"Philips-LCT010-1-A19ECLv4","friendsOfHue":true,"colorGamut":"C","ha                scolor":true,"name":"Kugelleuchte mobil","config":{"archetype":"classicbulb","function":"functional","direction":"omnidirectional"},"capabilities":{"certified":true,"streaming":{"renderer":false,"proxy":false},"control":{                }}}
15:21:14.661801 IP alexa.fritz.box.39948 > openhab.http: Flags [P.], seq 1835409722:1835409857, ack 1232458602, win 913, options [nop,nop,TS val 2238209 ecr 2184186017], length 135: HTTP: GET /api/c8b3021d-e6bb-4ce2-b4f3-                6f4f230385bf/lights/89 HTTP/1.1
E.....@.@.L....-...(...Pmf!:Iu.j....=......
."'..0..GET /api/c8b3021d-e6bb-4ce2-b4f3-6f4f230385bf/lights/89 HTTP/1.1
Host: 192.168.178.40
Accept: */*
Content-Type: application/json


15:21:14.676658 IP openhab.http > alexa.fritz.box.39948: Flags [P.], seq 1:1196, ack 135, win 509, options [nop,nop,TS val 2184186034 ecr 2238209], length 1195: HTTP: HTTP/1.1 200 OK
E.....@.@.Rv...(...-.P..Iu.jmf!......x.....
.0..."'.HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Fri, 26 Jun 2020 13:21:14 GMT
Content-Type: application/json
Content-Length: 666
Connection: keep-alive
Access-Control-Allow-Origin: http://localhost
```

I've encountered that on ColorLighting items (this one) and Rollershutters (tagged as "Lighting")

**Comment by MikeJMajor** [comment] 2020-06-26 20:26
@mstormi can you provide your item definition and what was the colour change command issued to Alexa?

**Comment by mstormi** [comment] 2020-06-26 20:31
Switch mobil_Iris2            "Kugelleuchte mobil"    <hue>   (hue,Lichter,Blinklicht)        ["ColorLighting"]       { channel="hue:0200:00178811d1d7:1:color" }

Command was something like "Alexa set Kugelleuchte mobil to red" (the equivalent German, actually).

The item was correctly identified and the color was right, too. And it *did* switch to that color.
Only error was that it complains "appear to be malfunctioning" after that (again in German, actually)

**Comment by MikeJMajor** [comment] 2020-06-26 21:09
The reason is due to your item being defined as a switch. Since a switch only has an on/off state it's not possible to return the colour back to Alexa when it asks for its current state.

My fix relies on the state of the item matching the command that was sent to it. In your case it received a command of red, but the state is on.

**Comment by mstormi** [comment] 2020-06-26 21:19
Ah, makes sense. I'll change it to the Color type item.
I have a similar problem with a Rollershutter item (used like a dimmer as Alexa/Hue does not know shutters).
Any idea what to do there ?

**Comment by MikeJMajor** [comment] 2020-06-26 21:41
Can you add your item definition for the Rollershutter.

**Comment by mstormi** [comment] 2020-06-26 21:56
just standard
Rollershutter EG_Wohnen_Jalousie_links "Raffstore links [%d %%]"            <rollershutter> (EG_Wohnen,Rolladen,Jalousien) ["Lighting"]     { channel="zwave:device:dddxxxxx:node113:blinds_control" }

**Comment by MikeJMajor** [comment] 2020-06-26 22:17
In the event log how long is the delay from the item receiving the command to the item actually changing state?

**Comment by mstormi** [comment] 2020-06-26 22:20
ugh, cannot test ATM sorry but I remember it was almost instantaneous

**Comment by MikeJMajor** [comment] 2020-06-26 22:25
When you get time can you add the relevant bits from the event log and also a tcpdump.

**Comment by mstormi** [comment] 2020-06-26 22:42
Ok, I need to revise my report.  Almost everything to work with that rollershutter now. The only thing is it refuses to switch off, speaking the message from the title. But "ON", "UP" and "DOWN" work instantaneously.
It may or may not be that that is because I just un+re-installed hueemulation. Either way, it's working now. By the time it didn't there was some more stuff to temporarily not work but I cannot reproduce the state.

I'll close this issue. If I were to encounter another instance of this I'll reopen.
Thanks a lot for your support!

**Closed by mstormi** 2020-06-26 22:42 UTC
