### ISSUE TITLE
[Ecovacs] Ask for support for Deebot X2 Omni

### ISSUE THREAD

**Issue by magicmax1967** [openhab/openhab-addons#16321] opened 2024-01-23 23:22 UTC
Hello, as request i need support for Deebot X2 Omni, here the log line:

2024-01-24 00:08:04.971 [INFO ] [acs.internal.api.impl.EcovacsApiImpl] - Found unsupported device DEEBOT X2 (class lf3bn4, company eco-ng), ignoring.

Thank you for your great job
Massimo

## Environment
 * openHAB version 4.1.1 + Zulu JDK 17 on Windows 10 Home

**Comment by maniac103** [comment] 2024-02-27 13:29
This is a duplicate of #16117

**Closed by maniac103** 2024-02-27 13:29 UTC
