### ISSUE TITLE
[xmppclient] Not all dependencies are automatically resolved

### ISSUE THREAD

**Issue by pavel-gololobov** [openhab/openhab-addons#5473] opened 2019-04-17 11:14 UTC
## Expected Behavior
1. Install XMPP Client Binding from online Add-ons repository from Paper UI.
2. The binding and all its dependencies are installed and ready to work.

Correct list of bundles:

```
210 │ Active │  80 │ 4.3.3                 │ smack-core
211 │ Active │  80 │ 4.3.3                 │ smack-extensions
212 │ Active │  80 │ 4.3.3                 │ smack-im
213 │ Active │  80 │ 4.3.3                 │ smack-tcp
214 │ Active │  80 │ 0.6.3                 │ jxmpp-core
215 │ Active │  80 │ 0.6.3                 │ jxmpp-jid
216 │ Active │  80 │ 0.6.3                 │ jxmpp-util-cache
217 │ Active │  80 │ 0.3.3                 │ minidns-core
218 │ Active │  80 │ 2.5.0.201904131627    │ openHAB Add-ons :: Bundles :: XMPPClient Binding
219 │ Active │  80 │ 1.1.4                 │ XPP3 Library
220 │ Active │  80 │ 4.3.3                 │ smack-java7
221 │ Active │  80 │ 4.3.3                 │ smack-resolver-javax
```

## Current Behavior
1. Install XMPPClient Binding from online Add-ons repository from Paper UI.
2. Binding is installed, but not all of its dependencies.

Incorrect list of bundles:

```
210 │ Active │  80 │ 4.3.3                 │ smack-core
211 │ Active │  80 │ 4.3.3                 │ smack-extensions
212 │ Active │  80 │ 4.3.3                 │ smack-im
213 │ Active │  80 │ 4.3.3                 │ smack-tcp
214 │ Active │  80 │ 0.6.3                 │ jxmpp-core
215 │ Active │  80 │ 0.6.3                 │ jxmpp-jid
216 │ Active │  80 │ 0.6.3                 │ jxmpp-util-cache
217 │ Active │  80 │ 0.3.3                 │ minidns-core
218 │ Active │  80 │ 2.5.0.201904160039    │ openHAB Add-ons :: Bundles :: XMPPClient Binding
219 │ Active │  80 │ 1.1.4                 │ XPP3 Library
```

Missed bundles:

* smack-java7
* smack-resolver-javax

## Possible Solution
Add missed jar-s (smack-java7-4.3.3.jar and smack-resolver-javax-4.3.3.jar) to `addons` folder.

After manually installing the missing bundles, the binding works correctly.

## Steps to Reproduce (for Bugs)
1. Install XMPPClient Binding from online Add-ons repository from Paper UI.
2. bundle:list from console

## Context
Karaf feature.xml file looks like correct:

```
<feature name="openhab-binding-xmppclient" description="XMPP Client Binding" version="${project.version}">
        <feature>openhab-runtime-base</feature>
        <feature prerequisite="true">wrap</feature>
        <!-- Main dependencies -->
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-java7/4.3.3</bundle>
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-extensions/4.3.3</bundle>
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-im/4.3.3</bundle>
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-tcp/4.3.3</bundle>
        <!-- Dependencies of dependencies -->
        <bundle dependency="true">mvn:org.jxmpp/jxmpp-core/0.6.3</bundle>
        <bundle dependency="true">mvn:org.jxmpp/jxmpp-jid/0.6.3</bundle>
        <bundle dependency="true">mvn:org.jxmpp/jxmpp-util-cache/0.6.3</bundle>
        <bundle dependency="true">mvn:org.minidns/minidns-core/0.3.3</bundle>
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-core/4.3.3</bundle>
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-resolver-javax/4.3.3</bundle>
        <bundle dependency="true">mvn:org.igniterealtime.smack/smack-sasl-javax/4.3.3</bundle>
        <bundle dependency="true">wrap:mvn:xpp3/xpp3/1.1.4c$Bundle-Name=XPP3%20Library&amp;Bundle-SymbolicName=xpp3-xpp3&amp;Bundle-Version=1.1.4</bundle>
        <bundle start-level="80">mvn:org.openhab.addons.bundles/org.openhab.binding.xmppclient/${project.version}</bundle>
</feature>
```

## Your Environment
* Version used: 2.5.0-SNAPSHOT Build 1571
* Operating System and version: x86, Linux Debian 9.

Please help. I am not very familiar with karaf.

**Comment by J-N-K** [comment] 2019-05-24 17:36
I can confirm the behaviour and can'r explain it. But why do we need these bundles at all? Removing them from the feature (and the `smack-java7` from the dependencies still compiles and passes feature verification. Also All bundles activate in my test setup, even if those two are missing. Maybe they are not installed because they are marked as dependency bit not required by any other bundle?

**Comment by pavel-gololobov** [comment] 2019-05-27 08:47
Yes, these dependencies are used implicitly. But without them binding does not work. This occurs only when trying to connect to a real server.

**Comment by pavel-gololobov** [comment] 2019-05-27 08:52
I can provide an Jabber account on my own server for testing.

**Closed** 2019-06-12 19:52 UTC
Labels: infrastructure
