### ISSUE TITLE
[homekit] out of a sudden "no response"

### ISSUE THREAD

**Issue by Stefan300381** [openhab/openhab-addons#15348] opened 2023-08-01 10:16 UTC
Hi, 

Using latest OH 4.0 Milestone inside docker with homekit integration enabled.
I'm facing unexpected "no response" messages inside Apple Home app, as described in this community thread: https://community.openhab.org/t/homekit-no-response-error-on-all-openhab-items/118200/202

The container is configured to use the host network (which support ipv4 and ipv6).

Unfortunately I don't know what triggers this behavior and I haven't found a way to reproduce the issue. I just know how to fix it temporarily:

It helps to open OH main UI and edit the homekit integration settings, turning mDNS on or off. This means, whenever it's ON and I turn it OFF, homekit items can be controlled again. Same if the setting was turned off and I turn it on.

Is this a known issue? Anything I can do/provide in order to troubleshoot the issue?

best regards

Stefan

**Comment by lsiepel** [comment] 2023-08-08 20:47
Have it once in a while. After some time it is back to normal. Also never found the cause. It used to be much more  unstable with earlier versions.

you might consider logging debug level to separate file. And as soon as you encounter the issue, make a copy and analyse it.
Not sure if it helps, maybe worth the try?

**Comment by yfre** [comment] 2023-08-08 21:13
this issue is typically linked to fast changes on network interface. e.g. network interface get disconnected/down and connected/up again within seconds. 
on disconnect event, openHAB homekit addon stops advertising itself and as result, home app cannot find it anymore. normally, homekit addon would re-start advertising itself once the network interface is up again, but if it happens too quickly it might miss it. switching mDNS on/off forces addon to advertise itself

some more technical details are provided here
https://community.openhab.org/t/homekit-stops-working-after-some-hours-openhab-3-4-0/142502/43

ideally, you should try to fix the root cause, i.e. network disconnection, but im not sure how to troubleshoot and fix it on docker.

**Comment by lsiepel** [comment] 2023-08-08 21:50
In my case openHAB is hosted on a dedicated intel nuc, connected by Ethernet cable. The network connection is rock solid. 
I would be very surprised if this is the cause for the problem I experience once in a while.

**Comment by lsiepel** [comment] 2023-08-09 10:39
> do we have in common, that we run openHAB inside a Docker container?

No, mine is not in some sort of container

**Comment by yfre** [comment] 2023-08-09 16:40
it is not like physical network connection gets distributed but more kind of dhcp lease / ip / mac address update causing for a short network interface restart. this what i have observed on my side.
maybe it is something else in your case. 
i would suggest to enable more logging and also check linux/os system logs.. but if it is not reproducible it can create a lot of log before it happens again

**Comment by lsiepel** [comment] 2023-08-09 19:05
Will do, thanks

**Comment by lsiepel** [comment] 2024-07-30 13:00
Never had these transient problems again. Will close this for now.

**Closed by lsiepel** 2024-07-30 13:00 UTC
