### ISSUE TITLE
[unifi] OH 2.5 Binding broken for UniFi OS

### ISSUE THREAD

**Issue by TilmanGuenther** [openhab/openhab-addons#10837] opened 2021-06-09 12:56 UTC
**UPDATE:**

The problem is that UniFi OS changed how auth works, and this issue has already been fixed in 3+ releases. Someone would need to back-port a patch for OH 2.5

After my local Unifi Network was updated to version 6+, the binding no longer connects to the controller. In the UI, this shows as OFFLINE - COMMUNICATION_ERROR

## Expected Behavior
The bridge should connect to the UniFi software

## Current Behavior
Attempted to change thing port to 443 in bridge Thing config, only result in this log error:

`Unhandled exception while refreshing the UniFi Controller unifi:controller:a2bc7a83 - com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 12 path $`

## Steps to Reproduce (for Bugs)
1. Update UniFi software to 6+
2. Attempt to connect to a UniFi controller

## Context
Without connection to the bridge, the entire binding is effectively non-functional. 

## Your Environment
* Openhab 2.5.10
* UniFi Software Version 6.0.44

**Comment by Marmoset-threat** [comment] 2021-06-10 12:52
Alright, I've narrowed down the problem somewhat, specifically, I downgraded my UniFi version to 5.14.23 again, but it still doesn't work. Now I think the problem is the update on the cloud key has moved the access IP from 192.168.1.xxx:8443 to 192.168.1.xxx/network.

**Comment by Marmoset-threat** [comment] 2021-07-04 15:18
This is probably the fix that is missing: https://github.com/openhab/openhab-addons/pull/10041

**Comment by Hilbrand** [comment] 2022-01-04 12:03
Is this an issue with 2.5 only? In which case this issue can be closed as there is no support for 2.5 issues here.

**Comment by Marmoset-threat** [comment] 2022-01-04 15:42
@Hilbrand As far as I know, yes, although I ended up manually fixing it here: https://community.openhab.org/t/ubiquiti-unifi-binding-feature-discussion/14520/1179

The fix is simple enough that anyone who has the dev environment setup and can use git properly (I can't) should be able to fix it.

**Comment by lsiepel** [comment] 2022-12-31 14:14
As there is support for Unifi OS since version 3.1.0 of the binding i mark this as resolved. 2.5 is no longer supported.

**Closed by lsiepel** 2022-12-31 14:14 UTC
