### ISSUE TITLE
[fmiweather] stopped working, because FMI has stopped the HIRLAM weather forecast model.

### ISSUE THREAD

**Issue by meganiekje** [openhab/openhab-addons#13645] opened 2022-11-02 16:21 UTC
## Expected Behavior

It did work fine until November 1st.

## Current Behavior

FMI has switched to an other (better) forcast model, and the HIRLAM service is stopped.

## Possible Solution

Hopefully the binding can be adapted to read the new forcast model ?

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and add-on versions) 3.2.0.
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): windows10

**Comment by nils** [comment] 2022-11-10 20:23
Unfortunately it looks like only "northern Europe" is supported by the new HARMONIE weather model.

> In Northern Europe, the HARMONIE (MEPS) weather forecast data can be used as a replacement weather forecast model. 

This is confirmed by trying to get [data for Stuttgart, Germany](https://opendata.fmi.fi/wfs?endtime=2022-11-12T22%3A20%3A00Z&latlon=48.7758%2C9.1829&parameters=Temperature%2CHumidity%2CWindDirection%2CWindSpeedMS%2CWindGust%2CPressure%2CPrecipitation1h%2CTotalCloudCover%2CWeatherSymbol3&request=getFeature&service=WFS&starttime=2022-11-10T20%3A00%3A00Z&storedquery_id=fmi%3A%3Aforecast%3A%3Aharmonie%3A%3Asurface%3A%3Apoint%3A%3Amultipointcoverage&timestep=20&version=2.0.0): 

> <ExceptionText>No data available for 'Akademiegarten'!</ExceptionText>

[Data for Hamburg, Germany](https://opendata.fmi.fi/wfs?endtime=2022-11-12T22%3A20%3A00Z&latlon=53.5502%2C9.9920&parameters=Temperature%2CHumidity%2CWindDirection%2CWindSpeedMS%2CWindGust%2CPressure%2CPrecipitation1h%2CTotalCloudCover%2CWeatherSymbol3&request=getFeature&service=WFS&starttime=2022-11-10T20%3A00%3A00Z&storedquery_id=fmi%3A%3Aforecast%3A%3Aharmonie%3A%3Asurface%3A%3Apoint%3A%3Amultipointcoverage&timestep=20&version=2.0.0) is available however.

**Comment by meganiekje** [comment] 2022-11-26 10:04
@nils : I'm very happy that you are working on this problem !
Can you please tell me how I can use your test version in my OH3 system?
I 'need' this binding to optimize my Tado heating system, to predict sunshine, and prevent unnessesary heating if prevailing weather id < 3.
Thanks in advance !!

**Comment by lsiepel** [comment] 2023-11-12 20:26
Looks like the related PR was merged and the binding has been fixed since 4.0.0 and was backported to 3.4.x

**Closed by lsiepel** 2023-11-12 20:26 UTC
