### ISSUE TITLE
[icalendar] Timeout exception

### ISSUE THREAD

**Issue by chris922** [openhab/openhab-addons#10308] opened 2021-03-10 07:18 UTC
This morning I noticed that the icalendar binding didn't trigger the expected actions.

According to the logs since the night a timeout exception occurred.

The calendar itself is hosted via google.com and I also verified that my Raspberry Pi still has a connection to the internet by downloading the same calendar via `wget` on the console.

Log extract:
```
2021-03-10 08:00:40.326 [DEBUG] [g.icalendar.internal.handler.PullJob] - TimeoutException message is: null
2021-03-10 08:00:40.313 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-03-10 07:44:40.310 [DEBUG] [g.icalendar.internal.handler.PullJob] - TimeoutException message is: null
2021-03-10 07:44:40.298 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-03-10 07:28:40.296 [DEBUG] [g.icalendar.internal.handler.PullJob] - TimeoutException message is: null
2021-03-10 07:28:40.283 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-03-10 07:12:40.280 [DEBUG] [g.icalendar.internal.handler.PullJob] - TimeoutException message is: null
2021-03-10 07:12:40.268 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
```

## Expected Behavior
* No timeout exception occurs.
* In case of an exception use the previously loaded calendar

## Current Behavior
* Timeout occurs
* Calendar seems to be discarded -> no rules triggered

## Possible Solution
* Don't run into a timeout when the device is still connected to the internet and the target calendar is available
* More detailed logging about timeout exception
* Catch exceptions when reloading the calendar and fallback to the old one

## Steps to Reproduce (for Bugs)
Unfortunately, I don't know how to reproduce this and I assume it will be very difficult to find the root cause, so just improving logging + error handling could already be nice.

## Context
Triggering rules via icalendar binding

## Your Environment
* Version used: openHAB 3.0, icalendar 3.0
* Operating System and version. Openhabian

**Comment by daMihe** [comment] 2021-06-05 15:31
This seems to be not an issue of iCalendar binding, but HttpClient instead (other users also wrote about other plugins not working). I've seen this behaviour together with WiFi-deauths (when the signal strength is not good or 100% stable etc.). Is your system connected via WiFi to the internet?

**Comment by chris922** [comment] 2021-06-05 16:33
It's connected via ethernet cable, not via WiFi :/

**Comment by daMihe** [comment] 2021-06-05 17:10
`dmesg` is also not showing anything about your network connection after boot completion? This is how i correlated the events. The workaround there was to add a hook to the network manager that restarts openhab after establishing connection.

**Comment by rueckix** [comment] 2021-06-05 17:45
Same issue here, using openhab in Docker. Could not reproduce this yet with anything other than google calendar, using private ical links. File pulls ok using cURL. No idea yet.

**Comment by evilphish** [comment] 2022-01-23 15:01
I can confirm this and the file at the url pulls just fine using curl/wget or in a browser. Version OH 3.2.0 and icalendar 3.2.0

**Comment by daMihe** [comment] 2023-04-15 14:55
This is not an issue of icalendar binding and is not reproducible. The issue was awaiting a long time for more details i did not get. I'm closing it here. Please reopen with more details in the core if the issue comes back.

**Closed by daMihe** 2023-04-15 14:55 UTC
