### ISSUE TITLE
[weather binding] ApiXU - provider no longer responding

### ISSUE THREAD

**Issue by HomeOfSourceCode** [openhab/openhab-addons#8598] opened 2020-09-28 14:40 UTC
It looks like that provider does not deliver data anymore

## Expected Behavior
get weather data

## Current Behavior
URL request error in OH log

## Possible Solution
delete support for that weather provider from binding

## Steps to Reproduce (for Bugs)
configure provider and see if datas are arrived

## Your Environment
OH 2.5.9 on windows 10

**Comment by wborn** [comment] 2020-09-28 15:10
Seems like a duplicate of https://github.com/openhab/openhab1-addons/issues/5897.

**Closed by wborn** 2020-09-28 15:10 UTC
