### ISSUE TITLE
[openhabcloud] Frequent disconnects from myopenhab and wrong log messages

### ISSUE THREAD

**Issue by lhurt** [openhab/openhab-addons#14200] opened 2023-01-10 06:01 UTC
myopenhab.org gets disconnected from time to time and sometimes the reconnection fails in a way that the web portal displays the connected local openHAB instance as **Offline**, whereas the log states a successful reconnection.
The connection actually is offlince becuase Alexa commands are not propagated to the local instance.

This issue seems to have worsened since the release of 3.4. Under 3.3 the connection was rock stable. It is discussed in the community [in this thread](https://community.openhab.org/t/disconnected-from-the-openhab-cloud-service/132335) and seems clear that there are quite some users affected.

One user has [developed a workaround here](https://community.openhab.org/t/disconnected-from-the-openhab-cloud-service/132335/95?u=dolittle) to mitigate the problem by automatically restarting the affected bundle. But in my point of view there should be a fix for that.

## Expected Behavior
In case of a disconnection there should be a reliable reconnection and a fail error message in case of an unsuccessful attempt.

## Current Behavior
The behavior is not reproduceable in my case but happens every couple of days
According to the log in DEBUG mode, the system recognizes a disconnection and executes a reconnect procedure, but somehow it _sometimes_ doesn't detect a successful reconnection and reports success in cases of failure. Sometimes the reconnect is successful as well.

## Context
I've turned on DEBUG logging for org.openhab.io.openhabcloud and I get the following log outputs in both cases
### Successful reconnect
```
2023-01-09 10:04:49.416 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO pong: 24 ms
2023-01-09 10:05:14.416 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO ping
2023-01-09 10:05:19.417 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO CLOSE: ping timeout
2023-01-09 10:05:19.418 [WARN ] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected: ping timeout
2023-01-09 10:05:19.418 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = c3...c7, base URL = http://localhost:8080)
2023-01-09 10:05:20.005 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 1)
2023-01-09 10:05:30.484 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:05:30.487 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:05:32.439 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 2)
2023-01-09 10:05:32.440 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:05:32.440 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:05:36.374 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 3)
2023-01-09 10:05:36.375 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:05:36.376 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:05:41.377 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 4)
2023-01-09 10:05:51.389 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:05:51.390 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:05:56.390 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 5)
2023-01-09 10:05:56.391 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:05:56.392 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:06:01.393 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 6)
2023-01-09 10:06:11.407 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:06:11.409 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:06:16.409 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 7)
2023-01-09 10:06:16.410 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:06:16.411 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:06:21.411 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 8)
2023-01-09 10:06:31.421 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:06:31.421 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:06:36.422 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 9)
2023-01-09 10:06:36.423 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:06:36.423 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:06:41.424 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 10)
2023-01-09 10:06:51.434 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:06:51.435 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:06:56.436 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 11)
2023-01-09 10:06:56.437 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:06:56.440 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:07:01.441 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 12)
2023-01-09 10:07:11.451 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:07:11.452 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:07:14.479 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.de/api/cloudplayer/playlists?deviceSerialNumber=G091ET10106306QG&deviceType=A2H4LV5GIZ1JFT&mediaOwnerCustomerId=ASIEOO5F99KW6' fails with unknown error
2023-01-09 10:07:14.515 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.de/api/cloudplayer/playlists?deviceSerialNumber=G090U5068357065U&deviceType=A32DOYMUN6DTXA&mediaOwnerCustomerId=ASIEOO5F99KW6' fails with unknown error
2023-01-09 10:07:16.451 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 13)
2023-01-09 10:07:16.453 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:07:16.453 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:07:21.454 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 14)
2023-01-09 10:07:31.476 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:07:31.477 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:07:36.477 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 15)
2023-01-09 10:07:36.478 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:07:36.479 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:07:41.480 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 16)
2023-01-09 10:07:51.491 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:07:51.492 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:07:56.492 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 17)
2023-01-09 10:07:56.494 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:07:56.495 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:08:01.494 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 18)
2023-01-09 10:08:11.505 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:08:11.505 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:08:16.506 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 19)
2023-01-09 10:08:16.525 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:08:16.531 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:08:21.531 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 20)
2023-01-09 10:08:24.660 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.de/api/cloudplayer/playlists?deviceSerialNumber=G091ET10106306QG&deviceType=A2H4LV5GIZ1JFT&mediaOwnerCustomerId=ASIEOO5F99KW6' fails with unknown error
2023-01-09 10:08:24.665 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.de/api/cloudplayer/playlists?deviceSerialNumber=G090U5068357065U&deviceType=A32DOYMUN6DTXA&mediaOwnerCustomerId=ASIEOO5F99KW6' fails with unknown error
2023-01-09 10:08:31.541 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:08:31.545 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:08:36.544 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 21)
2023-01-09 10:08:36.545 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:08:36.546 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:08:41.546 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 22)
2023-01-09 10:08:51.559 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:08:51.560 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:08:56.560 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 23)
2023-01-09 10:08:56.562 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:08:56.563 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:09:01.563 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 24)
2023-01-09 10:09:11.573 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:09:11.574 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:09:16.574 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 25)
2023-01-09 10:09:16.576 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:09:16.577 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:09:21.577 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 26)
2023-01-09 10:09:31.589 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:09:31.590 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:09:34.763 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.de/api/cloudplayer/playlists?deviceSerialNumber=G091ET10106306QG&deviceType=A2H4LV5GIZ1JFT&mediaOwnerCustomerId=ASIEOO5F99KW6' fails with unknown error
2023-01-09 10:09:34.766 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.de/api/cloudplayer/playlists?deviceSerialNumber=G090U5068357065U&deviceType=A32DOYMUN6DTXA&mediaOwnerCustomerId=ASIEOO5F99KW6' fails with unknown error
2023-01-09 10:09:36.590 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 27)
2023-01-09 10:09:36.592 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-09 10:09:36.592 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-09 10:09:41.593 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 28)
2023-01-09 10:09:46.722 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO OPEN
2023-01-09 10:09:46.723 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connected successfully (attempt 28)
2023-01-09 10:09:46.817 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO connected
2023-01-09 10:09:46.818 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = c3...c7, base URL = http://localhost:8080)
2023-01-09 10:10:11.724 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO ping
2023-01-09 10:10:11.747 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO pong: 23 ms
```
### Unsuccessful reconnect

```
2023-01-08 02:28:52.411 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO pong: 25 ms
2023-01-08 02:29:17.411 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO ping
2023-01-08 02:29:20.911 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO pong: 3500 ms
2023-01-08 02:29:45.912 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO ping
2023-01-08 02:29:50.955 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO CLOSE: ping timeout
2023-01-08 02:29:50.956 [WARN ] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected: ping timeout
2023-01-08 02:29:50.956 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = c3...c7, base URL = http://localhost:8080)
2023-01-08 02:29:52.269 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 1)
2023-01-08 02:30:02.447 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:30:02.448 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:30:04.972 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 2)
2023-01-08 02:30:15.070 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:30:15.071 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:30:20.071 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 3)
2023-01-08 02:30:30.168 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:30:30.169 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:30:35.170 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 4)
2023-01-08 02:30:45.270 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:30:45.307 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:30:50.308 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 5)
2023-01-08 02:31:00.425 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:31:00.426 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:31:05.426 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 6)
2023-01-08 02:31:15.546 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:31:15.550 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:31:20.550 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 7)
2023-01-08 02:31:20.673 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO OPEN
2023-01-08 02:31:20.674 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connected successfully (attempt 7)
2023-01-08 02:31:20.774 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO connected
2023-01-08 02:31:20.775 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = c3...c7, base URL = http://localhost:8080)
2023-01-08 02:31:30.777 [WARN ] [io.openhabcloud.internal.CloudClient] - Error during communication: EngineIOException xhr poll error
2023-01-08 02:31:30.869 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO CLOSE: transport error
2023-01-08 02:31:30.869 [WARN ] [io.openhabcloud.internal.CloudClient] - Socket.IO disconnected: transport error
2023-01-08 02:31:30.869 [INFO ] [io.openhabcloud.internal.CloudClient] - Disconnected from the openHAB Cloud service (UUID = c3...c7, base URL = http://localhost:8080)
2023-01-08 02:31:31.836 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 1)
2023-01-08 02:31:41.940 [DEBUG] [io.openhabcloud.internal.CloudClient] - Error connecting to the openHAB Cloud instance: EngineIOException xhr poll error. Should reconnect automatically.
2023-01-08 02:31:41.940 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connect attempt error: SocketIOException Connection error
2023-01-08 02:31:44.275 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connecting (attempt 2)
2023-01-08 02:31:44.418 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO OPEN
2023-01-08 02:31:44.419 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO re-connected successfully (attempt 2)
2023-01-08 02:31:44.517 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO connected
2023-01-08 02:31:44.518 [INFO ] [io.openhabcloud.internal.CloudClient] - Connected to the openHAB Cloud service (UUID = c3...c7, base URL = http://localhost:8080)
2023-01-08 02:32:09.419 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO ping
2023-01-08 02:32:09.443 [DEBUG] [io.openhabcloud.internal.CloudClient] - Socket.IO pong: 24 ms
```

## Your Environment
Docker on  Ubuntu 22.04
openHAB 3.4.0

Was rockstable almoust without noticeable offline periods under openHAB 3.3

The [community thread](https://community.openhab.org/t/disconnected-from-the-openhab-cloud-service/132335) gives a strong indication that the issue is not related to the environment as users with different setup report the issue as well.

**Comment by ssalonen** [comment] 2023-01-10 06:47
I see this as duplicate of https://github.com/openhab/openhab-cloud/issues/134

Pinging @digitaldan for comment as well

**Comment by wborn** [comment] 2023-01-12 12:12
Duplicates openhab/openhab-cloud#134

**Closed by wborn** 2023-01-12 12:12 UTC
Labels: duplicate
