### ISSUE TITLE
[mapdb] Index out of bounds error

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-addons#8790] opened 2020-10-18 11:51 UTC
## Current Behavior
Running OH3  build #1972 i get the following error on system start up. Due to the fact that every item is persisted with mapdb and i have currently more that 500 item, i did not see any missing data.

```
2020-10-18 13:40:12.958 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'QueryablePersistenceService.query()' on 'org.openhab.persistence.mapdb.internal.MapDbPersistenceService@710e5de1': Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:48) ~[?:?]
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:1) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:893) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:888) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:774) ~[bundleFile:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.deserialize(MapDbPersistenceService.java:168) ~[?:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.query(MapDbPersistenceService.java:155) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-18 13:40:12.984 [ERROR] [ence.internal.PersistenceManagerImpl] - Exception occurred while querying persistence service 'mapdb': Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:48) ~[?:?]
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:1) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:893) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:888) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:774) ~[bundleFile:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.deserialize(MapDbPersistenceService.java:168) ~[?:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.query(MapDbPersistenceService.java:155) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-18 13:40:15.192 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'QueryablePersistenceService.query()' on 'org.openhab.persistence.mapdb.internal.MapDbPersistenceService@710e5de1': Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:48) ~[?:?]
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:1) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:893) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:888) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:774) ~[bundleFile:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.deserialize(MapDbPersistenceService.java:168) ~[?:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.query(MapDbPersistenceService.java:155) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2020-10-18 13:40:15.199 [ERROR] [ence.internal.PersistenceManagerImpl] - Exception occurred while querying persistence service 'mapdb': Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:48) ~[?:?]
        at org.openhab.persistence.mapdb.internal.StateTypeAdapter.read(StateTypeAdapter.java:1) ~[?:?]
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:893) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[bundleFile:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:888) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[bundleFile:?]
        at com.google.gson.Gson.fromJson(Gson.java:774) ~[bundleFile:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.deserialize(MapDbPersistenceService.java:168) ~[?:?]
        at org.openhab.persistence.mapdb.internal.MapDbPersistenceService.query(MapDbPersistenceService.java:155) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:152) [bundleFile:?]
        at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

## Your Environment
openhab Version: 3 build 1972
HW: Virtual maschine on Synology NAS
OS: Debian 10

**Comment by kaikreuzer** [comment] 2020-10-18 16:36
I cannot reproduce it when persisting the states with OH3. I have created https://github.com/openhab/openhab-addons/pull/8792, which will provide suitable log messages, which can help us identifying why this problem turns up in your case. Would hence be great if you could update your instance to a new build, once #8792 is merged and report back with the logs here.

**Comment by TBail** [comment] 2020-10-18 16:59
I am updating on a regular base to see when OH3 is production ready for me. I will give feedback when the error changes.

**Comment by TBail** [comment] 2020-10-19 07:14
After installing build 1975 i got the following error

`2020-10-19 09:12:39.655 [WARN ] [ence.mapdb.internal.StateTypeAdapter] - Couldn't deserialize state 'org.openhab.core.library.types.StringType@@@': Index 1 out of bounds for length 1
2020-10-19 09:12:39.671 [WARN ] [pdb.internal.MapDbPersistenceService] - Deserialized invalid item: [FAILED toString()]
2020-10-19 09:12:40.095 [WARN ] [ence.mapdb.internal.StateTypeAdapter] - Couldn't deserialize state 'org.openhab.core.library.types.StringType@@@': Index 1 out of bounds for length 1
2020-10-19 09:12:40.112 [WARN ] [pdb.internal.MapDbPersistenceService] - Deserialized invalid item: [FAILED toString()]
2020-10-19 09:12:46.509 [WARN ] [ence.mapdb.internal.StateTypeAdapter] - Couldn't deserialize state 'org.openhab.core.library.types.StringType@@@': Index 1 out of bounds for length 1
2020-10-19 09:12:46.514 [WARN ] [pdb.internal.MapDbPersistenceService] - Deserialized invalid item: [FAILED toString()]
`

**Closed** 2020-10-24 16:10 UTC
