### ISSUE TITLE
[velux] binding need flip option for Rollershutter control in UI

### ISSUE THREAD

**Issue by lgusewski** [openhab/openhab-addons#9705] opened 2021-01-05 21:10 UTC
## Your Environment

* Version used: 3.0
* Environment name and version: Safari, Chrome, Firefox
* Operating System and version: Linux Ubuntu Server 20.04 LTS

I use the Velux Binding in openHAB 3 and hat first the _inverted_ option in the binding configuration.

`inverted=true`

With Basic UI I used the dimmer control and closed was 0%, open 100% but the Rollershutter control in the new UI under Locations and Devices had wrong buttons. The arrow up drives the roller shutter down. The arrow down drives the Rollershutter up. So I deactivated the _inverted_ option in the binding and the buttons in the UI matches the function.

Additional I changed the item options for the Alexa Skill for openHAB.

`alexa="RangeController.rangeValue" [category="EXTERIOR_BLIND", friendlyNames="@Setting.Opening", supportedRange="0:100:10", unitOfMeasure="Percent", actionMappings="Close=100,Open=0,Lower=(+10),Raise=(-10)", stateMappings="Closed=100,Open=0:99"]`

But now in the Amazon Alexa App, the controls did not match to the state of the Rollershutter.

![Alexa_App_iOS](https://user-images.githubusercontent.com/35467203/103698970-7ddf1400-4fa2-11eb-965f-f83ef571b542.jpg)

At the end, to get openHAB, Basic UI, Locations, Devices and Amazon App (for iOS) in a matching state, it would be necessary to have an option also to flip the Rollershutter UI.

![rollershutter_mirrored](https://user-images.githubusercontent.com/35467203/103698504-bc280380-4fa1-11eb-8953-231e52a5eb21.jpg)

**Comment by andrewfg** [comment] 2021-01-19 14:32
@lgusewski this is not an issue with the Velux binding; IMHO it is an issue with your configuration.

1. Most (Velux) Roller Shutters are NOT inverted. So either set `inverted=false` or just delete it from your configuration file (its default value is `false`). Note: `inverted=true` is normally only required on (Velux) roof _Windows_..

2. Try to be very clear in your mind about the difference between a) 'Closed' / 'Open' (the aperture is covered or un-covered), b) 'Up' / 'Down' (the movable bar is at the top or bottom of the aperture), and the `UpDownType` commands (what you see in the User Interface). The table below might help you..

![image](https://user-images.githubusercontent.com/893994/105047848-c26ab500-5a62-11eb-9098-9f4cc12ebb29.png)

3. In light of the above, you may also need to rethink your Alexa Open/Close mappings again..

PS you may want to look at [this table in the Hunter Douglas binding](https://openhab.org/addons/bindings/hdpowerview/#roller-shutter-up-down-position-vs-open-close-state)

PPS you may also want to look at Appendix 2 of the [Velux API Specification](https://github.com/PLCHome/velux-klf200-api/raw/master/technical%20specification%20for%20klf%20200%20api.pdf) (although it is admittedly rather dense..)

**Comment by andrewfg** [comment] 2021-01-19 14:47
PS in your UI image (below) the 

- ▲ sends the command `UpDownType.UP`
- ▼  sends the command `UpDownType.DOWN`
- █  sends the command `StopMoveType.STOP`




![image](https://user-images.githubusercontent.com/893994/105048560-9ef43a00-5a63-11eb-879c-ff169da32126.png)

**Comment by lgusewski** [comment] 2021-01-19 17:10
> Note: inverted=true is normally only required on (Velux) roof Windows..

Yes, that's the reason why I wrote this. We are talking about my roof windows with roller shutters. The rest like I wrote has endurance.

I can decide if the Alexa App shows the correct UI or openHAB 3 (not Basic UI, there are more options to solve this problem).

**Comment by andrewfg** [comment] 2021-01-19 17:15
> We are talking about my roof windows with roller shutters.

The windows will need 'inverted=true' and the shutters will need 'inverted=false'..

**Comment by lgusewski** [comment] 2021-01-19 17:54
That is exactly the configuration I use. And this is the reason, that the Alexa integration shows in the Amazon app the wrong information. They speak about "Degree of opening" and 0% means now open and 100% closed. In the App is it inverted.

**Comment by andrewfg** [comment] 2021-01-19 17:57
Then I guess your problem is in the Alexa integration. Or?

**Comment by lgusewski** [comment] 2021-01-19 18:06
Hmm, yes and no. I can't change the things Amazon do. But openHAB can offer options to change the functionality of bindings. And what I need to solve the problem on my side, is something like this: [Invert control: Yes / No](https://community.openhab.org/t/oh3-rollershutter-invert-command-missing/112391).

And, don't forget. It will not be only my problem. Every user with the combination of a velux roof windows with roller shutters AND Alexa integration will run into this inconsistent UI.

**Comment by andrewfg** [comment] 2021-01-19 18:11
The Velux binding has an 'invert control yes / no' setting. If that does not do what you want, then please don't blame the binding.

**Comment by lgusewski** [comment] 2021-01-19 18:20
I blame nothing. I only opened an Github Issue about a problem a can't solve by myself. I am on the final version from December 2020 and my binding settings, apart from the fact that I use a file to configure, looks like this:

![velux_bindig](https://user-images.githubusercontent.com/35467203/105076135-fa85ee00-5a8a-11eb-96c5-76e912fa8d54.jpg)

I did not see here any option like in the linked Z-Wave binding to "Invert control". Only the position invert, and this is the thing we talk above (inverted=true), or not?

**Comment by andrewfg** [comment] 2021-01-19 18:31
Yes.

**Comment by andrewfg** [comment] 2021-01-19 19:10
Is the following Alexa configuration for your window or your shutter? The window will be inverted in the Velux configuration, and the shutter will be not inverted. And therefore I suppose that either the window or the shutter will need a configuration reverse of the one below i.e. where you swap (some of) the action titles "Close<=>Open" and "Lower<=>Raise" ??

```
alexa="RangeController.rangeValue" [category="EXTERIOR_BLIND", friendlyNames="@Setting.Opening", supportedRange="0:100:10", unitOfMeasure="Percent", actionMappings="Close=100,Open=0,Lower=(+10),Raise=(-10)", stateMappings="Closed=100,Open=0:99"]
```

You may want to post this on the OH Community Forum under the Alexa moniker..

Further notes from my side:
- I guess that supportedRange="0:100:10" could be omitted (it defaults to "0:100:1") since the Velux binding has at least 1% position resolution.
- And are you sure about your stateMappings="Closed=100,Open=0:99"? (it does not make much sense to me..)

**Comment by lgusewski** [comment] 2021-01-19 19:36
The code is only for the shutter. To open the window over voice is too critical with kids. The roller shutter commands work perfect and I have no problems with the voice commands. The "Closed=100,Open=0:99" means, that a value between 0-99 is a open roller shutter and this is equal to your table with the yellow marker. The 100 is the 100% closed state.

**Comment by andrewfg** [comment] 2021-01-19 19:39
Now I am confused. You say it works. So what is the problem?

**Comment by lgusewski** [comment] 2021-01-19 20:10
The problem is the shown state in the **Alexa app** on my Phone. This is inverted to the real state of the roller shutter. The changes on the item definition are only on the openHAB site. So the only solution is to flip the control buttons in the openHAB UI as I initial wrote with the mockup. Then I could invert the roller shutter, invert the Alexa commands to the default example in the openHAB documentation and I could have a correct shown state on the openHAB and Alexa app.

Now, the openHAB shows 100% open and the Alexa **app** show 0% open.

**Comment by andrewfg** [comment] 2021-01-19 20:17
Two thoughts..

1. Invert it on the Velux, and then invert again on the Alexa settings.
2. Try just inverting the stateMappings

**Comment by andrewfg** [comment] 2021-01-19 20:19
But perhaps you can make a table showing what is displaying / commanding correctly, and where?

**Comment by lgusewski** [comment] 2021-01-19 20:29
This is the **only** problem, because it is the **only** thing I can't invert.

![problem](https://user-images.githubusercontent.com/35467203/105089030-e814b000-5a9c-11eb-9f49-9782158cf713.jpg)

And this buttons are the missing part in the puzzle and this is why I wrote that the velux binding need a control flip option.

**Comment by andrewfg** [comment] 2021-01-19 20:39
What do these app arrows even mean? Does the up arrow mean 'up' or does it mean 'open', or does it mean 'increase percentage'?

Try thinking the other way round. Don't try to invert the arrows in the App. Try taking the app as it id, and figure out what you need to invert in the mappings to make it work.

In any case there is nothing ypu could do in the Velux binding to make the app behave differently.

**Comment by andrewfg** [comment] 2021-02-02 18:27
I am marking this issue as closed, because the issue is not solvable within the scope of OH

**Closed by andrewfg** 2021-02-02 18:27 UTC
