### ISSUE TITLE
[shelly] Handler ShellyRelayHandler tried updating the thing status although the handler was already disposed.

### ISSUE THREAD

**Issue by stefan-hoehn** [openhab/openhab-addons#14271] opened 2023-01-24 20:54 UTC
@rkoshak and me seen this the last few times. It’s pretty consistent so it’s worth reporting. It is happening on 3.4.1 and 4.0

After an upgrade/restart, when OH comes back online, the logs _get filled up_.

One example is:
```
2023-01-24 09:32:37.968 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ShellyRelayHandler tried updating the thing status although the handler was already disposed.
```

**Restarting makes these messages go away.** It’s a minor annoyance but probably needs to be addressed at least for 4.0.

It’s complaining about the Shelly Binding but the warning comes from core so it’s not clear where the problem lies, though I have hardly seen this for any other binding (only if I recall during development when replacing a binding during runtime).

cc: @markus7017

**Comment by lolodomo** [comment] 2023-01-29 17:19
This is a duplicate of #14032

**Closed by lolodomo** 2023-01-29 17:19 UTC
