### ISSUE TITLE
[evohome] Setpoint Send command 0 doesn't cancel the permanent override

### ISSUE THREAD

**Issue by HellStorm666** [openhab/openhab-addons#9007] opened 2020-11-12 10:26 UTC
since a few weeks I have a problem with the evohome binding.

Before, when I sended setpoint.sendCommand(0) to the evohome the permanent override got cancelled and thus evohome started to follow the schedule again.

However, if I now send this command, it tries to set the temp to 0, that fails and the temperature stays at a given temperature with permanent override.

I don't see any strange errors in the logs.

Also, sending a setpoint.sendCommand(10) does change the info in AopenHab, but doenst change it in the Evohome app, so my guess is that it doens't write to evohome.
If I change settings in evohome, it will display the changed values in Openhab2, so reading the data does work.

**Comment by HellStorm666** [comment] 2021-03-03 08:39
Any update on this?

Looks like writing any value to the evohome does get changed in OpenHAB, but a few seconds after that it gets overwritten with the value in the Evohome app value.

So, as example, the set-temp in the evohome app (and display) is 17C.
Setting this to 10C in OpenHAB gives a 'set temp to 10C' and 'expected temp to become 10C'. And after a few seconds I get a temp is 17C.

So it looks like the value isn't send to evohome, or evohome ignores the value.

**Comment by Birchcroft** [comment] 2022-10-01 09:38
I have the same problem on 1 of my heating zones.  On careful inspection I found that I had set the "Set Point Item" to type "number:temperature" for that heating zone, whereas it was set to type "number" for the others.   Changing it to type "number" appears to have resolved the problem, although I need to monitor it for a while to check.

**Comment by lsiepel** [comment] 2023-01-07 12:44
I might look into this issue and come up with a fix. Are you available for performing some tests, run it for a couple of days?

**Comment by Birchcroft** [comment] 2023-01-07 14:04
Don't really have a lot of time at the moment, although I might be able to play a bit.

I can confirm that since my last post I believe that the problem relates to the "Type" of the Item associated with the setpoint.

If I use Type = number everything works as expected 

However 

If I use Type = number: temperature then I cannot change the setpoint using openhab.  Every time I try it reverts to the value set by the EvoHome controller.

So I just use a dimensionless number for set point and don't have a problem.

On 7 January 2023 12:44:37 GMT, lsiepel ***@***.***> wrote:
>I might look into this issue and come up with a fix. Are you available for performing some tests, run it for a couple of days?
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/openhab-addons/issues/9007#issuecomment-1374469150
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lsiepel** [comment] 2023-01-07 14:24
It is because Units of measure is not supported by the binding. I created a new version as i was allready doing some refactoring.
3.4.1. Test version: https://1drv.ms/u/s!AnMcxmvEeupwjp4MT2ZumTKtulvBWg?e=yrmAmM Anyone testing this, please report back so we can get this merged.

- Added UoM. 
- Added null annotations
- Added default semantic tags 

If you have textual config just update your Item config from to Number:Temperature (for both SetPoint and Temperature)
channel. Of recreate the Thing from the UI.

**Comment by lsiepel** [comment] 2023-01-24 22:51
@HellStorm666 gentle ping as you raised this issue, are you able to perform some tests ?

**Comment by lsiepel** [comment] 2023-02-05 20:37
@Birchcroft Are you able to do some basic tests?

**Comment by Birchcroft** [comment] 2023-02-06 08:28
@lsiepel I don't have a great deal of time but if you send me instructions on how to download and install what you want tested I will try and fit it in over the next week or so.

**Comment by lsiepel** [comment] 2023-02-06 12:41
1. Uninstall the current evohome binding
2. Download the 3.4.x jar here: https://1drv.ms/u/s!AnMcxmvEeupwjqVYEk7vWMf-I5fFNQ?e=Q1ands 
3. Place the jar in the addons folder.
4. Update both temperature channels (ui or textual might differ, as long as you change them form Number to Number: Temperature it will be fine. )
5. Perform soms tests (init the things, perform commands and watch some values get updated)

If you encounter some issues, let me know the details: what channel / values / error from log etc. Thanks a lot for testing!

**Comment by Birchcroft** [comment] 2023-02-07 22:48
Isiepel profuse apologies, I accidentally removed the wrong binding so my EvoHome tests were invalid.

I will do it properly in the next couple of days.

On 6 February 2023 12:41:34 GMT, lsiepel ***@***.***> wrote:
>1. Uninstall the current evohome binding
>2. Download the 3.4.x jar here: https://1drv.ms/u/s!AnMcxmvEeupwjqVYEk7vWMf-I5fFNQ?e=Q1ands 
>3. Place the jar in the addons folder.
>4. Update both temperature channels (ui or textual might differ, as long as you change them form Number to Number: Temperature it will be fine. )
>5. Perform soms tests (init the things, perform commands and watch some values get updated)
>
>If you encounter some issues, let me know the details: what channel / values / error from log etc. Thanks a lot for testing!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/openhab-addons/issues/9007#issuecomment-1419020449
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Birchcroft** [comment] 2023-02-08 12:36
Having removed the correct binding  and ensured I am using 
org.openhab.binding.evohome-3.4.1-SNAPSHOT.jar I have done a Series of 5 
tests using the heating in my study

The StudyHeating_Setpoint ITEM has the following characteristics:

Type:  Number:Temperature

Category: heating

Semantic Class: Setpoint    - /Note I probably would have set this to 
Dimmer but the option does not appear to be available/

Semantic Property: Temperature

*Test 1:*

I selected the StudyHeating_Setpoint ITEM and changed the displayed 
value by using back-delete to delete the existing value (17) and 
replaced it with the new value (25) .  As you can see from below it sent 
a command each time a digit was deleted, so it first set demand to 1 
then zero.  When I typed in 2 followed by 5 (ie 25) it first sent set 
the demand to 20 then 35 at which point the status changed to 
PermanentOverride then eventually the demand was set to 25 as requested.

2023-02-08 09:11:04.051 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 1

2023-02-08 09:11:04.051 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 1

2023-02-08 09:11:04.055 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 17°Cto 1°C

2023-02-08 09:11:04.756 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 0

2023-02-08 09:11:04.756 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 0

2023-02-08 09:11:04.758 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 1°Cto 0°C

2023-02-08 09:11:06.716 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 20

2023-02-08 09:11:06.718 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 20

2023-02-08 09:11:06.724 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 0°Cto 20°C

2023-02-08 09:11:09.288 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 35

2023-02-08 09:11:09.290 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 35

2023-02-08 09:11:09.297 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 20°Cto 35°C

2023-02-08 09:11:18.363 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom FollowScheduleto 
PermanentOverride

2023-02-08 09:11:33.563 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'BackBedroomHeating_Temperature' changedfrom 16.5to 17

2023-02-08 09:11:33.571 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 17°Cto 16.5°C

2023-02-08 09:11:33.572 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 35°Cto 25°C

So it would appear that there is something not quite right in the 
setting of the demand as there is no reason it should have been set to 
35 prior to being set to the correct value of 25.

*Test 2:*

I highlighted the current set point value (17) and typed in the new 
value (25).  As you can set the  demand to 2 then 25

2023-02-08 10:13:13.295 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 2

2023-02-08 10:13:13.297 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 2

2023-02-08 10:13:13.309 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 17°Cto 2°C

2023-02-08 10:13:14.412 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 25

2023-02-08 10:13:14.414 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 25

2023-02-08 10:13:14.419 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 2°Cto 25°C

2023-02-08 10:13:22.132 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 19°Cto 19.5°C

2023-02-08 10:13:22.134 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom FollowScheduleto 
PermanentOverride

Interestingly this time when I typed the 2 the demand became 2 rather 
than 20 as in Test 1.

*Test 3:*

Following on from Test 2 I overwrote the demand with 0 as you can see it 
changed the demand to 0 and the status to FollowSchedule before changing 
the demand back to 25 and then the scheduled value of 17.

2023-02-08 10:17:44.422 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 0

2023-02-08 10:17:44.424 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 0

2023-02-08 10:17:44.429 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 25°Cto 0°C

2023-02-08 10:17:55.507 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom PermanentOverrideto 
FollowSchedule

2023-02-08 10:17:55.509 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 0°Cto 25°C

2023-02-08 10:18:10.674 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 19.5°Cto 19°C

2023-02-08 10:18:10.689 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 25°Cto 17°C

then after a delay of 25s I got the following messages:

2023-02-08 10:19:29.699 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom NULLto 17°C

2023-02-08 10:19:29.700 [INFO ] [openhab.event.ItemUpdatedEvent ] - Item 
'StudyHeating_SetPoint' has been updated.

So it would appear something is not quite right.

*Test 4:*

I wrote a rule which when the Status changed to TemporaryOverride after 
2 minutes it would limit the override to 22C and then after a further 2 
minutes it would cancel the override

I then increased the demand to 25C using the dial on the valve. After 2 
minutes it reduced the demand as expected:

2023-02-08 11:12:22.498 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 22

2023-02-08 11:12:22.498 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 22

2023-02-08 11:12:22.505 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 25°Cto 22°C

2023-02-08 11:12:23.194 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom TemporaryOverrideto 
PermanentOverride

After a further 2 minutes it received the command "0" and changed the 
Demand to 0 and status to FollowSchedule and then changed the demand 
back to 22.

2023-02-08 11:14:22.518 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 0

2023-02-08 11:14:22.519 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 0

2023-02-08 11:14:22.523 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 22°Cto 0°C

2023-02-08 11:14:24.792 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom PermanentOverrideto 
FollowSchedule

2023-02-08 11:14:24.795 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 0°Cto 22°C

Then after another 31 seconds changed the demand to the scheduled value 
of 17.

2023-02-08 11:14:55.152 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 22°Cto 17°C

Once again after the status changed to FollowSchedule it set the demand 
to the previous value before it was set to the correct value after a 
short period.

*Test 5:*

In order to check if the changing of demand when the status changed from 
PermanentOverride to FollowSchedule from 0 to the previous value and 
then to the correct value was an EvoHome feature I ran a test using the 
EvoHome App.

I changed the demand from 23 to 24 and set it to PermanentOverride:

2023-02-08 11:47:20.978 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom FollowScheduleto 
PermanentOverride

2023-02-08 11:47:20.979 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 23°Cto 24°C

I then cancelled the PermanentOverride so it returned to FollowSchedule:

2023-02-08 11:47:51.437 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom PermanentOverrideto 
FollowSchedule

the temperature then returned directly to the scheduled temperature 
without the intermediate step of going to the previously demanded 
temperature, all be it there was a ~3 delay

2023-02-08 11:50:08.295 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 24°Cto 17°C

So at first glance I think it might be a feature of your software.
Hope this helps
Ken

**Comment by lsiepel** [comment] 2023-02-09 15:50
Don't know why there are these intermediate states, not something that i would suspect from the code change.  Could you share the log of evohome, preferrably in debug mode? If i have that log i can determine the cause/origin from the changes.
From console:
log:set debug org.openhab.binding.evohome

Thanks for spending some time on this!

**Comment by Birchcroft** [comment] 2023-02-10 07:27
Will do when I get chance

**Comment by lsiepel** [comment] 2023-02-10 09:32
No need to rush, take your time.

**Comment by Birchcroft** [comment] 2023-02-22 17:03
Hi Isiepel

I reran Tests 1 to 4,  Log results below, and all seemed to be OK.  The 
one thing I did notice on a number of occasions was the message "Request 
failed with unexpected response code 201"


*Test 1*

2023-02-22 15:35:36.576 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 1

2023-02-22 15:35:36.577 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 1

2023-02-22 15:35:36.580 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 17°Cto 1°C

==> /var/log/openhab/openhab.log <==

2023-02-22 15:35:37.345 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/6522902/heatSetpoint]

2023-02-22 15:35:37.489 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Request failed with unexpected response code 201

2023-02-22 15:35:37.964 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/6522902/heatSetpoint]

==> /var/log/openhab/events.log <==

2023-02-22 15:35:37.335 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 0

2023-02-22 15:35:37.336 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 0

2023-02-22 15:35:37.338 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 1°Cto 0°C

2023-02-22 15:35:37.959 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 2

2023-02-22 15:35:37.959 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 2

2023-02-22 15:35:37.962 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 0°Cto 2°C

==> /var/log/openhab/openhab.log <==

2023-02-22 15:35:38.225 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Request failed with unexpected response code 201

2023-02-22 15:35:38.558 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/6522902/heatSetpoint]

2023-02-22 15:35:38.743 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Request failed with unexpected response code 201

==> /var/log/openhab/events.log <==

2023-02-22 15:35:38.553 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 25

2023-02-22 15:35:38.554 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 25

2023-02-22 15:35:38.557 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 2°Cto 25°C

==> /var/log/openhab/openhab.log <==

2023-02-22 15:35:40.891 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 15:35:41.105 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 21°Cto 21.5°C

2023-02-22 15:35:41.106 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom FollowScheduleto 
PermanentOverride


*Test 2*

2023-02-22 15:40:35.076 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 2

2023-02-22 15:40:35.077 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 2

2023-02-22 15:40:35.082 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 17°Cto 2°C

2023-02-22 15:40:35.533 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 25

2023-02-22 15:40:35.534 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 25

2023-02-22 15:40:35.539 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 2°Cto 25°C

==> /var/log/openhab/openhab.log <==

2023-02-22 15:40:44.887 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 15:40:45.112 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 21°Cto 21.5°C

2023-02-22 15:40:45.113 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom FollowScheduleto 
PermanentOverride

*Test 3*

2023-02-22 15:44:12.706 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 0

2023-02-22 15:44:12.707 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 0

2023-02-22 15:44:12.711 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 25°Cto 0°C

==> /var/log/openhab/openhab.log <==

2023-02-22 15:44:17.806 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 15:44:17.997 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom PermanentOverrideto 
FollowSchedule

2023-02-22 15:44:17.999 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 0°Cto 25°C

==> /var/log/openhab/openhab.log <==

2023-02-22 15:44:32.995 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 15:44:48.183 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 15:44:48.381 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 21.5°Cto 21°C

2023-02-22 15:44:48.382 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 25°Cto 17°C

*Test 4*

2023-02-22 16:47:03.876 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 18°Cto 18.5°C

2023-02-22 16:47:03.877 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom FollowScheduleto 
TemporaryOverride

2023-02-22 16:47:03.878 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 17°Cto 25°C

==> /var/log/openhab/openhab.log <==

2023-02-22 16:47:18.873 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:47:34.062 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:47:49.275 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:48:04.452 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:48:19.628 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:48:34.802 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:48:49.989 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:49:04.692 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/6522902/heatSetpoint]

==> /var/log/openhab/events.log <==

2023-02-22 16:49:04.685 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 22

2023-02-22 16:49:04.686 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 22

2023-02-22 16:49:04.691 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 25°Cto 22°C

==> /var/log/openhab/openhab.log <==

2023-02-22 16:49:04.859 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Request failed with unexpected response code 201

2023-02-22 16:49:05.177 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 16:49:05.433 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom TemporaryOverrideto 
PermanentOverride

==> /var/log/openhab/openhab.log <==

2023-02-22 16:49:20.431 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:49:35.616 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:49:50.863 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 16:49:59.840 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'PMSocket001_PMSocket001voltage' changedfrom 240 Vto 241 V

2023-02-22 16:49:59.896 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'PM_Socket_002_PM_Socket_002_voltage' changedfrom 240to 241

==> /var/log/openhab/openhab.log <==

2023-02-22 16:50:06.070 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:50:21.267 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 16:50:24.528 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'FrientMultiSensor001_FrientMultiSensor001illuminancelux' 
changedfrom 118to 99

==> /var/log/openhab/openhab.log <==

2023-02-22 16:50:36.462 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:50:51.654 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:51:04.702 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/temperatureZone/6522902/heatSetpoint]

==> /var/log/openhab/events.log <==

2023-02-22 16:51:04.697 [INFO ] [openhab.event.ItemCommandEvent ] - Item 
'StudyHeating_SetPoint' received command 0

2023-02-22 16:51:04.698 [INFO ] [penhab.event.ItemStatePredictedEvent] - 
Item 'StudyHeating_SetPoint' predictedtobecome 0

2023-02-22 16:51:04.700 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 22°Cto 0°C

==> /var/log/openhab/openhab.log <==

2023-02-22 16:51:04.889 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Request failed with unexpected response code 201

2023-02-22 16:51:06.849 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 16:51:07.046 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPointStatus' changedfrom PermanentOverrideto 
FollowSchedule

2023-02-22 16:51:07.047 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 0°Cto 22°C

==> /var/log/openhab/openhab.log <==

2023-02-22 16:51:22.042 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

==> /var/log/openhab/events.log <==

2023-02-22 16:51:22.236 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_Temperature' changedfrom 18.5°Cto 18°C

2023-02-22 16:51:22.237 [INFO ] [openhab.event.ItemStateChangedEvent ] - 
Item 'StudyHeating_SetPoint' changedfrom 22°Cto 17°C

==> /var/log/openhab/openhab.log <==

2023-02-22 16:51:37.233 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

2023-02-22 16:51:52.422 [DEBUG] [nding.evohome.internal.api.ApiAccess] - 
Requesting: 
[https://tccna.honeywell.com/WebAPI/emea/api/v1/location/2511276/status?includeTemperatureControlSystems=True]

**Comment by lsiepel** [comment] 2023-02-22 21:01
That 201 is certainly unexpected for the request performed, but I guess that is what evohome api returns. Will look at the code for a fix. But this is not introduced by this change.

thanks for testing, great that all seems fine.

**Closed** 2023-02-24 15:08 UTC
