### ISSUE TITLE
Upgrade H2 jdbc to 2.1.214

### ISSUE THREAD

**Issue by wollyd** [openhab/openhab-addons#13687] opened 2022-11-09 15:19 UTC
## Your Environment

* Version used: openhab 3.3, H2 jdbc 1.4.200
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): java 11

Is it possible to upgrade the H2 database driver from 1.4.200 to 2.1.214 ?
Or keep both drivers  as an  option ? 
thanks 

Willy

**Comment by wborn** [comment] 2022-11-09 22:56
IIRC everyone will need to export and reimport their H2 DBs for that upgrade? Might be another breaking change to do as part of OH4.

**Comment by wborn** [comment] 2022-11-09 23:05
If that JDBC driver is an OSGi bundle, you can add it to the /addons dir and use it since there is a dynamic import that can load it now with the changes in https://github.com/openhab/openhab-addons/pull/13038 🙂

**Comment by lolodomo** [comment] 2022-11-12 19:22
Closed as duplicate of #13115

**Closed by lolodomo** 2022-11-12 19:22 UTC
