### ISSUE TITLE
[hue] ColorTemperature channels becomes UNDEF when changed

### ISSUE THREAD

**Issue by toomtech** [openhab/openhab-addons#17643] opened 2024-10-28 00:08 UTC
When I have a semantic model like this:
 
```
Item (Group/Equipment)
+- Item (Color/Point) 
+-- (hue:device:...:color channel)
+- Item (Dimmer/Point)
+-- (hue:device:...:color-temperature channel)
```

I see the following occur:
* Using the MainUI I click the box marked equipment via Equipment tab in the web or ios app (3.0.5 (11)) UI
* I adjust the slider controlling the color-temperature
* After 1 or sometimes more interactions with the slider (1 in below example) the state becomes `UNDEF`, this is reflected by the log:
```
2024-10-27 18:17:19.360 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'office_lights_temp' received command 68
2024-10-27 18:17:19.462 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_lights_temp' changed from 19.88 to 68.01
2024-10-27 18:17:19.462 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_room_color' changed from 46.581,18.77100,83 to 37.999,57.25200,83
2024-10-27 18:17:19.468 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'office_room_color' received command 37,57,83
2024-10-27 18:17:20.470 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_lights_temp' changed from 68.01 to UNDEF
2024-10-27 18:17:20.471 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_room_color' changed from 37.999,57.25200,83 to 37.002,56.9900,83
```
* After that the color temperature slider no longer responds to interaction, no entries indicating interactions took place appear in the log, and ON/OFF toggle causes the light to turn off and immediately turn on which is reflected in the log:
```
2024-10-27 18:18:14.499 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'office_room_color' received command OFF
2024-10-27 18:18:14.599 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_room_color' changed from 37.002,56.9900,83 to 37.002,56.9900,0
2024-10-27 18:18:14.604 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'office_room_color' received command 37,57,83
2024-10-27 18:18:15.607 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_room_color' changed from 37.002,56.9900,0 to 37.002,56.9900,83
```
* Refreshing the page (or reloading the app) causes the on off switch to behave normally (log snippet follows) however the behavior returns as soon as I interact with the color temperature slider again:
```
2024-10-27 18:20:03.253 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'office_room_color' received command OFF
2024-10-27 18:20:03.373 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_room_color' changed from 37.002,56.9900,83 to 37.002,56.9900,0
```

I've noticed the following as well:
* The same behavior **DOES** occur with the Equipment Group under an Item (Group/Location) and controlling it using the box in the Item tab of the MainUI from web/app.
* The same behavior **DOES NOT** occur when an Item/Point linked to the `hue:device:...:color` channel is not present in same Equipment group as the color-temperature one
* The same behavior **DOES NOT** occur via web in `<openhaburl>/settings/model/` when I have the color-temperature item/point selected and adjust the color temperature slider on the side bar.
* The same behavior **DOES NOT** occur via web in `<openhaburl>/settings/items/<color_temp_item>` when I adjust the slider there.

## Expected Behavior
UNDEF state should not occur when interacting with color temperature

## Current Behavior
Provided in summary

## Possible Solution
I tried but I don't do any development in Java and I'm afraid this code base is a bit deep for me to fake my way through it 😊

## Steps to Reproduce (for Bugs)
Create model as described in summary with live hue light (or attached files) and adjust color-temperature slider a few times.

## Context
Color temperature and Color are both useful controls to cohabitate within the same equipment.  The temperature slider is a nice, quick way to adjust the tone of a room within natural boundaries which is much more difficult with the color wheel, and the color selector is great for freely picking any color.  The setup I've provided is stripped down as much as possible, but I have 100s of these lights organized into various rooms in the manner described (but with locations as parents) and I'd really like to not have to use the HUE app anymore for this functionality.

## Your Environment
* OpenHAB `4.3.0.M2` (occurs with latest stable `4.2.1` as well)
* AlmaLinux release 9.3, Java: build 17.0.10+11-LTS-240
* Chrome: 130.0.6723.70 (Official Build) (64-bit), IOS 18.0.1, App: (3.0.5 (11)
* 

I've included the complete responses (with some info redacted) from the `/things`, `/items`, and `/links` API endpoints to provide the device metadata and configuration:
[links.json](https://github.com/user-attachments/files/17535836/links.json)
[things.json](https://github.com/user-attachments/files/17535837/things.json)
[items.json](https://github.com/user-attachments/files/17535838/items.json)

If you need anything else please let me know!

**Comment by andrewfg** [comment] 2024-10-29 14:13
@toomtech many thanks for the report. 

It looks as though there is a deadly cycle between the User Interface and the Hue bridge. Which I think is due to the OH UI code wrongly rounding of HSB float values to integers. 

The sequence of events is as follows..

1. The binding posts a command to the Hue bridge to change the color temperature. The bridge replies with TWO events..
2. The bridge sends an event to confirm the new color temperature, and 
3. The bridge sends an event about the new color xy point on the color temperature locus on the CIE color space. 
4. The binding converts the new color xy to a new HSB value, which it sends to OH core.
5. OH core sends the new HSB value to the UI to update the respective widget.
6. The UI widget **ROUNDS** the respective HSB float values to the nearest integer, and sends them back to OH core.
7. OH core sends the new rounded HSB values to the binding.
8. The binding converts this HSB to a new color xy point which it posts to the Hue bridge. The bridge replies with TWO events..
9. The bridge sends an event to confirm the new color xy, and 
10. The bridge finds that the new color xy point is NOT on the color temperature locus on the CIE color space, so 
11. The bridge sends an event to say that the color temperature is now undefined.

Can you please do the following..

- Let me know what UI you are using? Main UI / Sitemap / other.
- Try it again with Main UI.
- Try to send a colour temperature command to the item, when there is NOT a UI page open. This prevents step 5. above and onwards.
- Turn on `log:set TRACE org.openhab.binding.hue` and upload the respective log file entries? With/without the UI page open.

**Comment by andrewfg** [comment] 2024-10-29 14:20
^
The critical lines from the log are below..

```
2024-10-27 18:17:19.462 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'office_room_color' changed .. to 37.999,57.25200,83
2024-10-27 18:17:19.468 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'office_room_color' received command 37,57,83
```

@jlaur personally I would say this is a bug in the UI. It sounds like an issue that we encountered before https://github.com/openhab/openhab-webui/issues/1862 => WDYT?

**Comment by lolodomo** [comment] 2024-10-29 18:35
> The UI widget ROUNDS the respective HSB float values to the nearest integer, and sends them back to OH core.

The fact that Main UI sends a command to core after rounding the received value looks like a critical issue.

**Comment by maniac103** [comment] 2024-10-29 18:52
> The fact that Main UI sends a command to core after rounding the received value looks like a critical issue.

Indeed, if step 6 really works that way, it's the root issue here. UIs only should send commands for user interactions.

**Comment by andrewfg** [comment] 2024-10-29 19:04
@maniac103 / @lolodomo thanks for the feedback. I will wait for the trace logs and information about the used UI from @toomtech before confirming the hypothesis, and if confirmed I will open an issue in OH WebUI

**Comment by andrewfg** [comment] 2024-10-29 19:25
@toomtech thanks for the logs. It seems to confirm my hypothesis. But I will need some more / different logging on the UI in order to open an issue in OH WebUI. I will get back to you tomorrow with info about which logging to enable..

**Comment by andrewfg** [comment] 2024-10-29 19:36
@toomtech what widgets are you using in Main UI? Perhaps you can post a screen shot? Also it might be easiest to see a capture of the actual traffic between OH and the UI. Do you have (and know how to use) Wireshark? If you are worried about your secure data, please either PM it to me on the Community forum, or email me instead.

**Comment by maniac103** [comment] 2024-10-29 20:08
> Do you have (and know how to use) Wireshark?

Shouldn't a network log from the browser's developer tools (usually opened by pressing F12) be sufficient for that purpose?

**Comment by andrewfg** [comment] 2024-10-30 18:55
@toomtech many thanks for the pcap. It shows something rather odd. See screenshot below. I am pretty sure that this is an error in Main UI. And to be specific the problem is NOT in the OH standard items slider screen, but IS in your Locations | Office widget. 

Your pcap shows the following sequent of events:

1. UI client commands CT item to 67%
2. OH server notifies CT item changed to 66.86%
3. OH server notifies Color item changed to HSB 38.101,56.52900,98.02 // note: S=**56.52900** !!
4. UI client commands Color item changed to HSB 39,39,98 // note: S=**39** !!
5. OH server notifies CT item changed to Undef
6. OH server notifies Color item changed to HSB 39.016,39.00500,98.02

Specific observation is that the S value massively changes between events 3. and 4. !! => It makes me suspect that your Client | Locations | Office widget is wrongly sending `HHB` instead of `HSB`. _=> We need to look into the widget code!_

![image](https://github.com/user-attachments/assets/9c6048aa-a54c-46eb-b18d-700c9c1ae3f0)

**Comment by andrewfg** [comment] 2024-10-30 20:03
> Is the wireshark dissector you're using there available publicly by any chance?

I "dissected" it by manually copy/pasting from WS into Excel. So I guess I must be publicly available at least from time to time. :)

**Comment by andrewfg** [comment] 2024-11-03 14:00
Just adding @toomtech 's image from the referenced issue..

![17306422989883087052599568809955](https://github.com/user-attachments/assets/bc4a5261-1e2b-4fb0-b000-b7e5b0b37a29)

**Comment by lolodomo** [comment] 2024-11-03 14:56
The video shows clearly Main UI standard screens.

**Comment by andrewfg** [comment] 2024-11-03 16:01
> video shows clearly Main UI standard screens.

Indeed. And to be more specific the issue only occurs on a screen where there are both a color item widget and a color temperature slider on the same screen (see below). And the problem is that when the UI POSTS a command to change the color temperature, then the OH core (correctly) notifies both the new color temperature and color values, and then the UI wrongly POSTS a second command for the new color value. => This second POST SHALL NOT happen!

![image](https://github.com/user-attachments/assets/f6997a17-e60a-43b9-8cda-a5bf1ecfec8e)

**Comment by andrewfg** [comment] 2024-11-03 16:09
This is indeed definitely a WebUI issue, so I have just copied the above two posts from this Issue to [the WebUI Issue](https://github.com/openhab/openhab-webui/issues/2849), and I will now close this issue here.

**Closed** 2024-11-06 13:17 UTC
