### ISSUE TITLE
[avmfritz] FritzBox 7490 Firmware 7.51

### ISSUE THREAD

**Issue by renek74** [openhab/openhab-addons#14073] opened 2022-12-27 11:51 UTC
AVM FRITZ!Box Binding 
after updating the FritzBox, all AVM Thigs are in error:bridge
no way to bring them back

![Unbenannt](https://user-images.githubusercontent.com/74518189/209662586-e90af95d-167e-4f25-981f-0b973a0aa2ac.PNG)

**Comment by lsiepel** [comment] 2023-01-01 00:28
https://en.avm.de/fritz-lab/fresh-from-development/updates-improvements/ Shows some login and ui related changes. Not sure if it is the cause.

**Comment by renek74** [comment] 2023-01-03 04:35
all was I read is new fuction. No things removed from box. Don´t know if other users have same problem with 7.51 Beta firmware on FritzBox.

**Comment by lsiepel** [comment] 2023-01-04 17:27
Under system: Improved New design for the FRITZ!Box login

I don’t know if it is the cause, but it might be related. I don’t have such device so I’m unable to help you without a trace log. If you can provide one that covers the initialisation. I might be able to look at it.

**Comment by renek74** [comment] 2023-01-04 21:00
since yesterday is working. I had two bidges to the Fritzbox in the past. No problems, but with new firmware was not working. Now is deactivate one of the connection to the bridge and now with only one bridge, connection ist working. Don´t know why....

**Comment by lsiepel** [comment] 2023-01-04 22:09
Then i assume we can close this issue. Please re-open when you encounter new issues with firmware and the openHAB binding.

**Closed by lsiepel** 2023-01-04 22:09 UTC

**Comment by r-wolff** [comment] 2023-08-06 21:17
Having the same issue for some time as well. Tried different Fritzlab-Versions for my 7490 without success, and after the final Update 7.56 is released, tried again, with OH 3.4 as well as OH4.0. Tried as well with different usernames and a freshly installed OH4 installation on another device (both raspi/Openhabian).
I know at least from another user in the german OH forum having the same problem.
Log entries:
Thing 'avmfritz:fritzbox:192_168_178_1' changed from OFFLINE (COMMUNICATION_ERROR): FRITZ!Box does not respond. to OFFLINE (COMMUNICATION_ERROR): Request is invalid
Thing 'avmfritz:fritzbox:192_168_178_1' changed from OFFLINE (COMMUNICATION_ERROR): Request is invalid to OFFLINE (COMMUNICATION_ERROR): FRITZ!Box does not respond.
