### ISSUE TITLE
[MPD] doesn't work with external mpd player

### ISSUE THREAD

**Issue by agh251256** [openhab/openhab-addons#10142] opened 2021-02-13 17:20 UTC
MPD Binding doesn't work with external MPD-Player. I've openhab on an raspberry installed and on two raspberries I installed MPD as musicplayer. Both player worked fine and I can control this with Gnome Music Player Client.
Now I'will try this with openhab. The version on OH 2.5.latest and 3,x gives the same result. it will not work completly. OH Binding goes online and that all. I can't control anything.
My OH Installation run on IP xx.xx.xx.10 my MPD's on xx.xx.xx.13 an .20 .

The only thing what I've found is an error in the Syslog on my OH3 Raspi (after the latest update, there is nothing in the syslog):
`Feb  8 20:27:57 raspiOHTest karaf[32614]: Exception in thread "OH-binding-mpd:mpd:Musik" java.lang.IllegalArgumentException: Value must be between 0 and 100
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:57)
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.core.library.types.PercentType.<init>(PercentType.java:42)
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.binding.mpd.internal.handler.MPDHandler.updateMPDStatus(MPDHandler.java:257)
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.binding.mpd.internal.protocol.MPDConnection.handleResponseStatus(MPDConnection.java:218)
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.binding.mpd.internal.protocol.MPDConnection.onResponse(MPDConnection.java:172)
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.binding.mpd.internal.protocol.MPDConnectionThread.processPendingCommands(MPDConnectionThread.jav
Feb  8 20:27:57 raspiOHTest karaf[32614]: #011at org.openhab.binding.mpd.internal.protocol.MPDConnectionThread.run(MPDConnectionThread.java:81)
`
Thats all, no errors more, not in the openhab.log and so on. The events.log shows me the sending commands, but nothing works.
There are no firewalls inside my internal network. People, how brings the binding up to work are using MPD and OH on the same IP adrress, on the same raspi. That's not the way for me.

**Comment by J-N-K** [comment] 2021-02-13 17:28
Looks like you get a value that can‘t be converted to PercentType. Increase Binding loglevel and see if you get more information.

**Comment by agh251256** [comment] 2021-02-13 18:19
I found to change the loglevel. 
I'm pressing the play  button for playing the current playlist in the mpd. After changing the loglevel, I get:
`2021-02-13 18:00:30.450 [WARN ] [s.impl.WebApplicationExceptionMapper] - javax.ws.rs.ClientErrorException: HTTP 405 Method Not Allowed
	at org.apache.cxf.jaxrs.utils.SpecExceptions.toHttpException(SpecExceptions.java:117)
	at org.apache.cxf.jaxrs.utils.ExceptionUtils.toHttpException(ExceptionUtils.java:168)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.findTargetMethod(JAXRSUtils.java:514)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.processRequest(JAXRSInInterceptor.java:181)
	at org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor.handleMessage(JAXRSInInterceptor.java:78)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:278)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:293)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:494)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:314)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
	at java.base/java.lang.Thread.run(Thread.java:834)`
I hope, it helps

**Comment by J-N-K** [comment] 2021-02-13 20:46
I can reproduce the original issue (and that is a bug), but controlling a mpd instance works fine (from a remote computer). Did you configure mpd to listen on the IP address? The dault is listen to localhost only.

**Comment by agh251256** [comment] 2021-02-13 21:18
My mpd listen on my network, not localhost. I can control the mpd from my pc with gmpc and from my tablet and so on

----- Originale Nachricht -----
Von: J-N-K <notifications@github.com>
Gesendet: 13.02.2021 - 21:46
An: openhab/openhab-addons <openhab-addons@noreply.github.com>
Betreff: Re: [openhab/openhab-addons] [MPD] doesn't work with external mpd player (#10142)

> I can reproduce the original issue (and that is a bug), but controlling a mpd instance works fine (from a remote computer). Did you configure mpd to listen on the IP address? The dault is listen to localhost only. 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/openhab/openhab-addons/issues/10142#issuecomment-778675979


-- 
Andreas Guhr
----------------------
um mein Signaturzertifikat auf Echtheit prüfen zu können, benötigen Sie das Wurzel(Root)zertifikat von CAcert: https://www.cacert.org/index.php?id=3

**Comment by J-N-K** [comment] 2021-02-14 06:38
Please try if the first fix also fixes your other problems: 

```
update org.openhab.binding.mpd https://janessa.me/esh/org.openhab.binding.mpd-3.1.0-SNAPSHOT.jar
```

I doubt it helps, but it's worth a try.

**Comment by agh251256** [comment] 2021-02-14 11:25
IT HELPS!!!!!!! I can control the extern MPD!! Danke, thanks,. You can close this bug

 

One question: How can I change or list playlists/albums and so on? Is this possible?

 

Von: J-N-K <notifications@github.com> 
Gesendet: Sonntag, 14. Februar 2021 07:39
An: openhab/openhab-addons <openhab-addons@noreply.github.com>
Cc: agh251256 <a.guhr@aghnet.de>; Author <author@noreply.github.com>
Betreff: Re: [openhab/openhab-addons] [MPD] doesn't work with external mpd player (#10142)

 

Please try if the first fix also fixes your other problems:

update org.openhab.binding.mpd https://janessa.me/esh/org.openhab.binding.mpd-3.1.0-SNAPSHOT.jar

I doubt it helps, but it's worth a try.

**Comment by agh251256** [comment] 2021-02-14 11:43
One question again, because I'm interesting of that. I've looking your changing code. I'm not a programer in java/C++, but I can understand a little bit. Now my question: Why do you set the volume to undef and not to the min or max value?

**Comment by J-N-K** [comment] 2021-02-14 11:47
Playlist/album: no idea, I don‘t even use mpd

From my understanding a value of -1 means „not set/unknown“, so UNDEF seems to be the closest equivalent.

**Comment by agh251256** [comment] 2021-02-14 12:03
You can thinking about using playlist and so on, to complete the binding. ;-)
Thank you very much for your help

My understanding is that values can be +/- and greater than 100 :-)

Must I close this issue?

**Comment by J-N-K** [comment] 2021-02-14 12:07
I think volume is usually 0-100%, what would a value of -10 mean (ok, it could be dB or something like that, but that is not what mpd is reporting).

No, please don’t close this issue until someone fixes it on openHAB.

**Comment by stefanroellin** [comment] 2021-02-15 13:29
Which version of mpd are you using? According to the protocol specification a volume -1 is deprecated and should not occur in never versions. I have nevertheless submitted a fix.
You can use an action to change the playlist - see the example at the bottom of https://www.openhab.org/addons/bindings/mpd/

**Comment by agh251256** [comment] 2021-02-15 15:06
Both mpd version are 0.19.21 Debian stretch

for changing the playlist/album, it's better to know which playlist/album exist.  In the example, I saw some possible actions, but I don't know what is also possible. My next handicap is the english language, that is not so well. What I missed are more functions like gmpc, I know that's a dream :-)

**Comment by stefanroellin** [comment] 2021-02-15 15:21
This is a really old version! If you encounter other problems with the mpd binding I suggest you update to a more recent version.

With actions you can do almost everything you can do with gmpc. Have you tried the example? Define a switch named `morning_music` and define the rule:

```
rule "turn on morning music"
when
        Item morning_music changed to ON
then
        val actions = getActions("mpd","mpd:mpd:music")  // change "mpd:mpd:music" to your thing id
        if(actions === null) {
                logWarn("myLog", "actions is null")
                return
        }

        actions.sendCommand("clear");                // clears the queue
        actions.sendCommand("load", "MorningMusic"); // loads the playlist named "MorningMusic" 
        actions.sendCommand("shuffle");              // shuffle the queue
        actions.sendCommand("play");                 // play
end
```
Now, if the switch changes to ON, the queue is cleared, the playlist "MorningMusic" is loaded and shuffled and then played. 

If you don't want to hard-code the name of the playlist you can define a string item and use the state of the item for the playlist.

For a list of commands see https://www.musicpd.org/doc/html/protocol.html

**Comment by agh251256** [comment] 2021-02-15 15:55
Dear Stefan,
I've understood the example, you can believe it. :-) Your last sentence is a good note, that I missed in the discription of the binding.

**Closed** 2021-02-17 20:06 UTC
