### ISSUE TITLE
[homekit] Exception in OH log file

### ISSUE THREAD

**Issue by EjvindHald** [openhab/openhab-addons#14177] opened 2023-01-07 15:28 UTC
## Expected Behavior
I am not sure it is homekit related, but this is what I think, because hapjava.server is mentioned many times in the error messages.
The expected behaviour is no errors in the log file.

## Current Behavior
This error message appeared in my openhab.log. There are no lines before or after related to the error. Unfortunately, I do not have any event or similar clue to share some light on this. When it happened I was not in process of doing any changes to my OH setup. 

`2023-01-06 18:31:52.059 [WARN ] [.server.impl.connections.HttpSession] - Could not handle request

java.lang.RuntimeException: Unrecognized method: 5

	at io.github.hapjava.server.impl.pairing.PairingUpdateController.handle(PairingUpdateController.java:36) ~[bundleFile:?]

	at io.github.hapjava.server.impl.connections.HttpSession.handleAuthenticatedRequest(HttpSession.java:87) [bundleFile:?]

	at io.github.hapjava.server.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:55) [bundleFile:?]

	at io.github.hapjava.server.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:49) [bundleFile:?]

	at io.github.hapjava.server.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) [bundleFile:?]

	at io.github.hapjava.server.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) [bundleFile:?]

	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [bundleFile:4.1.72.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]

	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) [bundleFile:4.1.72.Final]

	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) [bundleFile:4.1.72.Final]

	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [bundleFile:4.1.72.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [bundleFile:4.1.72.Final]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.72.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.72.Final]

	at java.lang.Thread.run(Thread.java:829) [?:?]`

## Possible Solution
Identify root cause and apply proper change.

## Steps to Reproduce (for Bugs)
Sorry, I do not know how to reproduce. I will update the issue, if I can see how it can be reproduced.

## Context
I am trying to get all OH log file without any errors. This is because I am facing daily increase in memory consumption in my OH 3.4 instance, and I do not know why. In OH 3.3 everything was fine. See [link](https://community.openhab.org/t/how-can-i-find-a-memory-leak/142595)

## Your Environment
I am running OH 3.4.0 in Docker with these bindings: hue,mqtt,modbus,rfxcom,ihc,exec,velux,pushover,deconz It is running on a Intel based Linux Ubunto server version 2022.

**Comment by ccutrer** [comment] 2023-01-07 16:04
This is a duplicate of https://github.com/openhab/openhab-addons/issues/13949. The issue is not openHAB 3.4.0, but iOS 16.2. It has already been fixed. Until 3.4.1 is released, you can run `update org.openhab.io.homekit https://github.com/ccutrer/openhab-addons/releases/download/homekit-20221220-02/org.openhab.io.homekit-3.4.0-SNAPSHOT.jar` in the openHAB console to update to a working snapshot.

**Closed by ccutrer** 2023-01-07 16:04 UTC

**Comment by ccutrer** [comment] 2023-01-09 15:16
openHAB 3.4.1 has been released, which includes the fix.

**Comment by EjvindHald** [comment] 2023-01-09 15:39
Thank you very much!
