### ISSUE TITLE
[enocean] Cannot build due to spotless issue

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#13886] opened 2022-12-09 11:52 UTC
```
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.22.5:check (codestyle_check) on project org.openhab.binding.enocean: The following files had format violations:
[ERROR]     src/main/java/org/openhab/binding/enocean/internal/discovery/EnOceanDeviceDiscoveryService.java
[ERROR]         @@ -109,9 +109,9 @@
[ERROR]          
[ERROR]          ········String·enoceanId·=·HexUtils.bytesToHex(eep.getSenderId());
[ERROR]          
[ERROR]         -········bridgeHandler.getThing().getThings().stream()
[ERROR]         -················.filter(t·->·t.getConfiguration().getProperties().getOrDefault(PARAMETER_ENOCEANID,·EMPTYENOCEANID)
[ERROR]         -························.toString().equals(enoceanId))
[ERROR]         +········bridgeHandler
[ERROR]         +················.getThing().getThings().stream().filter(t·->·t.getConfiguration().getProperties()
[ERROR]         +························.getOrDefault(PARAMETER_ENOCEANID,·EMPTYENOCEANID).toString().equals(enoceanId))
[ERROR]          ················.findFirst().ifPresentOrElse(t·->·{
[ERROR]          ····················//·If·repeated·learn·is·not·allowed·=>·send·teach·out
[ERROR]          ····················//·otherwise·do·nothing
```

**Comment by lolodomo** [comment] 2022-12-10 08:42
It builds without error on my local machine.
And if I run "mvn spotless:apply" at the root of the binding, no file is changed.

**Comment by lolodomo** [comment] 2022-12-10 08:50
And the last change on this file was apparently merged 11 months ago.

**Comment by lsiepel** [comment] 2022-12-11 15:11
The current pom.xml has version 2.0.3, it looks like 2.22.5 was used. I just tried that version. Same result as lolodomo, builds fine. Could you check again J-N-K  and make sure it is not your build environment?

**Comment by lolodomo** [comment] 2022-12-17 09:16
@J-N-K : can we close your issue?

**Comment by lsiepel** [comment] 2022-12-20 18:49
Cannot reproduce. Just made a PR, it builds fine locally and on CI / Build (Java 17, ubuntu-22.04) So i think something else was wrong there. Re-open if this is still an issue.

**Closed by lsiepel** 2022-12-20 18:49 UTC
