### ISSUE TITLE
configuration = getConfigAs(); error on integers

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-addons#64] opened 2014-11-28 22:42 UTC
I'm struggling with getting the item configuration via  getConfigAs() 

e.g.    MaxCubeBridgeConfiguration configuration = getConfigAs(MaxCubeBridgeConfiguration.class);
This works fine for string items, but for integers it seems to fail

the description 

```
        <parameter name="port" type="integer">
                <context>port</context>
                <label>MAX! Cube LAN gateway port</label>
                <description>Port of the LAN gateway</description>
                <default>62910</default>
                <required>false</required>
            </parameter>
```

23:25:36.073 WARN  o.e.s.c.core.Configuration[:59] - Could not set field value for field 'port': Can not set int field org.openhab.binding.max.config.MaxCubeBridgeConfiguration.port to java.lang.String
java.lang.IllegalArgumentException: Can not set int field org.openhab.binding.max.config.MaxCubeBridgeConfiguration.port to java.lang.String
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
    at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
    at sun.reflect.UnsafeIntegerFieldAccessorImpl.set(Unknown Source)
    at java.lang.reflect.Field.set(Unknown Source)
    at org.eclipse.smarthome.config.core.Configuration.as(Configuration.java:57)
    at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.getConfigAs(BaseThingHandler.java:129)
    at org.openhab.binding.max.internal.handler.MaxCubeBridgeHandler.initialize(MaxCubeBridgeHandler.java:141)
    at org.eclipse.smarthome.core.thing.binding.BaseThingHandlerFactory.registerHandler(BaseThingHandlerFactory.java:109)
    at org.eclipse.smarthome.core.thing.internal.ThingManager.registerHandler(ThingManager.java:290)
    at org.eclipse.smarthome.core.thing.internal.ThingManager.thingAdded(ThingManager.java:221)
    at org.eclipse.smarthome.core.thing.internal.ThingRegistryImpl.notifyTrackers(ThingRegistryImpl.java:142)
23:25:36.073 WARN  o.e.s.c.core.Configuration[:59] - Could not set field value for field 'refreshInterval': Can not set java.lang.Long field org.openhab.binding.max.config.MaxCubeBridgeConfiguration.refreshInterval to java.lang.String

**Comment by marcelrv** [comment] 2015-01-07 11:34
Can be closed now as it is implemented in ESH

**Comment by marcelrv** [comment] 2015-01-07 21:17
Well.... it worked for a day. 
Seems it broke again, I think because of commit https://github.com/eclipse/smarthome/commit/f7953f2f1e32cec9a38230fc14386587f75084da

Now the value after discovery is of type bigdecimal, but once restarted and it comes from the database it comes with double type

As in the conversion class  if (value != null && **value instanceof BigDecimal** && !typeName.equals("BigDecimal"))  it fails this test and does not do conversion

**Comment by dnobel** [comment] 2015-01-07 21:24
I don´t think that the mentioned PR has broken it. There seems to a general issue with the GSON serialization and deserialization for the database. I´ll try to investigate this.

**Comment by dnobel** [comment] 2015-01-07 21:46
I have written a test for it and unfortunately it fails:

```java
@Test
    void 'assert store configuration works'() {
        def storageWithoutClassloader = storageService.getStorage("storage")
        
        def configuration = new Configuration();
        configuration.put("bigDecimal", new BigDecimal(3))
        
        storageWithoutClassloader.put("configuration", configuration)
        
        def bigDecimal = storageWithoutClassloader.get("configuration").get("bigDecimal")
        assertThat bigDecimal instanceof BigDecimal, is(true)
    }
```

That means GSON deserializes doubles for serialized BigDecimal values as default. We need another bug in ESH to fix this issue (I will create one), but it is independent from the configAs feature.

**Comment by kaikreuzer** [comment] 2015-01-07 21:48
Now this is a truly unexpected behavior. This GSON stuff is really weird...

**Comment by dnobel** [comment] 2015-01-07 21:53
Bug created: https://bugs.eclipse.org/bugs/show_bug.cgi?id=456979

**Comment by marcelrv** [comment] 2015-01-07 23:23
What's strange to me is that I'm sure it was working yesterday when I'm
testing it.
Did anything change in the configuration between yesterday and today?

2015-01-07 22:53 GMT+01:00 Dennis Nobel <notifications@github.com>:

**Comment by dnobel** [comment] 2015-01-08 07:41
No, it was not changed. The error is potentially there since the initial contribution. But with the introduction of the typed parameters, the bug went visible. 

Please note, that it only occurs, after the configuration is deserialized from the Database, so only after you restart your openHAB  instance.

**Comment by kaikreuzer** [comment] 2015-02-11 15:29
As https://bugs.eclipse.org/bugs/show_bug.cgi?id=456979 is fixed and available to openHAB 2, I close this issue.

**Closed by kaikreuzer** 2015-02-11 15:29 UTC
