### ISSUE TITLE
[amazonechocontrol] WebSocketClient threads will not be closed

### ISSUE THREAD

**Issue by chris922** [openhab/openhab-addons#7945] opened 2020-06-19 14:33 UTC
## Expected Behavior
WebSocketClient threads will be closed properly after the request

## Current Behavior

I had the issue that my openHAB2 instance crashes after running for a few hours, in the logs I found a hint that no new thread could be created (_OutOfMemoryError: unable to create native thread_). After digging deeper I saw that my openHAB process spawned a hgue amount of threads (a few thousands) and most of the threads were named like `WebSocketClient@31337807-4743`.
Therefore I checked the installed bindings and saw that the amazonechocontrol binding can spawn threads, after removing it the issue was gone and no new `WebSocketClient` threads were spawned.
I verified this by installing the binding again, checking periodically the thread dump and removing the binding. During the time it was installed the amount of `WebSocketClient` threads growed.

In the logs I also found this exception:

```
2020-06-15 20:01:55.784 [INFO ] [control.internal.WebSocketConnection] - Web Socket error
java.nio.channels.AsynchronousCloseException: null
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:181) [bundleFile:9.4.20.v20190813]
        at java.util.ArrayList.forEach(ArrayList.java:1540) [?:?]
        at org.eclipse.jetty.client.AbstractConnectionPool.close(AbstractConnectionPool.java:208) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.DuplexConnectionPool.close(DuplexConnectionPool.java:237) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpDestination.close(HttpDestination.java:385) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.client.HttpClient.doStop(HttpClient.java:260) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:180) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:201) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.websocket.client.WebSocketClient.doStop(WebSocketClient.java:371) [bundleFile:9.4.20.v20190813]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:93) [bundleFile:9.4.20.v20190813]
        at org.openhab.binding.amazonechocontrol.internal.WebSocketConnection.close(WebSocketConnection.java:159) [bundleFile:?]
        at org.openhab.binding.amazonechocontrol.internal.WebSocketConnection$2.run(WebSocketConnection.java:184) [bundleFile:?]
        at java.util.TimerThread.mainLoop(Timer.java:556) [?:?]
        at java.util.TimerThread.run(Timer.java:506) [?:?]
```

## Possible Solution
I don't know why the connection couldn't be closed, but maybe the bug will be solved switching to the openHAB WebSocketFactory:

The binding creates the `WebSocketClient` here: 

https://github.com/openhab/openhab-addons/blob/2.5.5/bundles/org.openhab.binding.amazonechocontrol/src/main/java/org/openhab/binding/amazonechocontrol/internal/WebSocketConnection.java#L74

I saw that the openHAB core provides a way to create new `WebSocketClient` instances that takes care about the required thread pooling:

https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.io.net/src/main/java/org/openhab/core/io/net/http/WebSocketFactory.java#L39

Maybe this factory should be used in the binding as well? Anyways the issue with closing the connection might persist.

## Steps to Reproduce (for Bugs)
Unfortunately I think the issue is somehow related to my environment, anyway the way for me to reproduce it is the following:
1. Install Amazon Echo Control binding
2. Check thread dumps periodically -> `WebSocketClient` thread amount increases
3. Remove Amazon Echo Control binding
4. Check thread dumps periodically  -> `WebSocketClient` thread amount is stable

## Your Environment
* Version used: openHAB 2.5.5
* Operating System and version: Debian Buster

**Comment by J-N-K** [comment] 2020-06-19 14:38
Duplicate of #7910

**Closed by J-N-K** 2020-06-19 14:38 UTC

**Comment by chris922** [comment] 2020-06-19 14:42
Ouh damn. Just searched the opened issues. But great to hear the issue was already solved! :)
