### ISSUE TITLE
[gardena] ClassCastException in GardenaAccountHandler.onDeviceUpdated()

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#13001] opened 2022-06-24 11:49 UTC
The binding throws a ClassCastException in the GardenaAccountHandler.onDeviceUpdated() method approximately every 2 minutes.

I am not sure if this is a regression due to recent PRs #12947 or #12957 (but I have not noticed this error in prior builds).

```
2022-06-20 12:40:43.046 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.ClassCastException: class org.openhab.binding.gardena.internal.handler.GardenaThingHandler cannot be cast to class org.openhab.binding.gardena.internal.handler.GardenaThingHandler (org.openhab.binding.gardena.internal.handler.GardenaThingHandler is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @cb87ab; org.openhab.binding.gardena.internal.handler.GardenaThingHandler is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @aedffa)
	at org.openhab.binding.gardena.internal.handler.GardenaAccountHandler.onDeviceUpdated(GardenaAccountHandler.java:172) ~[?:?]
	at org.openhab.binding.gardena.internal.GardenaSmartImpl.lambda$1(GardenaSmartImpl.java:419) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by andrewfg** [comment] 2022-06-24 11:49
@jlaur any thoughts?

**Comment by lolodomo** [comment] 2022-06-24 11:55
Very bad timing !
This should be fixed if possible this weekend, between 3.3RC1 and ifnal 3.3.

**Comment by jlaur** [comment] 2022-06-24 12:49
@andrewfg - #12957 was not really intended for 3.3 as it was not a bugfix, but on the other hand, I doubt it's causing this problem. Seems to happen here:

```
            final GardenaThingHandler gardenaThingHandler;
            if ((gardenaThing = getThing().getThing(thingUID)) != null
                    && (gardenaThingHandler = (GardenaThingHandler) gardenaThing.getHandler()) != null) {
```

So `gardenaThing.getHandler()` returns an object which is not a `GardenaThingHandler` - perhaps null? Not sure.

If there would be any doubt or in panic mode, I have no problems with #12957 being reverted for the release, as it doesn't improve anything runtime. Unfortunately I have no time today.

@andrewfg - before doing anything in panic:
- Can you reproduce it all the time?
- Can you try reproducing it when having reverted latest changes?

Just to pinpoint if related to changes or some other unknown.

**Comment by andrewfg** [comment] 2022-06-24 14:57
> Can you reproduce it consistently?

Unfortunately not. The only thing that I can think of is that when I was testing the last PR's I enabled/disabled the bridge thing repeatedly in order to force a refresh of the `DeviceItem` states. And I may have set the handler into some odd state. I have now added more logging to the code, and done a fresh shutdown, reboot, restart of the OH system. An I will let it run for a while in case it was just a spurious problem

> Can you try reproducing it when having reverted latest changes?

Therefore, ditto..

> Will it help logging something where this exception is thrown?

Yes I am running this now.

---

```
final GardenaThingHandler gardenaThingHandler;
            if ((gardenaThing = getThing().getThing(thingUID)) != null
                    && (gardenaThingHandler = (GardenaThingHandler) gardenaThing.getHandler()) != null) {
```

You are correct that this is apparently the cause. Which indeed makes me also think that the last two PR's could not have caused the issue directly. But perhaps only indirectly because I think it is a concurrency related issue, and the rebuild might have made different nuances of timing and stack etc. In any case, the code snippet above is IMHO not good code, and I would in any case refactor it to unwind the assignments and null checks etc. and prevent throwing a runtime exception.

---

I am tending to think there is a concurrency issue in this code where `deviceToNotifyFuture` refers to itself. And perhaps I need to synchronize the outer method or the inner runnable in some way??

https://github.com/openhab/openhab-addons/blob/a1a02f05bfb5b050d7f0579a4cb638bf913ec7ee/bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java#L423

---

> This should be fixed if possible this weekend, between 3.3RC1 and ifnal 3.3.

@jlaur / @lolodomo I will definitely do that!

**Comment by andrewfg** [comment] 2022-06-24 15:33
@jlaur / @lolodomo I opened PR #13004 as a quick fix to eliminate ClassCastException errors and add more logging. The purpose of this PR is so that v3.3 RC1 resp. v3.3 Final can be released as clean as possible..

**Closed** 2022-06-24 16:25 UTC

**Comment by andrewfg** [comment] 2022-06-24 17:15
> This error looks to me as if there are older instances of the same class involved, e.g. like after an update or restart of the bundle at runtime.

@kaikreuzer this is a very interesting insight, thank you; and most probably the correct one since while testing #12947 and #12957 I was repeatedly disabling/enabling the bridge thing and/or dropping a modified binding JAR in the 'addons' folder without explicitly doing system stops and starts.

I am now running the newly merged #13001 on a newly rebooted system, and it looks clean to me.

> this wouldn't explain why it happens every 2 minutes.

The error was occurring every time that the hub sent a state change event over the web socket. This obviously depends on how many sensors are connected, and (for example) how fast the soil humidity measurement was changing. i.e. the two minutes was an average for my case only..

**Comment by kaikreuzer** [comment] 2022-06-25 09:46
Ok, then I wouldn't consider this issue to be too critical. 
We might want to have another look at the lifecycle management, though, so that the `dispose()` method really makes sure that any async jobs are stopped and no further calls (with old class versions) are coming in after a restart.

**Comment by jlaur** [comment] 2022-06-25 10:46
> We might want to have another look at the lifecycle management, though, so that the `dispose()` method really makes sure that any async jobs are stopped and no further calls (with old class versions) are coming in after a restart.

I agree, and this also triggered an idea about possible cause. I wondered if a construct like this could be causing a wild-running job:

```
private void rescheduleJob()
{
    ScheduledFuture<?> job = this.job;
    if (job != null)
    {
        job.cancel(false);
    }
    job = scheduler.schedule() // ...
}
```
(the bug here is that no reference to the job is kept, since it's stored in local variable)

I briefly went through job scheduling in the binding, and didn't find any such obvious issues, but potentially found a smaller one in `GardenaSmartImpl`:

```
                    // delay the deviceUpdated event to filter multiple events for the same device dataItem property
                    if (deviceToNotifyFuture == null) {
                        deviceToNotifyFuture = scheduler.schedule(() -> {
                            deviceToNotifyFuture = null;
                            Iterator<Device> notifyIterator = devicesToNotify.iterator();
                            while (notifyIterator.hasNext()) {
                                eventListener.onDeviceUpdated(notifyIterator.next());
                                notifyIterator.remove();
                            }
                        }, 1, TimeUnit.SECONDS);
                    }
```

It seems that if a web socket message is received, which trigger this 1s delayed job, then the job itself will remove its own reference before iterating. So if `dispose()` is called right after this 1s delay when job is triggered, the job will continue after `dispose()`, and `onDeviceUpdated()` might still be called, which would then throw.

This happens to be the method @andrewfg just improved.

But since the job is a one-shot job, even if exception is thrown like in this case, it shouldn't be repeating, so probably not the real issue.

**Comment by andrewfg** [comment] 2022-06-25 14:15
> potentially found a smaller one in GardenaSmartImpl:

@jlaur if you look at my prior post https://github.com/openhab/openhab-addons/issues/13001#issuecomment-1165657845 (last point) you will see that I already highlighted this code as being suspicious. And BTW the issue about 'repeating' has nothing to do with scheduled tasks; it just 'repeats' (i.e. re-occurs) every time the hub sends a new event notification (which in my case is about every two minutes)..

**Comment by andrewfg** [comment] 2022-06-25 17:16
@jlaur / @kaikreuzer => #13011 was created just now

**Comment by jlaur** [comment] 2022-06-25 20:43
> if you look at my prior post [#13001 (comment)](https://github.com/openhab/openhab-addons/issues/13001#issuecomment-1165657845) (last point) you will see that I already highlighted this code as being suspicious.

Sorry, I missed that note.
