### ISSUE TITLE
[fineoffsetweatherstation] no more updates after java.lang.IllegalMonitorStateException warning

### ISSUE THREAD

**Issue by TheNinth7** [openhab/openhab-addons#14322] opened 2023-02-03 05:58 UTC
The binding regularly looses connection to the gateway. The gateway Thing is still shown as ONLINE, but no more updates are received and all the readings (temperature, wind, rain etc.) stay at at their previous value.

## Current Behavior

The following entry is shown in the log, after which no more updates are received:

```
2023-02-02 15:33:28.882 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.IllegalMonitorStateException: null
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:149) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302) ~[?:?]
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.GatewayQueryService.executeCommand(GatewayQueryService.java:123) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.executeCommand(FineOffsetGatewayQueryService.java:113) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.getMeasuredValues(FineOffsetGatewayQueryService.java:93) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.query(FineOffsetGatewayHandler.java:277) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.updateLiveData(FineOffsetGatewayHandler.java:159) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

When I disable and enable the gateway thing, updates are received again.

Here a screenshot of the wind reading, which flat lined yesterday afternoon after the above warning, until I disabled/enabled the gateway thing today in the morning:

![Screenshot - 03_02_2023 , 06_55_34](https://user-images.githubusercontent.com/118298758/216523837-47d3be86-d2ab-4d13-8662-8bb72eb27c51.png)

## Steps to Reproduce (for Bugs)
Not sure yet how to reproduce it, but it happens every day or two, so quite regularly.

## Your Environment
* Version used: openHAB 3.4.0
* Running in a Docker container on a Synology DS420+ NAS
* Ecowitt GW2000 with an WS90. The GW2000 is connected via wired LAN to openHAB

**Comment by Andy2003** [comment] 2023-02-03 11:25
seems to be this issue: https://stackoverflow.com/a/25571191/1666829

**Comment by Andy2003** [comment] 2023-02-03 11:29
@TheNinth7 do you see any `executeCommand(XXX) time out while getting lock` in the trace logs?

**Comment by TheNinth7** [comment] 2023-02-03 14:15
> @TheNinth7 do you see any `executeCommand(XXX) time out while getting lock` in the trace logs?

Not really, but there is two other warnings/errors that I see in the log files, both seem to happen when disabling/enabling the gateway, but again not always.

Here is the first:

```
2023-02-03 06:37:12.582 [WARN ] [ervice.FineOffsetGatewayQueryService] - executeCommand(CMD_GW1000_LIVEDATA)
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireNanos(AbstractQueuedSynchronizer.java:982) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(AbstractQueuedSynchronizer.java:1288) ~[?:?]
	at java.util.concurrent.locks.ReentrantLock.tryLock(ReentrantLock.java:424) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.GatewayQueryService.executeCommand(GatewayQueryService.java:80) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.executeCommand(FineOffsetGatewayQueryService.java:113) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.getMeasuredValues(FineOffsetGatewayQueryService.java:93) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.query(FineOffsetGatewayHandler.java:277) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.updateLiveData(FineOffsetGatewayHandler.java:159) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-02-03 06:37:17.623 [WARN ] [core.thing.internal.ThingManagerImpl] - Initializing handler for thing 'fineoffsetweatherstation:gateway:2353730741' takes more than 5000ms.
```

And here the second:

```
2023-02-03 10:13:33.493 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler@dfeb4e2': null
java.lang.IllegalMonitorStateException: null
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:149) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302) ~[?:?]
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.GatewayQueryService.executeCommand(GatewayQueryService.java:123) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.executeCommand(FineOffsetGatewayQueryService.java:113) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.fetchSystemInfo(FineOffsetGatewayQueryService.java:81) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.lambda$0(FineOffsetGatewayQueryService.java:71) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetDataParser.getRegisteredSensors(FineOffsetDataParser.java:94) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.getRegisteredSensors(FineOffsetGatewayQueryService.java:69) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.query(FineOffsetGatewayHandler.java:277) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.fetchAndUpdateSensors(FineOffsetGatewayHandler.java:127) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.initialize(FineOffsetGatewayHandler.java:118) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-02-03 10:13:33.499 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'fineoffsetweatherstation:gateway:2353730741': null
java.lang.IllegalMonitorStateException: null
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:149) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302) ~[?:?]
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.GatewayQueryService.executeCommand(GatewayQueryService.java:123) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.executeCommand(FineOffsetGatewayQueryService.java:113) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.fetchSystemInfo(FineOffsetGatewayQueryService.java:81) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.lambda$0(FineOffsetGatewayQueryService.java:71) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetDataParser.getRegisteredSensors(FineOffsetDataParser.java:94) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.service.FineOffsetGatewayQueryService.getRegisteredSensors(FineOffsetGatewayQueryService.java:69) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.query(FineOffsetGatewayHandler.java:277) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.fetchAndUpdateSensors(FineOffsetGatewayHandler.java:127) ~[?:?]
	at org.openhab.binding.fineoffsetweatherstation.internal.handler.FineOffsetGatewayHandler.initialize(FineOffsetGatewayHandler.java:118) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```

**Comment by Andy2003** [comment] 2023-02-03 15:07
Perfect, the 1st one (InterruptedException) is the cause, which I fixed with the PR

**Closed** 2023-02-04 17:03 UTC
