### ISSUE TITLE
[mqtt] Instance is not an MQTTActions class

### ISSUE THREAD

**Issue by JornHermans** [openhab/openhab-addons#7215] opened 2020-03-23 17:52 UTC
**I already did post my question to the OpenHAB community but i got a forward to here. Because it's an issue with the binding, will post my full experience bellow:**

These are **the rules** that i'm running to communicate to the cloud mqtt and to the local mqtt:

    rule "Publish updates to the local and cloud event bus"
    when
        Member of PubItems received update
    then
        val mqttActionsLocal = getActions("mqtt","mqtt:broker:local")
        mqttActionsLocal.publishMQTT("/bus/out/"+triggeringItem.name+"/state",triggeringItem.state.toString,true)
        val mqttActionsCloud = getActions("mqtt","mqtt:broker:cloud")
        mqttActionsCloud.publishMQTT("/bus/43193719-F06E-4045-82E8-CF145AA7DB04/out/"+triggeringItem.name+"/state",triggeringItem.state.toString,true)
    end

    rule "Subscribe for commands and updates from the local event bus"
    when
        Channel 'mqtt:broker:local:bus' triggered
    then
        val itemName = receivedEvent.toString.split("/").get(3)
        val type = receivedEvent.toString.split("/").get(4)
        val state = receivedEvent.toString.split("#").get(1)

        if(type == "command") sendCommand(itemName, state)
        else postUpdate(itemName, state)
    end 

    rule "Subscribe for commands and updates from the cloud event bus"
    when
        Channel 'mqtt:broker:cloud:bus' triggered
    then
        val itemName = receivedEvent.toString.split("/").get(4)
        val type = receivedEvent.toString.split("/").get(5)
        val state = receivedEvent.toString.split("#").get(1)

        if (type == "command") sendCommand(itemName, state)
        else postUpdate(itemName, state)
    end 

**The full error that i get is this:**
> Rule ‘Publish updates to the local and cloud event bus’: Instance is not an MQTTActions class.

*Like you already noticed, i did a few changes to the example above becausse i'm sending updates and recieving commands to/from 2 mqtt brokers (one localy and one in the cloud)*

The wierd thing is that when i did a restart of the whole system it didn't help :confused: 
when i disabled the broker thing and enabled it back it was working fine again, and no error's so far... 
This happend 3 times so far.

**Comment by micha-tum** [comment] 2020-04-06 16:05
I've got the same issue. Only using one broker though. Are you using the zram feature of openhabian? I feel like the issues started when I enabled that.
For me, a restart of the openhab service fixes the issue until the next restart. Restarting the whole operating system (raspberry pi) did not help on the other side and the issue was there again on startup (so it might be a startup sequence thing).

**Comment by andy-ich** [comment] 2020-07-28 12:37
I had the same problem.
Could solve it by renaming the rule-file from Bewässerung.rules to Bewaesserung.ruels, so without special characters.
Is that also the case with you?

**Comment by andy-ich** [comment] 2020-08-03 15:24
Unfortunately that wasn't the cause!
Had the same bug again today.
a new Try: the definition "val mqttActions = getActions..." set before each "mqttActions.publishMQTT..." command.

**Comment by stefan-muc** [comment] 2020-12-29 10:52
Same problem here - out of nowhere the rule doesn't work anymore yielding the same error message.
Another rule (with analog code) simply doesn't work anymore, producing no error message.
Possibly a side effect: a map for outgoing values (mapping ON to true) doesn't work anymore.
Receiving values works fine.

OpenHAB 2.4.0 with mqtt and mqtt1 binding (mqtt1 not used for this case here)

**Comment by hmerk** [comment] 2022-07-04 19:14
Closed as there will be no more fixes/enhancements for openHAB 2. If still valid for openHAB 3, please open a new issue with actuals logs.

**Closed by hmerk** 2022-07-04 19:14 UTC

**Comment by ptrooms** [comment] 2022-12-29 16:32
A bit silly as close remark which effectively means one has to migrate to version 3 while this bug was introduced in version 2.4.0
