### ISSUE TITLE
[knx] brightness status "UNDEF" when dimmed via knx switch for values < 1%

### ISSUE THREAD

**Issue by smartheit** [openhab/openhab-addons#11802] opened 2021-12-17 08:13 UTC
## Current Behavior
When brightness values below 1% are adjusted externally (e.g. from a KNX light switch) the dimmer item states undefined:
![image](https://user-images.githubusercontent.com/88311932/146506900-db114afa-ffad-4836-a1d2-6a27dc163810.png)

Setup: Dali Gateway with active brightness feedback. openHAB 3.2.0.M4 in docker environment. KNX Gateway: knxd.

OH3 things item:
`Type dimmer : Licht_OG_Tim [ switch="10/3/10+<11/3/10", position="13/3/10+<14/3/10", increaseDecrease="12/3/10"]`

KNX bus plot:
![image](https://user-images.githubusercontent.com/88311932/146507766-856b4b70-7754-4f74-afd9-3d538a046871.png)

Forcing a manual readback via the ETS updates the brightness value:
![image](https://user-images.githubusercontent.com/88311932/146509801-d4d3359a-2782-4a5a-9dc6-8b1123965d25.png)
![image](https://user-images.githubusercontent.com/88311932/146510170-f2322649-31e9-4d63-b9ee-0b57259da8d3.png)

## Expected Behavior
no "UNDEF" status. The value should be 0%

## Note:
The LEDs are still on with minimum brightness

## What could be the problem
The brightness is a byte value between 0..255
2% => 0x05
1% => 0x03
0% => 0x00

However, the Dali gateway allows also brightness values of 0x01 so 1/255*100% = 0.392156863%

## Workaround
Limit the minimum brightness value in the DALI gateway. However, the very low brightness is desired and you can clearly see a difference between 0x03 and 0x01 values.

**Comment by holgerfriedrich** [comment] 2021-12-18 10:38
Could you please retest 3.2 RC1? 
Between M5 and RC1 the Calimero library was upgraded from 2.4 to 2.5... just to confirm if it is still an issue.
Thanks.

**Comment by J-N-K** [comment] 2021-12-18 10:41
The issue is a faulty implementation of the incremental dimming in the binding, it's not a Calimero issue.

**Comment by holgerfriedrich** [comment] 2021-12-19 22:36
OpenHAB and Calimero seem to handle the brightness values properly, even if one used the numerical values between 0% and 1% (of course it is rounded to the integer value, which might not be intended for the described use case, but this does not cause the UNDEF value of the item.

The problem seems to be caused by the relative dimming. When a stop dimming ("break") command is received, the item value is cleared to UNDEF.

```[INFO ] [openhab.event.ItemStateChangedEvent  ] - Item '...' changed from ... to 10
[TRACE] [knx.internal.client.AbstractKNXClient] Received a Group Write telegram from '...' to '...' with value '[0]'
[DEBUG] [x.internal.handler.DeviceThingHandler] - onGroupWrite Thing '...' received a GroupValueWrite telegram from '...' for destination '...'
[TRACE] [x.internal.handler.DeviceThingHandler] - onGroupWrite Thing '...' processes a GroupValueWrite telegram for destination '...' for channel '...'
[TRACE] [ng.knx.internal.dpt.KNXCoreTypeMapper] - toType datapoint DPT = 3.007
[DEBUG] [ng.knx.internal.dpt.KNXCoreTypeMapper] - toType: KNX DPT_Control_Dimming: break received.
[INFO ] [openhab.event.ItemStateChangedEvent  ] - Item '...' changed from 10 to UNDEF
```
No change in brightness level was observed ("break" sent without starting a slow relative change before). My DALI GW did not send an update of status GA for dimming value. Manually triggering a group address read from ETS restored the previous value.
```[INFO ] [openhab.event.ItemStateChangedEvent  ] - Item '...' changed from UNDEF to 10```.

**Comment by smartheit** [comment] 2021-12-21 16:54
Do I need to res-test on 3.2 RC1 or is the problem isolated to the dimmer break command? When I use the knx dimmer with values > 1% the brightness is displayed correctly. So in this case the break command is not causing an "UNDEF" value.

**Comment by holgerfriedrich** [comment] 2021-12-21 17:03
@smartheit No retest necessary, this is independent of Calimero version.

**Comment by smartheit** [comment] 2022-01-01 11:48
Hi Holger,
it seems you are quite familiar with the KNX Binding. Would you be interested in the bountyscore approach for getting a donation?
Unfortunately my Java knowledge is limited and I cannot assist here much.
Cheers
Marco

**Comment by holgerfriedrich** [comment] 2023-05-23 19:42
This issue is likely to be fixed in the current implementation of the binding.
With #14504 the update to UNDEF should be gone.
I did a short test and cannot reproduce anymore.
Closing the issue, please reopen in case the problem occurs again (in current OH4.x milestone builds or later).

**Closed by holgerfriedrich** 2023-05-23 19:42 UTC
