### ISSUE TITLE
[evcc] 0.111.x: some values not recognized / incorrectly interpretet

### ISSUE THREAD

**Issue by prior-philip** [openhab/openhab-addons#14293] opened 2023-01-30 10:51 UTC
## Expected Behavior
following channels
- prioritySoc
read/write prioritySoc API key

- Vehicle Battery SoC
interpret value as kWh

- Active Phases
read active phases

## Current Behavior

- prioritySoc
Seems prioritysoc is not functioning as expected.
This channel value follows home battery Soc rather than prioritySoc. Changing value thru setpoint is not respected.
Manually setting thru curl API call works:
`curl -X POST http://localhost:7071/api/prioritysoc/50`
API response is successful
`{"result":50}`

- Vehicle Battery SoC
Vehicle Battery comes as kWh. This binding interprets it as Wh.
`/api/state` returns `“vehicleCapacity”:64`

- Active Phases
Channel (:loadpoint0#activePhases (Number)) always is 0
`/api/state` returns `“phasesActive”:3`
## Possible Solution

- **prioritySoc**: possibly this one?:  https://github.com/openhab/openhab-addons/blob/bf105008a1f6fc6f5730aa651159364b01b5768c/bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/EvccHandler.java#L351

## Steps to Reproduce (for Bugs)

1. configure evcc and add items to channels
2. review item values and compare with evcc API key values

## Context
- prioritySoc changes are not respected and gets reset to home battery Soc
- Vehicle Battery capacity is incorrectly displayed
- no phases information displayed and calculating min charging power therefore is not possible

## Your Environment

* Version used:  3.4.1
* Environment name and version: RaspberryPi 4B
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu Server 22.04

**Comment by jlaur** [comment] 2023-01-30 12:19
Duplicate of #14276.

**Comment by prior-philip** [comment] 2023-01-30 12:25
@jlaur 
Reported issues in this defect report are verified with latest marketplace binding release from @florian-h05.
Pls consider to reopen it.

**Comment by jlaur** [comment] 2023-01-30 12:32
Are you using evcc 0.111?

**Comment by prior-philip** [comment] 2023-01-30 12:50
yes
0.111.1

**Comment by florian-h05** [comment] 2023-01-30 16:46
I‘ve just checked the code:

- `prioritySoC`:
  - wrong getter is used in the EvccHandler as you linked above
  - unwritable from openHAB, but evcc seems to have introduced a few new write APIs: https://docs.evcc.io/docs/reference/api
- `vehicleSoC`: is in percent, not in kWh or Wh as you wrote above; binding is **correct**
- `vehicleCapacity`: is kWh, but binding uses Wh
- `activePhases`: was renamed in evcc, I need to adjust the DTO

Generally, I should consider adding write access to the new channels where possible.

My problem is, that I still can‘t use evcc at home and therefore have no real instance to test because my wallbox manufacturer is still working on the API (feels like they need eternity to publish the API although it is listed under „Coming Soon“).

**Comment by prior-philip** [comment] 2023-01-30 17:05
> * Vehicle Battery SoC
>   Vehicle Battery comes as kWh. This binding interprets it as Wh.
>   `/api/state` returns `“vehicleCapacity”:64`

> * `vehicleSoC`: is in percent, not in kWh or Wh as you wrote above; binding is **correct**

Sorry, typo on my end. I meant Vehicle Battery "capacity", **not** "Soc"

**Comment by florian-h05** [comment] 2023-01-30 17:07
👍
Is the unit for the home battery capacity in kWh as well? Binding uses Wh here as well.

**Comment by prior-philip** [comment] 2023-01-30 17:11
> 👍 Is the unit for the home battery capacity in kWh as well? Binding uses Wh here as well.

I couldnt find home battery capacity statement in evcc,yaml and related doc yet.

**Comment by florian-h05** [comment] 2023-01-30 17:29
Hmm, okay thanks. I would expect it to be kWh since the vehicle capacity is kWh as well, but evcc uses Wh as well: for charged and remaining charge energy.
Update: looking at the evcc souce code, it seems that home battery capacity is in kWh:

https://github.com/evcc-io/evcc/blob/ee12a544a80c0eb27933405d3f36d41ae9de5aa8/api/api.go#L78

**Comment by florian-h05** [comment] 2023-02-04 20:25
@prior-philip 
Can you please test my fixes?
You can download the JAR from https://we.tl/t-aWScbOYsR8. I have built it for openHAB 3.4.x.

**Comment by prior-philip** [comment] 2023-02-05 15:49
Hi @florian-h05 
Did some tests and got correct values for vehicle battery capacity, PrioritySOC and active phases.

One issue left: prioritySOC seems not to be written..
`evcc/site/prioritySoc
`

**Comment by florian-h05** [comment] 2023-02-05 16:06
> One issue left: prioritySOC seems not to be written..

This is currently not intended to be writable, see https://next.openhab.org/addons/bindings/evcc/#general-channels.

If I want to get the fixes from this upcoming PR included in 3.4.x releases, I have to limit my changes to fixes. Making this channel writable (which is a newer capability of the evcc API) is an enhancement and possibly disqualifies from 3.4.x releases.

**Comment by prior-philip** [comment] 2023-02-05 16:28
sure, will create EnhancementRequest
thanks for given fixes anyhow.

**Closed** 2023-02-10 22:55 UTC
