### ISSUE TITLE
[homekit] Lightning Group Support

### ISSUE THREAD

**Issue by grzegorz914** [openhab/openhab-addons#12531] opened 2022-03-27 06:43 UTC
Right now we can’t use Group to create Light Item like this:

```
Group         gLight  "Light"                    {homekit = "Lighting"}
Switch        light_state         (gLight)       {homekit = "Lighting.OnState"}
Dimmer        light_brightness    (gLight)       {homekit = "Lighting.Brightness"}
Color         light_color         (gLight)       {homekit = "Lighting.Hue"}
Dimmer        light_saturation    (gLight)       {homekit = "Lighting.Saturation"}
```
If try create in this way the HomeKit stop responding. 
Any plan to add this possibility?

Thanks

**Comment by yfre** [comment] 2022-03-29 08:11
@grzegorz914  this is actually already there, from day one. 
I just copy& pasted your configuration and it works. i got light in home app. 
it must be something else
![image](https://user-images.githubusercontent.com/11726616/160564874-c5438f2a-8ac3-45f2-b1d6-5d2b75d11844.png)

**Comment by grzegorz914** [comment] 2022-03-29 09:08
Very strange is start working but do not display as color light, however the slider change its color.

The UI config is:
<img width="804" alt="Zrzut ekranu 2022-03-29 o 11 03 12" src="https://user-images.githubusercontent.com/28867813/160576016-d5b560e4-55e2-4463-b183-3ae84bacf5ac.png">
<img width="801" alt="Zrzut ekranu 2022-03-29 o 11 03 39" src="https://user-images.githubusercontent.com/28867813/160576038-c4578c5d-e566-4af7-9aee-dbf41d383919.png">
![IMG_2128](https://user-images.githubusercontent.com/28867813/160576186-b3a2b7f1-85b2-4d7a-ab52-2d9dd688cc78.PNG)

In other thing we have no support for adaptive light characteristic, it will be nice to add it.

**Comment by yfre** [comment] 2022-03-29 09:16
for color light you need to add a mapping for the saturation. 

regarding adaptive light characteristic -  i have not found any technical documentation, so, it is unclear how to implement it.

**Comment by grzegorz914** [comment] 2022-03-29 09:33
God Tip, working like a harm.

Regarding AdaptiveLightControler here is from HAP-NodeJS, may be can be ported to OH.
https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/controller/AdaptiveLightingController.ts

**Comment by yfre** [comment] 2022-03-29 09:41
thanks, i will take a look on the HAP NodeJS implementation. 

closing this ticket as the issue is solved

**Closed by yfre** 2022-03-29 09:41 UTC
