### ISSUE TITLE
[hueemulation] hueemulation (openhab 2.5) not working in docker

### ISSUE THREAD

**Issue by marbon87** [openhab/openhab-addons#6662] opened 2019-12-22 19:59 UTC
Hi,

i am running openhab based on the official docker image on a raspi.
I use the hueemulation-service to integrate my openhab-items into alexa.
Until my update to openhab 2.5 everything was working fine, but after the update i cannot connect them together anymore.

I removed all devices that are configured by openhab in alexa and now i am trying to link them again, but the hueemulation-bridge is not found by my devices.
This is my config:

```
org.openhab.hueemulation:discoveryIps=192.168.4.200
org.openhab.hueemulation:temporarilyEmulateV1bridge=false
org.openhab.hueemulation:createNewUserOnEveryEndpoint=true
org.openhab.hueemulation:pairingEnabled=true
```

i also tried to set temporarilyEmulateV1bridge to true but that does not make any difference.

openhab is also avaiable on port 80, as adviced by the hueemulation documentation.
What wonders me is that /description.xml show the following URLBase:

```
<root>
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<URLBase>http://127.0.0.1:80/</URLBase>
```

Is that a problem? how can i change that?

And do i need to select Philips Hue V1 or V2 bridge in the alexa app, when i try to connect them?

**Comment by davidgraeff** [comment] 2019-12-23 14:45
hueemulation 2.5 is a V2 bridge but without https (if openhab doesn't run on https via reverse proxy).

hueemulation tries its best to not fail during startup. The given IP 192.168.4.200 didn't seem to work (given IPs are tested!) and it fall back to the localhost IP. This doesn't help Alexa to find the device on the network of course.

You might want to run the docker container with host network mode. i have no time to diagnose this but maybe someone else has.

**Comment by marbon87** [comment] 2019-12-23 19:51
I changed my complete subnet to 192.168.1.0/24 but have the same problem :/

**Comment by pwefels** [comment] 2019-12-24 10:13
I think the problem is similar to my post at the community forum. But not solved at the moment. https://community.openhab.org/t/solved-hueemulation-no-longer-able-to-pair-with-harmony-hub/80557/24

**Comment by pwefels** [comment] 2020-01-04 17:37
i dont use docker but have the same problem. any ideas? with 2.4 everything works as expected.

**Comment by SnapStef** [comment] 2020-01-04 19:50
Same here for 2.5 Release Build <URLBase> is localhost...with 2.4 on the same machine <URLBase> is the actual host adress. Windows 10 btw..

**Comment by SnapStef** [comment] 2020-01-04 21:39
> Same here for 2.5 Release Build URLBase is localhost...with 2.4 on the same machine URLBase is the actual host adress. Windows 10 btw..

I think I found the defect for my problem. In ConfigStore.java seems to be a problem. In case that disoceryIps have been configured the code defaults to `InetAddress.getLoopbackAddress();` I removed all configured discoveryIps (textual and via ui) and now it works for me

**Comment by pwefels** [comment] 2020-01-05 11:43
> > Same here for 2.5 Release Build URLBase is localhost...with 2.4 on the same machine URLBase is the actual host adress. Windows 10 btw..
> 
> I think I found the defect for my problem. In ConfigStore.java seems to be a problem. In case that disoceryIps have been configured the code defaults to `InetAddress.getLoopbackAddress();` I removed all configured discoveryIps (textual and via ui) and now it works for me

Thanks this workaround works for me too! But this should be fixed.

**Comment by davidgraeff** [comment] 2020-01-05 13:41
Could someone come up with a PR please? Happy to review the changes. 2.5.1 will be released mid Jan, maybe targeting it?

**Comment by marbon87** [comment] 2020-01-22 20:08
Hi @davidgraeff , i started a simple PR.
I am not sure why the binding allows to configure multiple discoveryIps, while the code can only use one. I didn't refactored that because i don't want to break the current configuration properties.
IMHO it only make sense to allow only one ip and fallback to loopback if non was configured.

**Comment by SnapStef** [comment] 2020-01-23 07:20
Hi, I think the fallback must be to use the first non loopback device in
case non ip was configured. Loopback should be used only as the last resort.


Mark Bonnekessel <notifications@github.com> schrieb am Mi. 22. Jan. 2020 um
21:08:

**Comment by marbon87** [comment] 2020-01-23 18:57
Ok, good point. I refactored the PR

**Closed** 2020-03-03 20:45 UTC
