### ISSUE TITLE
[hue emulation] Exception thrown when IPv6 is not available

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-addons#6452] opened 2019-11-25 21:48 UTC
Hue Emulation 2.5.0M5 throws the following exception when IPv6 is disabled on the OS Level.
```
karaf[16749]: Exception in thread "HueEmulation UPNP Server" java.lang.UnsupportedOperationException: IPv6 not available
karaf[16749]: #011at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:134)
karaf[16749]: #011at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:46)
karaf[16749]: #011at java.nio.channels.DatagramChannel.open(DatagramChannel.java:182)
karaf[16749]: #011at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:417)
karaf[16749]: #011at org.openhab.io.hueemulation.internal.upnp.UpnpServer.accept(UpnpServer.java:1)
karaf[16749]: #011at org.openhab.io.hueemulation.internal.upnp.HueEmulationConfigWithRuntime.run(HueEmulationConfigWithRuntime.java:111)
```

I would expect that this exception is caught or that there is an additional check before to see if IPv6 is available or not.

**Comment by davidgraeff** [comment] 2019-11-29 23:14
Duplicate of #6403

**Closed** 2019-11-29 23:15 UTC
