### ISSUE TITLE
[homekit] No response from accessories after restart of openHAB

### ISSUE THREAD

**Issue by NicBuh** [openhab/openhab-addons#12911] opened 2022-06-09 09:42 UTC
After restarting my RaspberryPi I am unable to control my accessories in homekit.
I have now upgraded to 3.3.0 M6, but to no avail.
Interestingly, I am able to add the openHAB bridge to a second iPhone and control the lights from there, which suggests the configuration itself is fine (after all I also didn't change it, but only restarted).

The issue instead seems to be related to some authentication issue as is also described by the logs:

```
11:35:35.559 [INFO ] [.netty.handler.logging.LoggingHandler] - [id: 0x085c3325, L:/192.168.0.59:9124] READ: [id: 0x1b717c61, L:/192.168.0.59:9124 - R:/192.168.0.2:50488]
11:35:35.632 [INFO ] [.netty.handler.logging.LoggingHandler] - [id: 0x085c3325, L:/192.168.0.59:9124] READ COMPLETE
11:35:35.637 [TRACE] [.server.impl.http.impl.LoggingHandler] - READ PooledUnsafeDirectByteBuf(ridx: 0, widx: 158, cap: 2048) [/192.168.0.2:50488]:
504F5354202F706169722D76657269667920485454502F312E310D0A486F73743A206F70656E4841422E5F6861702E5F7463702E6C6F63616C0D0A436F6E74656E742D4C656E6774683A2033370D0A436F6E74656E742D547970653A206170706C69636174696F6E2F70616972696E672B746C76380D0A0D0A06010103208770667E0794D6CFC0C4DD68AB5C1084BFE6C4F933331FB41322D3977613034E

11:35:35.635 [TRACE] [erver.impl.http.impl.AccessoryHandler] - New HomeKit connection from /192.168.0.2:50488
11:35:35.649 [TRACE] [.impl.pairing.PairVerificationManager] - Starting pair verification for openHAB
11:35:35.677 [TRACE] [ver.impl.http.HomekitClientConnection] - 200 /pair-verify
11:35:35.685 [TRACE] [.server.impl.http.impl.LoggingHandler] - WRITE PooledUnsafeDirectByteBuf(ridx: 0, widx: 243, cap: 256) [/192.168.0.2:50488]:
485454502F312E3120323030204F4B0D0A436F6E74656E742D747970653A206170706C69636174696F6E2F70616972696E672B746C76380D0A636F6E74656E742D6C656E6774683A203133390D0A636F6E6E656374696F6E3A206B6565702D616C6976650D0A0D0A0601020564654CA1341C78734BB43EAEA254D2EA0A6A59914DA62F072D09320C3D3449270A874EC7D11FD705A2CD498AFBEA198FBC1FB84EF797A0BF8D0DFA8C11B022E9FB4C8D53876A4CEEDCD49ABC476E7BBA3C012F741B9AB949C3961693422F7CDE3913A4651D03205F007ED84B92532D7F0D09AD8189C0ED790C7E116742DC9E0B89C96189FBBA78

11:35:35.743 [TRACE] [.server.impl.http.impl.LoggingHandler] - READ PooledUnsafeDirectByteBuf(ridx: 0, widx: 247, cap: 2048) [/192.168.0.2:50488]:
504F5354202F706169722D76657269667920485454502F312E310D0A486F73743A206F70656E4841422E5F6861702E5F7463702E6C6F63616C0D0A436F6E74656E742D4C656E6774683A203132350D0A436F6E74656E742D547970653A206170706C69636174696F6E2F70616972696E672B746C76380D0A0D0A0578470B4374C8C71812A893B46ABBFF312F4C8355263A1E49A9D42A3DC0B4EC37AC5635055DB78476066C1BB83191A7B4B39367CB03B758726135A99588AF9F20D084D4B0F3CC789CE8A973B58B400E25444542D6F641DDD78F66E6E06BCF7A51A49C1A585DF4D6C60D63D7A2CF7CECB356EE76F4EDBDFF10A0060103

11:35:35.753 [WARN ] [a.server.impl.connections.HttpSession] - Exception encountered while verifying pairing
java.lang.Exception: Unknown user: 5D98DB40-B79F-47CF-BA48-4BD999FEDE1B
        at io.github.hapjava.server.impl.pairing.PairVerificationManager.stage2(PairVerificationManager.java:113) ~[bundleFile:?]
        at io.github.hapjava.server.impl.pairing.PairVerificationManager.handle(PairVerificationManager.java:51) ~[bundleFile:?]
        at io.github.hapjava.server.impl.connections.HttpSession.handlePairVerify(HttpSession.java:127) [bundleFile:?]
        at io.github.hapjava.server.impl.connections.HttpSession.handleRequest(HttpSession.java:56) [bundleFile:?]
        at io.github.hapjava.server.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:56) [bundleFile:?]
        at io.github.hapjava.server.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:49) [bundleFile:?]
        at io.github.hapjava.server.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) [bundleFile:?]
        at io.github.hapjava.server.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) [bundleFile:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [bundleFile:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [bundleFile:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) [bundleFile:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370) [bundleFile:4.1.72.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [bundleFile:4.1.72.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [bundleFile:4.1.72.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [bundleFile:4.1.72.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [bundleFile:4.1.72.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
11:35:35.770 [TRACE] [ver.impl.http.HomekitClientConnection] - 500 /pair-verify
11:35:35.778 [TRACE] [.server.impl.http.impl.LoggingHandler] - WRITE PooledUnsafeDirectByteBuf(ridx: 0, widx: 101, cap: 232) [/192.168.0.2:50488]:
485454502F312E312035303020496E7465726E616C20536572766572204572726F720D0A636F6E74656E742D6C656E6774683A2031390D0A636F6E6E656374696F6E3A206B6565702D616C6976650D0A0D0A6A6176612E6C616E672E457863657074696F6E

11:35:35.794 [TRACE] [erver.impl.http.impl.AccessoryHandler] - Terminated HomeKit connection from /192.168.0.2:50488

```

**Comment by yfre** [comment] 2022-06-18 18:06
@NicBuh  for some reason your openhab got unpaired from your device. 
this could have multiple reasons 
- there were some bugs in < OH3.2
- you have executed clearPairing from karaf
- you have deleted bridge from home app
- OH config file (homekit.json) got corrupted 
- ... some else

this is also the reason for the another device be able to pair. normally you cannot pair different icloud accounts to the same homekit bridge. 

so, in order to understand whether it is a bug or something else i would need to more information like
- in which OH version it happend
- have you executed clearPairing
- have you change anything
- do you have any exceptions in the log files a day before restart?

**Comment by NicBuh** [comment] 2022-06-20 12:19
Hi @yfre,

I was running 3.2 before the upgrade. All I did to trigger the issue was a restart of the raspberrypi. At this point I have already updated and don't have the old logs anymore. I have re-setup my homekit and it works fine for now. In case the issue reoccurs, I will share more info in this thread.

**Comment by yfre** [comment] 2022-11-14 16:18
Hi @NicBuh 
please close this ticket if the issue is solved

**Closed** 2022-11-14 21:40 UTC
Labels: awaiting feedback
