### ISSUE TITLE
[evcc] Loadpoint Target SoC not set on evcc 0.112.5 

### ISSUE THREAD

**Issue by kad49007** [openhab/openhab-addons#14388] opened 2023-02-12 12:21 UTC
Loadpoint Target SoC not set from openhab on evcc 0.112.5

## Expected Behavior
Loadpoint TargetSoC should be set from Openhab
## Current Behavior
Loadpoint TargetSoc won't be set

## Possible Solution
Adopt latest API changes of evcc (see:  https://docs.evcc.io/docs/reference/api )
Looks like changes have to be made here
[Code](https://github.com/openhab/openhab-addons/blob/bf105008a1f6fc6f5730aa651159364b01b5768c/bundles/org.openhab.binding.evcc/src/main/java/org/openhab/binding/evcc/internal/api/EvccAPI.java#L97)

Also setTargetCharge looks to be outdated (didn't test it).

## Steps to Reproduce (for Bugs)
1. Connect evcc to openhab
2. Link targetSoc Items to appropriate channel
3. Set Loadpoint targe soc

## Context
Try to set Loadpoint targetSoc from Openhab. Try to reduce the point of interaction

## Your Environment
openHAB 3.4.1
Raspberry Pi 4 Modell B
5.4.1                  │ org.openhab.binding.evcc (latest patch from #14293  )

PS: Sorry, I'm not used to work in Github, my developer career ended 20 years ago...

**Comment by int5749** [comment] 2023-02-12 16:39
I trust evcc binding needs to be adopted to newly changes on several evcc "handles" like
- lodpoint string at 1 instead of 0
- etc

**Comment by kad49007** [comment] 2023-02-12 22:17
Just tested the index numbering of the loadpoints. Loadpoint 0 (as reported by /api/state) has to be configured with  POST http://x.xx.xx.xx:7070/api/loadpoints/1/target/soc/80 . 
Looks like the changes have not been consistent.

**Comment by florian-h05** [comment] 2023-02-14 15:42
Problem with „inconsistent“ loadpoint ids is, that /api/state returns an array of loadpoints, therefore the index starts at 0 and this behaviour cannot be changed.
If I were one of the evcc devs, I‘d rather have changed all APIs to have 0 as first index for loadpoints (means MQTT API change, no REST API change).

**The very latest version of the addon (as included in openHAB 3.4.2) is fully compatible with evcc 0.111.x.
But 0.112.x brought more breaking changes.**

I will close this issue as it is duplicate of #14348 and this issue is much more detailed. Please search for existing issues before opening a new one. Thanks.

**Closed by florian-h05** 2023-02-14 15:42 UTC
Labels: bug
