### ISSUE TITLE
[amazonechocontrol] Exception when getting playlists

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-addons#4912] opened 2019-02-17 06:51 UTC
Hi All

When starting up I get this large error:

````
07:35:12.204 [WARN ] [amazonechocontrol.internal.Connection] - Parsing json failed {}
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 8 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.Connection.parseJson(Connection.java:810) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.Connection.getPlaylists(Connection.java:897) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.refreshData(AccountHandler.java:472) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.checkData(AccountHandler.java:376) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.setConnection(AccountHandler.java:336) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.checkLogin(AccountHandler.java:293) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 8 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[?:?]
        ... 17 more
````

Has anyone seen this?

My Echo items for reference:

````
Group gAllEchoDots "All Alexa Echo Dots"
Group gAllEchoAlerts "Alerts to all Echo Dots"

// Player control
Player Echo_LivingRoom_Player                "Player"                                (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:player"}
Dimmer Echo_LivingRoom_Volume                "Volume [%.0f %%]" <soundvolume>        (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:volume"}
// Switch Echo_LivingRoom_Shuffle               "Shuffle"                            (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:shuffle"}

// Commands
String Echo_LivingRoom_TTS                   "Text to Speech"                        (gAllEchoAlerts) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:textToSpeech"}
String Echo_LivingRoom_LastVoiceCommand      "Last Voice Command"                    (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:lastVoiceCommand"}
String Echo_LivingRoom_Remind                "Remind"                                (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:remind"}
// String Echo_LivingRoom_PlayAlarmSound        "Play Alarm Sound"                   (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:playAlarmSound"}
// String Echo_LivingRoom_StartRoutine          "Start Routine"                      (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:startRoutine"}

// Flashbriefings
// Switch FlashBriefing_Technical_Save   "Save (Write only)"                                        { channel="amazonechocontrol:flashbriefingprofile:account1:flashbriefing1:save"}
// Switch FlashBriefing_Technical_Active "Active"                                                   { channel="amazonechocontrol:flashbriefingprofile:account1:flashbriefing1:active"}
// String FlashBriefing_Technical_Play   "Play (Write only)"                                        { channel="amazonechocontrol:flashbriefingprofile:account1:flashbriefing1:playOnDevice"}

// Player control
Player Echo_Garage_Player                "Player"                                (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:player"}
Dimmer Echo_Garage_Volume                "Volume [%.0f %%]" <soundvolume>        (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:volume"}
// Switch Echo_Garage_Shuffle               "Shuffle"                            (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:shuffle"}

// Commands
String Echo_Garage_TTS                   "Text to Speech"                        (gAllEchoAlerts) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:textToSpeech"}
String Echo_Garage_LastVoiceCommand      "Last Voice Command"                    (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:lastVoiceCommand"}
String Echo_Garage_Remind                "Remind"                                (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:remind"}
// String Echo_Garage_PlayAlarmSound        "Play Alarm Sound"                   (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:playAlarmSound"}
// String Echo_Garage_StartRoutine          "Start Routine"                      (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0U50783XXX:startRoutine"}

// Player control
Player Echo_MusicRoom_Player                "Player"                                (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:player"}
Dimmer Echo_MusicRoom_Volume                "Volume [%.0f %%]" <soundvolume>        (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:volume"}
// Switch Echo_MusicRoom_Shuffle               "Shuffle"                            (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:shuffle"}

// Commands
String Echo_MusicRoom_TTS                   "Text to Speech"                        (gAllEchoAlerts) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:textToSpeech"}
String Echo_MusicRoom_LastVoiceCommand      "Last Voice Command"                    (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:lastVoiceCommand"}
String Echo_MusicRoom_Remind                "Remind"                                (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:remind"}
// String Echo_MusicRoom_PlayAlarmSound        "Play Alarm Sound"                   (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:playAlarmSound"}
// String Echo_MusicRoom_StartRoutine          "Start Routine"                      (gAllEchoDots) {channel="amazonechocontrol:echo:31dd55b2:XXX0VC0683XXX:startRoutine"}
````

Any help would be great!

**Comment by 9037568** [comment] 2019-02-17 07:10
You need to attach a debug log that shows the rest of the error.

**Comment by edwolfe3** [comment] 2019-06-15 10:13
I'm having a problem with it too. Any solution yet?

```
2019-06-09 19:15:36.185 [WARN ] [mazonechocontrol.internal.Connection] - Request to url 'https://alexa.amazon.com/api/cloudplayer/playlists?deviceSerialNumber=G090LF117
4770CD5&deviceType=A3S5BH2HU6VAYF&mediaOwnerCustomerId=A38APXBDKA3JLQ' fails with unkown error
java.net.UnknownHostException: alexa.amazon.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:?]
        at java.net.Socket.connect(Socket.java:589) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666) ~[?:?]
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1159) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1043) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1041) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1040) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1567) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:93) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1487) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1485) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1484) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.Connection.makeRequest(Connection.java:572) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.Connection.makeRequestAndReturnString(Connection.java:485) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.Connection.makeRequestAndReturnString(Connection.java:480) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.Connection.getPlaylists(Connection.java:954) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.refreshData(AccountHandler.java:476) ~[?:?]
        at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.checkData(AccountHandler.java:380) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]

```

**Comment by mgeramb** [comment] 2019-07-14 21:30
This log is a different one, it seem your DNS does not work on your installation, because you get unknown host error for "alexa.amazon.com"

**Comment by edwolfe3** [comment] 2019-07-15 11:30
It does work; I can ping it from the machine.




Get Outlook for Android







On Sun, Jul 14, 2019 at 5:30 PM -0400, "Michael Geramb" <notifications@github.com> wrote:












This log is a different one, it seem your DNS does not work on your installation, because you get unknown host error for "alexa.amazon.com"

**Comment by DenBir** [comment] 2020-09-29 20:18
I use openHab 2.5.9 with the addon Amazon Echo Control Binding 2.5.9 and have the same issue.

2020-09-29 22:07:29.399 [WARN ] [mazonechocontrol.internal.Connection] - Illegal json: {"playlists":{"Louis":[{"entryList":null,"playlistId":"66643657-9629-4d16-82d0-4197c207206f","title":"Louis","trackCount":1,"version":"2"}],"Meine Favoriten":[{"entryList":null,"playlistId":"87df2826ae334f3ea69126bfa3bedcde","title":"Meine Favoriten","trackCount":0,"version":"1:447970446"}],"Nicole":[{"entryList":null,"playlistId":"c7436a44-c3ff-4dbb-93f7-c4d868064341","title":"Nicole","trackCount":0,"version":"1"}]}}

2020-09-29 22:07:29.832 [WARN ] [mazonechocontrol.internal.Connection] - Parsing json failed

com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "1:447970446"

	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]

	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[?:?]

	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[?:?]

	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[?:?]

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]

	at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]

	at org.openhab.binding.amazonechocontrol.internal.Connection.parseJson(Connection.java:966) ~[?:?]

	at org.openhab.binding.amazonechocontrol.internal.Connection.getPlaylists(Connection.java:1131) ~[?:?]

	at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.refreshData(AccountHandler.java:552) ~[?:?]

	at org.openhab.binding.amazonechocontrol.internal.handler.AccountHandler.checkData(AccountHandler.java:458) ~[?:?]

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_262]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_262]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_262]

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_262]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

Caused by: java.lang.NumberFormatException: For input string: "1:447970446"

	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_262]

	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_262]

	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_262]

	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1201) ~[?:?]

	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225) ~[?:?]

	... 25 more

**Comment by 9037568** [comment] 2020-12-30 05:38
Closing this because we've now had 3 different errors posted in here, 2 of which don't appear to be bugs at all.
If there's a reproducible error, someone can open a new ticket.

**Closed by 9037568** 2020-12-30 05:38 UTC
Labels: awaiting feedback
