### ISSUE TITLE
[tacmi] Error parsing API Scheme: Non-terminating decimal expansion; no exact representable decimal result

### ISSUE THREAD

**Issue by roednix** [openhab/openhab-addons#12445] opened 2022-03-08 10:47 UTC
## Error:
I am receiving the following error when parsing my Schema API page, if:
 * the parameter being parsed has a unit of "l/h" from the CMI   -- and --
 * the value is !=0
The value causing the error and all subsequent values are not updated

## Item Definition
The item definition is as follows:
    Number:VolumetricFlowRate D_V_ST "Solarthermie durchfluss" {channel="tacmi:cmiSchema:ratiotherm:dV_ST"}
I also tried:
    Number:Volume D_V_ST "Solarthermie durchfluss" {channel="tacmi:cmiSchema:ratiotherm:dV_ST"}
        --and--
    Number D_V_ST "Solarthermie durchfluss" {channel="tacmi:cmiSchema:ratiotherm:dV_ST"}
without change of behaviour

## Trace
Trace is the following (with one working parameter showing before the actual error):
```
2022-03-08 08:54:23.067 [TRACE] [.tacmi.internal.schema.ApiPageParser] - Found parameter pos25:78:8 [READ_ONLY] : temp_ST_RL "Solarthermie Ruecklauf" = 24.9 °C
2022-03-08 08:54:23.070 [TRACE] [.tacmi.internal.schema.ApiPageParser] - Found parameter pos26:81:8 [READ_ONLY] : dV_ST "Solarthermie Durchfluss" = 466 l/h
2022-03-08 08:54:23.071 [DEBUG] [i.internal.schema.TACmiSchemaHandler] - Error parsing API Scheme: Non-terminating decimal expansion; no exact representable decima
l result.
org.attoparser.ParseException: Non-terminating decimal expansion; no exact representable decimal result.
        at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393) ~[?:?]
        at org.attoparser.MarkupParser.parse(MarkupParser.java:257) ~[?:?]
        at org.attoparser.MarkupParser.parse(MarkupParser.java:175) ~[?:?]
        at org.attoparser.simple.SimpleMarkupParser.parse(SimpleMarkupParser.java:132) ~[?:?]
        at org.openhab.binding.tacmi.internal.schema.TACmiSchemaHandler.parsePage(TACmiSchemaHandler.java:160) ~[?:?]
        at org.openhab.binding.tacmi.internal.schema.TACmiSchemaHandler.refreshData(TACmiSchemaHandler.java:170) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
        at java.math.BigDecimal.divide(BigDecimal.java:1722) ~[?:?]
        at org.openhab.binding.tacmi.internal.schema.ApiPageParser.getApiPageEntry(ApiPageParser.java:388) ~[?:?]
        at org.openhab.binding.tacmi.internal.schema.ApiPageParser.handleCloseElement(ApiPageParser.java:210) ~[?:?]
        at org.attoparser.simple.SimplifierMarkupHandler.handleCloseElementEnd(SimplifierMarkupHandler.java:341) ~[?:?]
        at org.attoparser.MarkupEventProcessorHandler.handleCloseElementEnd(MarkupEventProcessorHandler.java:473) ~[?:?]
        at org.attoparser.ParsingElementMarkupUtil.parseCloseElement(ParsingElementMarkupUtil.java:201) ~[?:?]
        at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:725) ~[?:?]
        at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301) ~[?:?]
        ... 11 more
```
## Environment
- Openhab 3.2 release with corresponding TACMI binding on Debian Buster
- openjdk 11.0.13 2021-10-19 LTS

Thanks a lot for your support here
@marvkis, would be amazing if you could take a look, happy to help with further debugging or testing in my setup.

thanks and best regards,
/Michael

**Comment by lsiepel** [comment] 2024-07-23 08:13
Older issue, but does not seem to have been fixed. Can you confirm you still have this issue?

The issue is probably not related to the Item decleration, but rather a response from the API that does not mee the expected schema. If you put the binding into trace level, the response will be logged. If you can provide me that log, i can try to fix the issue.

**Comment by lsiepel** [comment] 2024-10-02 20:30
> I am running OH 4.2.2.1 (since today). IT´s not a DateTime problem but a problem with integer value (i.e. 480 l/h) instead of 480.0 l/h).
> 
> Also, Channeltype "%" seems missing.

If you put the logging into trace mode and reproduce this issue. I hope it logs the response data so we can use that for creating a unit test. Would you be able to provide such a log?

**Comment by marvkis** [comment] 2024-10-03 06:45
@holana: This PR should fix the integer parsing problem (Non-terminating decimal expansion).
It also updates the channel with the correct UoM (Unit of Measurment) type (VolumetricFlowRate). You will also need to update the Items linked with the channel to have the correct UoM in order to see the value correctly. Also note that TA uses l/h (litres per hour), Openhab uses l/m (litres per minute), so you won't see exactly the same value!

The DateTime thing is a different thing fixed with this PR not related to this issue. (To allow editing of items used by a time schedule)

**Comment by marvkis** [comment] 2024-10-03 12:17
Hi @holana ,

can you PM me directly? Use the sign-off address from the commit: https://github.com/openhab/openhab-addons/pull/17481/commits/3488620e295d8a62575effb2a0f5d295013dae2c

I've prepared a new version. It would be great if you could test it before I push it upstream.

Bye,
     Chris

**Comment by marvkis** [comment] 2024-10-03 16:56
Hi @holana,

PM is a common term and means 'private / personal message' depending on the context 😉 .  Since there are no private messages on github - I was referring to a commit message where my email address can be found so you can contact me directly ;)
That way we can test and troubleshoot things without spamming everyone here.

Cheers,
    Chris

**Closed** 2024-10-05 12:56 UTC

**Comment by marvkis** [comment] 2024-10-13 15:01
Hi @lsiepel ,

I have extended the binding to use a more universal mapping between TA and OpenHAB units (see PR #17556). You can get it here: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.tacmi/4.3.0-SNAPSHOT/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar

Would you be so kind and test it in your environment?
This version should handle your missing UoM's ("W", "°" (electrical phase shift cos phi), "bar" (pressure), "m3" (cbm), "W/m2",) correctly. Note: The channel will now change it's dimension according to the unit it has. The linked items must also be updated to the same dimension, otherwise OH won't update the value of the item correctly ;)

You can send your results and feedback directly to the PR #17556

Thanks & Bye,
      Chris

**Comment by lsiepel** [comment] 2024-10-13 16:08
> Hi @lsiepel ,
> 
> I have extended the binding to use a more universal mapping between TA and OpenHAB units (see PR #17556). You can get it here: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.tacmi/4.3.0-SNAPSHOT/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar
> 
> Would you be so kind and test it in your environment? This version should handle your missing UoM's ("W", "°" (electrical phase shift cos phi), "bar" (pressure), "m3" (cbm), "W/m2",) correctly. Note: The channel will now change it's dimension according to the unit it has. The linked items must also be updated to the same dimension, otherwise OH won't update the value of the item correctly ;)
> 
> You can send your results and feedback directly to the PR #17556
> 
> Thanks & Bye, Chris

I don’t have this device, maybe @holana can give  any assistence

**Comment by marvkis** [comment] 2024-10-13 16:17
Hi,

you can change values via OH that is editable on the schema page. I.e. you can use a fixed value input ('Fixwert') or set the input value directly.
I have quite a similar use case: The temperature is provided via a `fixed value` input.
<img width="965" alt="Bildschirmfoto 2024-10-13 um 18 06 31" src="https://github.com/user-attachments/assets/ff5d2762-198f-4330-8cf2-ac134a35dfd2">

This fixed value is made accessible via the TA-Designer:
<img width="677" alt="Bildschirmfoto 2024-10-13 um 18 11 17" src="https://github.com/user-attachments/assets/90cbdf0f-a16c-4a9e-891a-6f1d5708df46">

Then in OpenHAB link the Item where Homematic updates the Temperature to this channel in 'Follow' profile mode:
<img width="785" alt="grafik" src="https://github.com/user-attachments/assets/7c2d9bc0-17f6-4dbd-8aaa-832828c809ff">

This way it works for me ;)

**Comment by marvkis** [comment] 2024-10-13 16:21
> > Hi @lsiepel ,
> > I have extended the binding to use a more universal mapping between TA and OpenHAB units (see PR #17556). You can get it here: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.tacmi/4.3.0-SNAPSHOT/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar
> > Would you be so kind and test it in your environment? This version should handle your missing UoM's ("W", "°" (electrical phase shift cos phi), "bar" (pressure), "m3" (cbm), "W/m2",) correctly. Note: The channel will now change it's dimension according to the unit it has. The linked items must also be updated to the same dimension, otherwise OH won't update the value of the item correctly ;)
> > You can send your results and feedback directly to the PR #17556
> > Thanks & Bye, Chris
> 
> I don’t have this device, maybe @holana can give any assistence

In fact, I intended to address this to @holana - Sorry for the confusion.

@holana would you be so kind and test the new version?

**Comment by marvkis** [comment] 2024-10-13 16:25
> Hi Chris,
> 
> is there a way to change values in TA Schema Page from OH? I need to transfer a Room-Temperature form Homatic via OH to TA.
> 
> thx Reihold

@holana for questions like this https://community.openhab.org is a better place ;)

**Comment by marvkis** [comment] 2024-10-14 17:36
Hi @holana, thanks for all your effort! I'll have a closer look on it later!

**Comment by marvkis** [comment] 2024-10-14 20:01
HI @holana ,

Okay, I have found something. It seems the values are marked as 'editable', but the `changeto` field is missing.
This is what TA I have found in your logs for one of the failing voltage values:
```
<input type="hidden" value="03000940D10000" name="changeadrx2" id="changeadr">
```

When I add a fixed-value voltage field, I get something looking like this:
```
<input type="hidden" value="0400044414D10D" name="changeadrx2" id="changeadr">
0.00 - 300.00V<br><input type="number" name="changetox2" min="0.00" max="300.00" value="10.52" id="changeto" class="schanger" step="0.01">
```

Can you give me more details where this value is from? Is it something like an output from a function? It would be great to get enough details so I could reproduce it in my setup.

**Comment by marvkis** [comment] 2024-10-14 21:37
HI @holana ,

Okay, I have found something. It seems the values are marked as 'editable', but the `changeto` field is missing.
This is what TA I have found in your logs for one of the failing voltage values:
```
<input type="hidden" value="03000940D10000" name="changeadrx2" id="changeadr">
```

When I add a fixed-value voltage field, I get something looking like this:
```
<input type="hidden" value="0400044414D10D" name="changeadrx2" id="changeadr">
0.00 - 300.00V<br><input type="number" name="changetox2" min="0.00" max="300.00" value="10.52" id="changeto" class="schanger" step="0.01">
```

Can you give me more details where this value is from? Is it something like an output from a function? It would be great to get enough details so I could reproduce it in my setup. 

I have just pushed a new version with a few changes to handle the missing data. Maybe you could try the new version: https://openhab.jfrog.io/artifactory/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.tacmi/4.3.0-SNAPSHOT/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar

Thanks,
    Chris

**Comment by marvkis** [comment] 2024-10-15 11:10
Hi @holana ,

it would be great if you could test the new version. Yesterday I included a first fix that should handle the situation with the PID outputs and switch them to ReadOnly values.

Regarding the mariadb duplicates: Does this happen for all values or just some? If it is something generic, it should happen for all values. Also the time difference is very short - only one ms. That would speak against a separate process - the time lag would be greater here. Have you checked OH's `events.log` to see if you are also seeing multiple updates for the same value?

bye,
    chris

**Comment by marvkis** [comment] 2024-10-15 12:38
Hi Reinhold,

it seems that the jar was overwritten (by the build system?) with an older version last night. I've uploaded my current jar to https://github.com/marvkis/marvkis.github.io/blob/main/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar - Can you test it with my version? Sorry for the inconvenience.

Bye,
    chris

**Comment by marvkis** [comment] 2024-10-15 21:43
Hi Reinhold,

Regarding the `DateTime` issue: I've updated the plugin at https://github.com/marvkis/marvkis.github.io/blob/main/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar - it should now show up as Numeric.

Regarding the double entry issue:
At the moment we only know that two values arrive in the database. But we need to find out where the duplication is happening. To do this, I suggest:
- Enable debugging logging for the tacmi binding
- When the next duplicate insert occurs, find the corresponding log entries from the binding debugging log and from the events.log

If there is only one update in the tacmi log and event.log, we know the duplication is happening later. 

On the other hand: There are specialised time series databases for this use case, e.g. InflxuDB. I also started initially with a relational database, but it could only handle ~2 years of data. Then the tables got so big that the DB could not keep up with inserting new values in time. Now I'm using InfluxDB and have 10 years of data in it - and inserting and querying still works like a charm. And with these databases, it's no problem if we get multiple inserts for the same time. Or if the data doesn't arrive at the expected rate - sometimes the C.M.I. (or CAN bus?) seems to be busy and we don't get values in time, so we get quite a lot of jitter in polling over time. (just my thoughts on this).

However, if there is a problem in the tacmi binding that is causing the duplication, we should fix it. But at the moment I have no idea where this might be happening.

Bye,
    chris

**Comment by marvkis** [comment] 2024-10-16 20:43
Hi Reinhold,

I've also done a bit of searching on the forums, but haven't found anything similar. But there seems to be quite a lot of wired things happening with sql persistence. But most people are complaining about missing data, not duplicate data ;)
Quite a few discussions have also ended up with switching to influx...

I found one thing that mighta be a pointer into the right direction:
> Changing the persistence strategy from everyUpdate to everyCommand solved the issue for me. 

Maybe you could even try a update strategy with a fixed rate, ala ` every5min : "0 */5 * * * ?"` without `everyUpdate` ?

Regarding the addon / PR: I will try to find a solution to resolve the unit without accessing `tech.units.indriya.format.SimpleUnitFormat` - it seems the maintainer won't accept it that way. It would be great if you could test the final version and confirm that it works as expected.

Bye,
    chris

**Comment by marvkis** [comment] 2024-10-17 20:19
Hi Reinhold ,

Good to hear that you made progress on the persistence issue ;)

I solved the `tech.units.indriya.format` import issue and updated the PR. The (hopefully final) build is available (as usual) at https://github.com/marvkis/marvkis.github.io/blob/main/org.openhab.binding.tacmi-4.3.0-SNAPSHOT.jar

When you are done testing, could you leave a comment directly on https://github.com/openhab/openhab-addons/pull/17556 so that the OpenHAB team has it directly on the PR?

Thanks & Cheers,
Chris
