### ISSUE TITLE
[unifi] Add support for Dream Machine Pro

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#8388] opened 2020-09-03 15:02 UTC
<a alt="bounty" href="https://www.bountysource.com/issues/92746043-unifi-add-support-for-dream-machine-pro"><img src="https://api.bountysource.com/badge/issue?issue_id=92746043"></a>

As far as i know currently the unifi Binding doesn't support the dream machine pro.

I got an 404 if i configure the unifi binding on my openhab installation. @ericsante on the openhab community forum experienced the same behaviour (https://community.openhab.org/t/ubiquiti-unifi-binding-feature-discussion/14520/1072?u=regnets).

**Comment by regnets** [comment] 2020-09-03 15:05
I created a small bounty for this feature request:
https://www.bountysource.com/issues/92746043-unifi-add-support-for-dream-machine-pro

**Comment by cweitkamp** [comment] 2020-09-03 17:04
@regnets Thanks for posting a bounty on this issue :+1:.

**Comment by martinvw** [comment] 2020-09-03 18:08
@mgbowman FYI

**Comment by martinvw** [comment] 2020-09-03 18:10
@regnets could you elaborate on the issue, could you show/share the logs such that it might be easier to fix/reproduce without access to a UDM Pro

**Comment by HoLiuS85** [comment] 2020-09-09 08:40
@martinvw I do have the same Issue as described in this thread. I guess part of the problem is that interface are published via different ports that previously (now port 80, before 8443)...if that is all, I do not know. I tried configuring port 80, but it did not work.

I set the log level for the Unifi binding to `log:set TRACE org.openhab.binding.unifi` and restarted it, the following are the only entries I see:

`2020-09-09 10:31:17.918 [DEBUG] [.handler.UniFiControllerThingHandler] - Initializing the UniFi Controller Handler with config = UniFiControllerConfig{host = 192.168.1.1, port = 80, username = openhab, password = *****, refresh = 10}`
`2020-09-09 10:31:17.919 [TRACE] [nal.api.model.UniFiControllerRequest] - >> POST https://192.168.1.1:80/api/login`

If I can provide any further infromation to help fix this issue, let me know.

**Comment by martinvw** [comment] 2020-09-09 08:58
That seems like the main problem is that port 80 is most likely not https, does it not have an https available? Maybe on port 443, which is the default. Could you validate this?

So the fact that the unifi binding expects https could be the only problem.

**Comment by martinvw** [comment] 2020-09-09 09:05
@HoLiuS85 I replaced the hardcoded https by HTTP (still hardcoded) as a test, could you try:

https://download.martinvw.nl/org.openhab.binding.unifi-2.5.9-SNAPSHOT.jar

**Comment by HoLiuS85** [comment] 2020-09-09 09:29
@martinvw Thanks for looking into it. Actually configuring port 443 in the old binding or using port 80 on the snapshot you provided, results in the same `com.google.gson.stream.MalformedJsonException` error. 

I have attached a log extract with all traces for the Unifi binding here: [openhab_unifi.log](https://github.com/openhab/openhab-addons/files/5194077/openhab_unifi.log)

**Comment by paulianttila** [comment] 2020-09-09 18:16
Dream Machine Pro is based on new Unifi OS, which seems to have more differences than just port (mostly URL related changes).

There are couple of python implementations which already support DMP.

E.g. This commit seems to give some idea what has been changed:
https://github.com/NickWaterton/Unifi-websocket-interface/commit/6c45d5316647f6108de89660c5e173884807d467

There are some other related commits as well.

**Comment by mgbowman** [comment] 2020-10-06 06:05
Hey guys! I have finally started to settle down after a big life change back in March. I now have a new UniFi setup and have a UDM at home! Things are starting to quiet down for me, so here soon I should be able to work on the binding to at least support UDM (which I believe will support the UDM Pro).

Stay tuned!

**Comment by mdillmann** [comment] 2020-10-10 18:01
Matt,
I have an OH3 version ready in my local sandbox that works with my UDM PRO.
After some cleanup I'll push to my addons-fork on github so you can have a look, probably beginning of week. I'm not a Java-guy so I'm sure you'll write some cleaner code than me ...

**Comment by riker187** [comment] 2021-01-11 13:34
i would love to test with UDM Pro Controller Version 6.0.43 but i have already OH3 running... Is there a possibility to get a snapshot für 3.x?

**Comment by bortell** [comment] 2021-01-20 07:43
I would also like to get a OH3 Jar file to test on a UDM pro.

**Comment by WatcherWhale** [comment] 2021-02-04 20:18
I think my [pull request](https://github.com/openhab/openhab-addons/pull/10041) should also close this issue.

**Comment by riker187** [comment] 2021-02-05 07:00
sounds greate. Could you provide a jar file for us to test before the next milestone built?

**Comment by WatcherWhale** [comment] 2021-02-05 10:40
You can now find a jar file on [my fork](https://github.com/WatcherWhale/openhab-addons/releases/tag/udm-fix).

**Comment by riker187** [comment] 2021-02-05 11:36
> You can now find a jar file on [my fork](https://github.com/WatcherWhale/openhab-addons/releases/tag/udm-fix).

Thanks for the effort. I put it in my addons folder but my OH (3.1.0M1) does not import it. Is there something else to consider?

**Comment by WatcherWhale** [comment] 2021-02-05 12:12
Wow, that is strange if I give the jar file the name `org.openhab.binding.unifi.jar` it doesn't work but if I give it the build name `org.openhab.binding.unifi-3.1.0-SNAPSHOT.jar` it works. I changed the name on the release page.

**Comment by riker187** [comment] 2021-02-05 13:12
back again in business :) Thank you very much, works for me again.

**Comment by WatcherWhale** [comment] 2021-02-08 11:22
@regnets Does this also work for you?

**Comment by regnets** [comment] 2021-02-08 11:33
I currently don't have a working OH 3.0 installation to test. However, if @riker187 tested this. I am fine with that 😄 .

If I will have any issues with OH 3.0 in the future I will just open another issue.

Thanks a lot for the work so far. Sorry that i am currently too busy for proper testing.

**Comment by lfrancke** [comment] 2021-02-08 11:59
Hi, I just tested it and it works for me! (UDM Pro / 1.8.6)
Thank you very much for your work on this.

**Comment by astoffregen** [comment] 2021-02-17 05:56
Hi, I have been using the UDP for a few days and am facing the same problem with default openHAB binding (OH 3.0, UDM 1.8.6).  
Therefore I am glad about your solution. I put your .jar file in the addons folder and create a things, port 443 (also tried 80, 8443) and UnifiOS switch to on. 
Unfortunately I get a status offline and a configuration error with java.net.SocketTimeoutException: Connect Timeout. 
Any tip what I need to change?
Thanks and best regards

**Comment by WatcherWhale** [comment] 2021-02-17 11:40
Did you fill in the correct IP address and credentials?

**Comment by astoffregen** [comment] 2021-02-17 15:41
Hi WatcherWhale, thanks for response. IP seems correct. I take a user with limited admin role for logon credentials.

**Comment by WatcherWhale** [comment] 2021-02-18 09:18
Maybe open an issue on my fork with a copy of the log, so we don't bother the rest of the subscribers of this issue.

**Comment by astoffregen** [comment] 2021-02-19 15:13
Hi WatcherWhale, after reinstall openHAB everything works fine. Thanks for support

**Comment by martinvw** [comment] 2021-04-27 18:16
It seems @mdillmann  and @WatcherWhale solved this together with @mgbowman, I wish good luck with claiming the bounty but I do believe this issue is solved and could/should be closed. Please let me know when I'm wrong.

**Comment by larsskj** [comment] 2021-05-21 08:21
Unfortunately the above solution doesn't work for me. I have a Dream Machine Pro, but when I point the config to the machine, I get "Unknown HTTP status code 404 returned by the controller".
I am running the jar from WhatcherWhale's fork and have activated the switch for "Unifi OS".

**Comment by SGiehler** [comment] 2021-05-25 20:14
> Unfortunately the above solution doesn't work for me. I have a Dream Machine Pro, but when I point the config to the machine, I get "Unknown HTTP status code 404 returned by the controller".
> I am running the jar from WhatcherWhale's fork and have activated the switch for "Unifi OS".

Switching the port to 443 did the trick for me.

**Comment by larsskj** [comment] 2021-05-26 10:03
> Switching the port from 8433 to 443 did the trick for me.
Unfortunately not for me. The UI runs fine in a browser using HTTPS from the same location, but the binding will not connect. I'm using a proper certificate from Let's Encrypt, not a selfsigned.

**Comment by mdillmann** [comment] 2021-06-05 17:03
I just tried with 3.1 snapshot and I can perfectly connect to my UDMPro (1.9.3) with Controller (6.1.71) also with a certificate from Letsencrypt.
Do you see anything in the logs ?

**Comment by stamateviorel** [comment] 2021-06-26 11:11
tried also the snapshop from WatcherWhale but i get HANDLER_MISSING_ERROR

**Comment by larsskj** [comment] 2021-06-26 15:21
Still doesn't work - and I even have load of options to try.

I have my Dream Machine Pro running on X.X.X.1. If I try connecting at port 80, the binding complains "Error establishing an SSL connection with the UniFi controller". If I try connecting at port 443, the binding complains "Unknown HTTP status code 404 returned by the controller".

I usually connect to the UDM through an HA Proxy to add a proper SSL certificate. HA Proxy is running at X.X.X.16, but connecting to the proxy also returns "Unknown HTTP status code 404 returned by the controller".

I believe these examples show that the binding actually connects to the controller - error 404 means "Page not found" and is returned by either the UDM or the proxy.

Otherwise I might add that OH is running in a Docker container in my local bare metal Kubernetes cluster. It should be a problem in this context - everything seems to indicate that the binding does connect to the UDM, just not properly.

**Comment by HoLiuS85** [comment] 2021-07-07 09:01
I have reported this a while back and the issue is unfortunately still not resolved. Same behavior as reported by @larsskj .

I'm willing to assist in any way I can to get this on the road. Please let me know what I can do.

**Comment by WatcherWhale** [comment] 2021-07-16 17:39
I have found out what the bug exactly is and drafted a quick fix. Can you test it if all issues are resolved, then I will make a new PR?

[Link to the binding](https://github.com/WatcherWhale/openhab-addons/releases/tag/404-error-fix)

Also, sorry for being under the radar, I had to focus on my studies.

**Closed** 2021-07-31 16:55 UTC
Labels: bounty
