### ISSUE TITLE
[homematic] HM-ES-TX-WM Gasmeter not funktioning due to config error

### ISSUE THREAD

**Issue by TBail** [openhab/openhab-addons#12183] opened 2022-02-01 08:39 UTC
I am using the latest nightly and have a probelm that my gas meter stay in the state of handler_configuration_pendig.
<img width="223" alt="image" src="https://user-images.githubusercontent.com/40339145/151936274-503e30f9-9626-466a-a708-0aa7ed00d533.png">
if i try to save the thing i got the message that some configuration values are not right.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/40339145/151936443-29e3aaa5-2674-4ab8-969a-77dc0ad09a27.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/40339145/151936477-98f1fe7e-fc46-42e5-b9c3-f551197ed56f.png">
<img width="549" alt="image" src="https://user-images.githubusercontent.com/40339145/151936504-ce80b9f0-ce3f-4bd7-83fd-bdaaa6631c83.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/40339145/151936539-8b97341e-d7a7-4014-b00d-240ddd51ba27.png">
The meter constant is in the required Range and has worked in earlier versions of openHAB. The threshold could not be changed and saved, because the meter constand should not bei changed.

**Comment by J-N-K** [comment] 2022-02-01 09:17
Please show the config-description for this thing. You an get it from the REST API. First retrieve the thingType, take the config-description-uri from there and the request the config-description with that uri. Thanks.

**Comment by TBail** [comment] 2022-02-01 14:14
I just copied out the relevant parts.

        {
            "default": "0.01",
            "label": "Meter Constant Gas",
            "name": "HMP_1_METER_CONSTANT_GAS",
            "required": false,
            "type": "DECIMAL",
            "min": 0.001,
            "max": 65.536,
            "stepsize": 0.1,
            "readOnly": false,
            "multiple": false,
            "groupName": "HMG_1",
            "advanced": false,
            "verify": false,
            "limitToOptions": true,
            "unitLabel": "m3/Imp.",
            "options": [],
            "filterCriteria": []
        }

From my Point of view the step size does not match the default and the min values in some way

        {
            "default": "100.0",
            "description": "TX Differenz Leistung",
            "label": "Tx Threshold Power",
            "name": "HMP_1_TX_THRESHOLD_POWER",
            "required": false,
            "type": "DECIMAL",
            "min": 0.01,
            "max": 160000,
            "stepsize": 0.1,
            "readOnly": false,
            "multiple": false,
            "groupName": "HMG_1",
            "advanced": false,
            "verify": false,
            "limitToOptions": true,
            "unitLabel": "W",
            "options": [],
            "filterCriteria": []
        },

The attached file has the full definition
[Untitled-1.txt](https://github.com/openhab/openhab-addons/files/7979058/Untitled-1.txt)

**Comment by J-N-K** [comment] 2022-02-01 14:29
The step size is not validated ATM and needs to be fixed by the binding developer. The problem is that it is not possible just to change a file, the config description are auto-generated.

I'll check why the validation for saved values fails.

**Comment by J-N-K** [comment] 2022-02-01 14:38
It doesn't fail in the test for me. Can you please set `org.openhab.core.thing.internal.ThingManagerImpl` to TRACE logging and disable/enable the thing once? You should find a log-message `Failed to validate config for '{}' with URI '{}': {}` then which contains the detected violations. Thanks. You can revert to normal logging with a log-level of DEFAULT.

**Comment by TBail** [comment] 2022-02-01 15:07
These are the log entries.

```
16:02:01.816 [DEBUG] [.core.thing.internal.ThingManagerImpl] - Thing with UID homematic:HG-HM-ES-TX-WM:8FBEF76F-0C30-3305-BE99-1D32A72A7FAF:MEQ0381486 will be persisted as enabled..
16:02:01.819 [DEBUG] [.core.thing.internal.ThingManagerImpl] - Thing homematic:HG-HM-ES-TX-WM:8FBEF76F-0C30-3305-BE99-1D32A72A7FAF:MEQ0381486 will be enabled.
16:02:01.821 [DEBUG] [.core.thing.internal.ThingManagerImpl] - Calling 'HomematicThingHandlerFactory.registerHandler()' for thing 'homematic:HG-HM-ES-TX-WM:8FBEF76F-0C30-3305-BE99-1D32A72A7FAF:MEQ0381486'.
16:02:01.827 [TRACE] [.core.thing.internal.ThingManagerImpl] - Failed to validate config for 'homematic:HG-HM-ES-TX-WM:8FBEF76F-0C30-3305-BE99-1D32A72A7FAF:MEQ0381486' with URI 'thing-type:homematic:HG-HM-ES-TX-WM': {HMP_2_TX_THRESHOLD_POWER=The value must not be less than 0.01., HMP_1_TX_THRESHOLD_POWER=The value must not be less than 0.01.}
16:02:01.829 [DEBUG] [.core.thing.internal.ThingManagerImpl] - Thing 'homematic:HG-HM-ES-TX-WM:8FBEF76F-0C30-3305-BE99-1D32A72A7FAF:MEQ0381486' not initializable, check if required configuration parameters are present and set values are valid.

```
I tried to change the Value to the default of 100 and get a message
<img width="563" alt="image" src="https://user-images.githubusercontent.com/40339145/151993681-907876fa-5edb-4a01-9bc1-bfdb3ec1a25e.png">

With a value of 100,01 the message is gone

**Comment by J-N-K** [comment] 2022-02-01 15:49
Ok, so the issue is not in the validation code but UI/binding. The presented "step" value is invalid and therefore it is not possible to save valid values (defined by min/max). This is the case for "meter constant". The validation code complains about the TX Threshold power and which indeed has an invalid value of 0. 

I'm not entirely sure what the best way to proceed is. IMO the step values should probably be removed from the binding as they don't make sense (invalid for the "meter constant") or require "strange" values (like the TX power).

@MHerbst and @maniac103 I believe you did most of the work on this binding. WDYT?

**Comment by cweitkamp** [comment] 2022-02-01 16:03
Thanks for the analysis. Afair there have been done similar corrections for other devices like https://github.com/openhab/openhab-addons/pull/9434.

**Comment by maniac103** [comment] 2022-02-01 16:42
The problem is right below the code from #9434: [here](https://github.com/openhab/openhab-addons/pull/9434/files#diff-fb6fe57d2b12434b61e47c759f8fd9f4d714eb548569a991cad4d39624b100dfR291)
It looks like the CCU doesn't provide any information about the step size, only min and max ([this method](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/communicator/parser/CommonRpcParser.java#L170) doesn't even know about step size). The binding thus tries (not very hard) to second guess it.
I wonder what a meaningful approach should look like, though:
- Omit step completely? But the results may be unexpected as well, e.g. if one enters a value like '1.234567' in the field above and it gets truncated when sending it out.
- Or rather try to guess it from the number of decimal digits of the min or max value and only fall back to '1 decimal digit' in case the min/max values have no decimal digits?

**Comment by J-N-K** [comment] 2022-02-01 16:45
IMO it should be removed. It's only used for helping the UI to display sliders.

**Comment by TBail** [comment] 2022-02-01 16:48
At the moment my device is not usabel, because i could not set the gas meter constant to the right value.

I am with @J-N-K . Just remove it. Since openHAB 1.xxx i think it worked without this check and now these checks make more trouble.

**Comment by maniac103** [comment] 2022-02-01 17:27
> Since openHAB 1.xxx i think it worked without this check

The step generation is in there since (at least) the initial OH2 Homematic binding, committed in April 2016. If anything is new, it's the UI side of things.

**Comment by MHerbst** [comment] 2022-02-01 18:16
I agree, a step size of 0.1 does not make sense for large ranges like in this example.

It is OK for me to remove the stepsize if we are sure that it will not lead to further problems.

**Comment by J-N-K** [comment] 2022-02-01 18:20
The step-size only restricts what can be set in the UI. In textual configuration only min/max are validated, so I would be very surprised if it would lead to any issues.

**Comment by maniac103** [comment] 2022-02-01 18:45
> In textual configuration only min/max are validated

This is probably why it went unnoticed for so long... +1 for removing it in that case.

**Comment by maniac103** [comment] 2022-02-01 18:46
> At the moment my device is not usabel, because i could not set the gas meter constant to the right value.

BTW: wouldn't going back to textual configuration just for this one device be a viable workaround for now?

**Comment by MHerbst** [comment] 2022-02-02 17:44
If no one is faster, I can take a look at it this weekend and remove the stepsize.

**Comment by maniac103** [comment] 2022-02-03 06:38
Done -> #12192

**Closed** 2022-02-06 19:22 UTC
