### ISSUE TITLE
[omnikinverter] Disconnect after retrieve

### ISSUE THREAD

**Issue by drksavant** [openhab/openhab-addons#10123] opened 2021-02-11 00:20 UTC
Hi there, Great work on adding this into openhab.
Issue im facing is, I am also retrieving the data on a little rasbian node and feeding it to the database.
The Rasbian node connects every 10 minutes, polls the data and disconnects,
This Connection Seems to be persistent or polling to hard, Whenever I start this connection I cannot pull data from my other devices, could you add a variable for polling interval and disconnect (after data has been retrieved ?)

thanks

**Comment by hansbogert** [comment] 2021-08-01 11:58
Hi, I'm the writer of the binding. I'll put it on my todo list. I'd like to reproduce this first. Can you tell me the exact model of your inverter, and the first 3 digits of your serial?

**Comment by drksavant** [comment] 2021-08-01 15:16
Sweet i almost gave up on the thing ive reinstalled a new version of
openhab and could not find the binding at all.

Info id nlbn4020155b2048

The issue mainly is that openhab connects and does not let go whereas the
python script connects and resets the port by disconnecting. Inuse both and
once the port is open nothing else can interface

Sonbasiy it is awesome stuff

Sonthe worst part is that its no longer in addons for openhab2

**Comment by drksavant** [comment] 2021-08-01 15:26
Aan je naam te zien kunnen we ook in nederlands af 👌

**Comment by hansbogert** [comment] 2021-08-01 20:03
Let's keep it in english for the benefit of others.

> openhab and could not find the binding at all.
This worries me, this is the 2nd time I'm hearing this. Which version of OpenHAB are you running?

**Comment by hansbogert** [comment] 2021-08-01 20:48
> The issue mainly is that openhab connects and does not let go whereas the
How did you conclude this?
The socket is closed, as per the 'try-with-resources' construct in java, in the implementation at: https://github.com/openhab/openhab-addons/blame/main/bundles/org.openhab.binding.omnikinverter/src/main/java/org/openhab/binding/omnikinverter/internal/OmnikInverter.java#L46

**Comment by drksavant** [comment] 2021-08-04 07:59
I concluded this because when my bindings whwre connected in the old
openhab i could not connect withy the puthon script. After removing it it
was reenablee

**Comment by hansbogert** [comment] 2021-08-05 06:56
If you can provide the python script I should be able to reproduce this fairly quickly (right?)

**Comment by drksavant** [comment] 2021-08-07 09:57
Sure , its the default python script that everybody uses but ill download
it and attach it. Sorry for my slowness planning the holiday

**Comment by hansbogert** [comment] 2021-08-09 07:17
Not sure if you intended to have attached it with your email, but it's not showing here in Github.

**Comment by hk0017** [comment] 2021-11-01 13:01
Hi Hans, I have the same issue with an omnik5000tl2.
It looks like the Wifi-module is overwhelmed with request from the binding, so that it didn't responded anymore to another host or sended info to the website from Omnik. After resetting the Omnik-module (power off/On) it got back, but I  didn't dare to use the binding anymore.
So, is it possible for you to add a timer for how often the binding requests for info? I want, for exemple, get info every 5 minutes.

**Comment by hk0017** [comment] 2021-11-01 20:10
@hansbogert see comment above. Forgot to select your name.

**Comment by hansbogert** [comment] 2021-11-02 07:21
> so that it didn't responded anymore to another host 

What did you use to conclude that? Because I never got a script to reproduce this from @drksavant 

I doubt this is merely a "too small interval" issue.

**Comment by hk0017** [comment] 2021-11-02 08:08
I concluded it because the collection of the data, by a Raspberry Pi with the scripts of Wouterrr, stocked and also the website of Omnik didn't received no more data. And in the log of OH2.5 I saw a lot of requests per second. 
But it is more than a year ago I faced that, so no more logfiles. 
If you want, I will test it again with OH3.1. 
Using the binding instead of the Pi with the Wouterrr-scripts (producing csv-files) is much better I hope.

**Comment by hansbogert** [comment] 2021-11-02 09:38
>  OH2.5 I saw a lot of requests per second.

There was an oversight on my part that in some cases caused multiple threads to start polling. That should've been fixed by someone else. Could you indeed test with the latest version?

**Comment by hk0017** [comment] 2021-11-02 10:15
OK. I started some items. I'll let it go for some days.

Looks like every 10,5 seconds there is a change in power logged (when there is a change). So that's a lot more than the poll every 300 seconds with the Wouterrr-scripts that I configured. 
Is the binding polling the inverter continuously or every 10 seconds?

**Comment by hansbogert** [comment] 2021-11-02 10:37
~10s seems correct.

It's polling every 10s. It's UDP iirc, so there's no concept of *continuously* with UDP. (i might be wrong there.)

**Comment by hk0017** [comment] 2021-11-02 11:07
So it works as designed :-) 

My Wouterr-script is still working, but the Omnik-site (solarmanpv,com) is not getting information after 11:00 CET. And the webpage on the inverter says:  Last updated 66 Min Ago (at 12:06 CET)

I don't know how bindings are made - so it's marvelous what you made ! - , but is there a possibility to add a polling frequentie? 
Just like for example in the network binding where you can define in the things file the 'refreshInterval'.
This helps also to minimize the entries in Influxdb.

**Comment by hk0017** [comment] 2021-11-02 11:13
got an error also:

2021-11-02 12:02:55.351 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'omnikinverter:omnik:omnik5000tl2' changed from ONLINE to OFFLINE: Unknown error: Read timed out

2021-11-02 12:03:08.454 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'omnikinverter:omnik:omnik5000tl2' changed from OFFLINE: Unknown error: Read timed out to ONLINE

Pauzed the binding and inverter is pushing info again to website now.

**Comment by hansbogert** [comment] 2021-11-02 13:37
> My Wouterr-script is still working

So both the omnikinverter binding and the Wouterr-script are working at that point?

>  And the webpage on the inverter says: Last updated 66 Min Ago (at 12:06 CET)

You really mean on the 'local' webserver of the inverter? or the cloud environment of omnik?

If it's the former, can you add a screenshot so, because this might be a good way to see if I can reproduce this.

Otherwise I'll just try to run the Wouterr-script as well.

**Comment by hansbogert** [comment] 2021-11-02 13:38
> 2021-11-02 12:02:55.351 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'omnikinverter:omnik:omnik5000tl2' changed from ONLINE to OFFLINE: Unknown error: Read timed out
> 
> 2021-11-02 12:03:08.454 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'omnikinverter:omnik:omnik5000tl2' changed from OFFLINE: Unknown error: Read timed out to ONLINE

After these errors, do you now see more than 1 request per 10 seconds?

**Comment by hk0017** [comment] 2021-11-02 15:38
![Omnik-20211102-15h27m](https://user-images.githubusercontent.com/93526824/139876529-1bd2cefb-786d-4203-936b-121dab8d49f4.PNG)
I've restarted the binding at 12:49. 
At 15:27 the inverter says 63 minutes  not sended updates. Apparently the inverter manages to send an update very occasionally.
See also the graph on the Solarman-site:
![Solarman-graph-20211102-16h20m](https://user-images.githubusercontent.com/93526824/139877678-3859386c-14d6-46ca-ac88-95f0322f5a7b.PNG)

The binding is still polling every 10 seconds after the errors. And the Wouterrr-script is receiving data every 300 seconds without drops. This looks fine. The Wifi-module in the inverter is not crashed up till now.

**Comment by hk0017** [comment] 2021-11-02 21:56
I Think my inverter crashed at 20:15. Wouterscript gives a:
  File "/home/pi/Omnik-Data-Logger/OmnikExport.py", line 73, in run
    data = inverter_socket.recv(1024)
socket.timeout: timed out

The OH3.1 gives OFFLINE
But the webpage on the inverter is working (gives "Last updated 140 Min Ago" at 22:53) and  the inverter is pingable on his IP-adddress.

**Comment by hk0017** [comment] 2021-11-03 11:56
after pauzing the binding, the polling by script and pushing data to Omnik-site came back.

**Comment by hansbogert** [comment] 2023-01-05 13:02
@hk0017 sorry for not picking this up, would you still like a config parameter in the binding which sets the timeout duration?

**Closed** 2024-10-11 11:12 UTC
