### ISSUE TITLE
[sonos] Multiple docker networks interfere with binding

### ISSUE THREAD

**Issue by arins** [openhab/openhab-addons#13077] opened 2022-07-04 15:23 UTC
If i have multiple docker containers running with ports exposed besides openhab docker container this causes the sonos binding give error UPnP/DLNA binding: UPnP device not yet registered.
I can also let you know that I don't have any special network settings. I run everything under 192.168.1.x network. Sonos and OH3 is under same subnet.

## Expected Behavior
sonos binding should just work even though I have other containers running side by side with openhab docker container

## Current Behavior
When I have other docker containers with network_mode: host there is no issue but when exposing ports and not using network_mode: host this error appears: **UPnP/DLNA binding: UPnP device not yet registered.** This causes the sonos things to be offline.

## Possible Solution
If I use network_mode: host on all other docker containers and delete all networks in docker then sonos binding starts working and all sonos things becomes online.

## Steps to Reproduce (for Bugs)

1. Run OH3 in docker
2. Run other services with exposes ports on the same machine. (tested on both rasberry pi 4 and a intel machine.)
3. Sonos things becomes offline (sometimes some sonos things and sometimes all of them.) 

## Context
I can not use the sonos binding. I was thinking using node-red because there it works fine!
Maybe check if sonos binding get inteference when docker creates a lot of networks?

## Your Environment
Raspberry pi 4 with official openhab 3 docker image.

**Comment by pgfeller** [comment] 2023-04-06 07:42
Hi @arins 

I think I face the same issue that you suffer from - can you elaborate a little more on your "host" workarround - what do I need to change in the configuration for this and are there drawbacks?

I try to understand better, if this is more a configuration problem - or if the binding should do something differently (and if so - what ....). I do not know much about the protocols involved and spare time is rare (as usual); but will try to spend some of it to investigate to find a solution (if it is config - then I'll probably try to update the binding doc to make this known to others - as I think setups with docker containers will become more common in the future),

The bot linked my community post above if you are interested in my config.

kind regards,
Patrik

**Comment by arins** [comment] 2023-04-06 07:57
@pgfeller sorry for the solution not being clear.
I run all my containers on raspberry pi. So I have like 6 containers in a docker compose on the raspberry. 
What worked for me was to run all container in 

`network_mode: host`


so for example I have nginx running on the rapsberry (and other stuff) which requires a port.
In your docker-compose.yml file you have something like this 
```

version: '3'
services:
  nginx_proxy:
    container_name: nginx_proxy
    image: "nginx:latest"
    restart: unless-stopped
    network_mode: host
    ......... # your settings
  openhab:
    container_name: openhab
    image: "openhab/openhab:3.4.1"
    network_mode: host
    ...... # your settings
```
so basically your services need to use `network_mode: host`. It can cause port conflict on the host machine so you need the configure the services not to use the same port. 
for example ngnx might use 80, 443 and openhab might use 9443 or something like that. As long as they don't use the same ports. So this is the downside with `network_mode: host`

If you are using docker run command you can set network_mode from there as well. but I don't remember top of my head how to do it.

This solved my problems with Sonos binding for me at least.

**Comment by pgfeller** [comment] 2023-04-11 18:55
Hi @arins,

thank you for the help - the problems were indeed caused by the docker networks - despite that the openhab instance was not running in a container and was bound exclusively to the host adapter/IP. I think this should be treated as a bug in the sonos binding - as a default docker configuration should be possible on an openHAB server. If it is a configuration issue it should be mentioned in the binding documentation.

The original configuration looked like this:

![25a5cacfa489ab2d725d56df6bfdb17dca21706c 1](https://user-images.githubusercontent.com/9395643/231260013-c005a383-2317-4745-811b-59ab2b341dcb.png)

After the configuration change all docker containers use the host network directly (as you proposed) - which is not the optimal solution; but a work arround for the time beeing:

![image](https://user-images.githubusercontent.com/9395643/231260364-95c3beb5-1b96-4c8b-a952-951750612a51.png)

I wonder if it is worth to update the sonos binding docu to make users aware that there are limitations if there are docker containers running on the same machine. It would be great if someone with docker or sonos binding code expertise could comment if additional configuration is required to use isolated networks for the containers (which I would prefer) - then we could update the docu one way or the other.

with kind regards,
Patrik

**Comment by arins** [comment] 2023-04-11 20:11
@pgfeller Yes I agree that the documentation should contain information about running OH with other docker containers can interfere with OH if this bug is not fixed.  Maybe I will try to make a PR later for the documentation.

**Comment by lolodomo** [comment] 2023-04-15 15:45
> to update the sonos binding docu to make users aware that there are limitations if there are docker containers running on the same machine.

I guess this would not be specific to one binding like Sonos but rather to any binding using jUPnP library.

**Comment by pgfeller** [comment] 2023-05-08 09:01
@lolodomo & @arins 

> I guess this would not be specific to one binding like Sonos but rather to any binding using jUPnP library.

Good point! I switched some of my containers back to a private network and specified the interface to be used for jupnp in `services/runtime.cfg`:

```ini
org.eclipse.smarthome.network.upnp:networkInterface=eno1
```
So far I do not experience any connection issues withthe sonos binding anymore. @arins - maybe you can give this a try as well to x-check if it is a working solution for you as well. If so I would add it to the documentation of the sonos binding as a remark (in case it is used together with docker containers).

**Comment by lolodomo** [comment] 2023-05-08 09:51
I am surprised that the key still start with "org.eclipse.smarthome" !

> I would add it to the documentation of the sonos binding as a remark (in case it is used together with docker containers).

There is even a docker page in the documentation in which you can document that (docker / troubleshooting):
https://www.openhab.org/docs/installation/docker.html#troubleshooting

**Comment by lolodomo** [comment] 2023-05-08 09:56
IMHO, the best place would be in https://github.com/openhab/openhab-docker/blob/main/README.md

**Comment by lolodomo** [comment] 2023-05-08 10:00
> ```ini
> ```ini
> org.eclipse.smarthome.network.upnp:networkInterface=eno1
> ```
> 
> 
> 
> I am surprised that the key still start with "org.eclipse.smarthome" !
> ```

I wopuld rather expect org.openhab

**Comment by arins** [comment] 2023-05-08 22:09
@pgfeller I tried to set other containers **not** to use `netwwork_mode: host` and set the config 
``` 
org.eclipse.smarthome.network.upnp:networkInterface=wlan0
```
in `runtime.cfg`. Restarted OpenHAB. The sonos things are offline for me.
I could not find that configuration mentioned anywhere online. Anyway I use wifi on a rasperry and I saw it listed with `ifconfig` so that is why I set mine to **wlan0**. Don't know if that is correct.

**Comment by pgfeller** [comment] 2023-05-17 09:47
Hi @arins 

is this an openhab instance that you've upgraded from previous versions of OH, or is it a "clean" installation. Mine was upgraded since I think OH 1 ...

Until now my sonos runs stable with this setting - but I've found a file that might be related to the history of the installation:
`OPENHAB_RUNTIME/bin/update.lst`:

There is a command which might migrate my outdated setting to the new namespaces:
`REPLACE;org.eclipse.smarthome.network;org.openhab.network;$OPENHAB_USERDATA/config/org/openhab/network.config`

But I'm not sure if this only takes effect during upgrades or also is active during runtime. Anyhow - I'll change my setting to 
```properties
# org.eclipse.smarthome.network.upnp:networkInterface=eno1
org.openhab.network.upnp:networkInterface=eno1
```

And check if it also runs stable. I assume you determined the network adapter correctly - but you can also use nmcli if it installed to x-check.

I'll let you know if it also runs stable with the new property key ... if this will not help in your installation or mine will become unstable again I'll do some more investigation. But I'm quite sure the key is that we bind the upnp network to the right adapter/ip.

**Comment by arins** [comment] 2023-05-19 21:18
I switch to wired connection and I tried both
`org.openhab.network.upnp:networkInterface=eth0`
and
`org.eclipse.smarthome.network.upnp:networkInterface=eth0`

both gave offline sonos. I will go back not network_mode:host until some fix is out

**Comment by pgfeller** [comment] 2023-11-16 07:59
After the upgrade to openHAB 4.0.4 my existing SONOS setup stopped working - must llikely related to the issue with docker & jupnp multicast behavior. I use `network_mode: host` for the docker container - so I tried to had a look into it again using the karaf console to configure the relevant settings - with the following result:

[Relevant code in jupnp transport](https://github.com/jupnp/jupnp/blob/4a3ab9dec37cb9be324d02f6dc81ffca74237e1e/bundles/org.jupnp/src/main/java/org/jupnp/transport/spi/NetworkAddressFactory.java#L33)
```java
// An implementation can honor these if it wants (the default does)
public static final String SYSTEM_PROPERTY_NET_IFACES = "org.jupnp.network.useInterfaces";
public static final String SYSTEM_PROPERTY_NET_ADDRESSES = "org.jupnp.network.useAddresses";
```
Relevant Karaf configuration:
```
Pid:            org.jupnp
BundleLocation: ?
Properties:
   asyncThreadPoolSize = 30
   felix.fileinstall.filename = file:/openhab/userdata/etc/org.jupnp.cfg
   multicastResponsePort = 0
   service.pid = org.jupnp
   threadPoolSize = 15
```
```karaf
openhab> config:edit --type json --force org.jupnp
openhab> config:property-list
   asyncThreadPoolSize = 30
   multicastResponsePort = 0
   threadPoolSize = 15
openhab> config:property-append org.jupnp.network.useInterfaces "eno1"
openhab> config:property-append org.jupnp.network.useAddresses "192.168.0.65"
openhab> config:update
```

After a restart of OH I see this in the console:

```karaf
openhab> config:property-list --pid org.jupnp                                                                                                                                                          
   asyncThreadPoolSize = 30
   multicastResponsePort = 0
   org.jupnp.network.useAddresses = 192.168.0.65
   org.jupnp.network.useInterfaces = eno1
   threadPoolSize = 15
```
➡️ [Expected trace message](https://github.com/jupnp/jupnp/blob/4a3ab9dec37cb9be324d02f6dc81ffca74237e1e/bundles/org.jupnp/src/main/java/org/jupnp/transport/impl/NetworkAddressFactoryImpl.java#L413)
```java
log.trace("Skipping unwanted network interface (-D {} ): {}", SYSTEM_PROPERTY_NET_IFACES, iface.getName());
```
Actual result:
```log
userdata/logs/upnp.log:
  100: 2023-11-16 08:45:53.780 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 172.22.0.1
  104: 2023-11-16 08:45:53.780 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 172.21.0.1
  108: 2023-11-16 08:45:53.781 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 172.19.0.1
  112: 2023-11-16 08:45:53.782 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 172.20.0.1
  116: 2023-11-16 08:45:53.782 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 192.168.6.98
  120: 2023-11-16 08:45:53.783 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 192.168.0.65
```

... so that does not help either - but it seems at least in the original jupnp implementation there seems to be a settting to control the interface to use for upnp/multicast traffic. So either I did the config wrong - or openhab uses a different factory. Maybe this input brings us closer to a stable SONOS setup with docker. I'll follow up as soon as I find some time. But mabe someone spots my mistake - or knows if in OH the interfaces for jupnp are setup in a different way.

**Comment by arins** [comment] 2023-11-16 08:48
@pgfeller Great find! So do we open a bug in sonos binding? and refer to this bug?

In my opinion SONOS binding should use same settings jupnp or at least be able to configure the sonos binding to be able to pick network inteface. What do you think?

**Comment by lolodomo** [comment] 2023-11-16 15:24
I believe the solution was given in the community forum. There is a parameter to set in the Java command if I correctly remember.

**Comment by pgfeller** [comment] 2023-11-16 17:12
Hi @lolodomo,

there are various post, suggestions and discussions about this topic in the forum - I do not know if you the one you reference is [https://community.openhab.org/t/sonos-in-docker/150660](https://community.openhab.org/t/sonos-in-docker/150660/13?u=patrik_gfeller)? I try to follow this topic and searched the forum for approaches - and also did some post in the past what had worked for me. But as after the upgrade this config does not work anymore it also seems to be unrelated ... that's why I had a look into the code and the jupnp parameters might not be taken into account by the SONOS binding - and my configuration worked until now because something small was different to other docker setups (order of interfaces, timing ... you know - those computer things).

As the code from the binding seems to use another factory to communicate I suspect that the jupnp setting approach might not work. But I have to do some more investigation to see if this is correct.

If there are other posts that explain a reliable docker setup with SONOS in the forum I'm happy for a pointer and will try those settings as well. And once we know what works for all users/configurations I'll try to update the documentation of the docker image accordingly ...

with kind regards,
Patrik

**Comment by pgfeller** [comment] 2023-11-17 18:56
Hello @arins & @lolodomo 

I did some more digging and in theory the solution @lolodomo referenced should work - but maybe I did a mistake in the syntax of the compose file ... anyhow - I have now a working configuration in case @arins would like to x-check if this also works for you.

The SONOS binding is properly integrated with the current OH core upnp infrastructure - but the scope of the properties make the difference. I do not know why the ` EXTRA_JAVA_OPTS=-Dorg.jupnp.network.useInterfaces="eno1"` did not work (I suspect that the networks must be listed without the `"`...). But I will not follow up on this atm (time budget used and the system seems to work ...). 

What I did is to set the interface in `userdata/etc/system.properties':

```Properties
org.jupnp.network.useInterfaces=eno1
```

Until now the communication looks stable and the logs do make sense:

```log
userdata/logs/upnp.log:
   5: 2023-11-17 18:37:37.109 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth84ef8a1
   8: 2023-11-17 18:37:37.110 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth0496b9d
  11: 2023-11-17 18:37:37.110 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth99a640a
  14: 2023-11-17 18:37:37.111 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth422e0b5
  17: 2023-11-17 18:37:37.111 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth1ff1007
  20: 2023-11-17 18:37:37.112 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth1528ef9
  23: 2023-11-17 18:37:37.112 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth0ea4cf2
  26: 2023-11-17 18:37:37.113 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth24b2901
  29: 2023-11-17 18:37:37.114 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): vethd0f5998
  32: 2023-11-17 18:37:37.115 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth93bf6ff
  35: 2023-11-17 18:37:37.115 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth21f0d06
  38: 2023-11-17 18:37:37.116 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): veth3b67029
  41: 2023-11-17 18:37:37.117 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): br-d19ae4339d2f
  44: 2023-11-17 18:37:37.119 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): br-8db4ae73724f
  47: 2023-11-17 18:37:37.119 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): br-b8da1ab4b871
  56: 2023-11-17 18:37:37.121 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): docker_gwbridge
  59: 2023-11-17 18:37:37.122 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Skipping unwanted network interface (-D org.jupnp.network.useInterfaces ): eno1.4

```

```log
2023-11-17 18:37:37.129 [TRACE] [sport.impl.NetworkAddressFactoryImpl] - Discovered usable network interface address: 192.168.0.65
2023-11-17 18:37:37.131 [DEBUG] [org.jupnp.transport.Router          ] - Init multicast receiver on interface: eno1
2023-11-17 18:37:37.133 [DEBUG] [org.jupnp.transport.Router          ] - Starting multicast receiver on interface: eno1
2023-11-17 18:37:37.143 [DEBUG] [org.jupnp.transport.Router          ] - Init stream server on address: /192.168.0.65
2023-11-17 18:37:37.144 [DEBUG] [ansport.impl.ServletStreamServerImpl] - Setting executor service on servlet container adapter
2023-11-17 18:37:37.144 [DEBUG] [ansport.impl.ServletStreamServerImpl] - Adding connector: /192.168.0.65:-1
2023-11-17 18:37:37.148 [INFO ] [i.HttpServiceServletContainerAdapter] - Registering UPnP callback servlet as /upnpcallback
2023-11-17 18:37:37.158 [DEBUG] [org.jupnp.transport.Router          ] - Init datagram I/O on address: /192.168.0.65
```

If @arins or someone else can confirm that this works we can update the documentation for the docker use case (as this also affects other bindings probably the README of the docker image itself will be the right place).

It is also the question if the `EXTRA_JAVA_OPTS` would be the better approach (but I'll stay with the config file for the moment) - but if someone can confirm the other approach we might add both options to the docu ...

with kind regards,
Patrik

**Comment by lolodomo** [comment] 2023-11-17 19:13
> What I did is to set the interface in `userdata/etc/system.properties':
> 
> ```ini
> org.jupnp.network.useInterfaces=eno1
> ```

That looks weird to me to update this file and more generally any file in that directory.
Why not simply add you setting in a file in conf/services ? You can call your file jupnp.cfg for example.

**Comment by pgfeller** [comment] 2023-11-17 19:39
@lolodomo - thank you for your feedback 👍; I appreciate it - as what I do is a lot of try and error.

Such `.cfg` files were automatically created after a did the config in the karaf console:

```karaf
openhab> config:edit --type json --force org.jupnp
openhab> config:property-list
   asyncThreadPoolSize = 30
   multicastResponsePort = 0
   threadPoolSize = 15
openhab> config:property-append org.jupnp.network.useInterfaces "eno1"
openhab> config:property-append org.jupnp.network.useAddresses "192.168.0.65"
openhab> config:update
```
but this did not work - but maybe I've to remove the **"** for the values for this to work 🤔 ... - but for the moment I'm happy that I have a working configuration and spend quite some time with different experiments. It is likely that my solution is not the optimal one - but I'll not follow up atm - as I invested quite some time here and now it works. So I share what I've learned/experienced in the hope it helps a bit. 

I do not have the knowledge to say what is best practice for karaf and OH config and also docker is new to me (but I already think it is the best way to operate OH) . If other docker users are willing to experiment with the `.cfg` file, the `EXTRA_JAVA_OPTS` and/or manual karaf configuration to see if that also results in a working SONOS system (it probably does, as I suspect a syntax mistake on my side). I've checked the forum post again, and indeed in that example no **"** are used to set the parameter ...

Let's see if we get feedback from other users.

Who could advice what is best practice in this case? When we know what is the best approach I'll try it when the next OH update is available and update the docker README to share this with all users that use `upnp` transport.

**Comment by phenix1990** [comment] 2023-12-25 06:45
I also had problems with the sonos binding since i changed my setup to docker. I searched a lot and found as mentioned the solution to set several docker containers to host network mode.

But because i dont like this solution i tried the EXTRA_JAVA_OPTS and it worked just perfect with containers in bridge mode (except openhab container). I use only the ethernet connection so heres whats working for me:
`EXTRA_JAVA_OPTS: "-Dorg.jupnp.network.useInterfaces=eth0 -Dorg.jupnp.network.useAddresses=192.168.178.99 -Duser.timezone=Europe/Berlin"`

**Comment by lolodomo** [comment] 2023-12-25 11:14
Could you please contribute  by an enhancement of the following page in documentation ?
https://www.openhab.org/docs/installation/docker.html
The corresponding page in Github to propose your change :
https://github.com/openhab/openhab-docs/blob/main/installation/docker.md

**Comment by lolodomo** [comment] 2023-12-26 18:39
In case the idea is to enhance the OH docker page and not the Sonos bonding documentation, this issue should be moved to openhab-docs git repo.

**Comment by pgfeller** [comment] 2023-12-26 22:04
ok - is there a way to move the issue - or do we need to close this one and open a new issue in the docker repo (and e.g. x-link them for reference)?

**Comment by pgfeller** [comment] 2023-12-27 16:21
@Confectrician 

Hi Jerome,

as I've seen that you are a very active contributor to the `openhab-docs` repository. I wonder if you could help me with transfering this issue to the docs repository - as I do not have the necessary rights (or grant me the necessary permission to perform the move).

thanks.

**Comment by lolodomo** [comment] 2023-12-27 16:35
Don't loose your time with that but rather spend your time to enhance the doc. We will close this issue when your enhancement is merged.

**Comment by pgfeller** [comment] 2023-12-27 22:36
It's a while since I did the last PR - but did my best to follow the conventions:

https://github.com/openhab/openhab-docs/pull/2190

The preview of the documentation is available here:
https://deploy-preview-2190--openhab-docs-preview.netlify.app/docs/installation/docker.html#universal-plug-and-play-upnp

**Comment by arins** [comment] 2024-01-02 13:13
I know you are talking about documentation and this issue is closed but I want anybody viewing this issue knows that it worked for me. 
I used:

EXTRA_JAVA_OPTS: `-Dorg.jupnp.network.useInterfaces=eth0 -Dorg.jupnp.network.useAddresses=192.168.1.128"`

under `environment `options in my docker compose

**Comment by pgfeller** [comment] 2024-01-02 17:02
@arins - thanks; the issue is not close yet - but will probably be moved to the documentation repository. Maybe you can have a look at the propose documentation change and give feedback if you think something is missing,

**Comment by pgfeller** [comment] 2024-03-02 08:37
PR https://github.com/openhab/openhab-docs/pull/2190 added the necessary information to solve this problem to the documentation for the next release. Not sure if we can close this already, or wait until the docu is released 🤔.

**Comment by pgfeller** [comment] 2024-03-02 08:39
@stefan-hoehn 

Maybe you can transfer this issue to the docu repo - as it is not a bug as such in openHAB nor the binding code ... (I do not have the rights for the transfer).

**Comment by lolodomo** [comment] 2024-03-02 08:49
As the doc PR was merged, we can close it.

**Closed by lolodomo** 2024-03-02 08:49 UTC
Labels: documentation
