### ISSUE TITLE
[nuki] Error with nukiId Dec/Hex convert

### ISSUE THREAD

**Issue by momo584** [openhab/openhab-addons#13088] opened 2022-07-06 13:05 UTC
## Current Behavior

The Nuki-ID of my Smartlock is nukiId: "88710849"
The binding tries to convert it because it has 8 digits only, but it isn nessecary.
If It try to add a "0" at the beginning it is also failling.

## Your Environment

* Version used: openHAB 3.3.0

**Comment by Ger-sh-win** [comment] 2022-09-28 14:57
> Does that mean the binding does not work with smartlock with id this low?
Yes! The binding ist not working with smartlocks that have an ID with only 8 digits.

**Comment by janvyb** [comment] 2022-09-28 15:10
Ok, sorry for late reply, I had no idea this issue existed. The reason the conversion is there is for compatibility with old binding version since it required nukiId to be in hexadecimal format but the new one requires it to be in decimal format (same as the API uses). Does that mean that your hexadecimal nukiId starts with zero, or is just 7 digits long? I assumed all nukiIds are 8 hexadecimal digits long, now I'm wondering how to fix that since there's now way to tell if "88710849" should be interpreted as hexadecimal or decimal.

**Comment by momo584** [comment] 2022-09-29 07:27
Yes my hexadecimal  nukiId is just 7 digits long.
In the nuki API it does not show a "zero" at the beginning. Just the 7 digits.

In the meantime I replaced my old nuki with a new one, but maybe for other the same can appear. (and also for me if i would decide to use the old nuki for another door ;))

**Comment by janvyb** [comment] 2022-09-29 07:37
Right, I think the easiest solution would be to say nukiId is in hexadecimal format if it contains at least one a-f letter. It's still possible to have nukiId in hexadecimal format with only numeric digits, but that can be fixed by manually converting it to decimal (and it should only be problem for people who upgrade from old version of binding).

**Comment by momo584** [comment] 2022-09-29 07:42
Isn't it the best solution to use the id as it is, without converting ?!

**Comment by janvyb** [comment] 2022-09-29 08:08
The problem is that all Nuki APIs accept both formats but only return id in decimal. So when bridge sends callback some device was updated the binding searches for the changed thing using nukiId

**Closed** 2022-10-01 11:45 UTC
