### ISSUE TITLE
[influxdb] [oh3] [persistence] Values of Switches are all read as OFF from persistence

### ISSUE THREAD

**Issue by carnifex82** [openhab/openhab-addons#10121] opened 2021-02-10 19:58 UTC
## Expected Behavior
Switch states should show up in the graphs as ON/OFF area diagrams. 
I noticed this when the new charts were all working fine for number values but not for switch states. Persistence Service should return the same data as store in the influxdb.

## Current Behavior
With some help, I was able to figure out that the values of switch items retrieved from the persistence API do not reflect the values stored in the influx db. 

`> select value from  iPhone_Online
name: iPhone_Online
time                value
----                -----
1612954910668000000 0
1612954931794000000 1
1612954996835000000 0
1612955122916000000 1
1612955971594000000 0
1612956031705000000 1
1612956096732000000 0
1612956221874000000 1
1612956286901000000 0
1612956607030000000 1
1612956672098000000 0
1612956732145000000 1
1612956917395000000 0
1612957225425000000 1`

(partial) JSON Output from the API Explorer:

> {
>   "name": "iPhone_Online",
>   "datapoints": "77",
>   "data": [
>     {
>       "time": 1612954910668,
>       "state": "OFF"
>     },
>     {
>       "time": 1612954931794,
>       "state": "OFF"
>     },
>     {
>       "time": 1612954931794,
>       "state": "OFF"
>     },
>     {
>       "time": 1612954996835,
>       "state": "OFF"
>     },
>     {
>       "time": 1612954996835,
>       "state": "OFF"
>     },
>     {
>       "time": 1612955122916,
>       "state": "OFF"
>     },
>     {
>       "time": 1612955122916,
>       "state": "OFF"
>     },
>     {
>       "time": 1612955971594,
>       "state": "OFF"
>     },
>     {
>       "time": 1612955971594,
>       "state": "OFF"
>     },
>     {
>       "time": 1612956031705,
>       "state": "OFF"
>     },
>     {
>       "time": 1612956031705,
>       "state": "OFF"
>     },
>     {
>       "time": 1612956096732,
>       "state": "OFF"
>     },
>     {
>       "time": 1612956096732,
>       "state": "OFF"
>     },

Three things of note:
1st: within influxDB the timestamps are zero padded (probably not a problem)
2nd: all values except the first return twice
3rd: all values are “OFF”

This seems to be an issue for all switch ON/OFF items. Number items are working fine. 

See also this thread in the community forum:
https://community.openhab.org/t/analyze-charts-not-working-for-switches/116683

## Possible Solution
It looks like it might be a mapping issue? 1 from Influx DB apparently doesn't get mapped to ON in the persistence service.
I have no explanation for the data duplication though.

## Your Environment
influxdb is the only and default persistence service

Influx.persist file:
`Strategies {

    everyMinute : "0 * * * * ?"
    everyHour   : "0 0 * * * ?"
    everyDay    : "0 0 0 * * ?"

    default = everyUpdate

}

Items {
        iPhone_Online : strategy = everyChange
        RestoreOnStartup : strategy = restoreOnStartup

}`

openHAB 3.0.0 Release Build (Upgraded from OH2.4 via openhabian)
influxDB Persistence 3.0.0
X-Influxdb-Build: OSS
X-Influxdb-Version: 1.8.3

**Comment by wborn** [comment] 2021-02-11 10:17
I think it was already fixed in OH 3.1 with https://github.com/openhab/openhab-addons/pull/9545. We might want to cherry-pick the fix onto 3.0.x.

**Comment by carnifex82** [comment] 2021-02-11 10:23
Yes, that quite seems like the same issue. Depending on the release date for 3.1 an earlier fix would be greatly appreciated. 

However in #9545 the duplicate values issue is not mentioned. Is it a separate issue?

**Comment by inis1981** [comment] 2021-02-16 02:53
I'm having this issue as well 3.0.1, zwave switch not showing in analyze or grafana. Some of my switches are but atleast two are not. Found no solution so far.

**Comment by wborn** [comment] 2021-02-18 17:11
Hey I just cherry-picked #9545 to the [3.0.x branch](https://github.com/openhab/openhab-addons/commits/3.0.x)! :slightly_smiling_face: I don't know anything about the duplicate value issue.

**Comment by carnifex82** [comment] 2021-02-19 15:50
> Hey I just cherry-picked #9545 to the [3.0.x branch](https://github.com/openhab/openhab-addons/commits/3.0.x)! 🙂 I don't know anything about the duplicate value issue.

Thank you!

**Comment by M1000S** [comment] 2021-11-27 12:22
On my installation the issue still exists.
Openhab: 3.1.0
InfluxDB: 1.8.10

When will the issue be fixed?

InfluxDB query:
time                item                         type    value
----                ----                         ----    -----
1638013440292000000 HmIPHeizungBuero_WindowState Contact 0
1638013500292000000 HmIPHeizungBuero_WindowState Contact 0
1638013560292000000 HmIPHeizungBuero_WindowState Contact 0
1638013620292000000 HmIPHeizungBuero_WindowState Contact 0
1638013680292000000 HmIPHeizungBuero_WindowState Contact 0
1638013740293000000 HmIPHeizungBuero_WindowState Contact 0
1638013800292000000 HmIPHeizungBuero_WindowState Contact 0
1638013860292000000 HmIPHeizungBuero_WindowState Contact 0
1638013920293000000 HmIPHeizungBuero_WindowState Contact 0
1638013980292000000 HmIPHeizungBuero_WindowState Contact 0


API Explorer
{
  "name": "HmIPHeizungBuero_WindowState",
  "datapoints": "59",
  "data": [
    {
      "time": 1638013440292,
      "state": "CLOSED"
    },
    {
      "time": 1638013500292,
      "state": "CLOSED"
    },
    {
      "time": 1638013500292,
      "state": "CLOSED"
    },
    {
      "time": 1638013560292,
      "state": "CLOSED"
    },
    {
      "time": 1638013560292,
      "state": "CLOSED"
    },
    {
      "time": 1638013620292,
      "state": "CLOSED"
    },

**Comment by lujop** [comment] 2022-01-08 01:09
@M1000S  But the example you put in your last message all the values are 0, aren't they?
Then it's normal that all are closed, or I'm missing something?

**Comment by florian-h05** [comment] 2023-01-04 13:12
I can confirm that ON/OFF works correctly for Switch Items in InfluxDB Persistence (openHAB 3.4.0 Release Build), but I see the duplicate value issue as well:

```json
{
  "name": "Florian_Licht",
  "datapoints": "21",
  "data": [
    {
      "time": 1672837223228,
      "state": "OFF"
    },
    {
      "time": 1672837223242,
      "state": "OFF"
    },
    {
      "time": 1672837223242,
      "state": "OFF"
    },
    {
      "time": 1672837288783,
      "state": "OFF"
    },
    {
      "time": 1672837288783,
      "state": "OFF"
    },
    {
      "time": 1672837360183,
      "state": "OFF"
    },
    {
      "time": 1672837360183,
      "state": "OFF"
    },
    {
      "time": 1672837427396,
      "state": "OFF"
    },
    {
      "time": 1672837427396,
      "state": "ON"
    },
    {
      "time": 1672837510439,
      "state": "ON"
    },
    {
      "time": 1672837510439,
      "state": "ON"
    },
    {
      "time": 1672837510444,
      "state": "ON"
    },
    {
      "time": 1672837510444,
      "state": "ON"
    },
    {
      "time": 1672837511135,
      "state": "ON"
    },
    {
      "time": 1672837511135,
      "state": "ON"
    },
    {
      "time": 1672837552563,
      "state": "ON"
    },
    {
      "time": 1672837552563,
      "state": "ON"
    },
    {
      "time": 1672837604329,
      "state": "ON"
    },
    {
      "time": 1672837604329,
      "state": "OFF"
    },
    {
      "time": 1672837648324,
      "state": "OFF"
    },
    {
      "time": 1672837648324,
      "state": "OFF"
    }
  ]
}
```

I will close this issue here because it does not occur in the latest release and open a new one for the duplicate values.

**Comment by florian-h05** [comment] 2023-01-04 13:29
Issue for the duplicate datapoint is #14152.

**Closed by florian-h05** 2023-01-04 13:29 UTC
