### ISSUE TITLE
[Linky] binding not updating everyday

### ISSUE THREAD

**Issue by Tukks** [openhab/openhab-addons#9313] opened 2020-12-09 21:35 UTC
## Expected Behavior
Linky binding doesn't autoupdate automaticly, I need to deactivate and reactivate things to pull data and update my channel.

## Possible Solution
Auto pull update to have last day consumption updated everyday

## Context

openHAB 3.0.0
Build #2050

## Your Environment
Ubuntu server

**Comment by lolodomo** [comment] 2020-12-11 07:36
@clinique : I can confirm, this morning my values are identical to yesterday evening. 

@Tukks : did you enable the DEBUG logs to see what happens?

**Comment by lolodomo** [comment] 2020-12-12 10:05
I enabled DEBUG logs last evening and this morning I see absolutely no log entries. The refrsh scheduling is apparently broken.

**Comment by lolodomo** [comment] 2020-12-12 11:15
It could also be a problem with the cache handling.

**Comment by lolodomo** [comment] 2020-12-12 12:05
Refresh scheduling triggered every 6 hours looks good to me in the code.
I have added logs. Will see what happens tomorrow morning.
I am suspecting a problem with the cache.

**Comment by lolodomo** [comment] 2020-12-12 12:36
One thing to mention, I see no catching of Gson exception in the code.

**Comment by lolodomo** [comment] 2020-12-12 12:50
And I have more or less in mind that in my initial implementation of the dayly cache, the cache was sometimes invalidated, probably when the API call was failing. I don't see anymore this in the new code.

**Comment by lolodomo** [comment] 2020-12-12 13:01
Looking at the old code, I can see:
```
        LinkyConsumptionData result = cachedDaylyData.getValue();
        if (result != null && result.success()) {
...
        } else {
            cachedDaylyData.invalidateValue();
        }
```
Cache value no more invalidated could be the cause of the issue.

**Comment by clinique** [comment] 2020-12-12 13:35
@lolodomo : sorry, I let you dig this issue, I'm consumed by the Netatmo binding revamp.

**Comment by lolodomo** [comment] 2020-12-12 13:48
Ok. I hope I can reach the conclusion tomorrow.

**Comment by lolodomo** [comment] 2020-12-13 07:59
I got an exception at 5am:
```
2020-12-13 05:00:33.715 [DEBUG] [.linky.internal.handler.LinkyHandler] - updateData
2020-12-13 05:00:33.719 [DEBUG] [.linky.internal.handler.LinkyHandler] - updateDailyData
2020-12-13 05:00:33.726 [DEBUG] [.linky.internal.api.ExpiringDayCache] - getValue from cache "daily cache" is requiring a fresh value
2020-12-13 05:00:33.730 [DEBUG] [.linky.internal.handler.LinkyHandler] - cachedDailyData refresh
2020-12-13 05:00:33.734 [DEBUG] [.linky.internal.handler.LinkyHandler] - getConsumptionData from 2020-11-28 to 2020-12-13
2020-12-13 05:00:33.738 [DEBUG] [.linky.internal.handler.LinkyHandler] - Calling api.getEnergyData
2020-12-13 05:00:34.190 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:888) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[?:?]
        at com.google.gson.Gson.fromJson(Gson.java:774) ~[?:?]
        at org.openhab.binding.linky.internal.api.EnedisHttpApi.getMeasures(EnedisHttpApi.java:226) ~[?:?]
        at org.openhab.binding.linky.internal.api.EnedisHttpApi.getEnergyData(EnedisHttpApi.java:231) ~[?:?]
        at org.openhab.binding.linky.internal.handler.LinkyHandler.getConsumptionData(LinkyHandler.java:346) ~[?:?]
        at org.openhab.binding.linky.internal.handler.LinkyHandler.lambda$0(LinkyHandler.java:95) ~[?:?]
        at org.openhab.binding.linky.internal.api.ExpiringDayCache.refreshValue(ExpiringDayCache.java:104) ~[?:?]
        at org.openhab.binding.linky.internal.api.ExpiringDayCache.getValue(ExpiringDayCache.java:73) ~[?:?]
        at org.openhab.binding.linky.internal.handler.LinkyHandler.updateDailyData(LinkyHandler.java:204) ~[?:?]
        at org.openhab.binding.linky.internal.handler.LinkyHandler.updateData(LinkyHandler.java:183) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[?:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[?:?]
        ... 18 more
```
As I suspected, we have an uncaught exception. I will see if the refresh is run again at 11am or not.

**Comment by lolodomo** [comment] 2020-12-13 10:39
As I guessed, not catching the exception was leading to stop the refresh scheduling.

I have now handle Json parsing exception so if the refresh fails at 5am, it should run again at 11am, 5pm ... until it succeeds to get and parse data.

What remains to understand is why it fails at 5am. Apparently, the API request is returning code 200 but the Json has not the format we expect. I will have to wait for a next failure, probably tomorrow morning. I am now logging the Json data when the parsing fails.

**Comment by Tukks** [comment] 2020-12-13 10:50
@lolodomo thanks for your analysis
I'm not currently home, so I can't enable debug log.

**Comment by lolodomo** [comment] 2020-12-13 10:55
Regarding the cache management, I finally found nothing wrong, it looks good to me. If data can't be retrieved, null is put in cache and at next get, it will trigger a new refresh if the value is null or expired.

The only remaining problem is the parsing of the returned data early in the morning.

**Comment by lolodomo** [comment] 2020-12-14 08:10
I finally got more inputs. The API is in fact returning a HTML page asking you to push a button to continue. The page apparently mentions that "Since your browser does not support JavaScript, you must press the Continue button once to proceed..". The form contains a hidden field named "SAMLRequest" containing encrypted data.

I will see if the behaviour is the same at 11am but I guess it will.

@clinique: any idea ?

Maybe we should authenticate at each time we need to refresh data ?

**Comment by lolodomo** [comment] 2020-12-14 08:48
In fact, after few hours, we are probably logged out. I think we have to implement a re log.

**Comment by clinique** [comment] 2020-12-14 09:04
> 
> 
> In fact, after few hours, we are probably logged out. I think we have to implement a re log.

Yes, I think we could log in at each update, as it's a daily update, it's not a big overhead. This could also explain the issue you pointed with the three step unlog process (that could fail if the binding is seen as unlogged by the web service).

**Comment by lolodomo** [comment] 2020-12-14 19:47
The problem should be fixed now. I will confirm tomorrow morning but I am very confident ;)

**Comment by lolodomo** [comment] 2020-12-15 07:43
The refresh works this morning.

Well, now, we have another problem, I will create a different issuye.

**Closed** 2020-12-15 21:38 UTC
