### ISSUE TITLE
[sonos] Spotify playlist not restarted after notification sound (Spotify free account)

### ISSUE THREAD

**Issue by mlommers** [openhab/openhab-addons#6668] opened 2019-12-23 09:42 UTC
Using 2.5.0 M4
When a spotify playlist is playing and notification sound kicks in the spotify playlist is not restarted. This functionality is working for Tune in Radio, here the radio is restarted after the notification sound, but unfortunatily this doesn't happen with spotify

in a openhab rule I use:  playSound("sonos:PLAY5:room","doorbell.mp3")

**Comment by lolodomo** [comment] 2019-12-27 09:54
Is your playlist just started from the Sonos App ?

**Comment by mlommers** [comment] 2019-12-27 13:57
> Is your playlist just started from the Sonos App ?

Sonos or Spotify itself, in both cases the playlist is not restarted.

**Comment by lolodomo** [comment] 2019-12-29 10:23
I just tested several times the rule and it is working perfectly for me, the playlist is resumed as expected after the door bell is listened.
My playlist was first started from the Sonos app.

You are testing with what Sonos device ? Without a group ?

**Comment by mlommers** [comment] 2019-12-29 11:05
Upgraded to release 2.5. Still facing the same issue. I have a PLAY5 and a ONE gen2. Both same issue. I dont use a group. 

Could it be because we are using the free spotify version? The playlist is then always in shuffle mode

**Comment by lolodomo** [comment] 2019-12-29 11:22
I just tested with the shuffle mode and it still looks good.
I have a Spotify paying account so maybe your free version of Spotify is the source of the problem.

**Comment by lolodomo** [comment] 2019-12-29 11:37
I just discovered is that if the playlist is started from Spotify App (on my phone) and casted to the Sonos, then after the notification this is not this playlist which is resumed but the last playlist run from the Sonos app.
This is of course a different issue but I should investiguate it.

All that to tell you that you should rather do your tests using the Sonos app.

**Comment by mlommers** [comment] 2019-12-29 11:55
I was using the sonos app to play the playlist, but not succesfull in resuming the playlist after notification

**Comment by lolodomo** [comment] 2019-12-29 11:58
Ok, your free version of Spotify is probably the issue. There is probably something different in this case which is not yet supported by the binding.

PS: I thought a premium account was rerquired with Sonos.

**Comment by lolodomo** [comment] 2019-12-29 12:09
Ok it is apparently a new feature available since one month.
https://newsroom.spotify.com/2019-11-20/spotify-free-users-you-can-now-stream-music-on-amazon-alexa-sonos-and-bose-speakers/

I just imagine the free account is handled slightly differently by Sonos.

**Comment by mlommers** [comment] 2019-12-29 12:09
Sonos changed this a month ago

**Comment by lolodomo** [comment] 2020-01-04 12:26
Please follow the issue #6684, try the different provided sonos.jar and provide feedback and logs in this issue. You have the instructions for deployment in the issue.
I need to understand what is different when a free Spotify account is sued.

**Comment by lolodomo** [comment] 2020-01-04 18:25
Do you see the content of your playlist in the Sonos App ?
Or is it more like a radio and you see only the current title and you can only use previuous and next buttons to move ?

**Comment by mlommers** [comment] 2020-01-08 20:15
> Do you see the content of your playlist in the Sonos App ?
> Or is it more like a radio and you see only the current title and you can only use previuous and next buttons to move ?

No i dont see the content of the playlist, it is Indeed more like a radio.

**Comment by mlommers** [comment] 2020-01-08 20:17
> Please follow the issue #6684, try the different provided sonos.jar and provide feedback and logs in this issue. You have the instructions for deployment in the issue.
> I need to understand what is different when a free Spotify account is sued.

I Will come back on this later on, need to Find Some time to do the different test. Conclusie of the otter issue is that you cant start a specific playlist, does it still make Sense to do the test?

**Comment by lolodomo** [comment] 2020-01-11 14:29
You can wait for 2.5.1 and then just enable the debug logs to confirm what I guess.

**Comment by mlommers** [comment] 2020-01-11 15:16
ok, will do!

**Comment by schrieveslaach** [comment] 2020-04-11 15:43
I can confirm the issue with Sonos One and Alexa playing radio stations and Spotify (premium).

**Comment by Letrab** [comment] 2020-04-20 07:54
Is it actually an issue coming from Sonos? E.g. could they add the feature with added API/functionality, or is it from cloud providers perspective (Spotify Connect, Alexa, ...)?

**Comment by lolodomo** [comment] 2020-04-20 09:13
@schrieveslaach : you are off topic as this issue is about the usage of a Spotify free account.

@Letrab : with a Spotify free account, the technical way a playlist is rendered on the Sonos is apparently different. It is possible that I just miss the knowledge how to restore such playlist after a notification, or it could be a wish by cloud providers to be the only ones to start such playlist.

**Comment by lolodomo** [comment] 2021-07-03 11:00
I just tested again with a free account.
When playing a playlist, the URI looks like `x-rincon-queue:RINCON_XXXXXXXXXX1400#vli` .
So makes sense why the playlist is not restored after the notification (case not covered by the binding). I can try to restore this URI but I am almost sure that it will not work. My feeling would be that this kind of URI cannot be broken and then restored.

**Comment by lolodomo** [comment] 2021-07-03 11:47
Even if I try to update the code to restore the URI `x-rincon-queue:RINCON_XXXXXXXXXX1400#vli` with its associated metadata, as I unfortunately expected, it does not work.

**Comment by lolodomo** [comment] 2021-07-03 12:05
I see this "new" service: urn:upnp-org:serviceId:VirtualLineIn
This would certainly require more reverse engineering to understand how all this is working.

**Comment by lolodomo** [comment] 2021-08-01 15:06
As noone is able to find a solution, I close the issue. My personal feeling is that it is just not possible.

**Closed by lolodomo** 2021-08-01 15:06 UTC
