### ISSUE TITLE
[IPCamera] binding does not generate an error for incorrectly specified camera type.

### ISSUE THREAD

**Issue by definable** [openhab/openhab-addons#8618] opened 2020-09-30 17:44 UTC
When an unknown camera type is specified using textual configuration, the 
binding silently starts, but does not work.  No log messages are generated, so it is not clear what is wrong.  

## Expected Behavior
Error log message indicating an unknown camera type. 

## Current Behavior
Nothing happens. Binding is reported as started.  Can be started and stopped via the CLI interface without errors. 

## Steps to Reproduce (for Bugs)
Configure Thing with "Thing ipcamera:daha:001" instead of "Thing ipcamera:dah**u**a:001" 

## Your Environment
Openhab 2.5.9 Docker image on Ubuntu 18.04LTS.

**Comment by Skinah** [comment] 2020-11-01 00:15
I have looked at a number of other bindings and they also do not log when a user does a typo in textual configuration on the thing type ID. The move I see in V3 is that textual config is an advanced method, and those people that choose this should understand a typo will cause issues. Whilst I think it is a good idea to do this when a breaking change is done (like just recently) to help users out, I don't like the idea of it in the code long term if it is not considered 'the norm' for all bindings to do this. If there was an easy way to mark a change to be removed after X amount of time, it would then be simple to do.

I'll leave this open so maintainers can comment if I am wrong.

**Comment by Skinah** [comment] 2021-01-10 00:46
Closing as this is not a bug and no comments in more than 3 months, see previous reply why no change will be made unless this is discussed by maintainers.

**Closed by Skinah** 2021-01-10 00:46 UTC
