### ISSUE TITLE
[MCP23017] binding non funzionante su Openhab 3

### ISSUE THREAD

**Issue by pin32** [openhab/openhab-addons#14280] opened 2023-01-26 16:27 UTC
MCP23017 still doesn't work on Openhab3 even pi4j has been updated (11.0.16).

The MCp2017 binding is successfully initialized with all its elements

in the Paper UI it shows the association is online, but in the logs you can see incoming errors saying:
java.lang.NullPointerException: null

at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionPin although the same configuration on OH 2 works fine.
no test

I got no replies on the telegram group

## Current Behavior
I installed the binding for managing the mcp23017 chip (breakbord), the same is configured almost completely automatically and goes online, but the communication channels remain "null".
I updated java 11.0.16 and pi4j to version 1.4 but nothing changes. furthermore the items are automatically placed as contacts and not as switches in the part relating to the outputs. openhab version is 3.41

in the logs I have no errors related to binding. it seems that this is completely ignored by openhab

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by Hilbrand** [comment] 2023-01-26 19:58
Duplicate of #11253

**Closed by Hilbrand** 2023-01-26 19:58 UTC
Labels: duplicate

**Comment by pin32** [comment] 2023-01-26 22:52
I don't know if the problem is fixable or not...
