### ISSUE TITLE
[samsungtv] Binding does not work properly with UE55H6290

### ISSUE THREAD

**Issue by otbe** [openhab/openhab-addons#1216] opened 2016-09-03 13:47 UTC
Hi everyone,

I try to use the samsungtv binding with my UE55H6290 and it works for some features. For example: I can control volume and the mute button, but I cant send arbitrary keyCodes. I try to send `KEY_CHUP` and  `KEY_CHDOWN` commands.

My samsung.items file:

```
String SAMSUNG_TV_KEYCODE (gSAMSUNG_TV) {channel="samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0:keyCode"}
```

Log output when sending `KEY_CHUP` via iOS App:

```
==> /var/log/openhab2/openhab.log <==
2016-09-03 15:29:37.140 [ERROR] [rnal.service.RemoteControllerService] - Could not send command to device on 192.168.1.147:55000: org.openhab.binding.samsungtv.internal.protocol.RemoteControllerException: Connection failed

==> /var/log/openhab2/events.log <==
2016-09-03 15:29:37.154 [ItemCommandEvent          ] - Item 'SAMSUNG_TV_KEYCODE' received command KEY_CHUP
```

If I try to send this code through PaperUI (via control) the log message is a bit different:

```
==> /var/log/openhab2/openhab.log <==
2016-09-03 15:32:18.976 [WARN ] [g.samsungtv.handler.SamsungTvHandler] - Channel 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0:keyCode' not supported

==> /var/log/openhab2/events.log <==
2016-09-03 15:32:18.981 [ItemCommandEvent          ] - Item 'SAMSUNG_TV_KEYCODE' received command KEY_CHDOWN
```

I tried already `keycode` vs `keyCode` as channel name, but nothing works so far :/

I run one of the latest snapshot builds of OH2.

Any advices?

Thank your very much for your great work!
##

**Comment by paulianttila** [comment] 2016-09-04 08:30
H model doesn't support remote control emulation protocol. This is also the reason why you see "not supported" error message when you try to control via Paper UI. 

Nowadays OH support also dynamic channels, but this is not yet supported by the Samsung TV binding. All channels are "available", but only services which are discovered via upnp from the tv are really supported.

**Comment by otbe** [comment] 2016-09-04 08:39
Thanks for your answer @paulianttila !

It would be interesting to know how [miTifi](https://itunes.apple.com/de/app/mytifi-fernbedienung-fur-samsung/id441912305?mt=8) solves this problem. This app allows me to control nearly everything: Timeshift, Input Source, Channels, Volume etc

**Comment by paulianttila** [comment] 2016-09-04 10:08
@otbe if you enable debug logs for Samsung TV binding, you should see which UPnP services TV offers. Do you see something related to dial multiscreen?

Most probably miTifi use dial multiscreen protocol to control device. Maybe there is some kind of extension to control TV as well and miTifi have reverse engineered that.

Here you can find some discussion about it http://forum.samygo.tv/viewtopic.php?f=74&t=7707

Protocol specifications (also some test code in github) are also available http://www.dial-multiscreen.org.

**Comment by otbe** [comment] 2016-09-10 11:12
Hi,

sorry for the late response had some busy days :/
I enabled debug mode for samsungtv binding and all what I get is:
```
2016-09-10 13:10:21.305 [DEBUG] [covery.SamsungTvDiscoveryParticipant] - Discovered a Samsung TV '[TV]Samsung LED55' model 'UE55H6200' thing with UDN '08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:21.308 [DEBUG] [covery.SamsungTvDiscoveryParticipant] - Created a DiscoveryResult for device 'UE55H6200' with UDN '08f0d182-0096-1000-82d5-bc1485183cf0'
2016-09-10 13:10:21.310 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - thingDiscovered: DiscoveryResult [thingUID=samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0, properties={hostName=192.168.1.147}, flag=NEW, label=[TV]Samsung LED55, bridgeUID=null, ttl=-1, timestamp=1473505821307]
2016-09-10 13:10:21.312 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - thingDiscovered, thingUID=samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0, discoveredUID=samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0
2016-09-10 13:10:21.314 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Check and create missing UPnP services
2016-09-10 13:10:21.316 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] -  modelName=UE55H6200, udn=068e7781-006e-1000-bbbf-bc1485183cf0, type=RemoteControlReceiver
2016-09-10 13:10:21.317 [DEBUG] [rnal.service.RemoteControllerService] - Create a Samsung TV RemoteController service
2016-09-10 13:10:21.338 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] -  modelName=UE55H6200, udn=068e7782-006e-1000-bbbf-bc1485183cf0, type=dialreceiver
2016-09-10 13:10:21.339 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] -  modelName=UE55H6200, udn=08f0d182-0096-1000-82d5-bc1485183cf0, type=MediaRenderer
2016-09-10 13:10:21.341 [DEBUG] [nternal.service.MediaRendererService] - Create a Samsung TV MediaRenderer service
2016-09-10 13:10:21.343 [DEBUG] [nternal.service.MediaRendererService] - Start refresh task, interval=1000
2016-09-10 13:10:21.351 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] -  modelName=UE55H6200, udn=07bfa480-0082-1000-817d-bc1485183cf0, type=MainTVServer2
2016-09-10 13:10:21.365 [DEBUG] [internal.service.MainTVServerService] - Create a Samsung TV MainTVServer service
2016-09-10 13:10:21.367 [DEBUG] [internal.service.MainTVServerService] - Start refresh task, interval=1000
2016-09-10 13:10:21.506 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'volume':'9' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:21.692 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'mute':'OFF' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:21.838 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'brightness':'45' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:21.983 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'contrast':'100' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:22.127 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'sharpness':'50' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:25.875 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'channel':'181' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:26.081 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'sourceId':'0' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
2016-09-10 13:10:26.084 [DEBUG] [g.samsungtv.handler.SamsungTvHandler] - Received value 'sourceName':'TV' for thing 'samsungtv:tv:08f0d182_0096_1000_82d5_bc1485183cf0'
```

**Comment by Barnecke** [comment] 2018-01-01 19:53
@otbe I found this post today and I'm currently started with OH2 and my samsung TV (UE55HU6900).
Therefore I'm interested how you get some TV functions with your H model working?
Everything I found is, that newer models (since H series) are not working yet, but you post, that you can control some functions.

**Comment by Lemlin** [comment] 2018-01-13 13:18
> I try to use the samsungtv binding with my UE55H6290 and it works for some features. For example: I can control volume and the mute button, but I cant send arbitrary keyCodes.

I can confirm that. That's exactly what I figured out with my Samsung UE55H6270 TV too.

@Barnecke I installed the Samsung TV binding from @paulianttila , switched my TV an and searched for the device. That's all, TV appeared in the openHAB Inbox.

Unfortunately I still don't know how to change anything else, like for example channels. :/

**Comment by SunSeaAndPalms** [comment] 2018-04-04 18:39
I am also facing the same issue. The only think I can add is that I thinkg it was working with some prior version, but I don't remember the exact binding version. I can mess things up, but I believe it was in the days of OH1.

**Comment by Cossey** [comment] 2019-01-04 22:00
Newer Samsung TVs don’t support much over the UPnP interface except volume and mute controls. Newer TVs use web sockets/secure web sockets for remote control/power on/off. There’s a pull request currently waiting approval that adds support for web sockets for the add-on but if you have a newer TV with the latest firmware update like mine then you will need to wait for someone to add in **secure** web socket support. 

I would suggest you check out pull request 4169 and see if you can test the add-on arjanmels has done and give him some feedback on how it works for you (make sure you include your model no. and release year), he’s linked to a couple of versions of the add on he’s built with web sockets support.

**Comment by J-N-K** [comment] 2019-08-05 18:28
Is this solved after the samsungtv updates have been merged?

**Comment by tnemrap** [comment] 2019-12-18 18:02
No not for H models.

**Comment by Cossey** [comment] 2019-12-19 10:23
Whilst the updates now make the binding more useful for 2017/2018/2019 models there's still some issues with getting Power On/Off working reliably which I hope to improve in the next 3 weeks. Overall Samsung seemed to have dropped the ball on the IP control side of things with the later model TVs 👎 Remote Control protocol had to be reversed engineered by a group of people working on the samsungctl app, reduced features - no way to send Notifications to the TV, no way to list the TV channels. Mind you this may still actually be possible, but its all undocumented so it'll only be by shear luck if someone discovers this functionality.

**Comment by hmerk** [comment] 2021-07-24 19:45
closed due to inactivity.

**Closed by hmerk** 2021-07-24 19:45 UTC
