### ISSUE TITLE
[shelly] Missing channel at Shelly addon (Reed Contact)

### ISSUE THREAD

**Issue by xvs03** [openhab/openhab-addons#11970] opened 2022-01-05 20:21 UTC
If you connect a reed contact to the Shelly add-on, no channel is provided for the switch in the binding. Shelly explicitly allows this configuration, for example, for garage door switching and also offers a traffic jam icon with an open and closed door.
The Shelly app is configured for this too.

The solution to connect the reed contact to the switch input is not a clean solution!

The topic is discussed in many forums. In some cases, solutions are presented that can be very dangerous and also do not solve the problem of the missing channel.

## Your Environment
openHABIAN 3.2.0 with current Shelly Binding on RaspberryPI

**Comment by markus7017** [comment] 2022-03-02 19:51
@xvs03 any update, otherwise I need to close the issue

**Comment by xvs03** [comment] 2022-03-02 21:50
Hi Markus. There are no new updates from me. You can close this issue.

**Closed** 2022-11-14 22:30 UTC
Labels: work in progress

**Comment by anste** [comment] 2025-07-07 19:21
I think the problem is still current, so I'll post the requested information here.

Settings of Shelly 1 with temp addon as reed contact (reversed in my case):
`"ext_switch_enable":true,"ext_switch_reverse":true,"ext_switch":{"0":{"relay_num":-1}}`

Status with closed contact (closed door):
`"ext_switch":{"0":{"input":0}}`

Status with open contact (when the door is open):
`"ext_switch":{"0":{"input":1}}`

I didn't work through all the code but I think the relay_num "-1" could lead to the channel not appearing. This index has to match the relay index, but only one relay with index 0 exists.

ShellyChannelDefinitions.addAddonChannels:
```
boolean addon = profile.settings.extSwitch != null && profile.settings.extSwitch.input0 != null
        && idx == getInteger(profile.settings.extSwitch.input0.relayNum);
```

**Comment by jlaur** [comment] 2025-07-07 19:42
> I think the problem is still current, so I'll post the requested information here.

This issue was closed in 2022, can you please create a new issue and provide needed information by going through the template? For example, version number, Shelly device etc.
