### ISSUE TITLE
[evcc] "Ladedauer" and "Verbleibende Ladedauer" not working

### ISSUE THREAD

**Issue by Dasch2380** [openhab/openhab-addons#17432] opened 2024-09-17 13:22 UTC
The Values of Ladedauer and verbleibende Ladedauer are always showing 0.0

## Expected Behavior
should show correct minute values

## Current Behavior
Both values are always 0.0
![grafik](https://github.com/user-attachments/assets/ee09ad67-9861-4ccc-8bf2-413bb3bafcf7)
![grafik](https://github.com/user-attachments/assets/642c3322-bc09-43cc-a567-7686b4303942)

## Your Environment
OH4.3.0M1

**Comment by lsiepel** [comment] 2024-09-17 18:58
If you but the binding in debug mode you might get some usefull data that helps troubleshooting. It might also help if you share some of your thing / channel / item configuration. Did it work before?

**Comment by Dasch2380** [comment] 2024-09-25 13:33
Yes, it worked an few updates ago. Cannot say which version was last functional.
I will put the binding in debug mode and see what happens on next loading of vehicle.

**Comment by Dasch2380** [comment] 2024-09-25 14:15
Just plugged the car.
In debug log there are no infos just
2024-09-25 16:13:11.260 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Running refresh job ...
2024-09-25 16:13:11.263 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 loadpoints on site Fliederweg.
2024-09-25 16:13:11.263 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 vehicles on site Fliederweg.
2024-09-25 16:13:26.270 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Running refresh job ...
2024-09-25 16:13:26.273 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 loadpoints on site Fliederweg.
2024-09-25 16:13:26.274 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 vehicles on site Fliederweg.
2024-09-25 16:13:41.286 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Running refresh job ...
2024-09-25 16:13:41.288 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 loadpoints on site Fliederweg.
2024-09-25 16:13:41.288 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 vehicles on site Fliederweg.
2024-09-25 16:13:56.292 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Running refresh job ...
2024-09-25 16:13:56.295 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 loadpoints on site Fliederweg.
2024-09-25 16:13:56.295 [DEBUG] [ab.binding.evcc.internal.EvccHandler] - Found 1 vehicles on site Fliederweg.

**Comment by lsiepel** [comment] 2024-09-26 20:13
Sorry, if you put the loggin into trace, we would also see the json data that is received. 
When having a brief look at the code i could not discover an obvious reason this somewhat strange values.

**Comment by Dasch2380** [comment] 2024-09-27 18:42
Sure
![grafik](https://github.com/user-attachments/assets/b41e20fa-6f7a-4aa1-af00-00b648036224)

**Comment by Dasch2380** [comment] 2024-09-28 07:53
Did a Trace. Will this help?

2024-09-28 09:51:29.699 [TRACE] [ab.binding.evcc.internal.api.EvccAPI] - GET http://openhab:7070/api/state - {"result":{"auth":{},"battery":[{"power":59,"energy":3865.6130000000003,"soc":42,"controllable":true}],"batteryCapacity":0,"batteryDischargeControl":false,"batteryEnergy":3865.613,"batteryGridChargeActive":false,"batteryMode":"unknown","batteryPower":59,"batterySoc":42,"bufferSoc":95,"bufferStartSoc":0,"currency":"EUR","fatal":null,"greenShareHome":1,"greenShareLoadpoints":1,"gridConfigured":true,"gridCurrents":[6.455,-2.982,-3.33],"gridEnergy":34312.8,"gridPower":-0.9,"gridPowers":[1296,-586.1,-710.9000000000001],"homePower":51.751,"influx":{"url":"","database":"","org":"","user":""},"interval":10,"loadpoints":[{"chargeCurrent":9,"chargeCurrents":[9.423999786,0,0],"chargeDuration":60,"chargePower":2087.349,"chargeRemainingDuration":51837,"chargeRemainingEnergy":30056,"chargeTotalImport":2300.978,"chargedEnergy":44,"chargerFeatureHeating":false,"chargerFeatureIntegratedDevice":false,"chargerIcon":null,"chargerPhases1p3p":true,"chargerPhysicalPhases":null,"chargerStatusReason":"unknown","charging":true,"connected":true,"connectedDuration":0,"disableThreshold":0,"effectiveLimitSoc":90,"effectiveMaxCurrent":32,"effectiveMinCurrent":6,"effectivePlanSoc":0,"effectivePlanTime":null,"effectivePriority":0,"enableThreshold":0,"enabled":true,"limitEnergy":0,"limitSoc":0,"maxCurrent":32,"minCurrent":6,"mode":"pv","phaseAction":"inactive","phaseRemaining":0,"phasesActive":1,"phasesConfigured":0,"phasesEnabled":1,"planEnergy":0,"planOverrun":0,"planProjectedEnd":null,"planProjectedStart":null,"planTime":null,"priority":0,"pvAction":"inactive","pvRemaining":0,"sessionCo2PerKWh":null,"sessionEnergy":44,"sessionPrice":0.004,"sessionPricePerKWh":0.096,"sessionSolarPercentage":94.769,"smartCostActive":false,"smartCostLimit":-0.05,"smartCostNextStart":null,"title":"Carport","vehicleClimaterActive":null,"vehicleDetectionActive":false,"vehicleLimitSoc":100,"vehicleName":"kia-ev6","vehicleOdometer":11296.9,"vehicleRange":190,"vehicleSoc":55.051,"vehicleWelcomeActive":false}],"maxGridSupplyWhileBatteryCharging":0,"mqtt":{"broker":"","topic":"evcc","user":"","clientID":"","insecure":false},"network":{"schema":"http","host":"evcc.local","port":7070},"prioritySoc":20,"pv":[{"power":846,"energy":49605.342},{"power":248,"energy":3913.459},{"power":987,"energy":15380.095000000001}],"pvEnergy":68898.896,"pvPower":2081,"residualPower":50,"siteTitle":"Fliederweg","smartCostType":"priceforecast","sponsor":{"name":"DieITDienstleister","expiresAt":"2026-04-16T11:47:17Z"},"statistics":{"30d":{"avgCo2":0,"avgPrice":0.1011280614502207,"chargedKWh":199.32100000000037,"solarPercentage":91.75495134670987},"365d":{"avgCo2":0,"avgPrice":0.11309385564615211,"chargedKWh":2267.1542544588146,"solarPercentage":81.04170917494491},"thisYear":{"avgCo2":0,"avgPrice":0.11277086684316237,"chargedKWh":2174.186260184395,"solarPercentage":84.35486159650472},"total":{"avgCo2":0,"avgPrice":0.11309385564615211,"chargedKWh":2267.1542544588146,"solarPercentage":81.04170917494491}},"tariffFeedIn":0.09,"tariffGrid":0.211,"tariffPriceHome":0.09,"tariffPriceLoadpoints":0.09,"vehicles":{"kia-ev6":{"title":"Kia EV6","icon":"car","capacity":77.4,"minSoc":20,"limitSoc":90}},"version":"0.130.12"}}

**Comment by lsiepel** [comment] 2024-09-28 08:38
=> chargeRemainingDuration:51837
Do you know the value of the channel at about the same time the json was posted? 

I can work with these values and tryu to troubleshoot further

**Comment by MikeTheTux** [comment] 2024-10-08 17:02
The issue is a duplicate of https://github.com/openhab/openhab-addons/issues/17485 and will be fixed via https://github.com/openhab/openhab-addons/pull/17528.

**Closed** 2024-10-08 19:08 UTC
