### ISSUE TITLE
[oppo] issue with verbose mode after mains power on

### ISSUE THREAD

**Issue by Koala887** [openhab/openhab-addons#10282] opened 2021-03-05 19:36 UTC
I have tried the binding with my oppo 105 and a TCP serial bridge.
When i connect the player to the mains power, it starts with the default verbose mode 0.
So the binding discards all response messages because the player does not send the command code back.
The binding should first set the verbose mode to 2 after the connect. This also works when it is switched off.

**Comment by mlobstein** [comment] 2021-03-09 06:29
The bug should be fixed. I attached a test jar to the PR if you want to try it.

**Comment by mlobstein** [comment] 2021-04-02 02:24
@Koala887 are you able to test the changes to verify the issue is fixed? The updated binding code is now available in 3.1.0 M3 also.

**Comment by Koala887** [comment] 2021-04-02 08:41
Sorry i‘m still on 2.5, so i had to compile the binding first. It works as expected, but I've made a few small changes. I already set the verbose mode in scheduleReconnectJob() and removed the query commands because they don‘t geht an answer.

**Comment by mlobstein** [comment] 2021-04-02 15:21
Can you share your code or do an additional PR?

**Comment by mlobstein** [comment] 2022-03-04 04:49
fixed in #10306, closing issue

**Closed by mlobstein** 2022-03-04 04:49 UTC
