### ISSUE TITLE
[sonos] Playlist forgotten after notification sound (Beam with integrated alexa-function)

### ISSUE THREAD

**Issue by Erni2019** [openhab/openhab-addons#6684] opened 2019-12-25 13:49 UTC
Hello, I’m using openhab 2.5 and have a problem with SONOS Beam with integrated alexa-function. If I call up playlists via Alexa, they will not continue after the notification sound. If I use tuneIn via Alexa it works. I use the Alexa function in the beam. Unfortunately, the problem persists even after the update to 2.5. Does anyone have a solution?

Thanks a lot!

**Comment by Hilbrand** [comment] 2019-12-25 13:58
This sounds like the same problem as #6668

**Comment by lolodomo** [comment] 2019-12-27 09:34
This issue seems to be related to Alexa while the other does not mention it. 
I think I fixed a problem few weeks ago but I don't remember if it was when using Alexa or Google. Will have to search.

**Comment by lolodomo** [comment] 2019-12-27 09:53
I don"t own any Alexa products, I can't guess the problems if they are not declared. This is for "the problem persists...".

My recent change was relative to notification when the source was the TV, so not the same thing.

I provided a fix just one year ago which was relative to notification when the source was tune-in radio requested from Amazon Alexa. Problem with Spotify from Amazon Alexa never came to me. Without any Alexa device, this will require that someone reproduces the problem using a binding version with additional debug logs so that I can understand what is different when the playlist is started from Alexa.

**Comment by lolodomo** [comment] 2019-12-27 10:04
Maybe the integrated Alexa function in Beam is even different from the request from external Alexa devices.

**Comment by lolodomo** [comment] 2019-12-27 10:11
@Erni2019 : have you the skill to deploy a new jar in replacement of your current binding, enabling DEBUG logs and then reports the logs ?

**Comment by Erni2019** [comment] 2019-12-28 09:09
Hello lolodomo, thanks for the tip, but I'm not that fit with openhab. Could someone do that who is more familiar with openhab? 
Should I post the appropriate lines from the Log Viewer?
Thank you

**Comment by lolodomo** [comment] 2019-12-29 10:42
Did you first open a topic in the forum ? We could find help there.

**Comment by lolodomo** [comment] 2019-12-29 10:48
One thing you could do easily and that may give me a hint is to link the 2 channels named currenttrackuri and currenttransporturi and then show me their values when you start the playlist from the Beam Alexa feature.
You can look at the log viewer to see all the state changes for these channels.

**Comment by Erni2019** [comment] 2019-12-30 21:00
Hallo lolodomo, 
I went through the scenarios and compiled the log in the pdf. Can you do something with it or do you need it in another format? Thank you for your help.
[20191230 Sonos Beam Notification mit uri english 2.pdf](https://github.com/openhab/openhab-addons/files/4011004/20191230.Sonos.Beam.Notification.mit.uri.english.2.pdf)

**Comment by lolodomo** [comment] 2019-12-31 07:42
Ok I understand why the resume is not working. spotify through Alexa is not using the standard queue. 
I can try a fix but I don't know if it will work. It could require you or someone else testing a jar file I will build.

**Comment by Erni2019** [comment] 2019-12-31 09:13
Super thank you!! 
But I don't use spotify but the normal playlist from Amazon Prime Music.

**Comment by lolodomo** [comment] 2019-12-31 12:16
Ah ok.
When you start this playlist from the Sonos App, is there a problem with the notification ?

**Comment by Erni2019** [comment] 2019-12-31 17:00
no, it works when starting via the Sonos app

**Comment by lolodomo** [comment] 2019-12-31 17:08
Here is a first change for testing.
[sonos.zip](https://github.com/openhab/openhab-addons/files/4013130/sonos.zip)
To deploy this jar:

1. Unzip the file and put it on your server for example in /home/openhab/sonos.jar
2. Connectr to the console of the openHAB server
3. Run this command to get the id of the Sonos bundle: bundle:list -s | grep sonos
4. Run this command to update the binding replacing XXX by the id retrieved just before: bundle:update XXX file:///home/openhab/sonos.jar
5. Run again this command to check that the Sonos bundle was updated and is active: bundle:list -s | grep sonos
6. Enable the DEBUG logs: log:set DEBUG org.openhab.binding.sonos
7. Try again and tell me how it works now. New logs are starting with handleSharedQueue.

**Comment by Erni2019** [comment] 2020-01-01 16:35
helo lolodomo, I installed jar file there. Unfortunately there is no change. Playlist via integrated Alexa does not play a title after notification sound. Playlist via Sonos app works. 

However, if a playlist was started via the Sonos app and I then call up a playlist via integrated Alexa, then after the notification sound, the title from the playlist that was previously started via the Sonos app is played. That was apparently saved. But that was already the case before the new jar file. 

Do you have another idea?

Thank you

**Comment by lolodomo** [comment] 2020-01-02 12:38
Just to be sure, can you try again and show the logs containing handleSharedQueue. 

My feeling is that we are on a similar problem as with playlist started from Spotify app. 

I will then try something else.

**Comment by Erni2019** [comment] 2020-01-02 17:40
helo lolodomo, 
I like doing that. can you please tell me how to create logs with handleSharedQueue? I searched for it but couldn't find anything.
Thank you.

**Comment by lolodomo** [comment] 2020-01-03 08:15
You should find them if you ran the step 6 and if you successfully deployed the new jar file.

**Comment by Erni2019** [comment] 2020-01-03 08:52
helo lolodomo, ok i'm just seeing that there is more in the log now than before. I'll do the test right away and send you the logs. The jar file is active, see screenshot.
[sonos jar file.pdf](https://github.com/openhab/openhab-addons/files/4018545/sonos.jar.file.pdf)

**Comment by Erni2019** [comment] 2020-01-03 09:22
hello lolodomo, attached the logs. the file "playlist with integrated alexa.txt" is the scenario where after the nothification sound there is no playback. I am looking forward to your new proposal :-)
[TV.txt](https://github.com/openhab/openhab-addons/files/4018616/TV.txt)
[playlist with integrated alexa.txt](https://github.com/openhab/openhab-addons/files/4018617/playlist.with.integrated.alexa.txt)
[playlist with sonos app.txt](https://github.com/openhab/openhab-addons/files/4018618/playlist.with.sonos.app.txt)
[tuneIn.txt](https://github.com/openhab/openhab-addons/files/4018619/tuneIn.txt)

**Comment by lolodomo** [comment] 2020-01-04 10:45
Ok you are now a master in binding deployment.

I can try few different things but I have not THE solution. The problem is how to restore the queue list built by Alexa feature which is not the common queue list. Maybe I just need to provide the expected metadata, or maybe it is just not possible to restore it without re-building it.
One option I should investigate too is to insert the notification sound in the current queue list but I am not sure the Sonos API allows that.
I have the feeling that the problem I see with playlist started from Spotify App and casted to Sonos is very similar to the problem with integrated Alexa feature. If I find a solution for one problem, it could solve the other one too.

**Comment by lolodomo** [comment] 2020-01-04 11:56
Please try again with this new jar:  [sonos.zip](https://github.com/openhab/openhab-addons/files/4021862/sonos.zip)
In this version, I try to restore queue URI with metadata rather than just queue URI.

I am now interested by the log entries containing handleSharedQueue or setCurrentURI

**Comment by Erni2019** [comment] 2020-01-04 15:10
Hello lolo domo, the mistake remains. There is a difference with tuneIn. After the notification sound, the title is played from the beginning, not where the interruption was. Advertising is then also played.

[tuneIn.txt](https://github.com/openhab/openhab-addons/files/4022049/tuneIn.txt)
[playlist with integrated alexa.txt](https://github.com/openhab/openhab-addons/files/4022050/playlist.with.integrated.alexa.txt)
[playlist with sonos app.txt](https://github.com/openhab/openhab-addons/files/4022051/playlist.with.sonos.app.txt)
[sonos jar2.pdf](https://github.com/openhab/openhab-addons/files/4022052/sonos.jar2.pdf)

**Comment by lolodomo** [comment] 2020-01-04 15:28
Are you telling me that your playlist is now restored after the notification ? That would be already a first great (and almost miraculous) improvment ?

**Comment by lolodomo** [comment] 2020-01-04 15:30
In what cases advertising is played generally with Amazon Prime Music ?

**Comment by lolodomo** [comment] 2020-01-04 15:48
It looks like we are facing what they called a cloud queue.

**Comment by lolodomo** [comment] 2020-01-04 17:54
New version that did not try to set the track number:  [sonos.zip](https://github.com/openhab/openhab-addons/files/4022245/sonos.zip)
I just need the logs with Alexxa feature.

**Comment by Erni2019** [comment] 2020-01-04 19:04
Hello lolodomo, no, unfortunately the amazon-playlist was not continued when using the internal Alexa. 
When playing tuneIn via Alexa, the title was started again after the notification sound and an advertising block was also played, which always comes at the start of a station at tuneIn, at least at "Ballermanradio"

**Comment by Erni2019** [comment] 2020-01-05 10:03
Hello lolodomo, there is another scenario which I would like to describe, since it may help with the solution. This behavior occurs with all SONOS bindings:
1. I start an amazon prime playlist (1) with the Sonos app.b otification is played and playlist (1) continues.
2. I start another amazon prime playlist (2) via the integrated Alexa function. After the notification has been played, the playlist (1) is played.

**Comment by lolodomo** [comment] 2020-01-05 11:25
Yes, I discovered that and that is what I described in issue #6703 
In fact, all recent opened issues are I think the same, I don't know how to restart a playlist which was started by an external app, being Alexa, Google home or Spotify App.
Unfortunately, I have to give up.
I will at least provide a fix to avoid resuming a wrong playlist.

**Comment by lolodomo** [comment] 2020-01-05 12:11
@Erni2019 : please update your messages to erase your logs (I saved one), there may be ids of your Amazon Prime account inside.

**Comment by lolodomo** [comment] 2020-01-05 12:15
A new sonos.jar is provided in PR #6765 avoiding the resume of a wrong playlist after a notification.

**Comment by lolodomo** [comment] 2020-01-06 15:14
Please keep this issue opened.

**Comment by Erni2019** [comment] 2020-01-07 14:35
ok.
How can i exit debug mode (log:set DEBUG org.openhab.binding.sonos) ?

**Comment by Hilbrand** [comment] 2020-01-07 14:42
`log:set DEFAULT org.openhab.binding.sonos`

**Comment by lolodomo** [comment] 2021-08-01 15:05
As noone is able to find a solution, I close the issue. My personal feeling is that it is just not possible.

**Closed by lolodomo** 2021-08-01 15:05 UTC
