### ISSUE TITLE
[boschshc] Upgrade to REST API version 3.2

### ISSUE THREAD

**Issue by david-pace** [openhab/openhab-addons#15053] opened 2023-06-06 20:26 UTC
Today Bosch announced that in July the Smart Home Controllers will receive an update which does not support REST API version `2.x` anymore (https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/80).

This means that we have to update the openHAB binding because we currently use API version `2.1`.

**Comment by GerdZanker** [comment] 2023-06-08 15:21
The REST API will be updated in about one month and could break existing functionality.
Is there a way to provide a change for the released openhab v3.4.x bindings to fix things sooner?
A usual pull request is merged to main and therefore to 4.0.0-SNAPSHOT as far as I know.

**Comment by jlaur** [comment] 2023-06-08 21:08
> Is there a way to provide a change for the released openhab v3.4.x bindings to fix things sooner?

We can cherry-pick the commit into the 3.4.x branch after the PR branch is merged into main.

**Closed** 2023-06-11 15:52 UTC

**Comment by david-pace** [comment] 2023-06-11 21:35
@jlaur can you please point in into the right direction about how to cherry-pick this commit onto the `3.4.x` branch? I can currently only see branches for `3.0.x`, `3.1.x` and `3.2.x` on the origin side.

**Comment by jlaur** [comment] 2023-06-12 06:03
> @jlaur can you please point me into the right direction about how to cherry-pick this commit onto the `3.4.x` branch? I can currently only see branches for `3.0.x`, `3.1.x` and `3.2.x` on the origin side.

Only maintainers can do this. I'll try to remember to do this when I'm home from work today. Feel free to ping me if I fail. 🙂

**Comment by jlaur** [comment] 2023-07-11 19:21
@kaikreuzer - we have another broken binding, this time not caused by cloud services, but a firmware upgrade. There is a fix cherry-picked into 3.4.x. I'm not sure how much is needed to trigger a hotfix?

**Comment by kaikreuzer** [comment] 2023-07-12 19:26
Let's say we definitely do a 3.4 patch release still in July and check what other issues we might want to backport as well, so that it becomes valuable for more people than boschshc users.

**Comment by jlaur** [comment] 2023-07-12 19:36
> Let's say we definitely do a 3.4 patch release still in July and check what other issues we might want to backport as well, so that it becomes valuable for more people than boschshc users.

Agreed. There will also be a backport of #15187.
