### ISSUE TITLE
[hue] Default settings wrong

### ISSUE THREAD

**Issue by KenkiCK** [openhab/openhab-addons#14020] opened 2022-12-20 07:08 UTC
After upgrade from 3.3 stable to 3.4 stable, the HUE binding was set to HTTPS and the port to 80.  Bridge was offline and shows an error.  After changing Port to 443 it works. 

Not sure if it is here the right place - if not please shift.

best
Christian

**Comment by lolodomo** [comment] 2022-12-21 08:16
Probably your thing has the port parameter set to 80. Maybe you set it in the past? 
If this parameter was not set, the binding will automatically consider either 80 or 443 depending on the protocol parameter.

**Comment by lolodomo** [comment] 2022-12-21 11:11
Looking at the old discovery code (<=3.3), the port parameter was set by the discovery. So if you approved your hue bridge from the inbox in OH 3.3 or before, it explains why you had a port parameter set.

**Comment by lolodomo** [comment] 2022-12-21 11:13
The new discovery code is not setting the port. 

I believe this issue can now be closed.

**Comment by KenkiCK** [comment] 2022-12-21 15:21
Thanks for checking and solve.
bests and a great christmas time
Christian

**Comment by andkopp** [comment] 2022-12-29 17:04
I updated from 3.3 to 3.4 today and had the same issue. Maybe the issue is not resolved yet.

**Comment by lolodomo** [comment] 2022-12-29 17:29
> I updated from 3.3 to 3.4 today and had the same issue. Maybe the issue is not resolved yet.

There is nothing we can do as the port parameter was already set (to 80) in your thing, either by the (old) discovery code or by you.

If something is done, it could be to ignore the port parameter if it is set to 80 and the protocol parameter is HTTPS so that the port 443 would be rather considered.

**Comment by lolodomo** [comment] 2022-12-30 16:02
Let's reopen this issue as a lot of users could be concerned. 
The problem is a conflict between port parameter previously set to 80 by the old discovery code and the new protocol parameter which is httos by default. @cweitkamp : any idea what should be done.

**Comment by cweitkamp** [comment] 2022-12-30 19:38
I can understand the situation is not very nice. But I have no clue how it can be handled better like we do it now. The handler is OFFLINE, showing a COMMUNICATION_ERROR with message "HTTPS secure connection failed. Please check your configuration settings (network address, protocol, port, type of certificate) and change protocol to http when using a V1 bridge."

**Comment by cweitkamp** [comment] 2022-12-30 19:47
Maybe we should add a notice to the update list to remind the Hue binding users HTTPS is default protocol for now and everyone should check their Hue Bridge configured for their own sake.

**Comment by jlaur** [comment] 2022-12-30 20:16
I agree with @cweitkamp, we can't solve this in code at this point.

> If something is done, it could be to ignore the port parameter if it is set to 80 and the protocol parameter is HTTPS so that the port 443 would be rather considered.

This would introduce a quite obscure and hidden problem that it would no longer be possible to configure HTTPS to use port 80.

**Comment by lolodomo** [comment] 2023-01-01 10:23
I agree the thing status in UI is clear. 

> Maybe we should add a notice to the update list to remind the Hue binding users HTTPS is default protocol for now and everyone should check their Hue Bridge configured for their own sake.

Yes, no alert was inserted, probably because you expected a transparent change except for v1 bridge users. 
An alert could be added in the release notes, even if it will be read probably by only a small part of users.

**Comment by lolodomo** [comment] 2023-01-29 16:01
@kaikreuzer : my intention was to update the 3.4.0 release notes but the page is apparently not updatable ?
https://github.com/openhab/openhab-distro/releases/tag/3.4.0
Or should I update that page ?
https://github.com/openhab/openhab-distro/wiki/openHAB-3.4-Release-Notes

**Comment by lolodomo** [comment] 2023-07-24 07:05
I believe we can close this issue now.

**Closed by lolodomo** 2023-07-24 07:05 UTC
