### ISSUE TITLE
[bluetooth.bluegiga] BlueGiga SerialHandler thread stops after some days

### ISSUE THREAD

**Issue by pfink** [openhab/openhab-addons#9215] opened 2020-12-03 23:02 UTC
BlueGiga binding completely stops working after some days (no BLE events are passed anymore, no devices are discovered, ..). Restart or removing & re-adding the BlueGiga adapter solves the issue.

@paulianttila @cpmeister Maybe you could help? I already did comprehensive analysis (see below), but I don't really get further...

## Issue analysis / Observations in the log

Generally, no error or warning messages are thrown in the log that are correlating with the occurance of this issue. So I enabled debug log level for all bluetooth stuff: `log4j2.logger.org_openhab_binding_bluetooth.level = DEBUG`.

As long as the BlueGiga binding is working fine, log is constantly throwing BlueGiga framing errors (debug level) in the log, e.g.

```
2020-11-25 22:15:23.237 [DEBUG] [egiga.internal.BlueGigaSerialHandler] - BlueGiga framing error byte 1 = 156
2020-11-25 22:15:23.239 [DEBUG] [egiga.internal.BlueGigaSerialHandler] - BlueGiga framing error byte 1 = 36
2020-11-25 22:15:23.241 [DEBUG] [egiga.internal.BlueGigaSerialHandler] - BlueGiga framing error byte 1 = 182
```

Also, as long as it is working, new devices are discovered from time to time, e.g.:

```
2020-11-25 22:15:37.403 [DEBUG] [uegiga.handler.BlueGigaBridgeHandler] - BlueGiga adding new device to adaptor 88:6B:0F:A2:AE:74: 3E:80:F7:78:9C:DA
2020-11-25 22:15:37.405 [DEBUG] [oth.bluegiga.BlueGigaBluetoothDevice] - Creating new BlueGiga device 3E:80:F7:78:9C:DA
2020-11-25 22:15:37.527 [DEBUG] [uegiga.handler.BlueGigaBridgeHandler] - BlueGiga adding new device to adaptor 88:6B:0F:A2:AE:74: 54:67:B1:1A:1C:45
2020-11-25 22:15:37.530 [DEBUG] [oth.bluegiga.BlueGigaBluetoothDevice] - Creating new BlueGiga device 54:67:B1:1A:1C:45

```

Suddenly, after some days, it stops to work and above log messages are not thrown anymore. Instead, the only message that is still thrown is `Refreshing Bluetooth device list...`. At the exact time where above log messages are stopping, debug message **BLE length larger than 64 bytes (66)** is thrown. This message does only occur this one time, otherwise I cannot find it within the log:

```
2020-11-25 22:15:53.183 [DEBUG] [egiga.internal.BlueGigaSerialHandler] - BlueGiga framing error byte 1 = 120
2020-11-25 22:15:53.185 [DEBUG] [egiga.internal.BlueGigaSerialHandler] - BlueGiga framing error byte 1 = 247
2020-11-25 22:15:53.187 [DEBUG] [egiga.internal.BlueGigaSerialHandler] - BLE length larger than 64 bytes (66)
------------------- assumed time where it stops to work ------------------- 
2020-11-25 22:15:58.979 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:16:08.981 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:16:18.983 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:16:28.985 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:16:38.987 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:16:48.990 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:16:58.992 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
2020-11-25 22:17:08.994 [DEBUG] [tooth.AbstractBluetoothBridgeHandler] - Refreshing Bluetooth device list...
```

Full log attached: [openhab.log.zip](https://github.com/openhab/openhab-addons/files/5639406/openhab.log.zip)

Attaching debugger to the [relevant while loop of  BlueGigaSerialHandler](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java#L249) after the binding stopped working does not get any hits, so the while loop / thread seems to be stopped. Anyhow, no exception is thrown, also the end message of the loop ("BlueGiga BLE exited.") is not thrown.

Sometimes, it seems to be that erroneous array operations do lead to instant failure without any exception handling, I also observed a similar behavior on a past issue: https://github.com/openhab/openhab-addons/issues/6465#issuecomment-565828353 Anyhow, I'm not sure if that is the case here.

## Possible Solution

No idea from my side, unfortunately :(

## Steps to Reproduce

Unclear. Issue suddenly occurs after some days of operation, I'm not aware of any correlation with a user action.

## Your Environment

* Version used: 2.5.10
* Environment name and version: Raspbian, Java HotSpot 1.8.0_201

**Comment by cpmeister** [comment] 2020-12-03 23:14
The input stream might be blocking for whatever reason. Can you try running `sudo dmesg` on your rpi to see if any low level errors have occurred?

**Comment by pfink** [comment] 2020-12-03 23:18
Output of `dmesg` attached. BlueGiga is running on `ttyACM0`.

[dmesg.txt](https://github.com/openhab/openhab-addons/files/5639555/dmesg.txt)

**Comment by cpmeister** [comment] 2020-12-03 23:26
I don't see anything wrong from your dmesg either.

But after looking at the code it seems entirely possible that the reader thread might be stuck in a busy look if the input stream returns -1 (which means the end of stream was reached). This is definitely a circumstance in which a new input stream should be acquired.

If there had been an error on the thread, it would have been logged, so my best guess is that the thread is stuck in a busy loop. I'll see what I can do to fix that.

**Comment by cpmeister** [comment] 2020-12-03 23:30
This might be related to another issue that I've encountered where my openhab will crash if I pull out the BlueGiga dongle while it is running. Hopefully if I fix that it should also fix your issue as well.

**Comment by pfink** [comment] 2020-12-03 23:33
Mhm, in the thread dump, no thread named "BlueGigaBLEHandler" is there....

[threads.txt](https://github.com/openhab/openhab-addons/files/5639653/threads.txt)

**Comment by cpmeister** [comment] 2020-12-03 23:37
Why are there so many telnet threads in that dump? I'll add that to my list of things to look into...

**Comment by pfink** [comment] 2020-12-03 23:39
Not sure if they are related to BlueGiga, they could come from the HEOS binding.

**Comment by cpmeister** [comment] 2020-12-03 23:42
I know they aren't related to the BlueGiga bindings, but thanks for pointing out the binding that is the likely culprit though, makes finding it easier 😄 .

But the fact that the thread somehow died without leaving a trace is very concerning. That means that the thread isn't stuck in a busy loop and somehow disappeared from existence instead. Only way to fix that would be to monitor the thread and recreate it if it dies.

**Comment by pfink** [comment] 2020-12-03 23:47
One remark: I have a symlink ttyBLUEGIGA ->ttyACM0, could that make problems? I just wanted to remove and re-add the BlueGiga adapter and noticed that as soon as I use ttyBLUEGIGA, config change is not applied. ttyACM0 works. Anyhow, ttyBLUEGIGA also worked in the past....

**Comment by cpmeister** [comment] 2020-12-03 23:47
That shouldn't make a difference that I'm aware of...

**Comment by cpmeister** [comment] 2020-12-04 01:11
Actually, I just realized. You are still using the 2.5.10 version of the binding. That version doesn't have any exception handler for sudden thread death. I'm betting that this bug is either fixed in the latest version or at the very least will have the exception logged.

**Comment by pfink** [comment] 2020-12-04 06:29
Ah, okay. Didn't see any changes related to that, otherwise I would have updated in advance.

Did update to OH3 now, will keep you posted.

**Comment by paulianttila** [comment] 2020-12-05 08:39
I quickly checked the master and I think this error situation is not correctly handled there either.

If frame length > 64, I think handler should start to find new frame rather than pass that as BlueGiga spec says that max frame length is 64. 

https://github.com/openhab/openhab-addons/blob/b8bc0203488d976cd03b93e660bd1398ac8d16d5/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java#L278-L284

Now, it just ignores oversized frame and wait that all bytes are received and then tries to get bluetooth response packet from received bytes which now probably fails as we can't see any other log messages from Patrick log.

https://github.com/openhab/openhab-addons/blob/b8bc0203488d976cd03b93e660bd1398ac8d16d5/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java#L285-L299


IOExeption is handled correctly. Handler notifies upper level which will eventually restart serial handler. But any other exceptions than IOExeption cause thread termination.

https://github.com/openhab/openhab-addons/blob/b8bc0203488d976cd03b93e660bd1398ac8d16d5/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java#L301-L309

There is uncaught exception handler, but it doesn't do anything else than log

https://github.com/openhab/openhab-addons/blob/b8bc0203488d976cd03b93e660bd1398ac8d16d5/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaSerialHandler.java#L68-L70

**Comment by paulianttila** [comment] 2020-12-05 09:10
I made a quick fix proposal, but if you @cpmeister have better fix in mind, please go-ahead :blush: I don't have much time to spent on this right now, but I think this should be fixed before OH3 is released. 

https://github.com/openhab/openhab-addons/compare/main...paulianttila:bluegiga-serial-handler-fix

It's really shame that BlueGiga protocol doesn't have any kind of frame checksum :disappointed:

**Comment by cpmeister** [comment] 2020-12-07 05:21
@paulianttila I think you might be on to something with your fix. I'll submit one of my own that includes some of the more important changes you are suggesting. But I would like to see the exception that is causing this bug before I start trying to guess what the problem is.  The UncaughtExceptionHandler was only added a couple of weeks ago, so you won't see any error in the logs in the 2.5.10 version of the binding since it wasn't present in that version of the code.

**Comment by paulianttila** [comment] 2020-12-07 09:35
Response packet instance is done by the hash from couple bytes and bits from the header.

https://github.com/openhab/openhab-addons/blob/d0480d0f2e4d6e31d326c355ece8a291a66b40f0/bundles/org.openhab.binding.bluetooth.bluegiga/src/main/java/org/openhab/binding/bluetooth/bluegiga/internal/BlueGigaResponsePackets.java#L183-L206

So I guess illegal packet received where length was over 64 bytes match one of the response packets hash and binding tries to instantiate wrong response packet which parsing will fail.

**Comment by pfink** [comment] 2020-12-18 06:11
FTR: It did not occur anymore yet on openHAB 3 yet. Anyhow, I updated frequently in the past weeks, so openHAB was restarted multiple times.

**Closed** 2022-05-03 22:06 UTC
