### ISSUE TITLE
[nanoleaf] OH3 build#2158. WARN log every minute

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-addons#9930] opened 2021-01-23 21:35 UTC
The WARN entries in the log started as soon as I added the panel item.
With only the controller, it was silent.

## Expected Behavior
No WARNings logged
## Current Behavior

Issue 1:
INFO->TRACE @ 22:07:14.883
```
2021-01-23 21:51:14.627 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:52:14.656 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:53:14.671 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:54:14.685 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:55:14.699 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:56:14.715 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:57:14.733 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:58:14.748 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 21:59:14.763 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:00:14.784 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:01:14.798 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:02:14.812 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:03:14.833 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:04:14.849 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:05:14.867 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:06:14.881 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back


2021-01-23 22:07:14.883 [DEBUG] [al.handler.NanoleafControllerHandler] - Run update job
2021-01-23 22:07:14.883 [DEBUG] [al.handler.NanoleafControllerHandler] - Update channels for controller nanoleaf:controller:741ADCF0C4B8
2021-01-23 22:07:14.884 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - RequestBuilder: Sending Request 192.168.1.12:16021 /api/v1/yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP/
2021-01-23 22:07:14.885 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - Sending Request http://192.168.1.12:16021/api/v1/yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP/ no query parameters
2021-01-23 22:07:14.886 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - Request method:GET uri:http://192.168.1.12:16021/api/v1/yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP/ params{}

2021-01-23 22:07:14.895 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - API response from Nanoleaf controller: {"name":"Canvas 7FFE","serialNo":"S19104C1315","manufacturer":"Nanoleaf","firmwareVersion":"1.6.4","hardwareVersion":"2.0-4","model":"NL29","cloudHash":{},"discovery":{},"effects":{"effectsList":["Christmas Lights","Color Burst","Falling Whites","Fireworks","Flames","Forest","Inner Peace","Lofi Xmas Day Vibes","Meteor Shower","Nemo","Northern Lights","Paint Splatter","Pulse Pop Beats","Radial Sound Bar","Rhythmic Northern Lights","Romantic","Sound Bar","Streaking Notes","Vintage Modern","Xmas"],"select":"*Solid*"},"firmwareUpgrade":{},"panelLayout":{"globalOrientation":{"value":0,"max":360,"min":0},"layout":{"numPanels":102,"sideLength":100,"positionData":[{"panelId":43566,"x":3300,"y":0,"o":0,"shapeType":3},{"panelId":17053,"x":3200,"y":0,"o":0,"shapeType":2},{"panelId":25091,"x":3100,"y":0,"o":0,"shapeType":2},{"panelId":46141,"x":3000,"y":0,"o":0,"shapeType":2},{"panelId":57575,"x":2900,"y":0,"o":0,"shapeType":2},{"panelId":32679,"x":2800,"y":0,"o":270,"shapeType":2},{"panelId":30347,"x":2700,"y":0,"o":270,"shapeType":2},{"panelId":10785,"x":2600,"y":0,"o":270,"shapeType":2},{"panelId":35565,"x":2500,"y":0,"o":270,"shapeType":2},{"panelId":47484,"x":2400,"y":0,"o":360,"shapeType":2},{"panelId":43000,"x":2300,"y":0,"o":630,"shapeType":2},{"panelId":21486,"x":2200,"y":0,"o":720,"shapeType":2},{"panelId":42995,"x":2100,"y":0,"o":990,"shapeType":2},{"panelId":61260,"x":2000,"y":0,"o":1080,"shapeType":2},{"panelId":23501,"x":1900,"y":0,"o":1350,"shapeType":2},{"panelId":42426,"x":1800,"y":0,"o":1440,"shapeType":2},{"panelId":53974,"x":1700,"y":0,"o":1710,"shapeType":2},{"panelId":35688,"x":1600,"y":0,"o":1710,"shapeType":2},{"panelId":13670,"x":1500,"y":0,"o":1710,"shapeType":2},{"panelId":9251,"x":1400,"y":0,"o":1710,"shapeType":2},{"panelId":62838,"x":1300,"y":0,"o":1710,"shapeType":2},{"panelId":54720,"x":1200,"y":0,"o":1710,"shapeType":2},{"panelId":31158,"x":1100,"y":0,"o":1710,"shapeType":2},{"panelId":43093,"x":1000,"y":0,"o":1800,"shapeType":2},{"panelId":17238,"x":900,"y":0,"o":2070,"shapeType":2},{"panelId":58857,"x":800,"y":0,"o":2070,"shapeType":2},{"panelId":49508,"x":700,"y":0,"o":2070,"shapeType":2},{"panelId":45041,"x":600,"y":0,"o":2070,"shapeType":2},{"panelId":41739,"x":500,"y":0,"o":2070,"shapeType":2},{"panelId":58698,"x":400,"y":0,"o":2070,"shapeType":2},{"panelId":10787,"x":300,"y":0,"o":2070,"shapeType":2},{"panelId":21504,"x":200,"y":0,"o":2070,"shapeType":2},{"panelId":7856,"x":100,"y":0,"o":2070,"shapeType":2},{"panelId":6575,"x":0,"y":0,"o":2160,"shapeType":2},{"panelId":41929,"x":0,"y":100,"o":2250,"shapeType":2},{"panelId":42633,"x":0,"y":200,"o":2520,"shapeType":2},{"panelId":40220,"x":100,"y":100,"o":2340,"shapeType":2},{"panelId":11875,"x":100,"y":200,"o":2340,"shapeType":2},{"panelId":14699,"x":200,"y":100,"o":2340,"shapeType":2},{"panelId":56142,"x":200,"y":200,"o":2340,"shapeType":2},{"panelId":40625,"x":300,"y":100,"o":2340,"shapeType":2},{"panelId":9276,"x":300,"y":200,"o":2340,"shapeType":2},{"panelId":4240,"x":400,"y":100,"o":2070,"shapeType":2},{"panelId":38037,"x":400,"y":200,"o":2070,"shapeType":2},{"panelId":54642,"x":500,"y":100,"o":2070,"shapeType":2},{"panelId":4147,"x":500,"y":200,"o":2070,"shapeType":2},{"panelId":6833,"x":600,"y":100,"o":2070,"shapeType":2},{"panelId":42490,"x":600,"y":200,"o":2340,"shapeType":2},{"panelId":41961,"x":700,"y":100,"o":2070,"shapeType":2},{"panelId":60924,"x":700,"y":200,"o":2340,"shapeType":2},{"panelId":16813,"x":800,"y":100,"o":2070,"shapeType":2},{"panelId":26663,"x":800,"y":200,"o":2340,"shapeType":2},{"panelId":31345,"x":900,"y":100,"o":2070,"shapeType":2},{"panelId":54375,"x":900,"y":200,"o":2070,"shapeType":2},{"panelId":36187,"x":1000,"y":100,"o":1800,"shapeType":2},{"panelId":26950,"x":1000,"y":200,"o":1800,"shapeType":2},{"panelId":37066,"x":1100,"y":100,"o":1980,"shapeType":2},{"panelId":3654,"x":1100,"y":200,"o":2070,"shapeType":2},{"panelId":7864,"x":1200,"y":100,"o":1710,"shapeType":2},{"panelId":15692,"x":1200,"y":200,"o":1980,"shapeType":2},{"panelId":1084,"x":1300,"y":100,"o":1710,"shapeType":2},{"panelId":2881,"x":1300,"y":200,"o":1980,"shapeType":2},{"panelId":40473,"x":1400,"y":100,"o":1710,"shapeType":2},{"panelId":55338,"x":1400,"y":200,"o":1980,"shapeType":2},{"panelId":64602,"x":1500,"y":100,"o":1710,"shapeType":2},{"panelId":31676,"x":1500,"y":200,"o":1980,"shapeType":2},{"panelId":40943,"x":1600,"y":100,"o":1980,"shapeType":2},{"panelId":9959,"x":1600,"y":200,"o":2070,"shapeType":2},{"panelId":40192,"x":1700,"y":100,"o":1710,"shapeType":2},{"panelId":62884,"x":1700,"y":200,"o":1710,"shapeType":2},{"panelId":15141,"x":1800,"y":100,"o":1440,"shapeType":2},{"panelId":22092,"x":1800,"y":200,"o":1530,"shapeType":2},{"panelId":20017,"x":1900,"y":100,"o":1350,"shapeType":2},{"panelId":38949,"x":1900,"y":200,"o":1620,"shapeType":2},{"panelId":62611,"x":2000,"y":100,"o":1080,"shapeType":2},{"panelId":40391,"x":2000,"y":200,"o":1080,"shapeType":2},{"panelId":58786,"x":2100,"y":100,"o":1260,"shapeType":2},{"panelId":19268,"x":2100,"y":200,"o":1260,"shapeType":2},{"panelId":52542,"x":2200,"y":100,"o":810,"shapeType":2},{"panelId":31010,"x":2200,"y":200,"o":810,"shapeType":2},{"panelId":45556,"x":2300,"y":100,"o":900,"shapeType":2},{"panelId":23072,"x":2300,"y":200,"o":990,"shapeType":2},{"panelId":57126,"x":2400,"y":100,"o":360,"shapeType":2},{"panelId":47347,"x":2400,"y":200,"o":450,"shapeType":2},{"panelId":34500,"x":2500,"y":100,"o":540,"shapeType":2},{"panelId":15535,"x":2500,"y":200,"o":630,"shapeType":2},{"panelId":42505,"x":2600,"y":100,"o":270,"shapeType":2},{"panelId":63234,"x":2600,"y":200,"o":270,"shapeType":2},{"panelId":26217,"x":2700,"y":100,"o":540,"shapeType":2},{"panelId":18766,"x":2700,"y":200,"o":630,"shapeType":2},{"panelId":41120,"x":2800,"y":100,"o":270,"shapeType":2},{"panelId":46502,"x":2800,"y":200,"o":540,"shapeType":2},{"panelId":55692,"x":2900,"y":100,"o":0,"shapeType":2},{"panelId":39617,"x":2900,"y":200,"o":0,"shapeType":2},{"panelId":11882,"x":3000,"y":100,"o":0,"shapeType":2},{"panelId":28885,"x":3000,"y":200,"o":0,"shapeType":2},{"panelId":46666,"x":3100,"y":100,"o":90,"shapeType":2},{"panelId":36112,"x":3100,"y":200,"o":90,"shapeType":2},{"panelId":62503,"x":3200,"y":100,"o":0,"shapeType":2},{"panelId":12437,"x":3200,"y":200,"o":0,"shapeType":2},{"panelId":42794,"x":3300,"y":100,"o":90,"shapeType":2},{"panelId":37716,"x":3300,"y":200,"o":360,"shapeType":2}]}},"schedules":{},"state":{"brightness":{"value":25,"max":100,"min":0},"colorMode":"hs","ct":{"value":5000,"max":6500,"min":1200},"hue":{"value":28,"max":360,"min":0},"on":{"value":true},"sat":{"value":20,"max":100,"min":0}}}
2021-01-23 22:07:14.896 [DEBUG] [nding.nanoleaf.internal.OpenAPIUtils] - API response code: 200
2021-01-23 22:07:14.902 [DEBUG] [al.handler.NanoleafControllerHandler] - Set to device type canvas
2021-01-23 22:07:14.904 [TRACE] [al.handler.NanoleafControllerHandler] - Configuration property: key deviceType value canvas
2021-01-23 22:07:14.905 [TRACE] [al.handler.NanoleafControllerHandler] - Configuration property: key address value 192.168.1.12
2021-01-23 22:07:14.905 [TRACE] [al.handler.NanoleafControllerHandler] - Configuration property: key port value 16021
2021-01-23 22:07:14.905 [TRACE] [al.handler.NanoleafControllerHandler] - Configuration property: key refreshInterval value 60
2021-01-23 22:07:14.905 [TRACE] [al.handler.NanoleafControllerHandler] - Configuration property: key authToken value yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP
2021-01-23 22:07:14.906 [DEBUG] [al.handler.NanoleafControllerHandler] - Thing property:  key serialNumber value S19104C1315
2021-01-23 22:07:14.906 [DEBUG] [al.handler.NanoleafControllerHandler] - Thing property:  key firmwareVersion value 1.6.4
2021-01-23 22:07:14.906 [DEBUG] [al.handler.NanoleafControllerHandler] - Thing property:  key modelId value NL29
2021-01-23 22:07:14.907 [DEBUG] [al.handler.NanoleafControllerHandler] - Thing property:  key vendor value Nanoleaf
2021-01-23 22:07:14.907 [DEBUG] [al.handler.NanoleafControllerHandler] - Update color channel for panel nanoleaf:lightpanel:741ADCF0C4B8:42426
2021-01-23 22:07:14.907 [DEBUG] [nternal.handler.NanoleafPanelHandler] - Sending Request from Panel for getColor()
2021-01-23 22:07:14.907 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - RequestBuilder: Sending Request 192.168.1.12:16021 /api/v1/yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP/effects
2021-01-23 22:07:14.908 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - Sending Request http://192.168.1.12:16021/api/v1/yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP/effects no query parameters
2021-01-23 22:07:14.908 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - Request method:PUT uri:http://192.168.1.12:16021/api/v1/yKF27VapNrVWDvPL9KnlGNqkAZkCt5NP/effects params{}

2021-01-23 22:07:14.909 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - Content {"write":{"command":"request","animType":"","animName":"*Static*","palette":[],"colorType":"","animData":"","loop":false}}
2021-01-23 22:07:14.912 [TRACE] [nding.nanoleaf.internal.OpenAPIUtils] - API response from Nanoleaf controller:
2021-01-23 22:07:14.913 [DEBUG] [nding.nanoleaf.internal.OpenAPIUtils] - API response code: 404
2021-01-23 22:07:14.913 [WARN ] [nternal.handler.NanoleafPanelHandler] - Panel data could not be retrieved as no data was returned (static type missing?) : OpenAPI request did not get any result back
2021-01-23 22:07:14.913 [TRACE] [nternal.handler.NanoleafPanelHandler] - updatePanelColorChannel: panelColor: null
2021-01-23 22:07:14.914 [DEBUG] [al.handler.NanoleafControllerHandler] - Starting TouchJob for Panel nanoleaf:controller:741ADCF0C4B8


```
2 items added by MAIN UI:
![image](https://user-images.githubusercontent.com/28068256/105614278-b49d9280-5dc8-11eb-9916-7cad63bfe5d0.png)
![image](https://user-images.githubusercontent.com/28068256/105614293-c7b06280-5dc8-11eb-9c88-b49488e0defa.png)

```
(The 101 other panels still in Inbox.)

Group:Switch canvasPanelSingleTap
Switch panel42426SingleTap  (canvasPanelSingleTap) { channel = "nanoleaf:lightpanel:741ADCF0C4B8:42426:singleTap" }
Switch panel42426DoubleTap  (canvasPanelDoubleTap) { channel = "nanoleaf:lightpanel:741ADCF0C4B8:42426:doubleTap" }

```

## Context
These could perhaps be issues caused by 102 panels?

## Your Environment
OH3 build 2158
openhab> list | grep -i nano
233 │ Active │  80 │ 3.1.0.202101210334      │ openHAB Add-ons :: Bundles :: Nanoleaf Binding
x64 system running on Ubuntu 18.04LTS

**Comment by stefan-hoehn** [comment] 2021-01-27 09:48
Yep, I am aware of it. Basically this is happening when the binding tries to retrieve the color of a specific panel and a 404 (not found) is returned by the nanoleaf controller device. I was told by Nanoleaf some time ago that the reason is that a color can only be retrieved in case a so called "static" pattern has been chosen by the user (my guess is that dynamic changes on animated patterns change too fast for retrieving colors). The downside is that the color in this case cannot be retrieved which leads to the fact that a user may think the binding is broken as it does return the correct color. Therefore I had added this warning as a hint why the color cannot be retrieved as I haven't found an easy way to check if the mode is static currently at the moment.
Anyway, in the meantime I noticed that this more often than wanted floods the logs with this "hint". So, finally I have decided to move that message to the debug" level and add a note to the Readme, so user will know that color retrieval only works on static mode. The change will be part of the next binding update on OH3 (note that a backport to OH 2.5 is not planned).

**Comment by olemr** [comment] 2021-01-27 09:58
Fine.
FYI, I've set a static pattern.
I only use OH to send power ON/OFF and detect tap-gestures. For other settings I use the Nanoleaf App.

![image](https://user-images.githubusercontent.com/28068256/105974789-8a7cf680-608e-11eb-82ae-20afbf2fb170.png)

**Comment by stefan-hoehn** [comment] 2021-01-27 10:19
Weird that you are on static mode. Can you set the binding to TRACE for a small amount of time until at least one of the messages appear and provide the HTTP Request and Response (I would expect a 404 response here) just before the warning?
Also could you send the following request to the controller?

http://nanoleafipaddress:16021/api/v1/aLtuKzpfdQmJ2xxxxxxzqmjjd4EPvVvHyj7HK7/effects

nanoleafipaddress: replace with the IP of the controlloer
aLtuKzpfdQmJ2xxxxxxzqmjjd4EPvVvHyj7HK7 : replace with the secret (I am sure you can see it in the above trace).

This may give us the information if the controller is currently on static which may be an idea to prevent the message at all.

**Comment by olemr** [comment] 2021-01-27 11:32
The TRACE is in the log above. There is indeed a 404 in there.

![image](https://user-images.githubusercontent.com/28068256/105985458-c5395b80-609b-11eb-9c7e-2b7a671fa523.png)

**Comment by olemr** [comment] 2021-01-27 12:10
My brag:
![nano](https://user-images.githubusercontent.com/28068256/105989152-fec09580-60a0-11eb-99f2-036a6ad302a7.jpg)

**Comment by stefan-hoehn** [comment] 2021-01-27 12:17
I get a totally different answer with that request

{
    "version": "2.0",
    "animName": "*Static*",
    "animType": "static",
    "animData": "14 36604 1 255 255 255 0 5 10523 1 255 255 255 0 5 37121 1 255 255 255 0 5 16398 1 255 255 255 0 5 42064 1 255 255 255 0 5 54086 1 255 255 255 0 5 186 1 255 255 255 0 5 60147 1 255 255 255 0 5 33626 1 255 255 255 0 5 45187 1 255 255 255 0 5 39163 1 255 255 255 0 5 3512 1 255 255 255 0 5 61141 1 255 255 255 0 5 19209 1 255 255 255 0 5",
    "palette": [
        {
            "hue": 0,
            "saturation": 0,
            "brightness": 100,
            "probability": 0.0
        }
    ]
}

**Comment by olemr** [comment] 2021-01-27 12:23
Strange. You also have the Canvas right?

**Comment by stefan-hoehn** [comment] 2021-01-27 12:24
Yes, I have several devices for the purpose of the binding maintenance. This is the answer of my canvas.

**Comment by olemr** [comment] 2021-01-27 12:27
Hm, I tried a non *solid* effect just now, and the only thing changing was the last Select: entry.

**Comment by kaikreuzer** [comment] 2021-01-28 19:59
Nice kitchen, @olemr!

FTR, I can confirm and reproduce the issue. Also seeing the warnings even if the mode is static.

Btw, I didn't yet get the tap events to work and also experience a huge CPU load by this binding.

> The change will be part of the next binding update on OH3

@stefan-hoehn Do you already have something in the working there? If so, it would be great if you could already push a WIP PR, so that I could potentially also help on analysis and enhancements.

**Comment by olemr** [comment] 2021-01-28 22:55
> Btw, I didn't yet get the tap events to work and also experience a huge CPU load by this binding.
Tap events from the single panel I have included so far, works fine, with no CPU usage spike noticeable when watching top.
(Double taps turns all panels on/off. I have not yet figured out how to turn that off.)

@kaikreuzer , how many panel items have you included?
I will try including more ans see how that goes.

**Comment by kaikreuzer** [comment] 2021-01-28 22:58
I have only included the panels in my dev environment so far - I have 15 altogether.

**Comment by olemr** [comment] 2021-01-28 23:14
OK, just added 101 more panels, and it went well.
CPU load was high for 10-15s after the bulk add, but settled.
Tap on the linked panel still turns my Z-Wave light on/off through a rule, no CPU spike.
Tapping any of the other panels produced a log entry reveling its ID.

But, the WARN log entry is per panel, so I now get 102 of them once a minute.

**Comment by stefan-hoehn** [comment] 2021-01-29 08:33
> > The change will be part of the next binding update on OH3
> 
> @stefan-hoehn Do you already have something in the working there? If so, it would be great if you could already push a WIP PR, so that I could potentially also help on analysis and enhancements.

Yes, the change is basically as simple as moving it to debug level which I did already. I had hoped I could easily detect the "static" mode by requesting the data as seen above but for some strange reason Ole's canvas seems to respond differently. Maybe I will eventually include that request in spite of that which may not make it worse for some people but helps others.

@kaikreuzer Which type of nanoleaf do you have? 
As mentioned somewhere else I need to detect the type because not all types support touch and I only start the touch handling if I am sure that type supports it. Up to now only NL29 (the first squares and the ones that Ole has) was supported and I will support NL42 (the one that are called "shapes" by Nanoleaf) from now as well.

You can look up the type in the controller's properties like so

![image](https://user-images.githubusercontent.com/5937600/106250821-706d2080-6214-11eb-98c1-32c55da32ed9.png)

The go to the edit mode of the controller and the "nanoleaf device type": it should say "CANVAS" and not "light panel".

Give me the weekend as I would like to do some QA and will push it to my repo and you can help me getting it merged from there.

cheers
Stefan

**Comment by kaikreuzer** [comment] 2021-01-29 19:57
> Which type of nanoleaf do you have?

I have the shapes (hexagon). The Thing property is indeed NL42.
I'll happily wait until after the weekend for your updates :-)

**Comment by lsiepel** [comment] 2023-01-13 22:44
I assume this has been fixed as many [PR’s have merged](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+nanoleaf+in%3Atitle+created%3A%3E2021-01-01), can someone confirm and close this issue?

**Comment by stefan-hoehn** [comment] 2023-01-14 08:47
I agree @lsiepel, this is not an issue anymore from what I know. Thanks for detecting the open issue. @olemr if you think this is still the case pls get in touch with me directly.

**Closed by stefan-hoehn** 2023-01-14 08:47 UTC
