### ISSUE TITLE
[influxdb] getAllStatesBetween returning error 'Cannot format given Object as a Date'

### ISSUE THREAD

**Issue by sascha777** [openhab/openhab-addons#17315] opened 2024-08-23 11:19 UTC
## Context
When I call the getAllStatesBetween function on items that are persisted in influxdb I get an error.
Querying historic states of this item from another persistence service works fine.

see also OpenHAB community:
https://community.openhab.org/t/quering-historic-item-information-from-persistence-service/157330

## Expected Behavior
Getting all items states from the corresponding timerange

## Current Behavior
Getting the error:
> [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'f3dcf456e8' failed: Cannot format given Object as a Date

## Possible Solution
Check function (sorry, I can't due to missing programming knowledge)

## Steps to Reproduce (for Bugs)
1. Set persistence settings for an item (I just tried a switch item) to be persisted in influxdb
2. Set rule to logInfo the historic states with: 
`logInfo(“test”, testitem.getAllStatesBetween(now.minusMinutes(1), now, "influxdb").toString)`
3. Run rule
4. Check log

## Environment
Platform information:
Hardware: Raspberry Pi 4 Model B Rev 1.1, 4GB
OS: Debian GNU/Linux 11 (bullseye)
Java Runtime Environment: openjdk version “17.0.11” 2024-04-16
openHAB version: 4.2.0 (as docker)

**Comment by J-N-K** [comment] 2024-08-24 09:33
I can't reproduce that:

```
var item = items.Bad_temp
var states = item.persistence.getAllStatesBetween(time.ZonedDateTime.now().minusHours(24), time.ZonedDateTime.now().minusHours(12), 'influxdb')
console.log("Bad temp was ", states[0].state, " at ", states[0].timestamp);
```

```
11:32:20.761 [INFO ] [enhab.automation.script.ui.f601845df6] - Bad temp was  23.3125 °C  at  2024-08-23T11:35:00.650+02:00[Europe/Berlin]
```

**Comment by sascha777** [comment] 2024-08-26 21:12
Is that ECMAScript? I am using DSL.

With default persistence
`var states = Xiaomi_Motion_Garage_Bewegung.getAllStatesBetween(now.minusHours(24), now)
logInfo("History was ", states.toString);`
I get a correct
`2024-08-26 23:05:27.550 [INFO ] [enhab.core.model.script.History was ] - [8/25/24, 11:06 PM: Xiaomi_Motion_Garage_Bewegung -> 0.0, 8/25/24, 11:07 PM: Xiaomi_Motion_Garage_Bewegung -> 0.0, 8/25/24, 11:08 PM: Xiaomi_Motion_Garage_Bewegung -> 0.0, 8/25/24, 11:09 PM: Xiaomi_Motion_Garage_Bewegung -> 0.0, 8/25/24, 11:10 PM: ...`

Using influxdb persistence
`var states = Xiaomi_Motion_Garage_Bewegung.getAllStatesBetween(now.minusHours(24), now, 'influxdb')
logInfo("History was ", states.toString);`
I get
`2024-08-26 23:07:05.494 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'f3dcf456e8' failed: Cannot format given Object as a Date`

**Comment by J-N-K** [comment] 2024-08-31 11:21
I can reproduce your issue with

```
var states = Bad_temp.getAllStatesBetween(now.minusHours(24), now.minusHours(12), 'influxdb')
logInfo("History was ", states.toString)
```

but 

```
var states = Bad_temp.getAllStatesBetween(now.minusHours(24), now.minusHours(12), 'influxdb')
states.forEach[ state | logInfo("History was ", state.getTimestamp.toString + " " + state.getState.toString) ]
```

works fine for me. The correct data is returned. So it doesn't seem to be an issue with influxdb or the persistence extensions itself but with Rules DSL. Maybe the difference is the collection that rrd4j and influxdb return. But both are fine, the interface requires the return value to be an `Iterable` which is clearly the case.

My personal suggestion would be to switch to JS or another modern scripting language.

**Comment by sascha777** [comment] 2024-08-31 12:08
Understand, thanks for that insight. 

I can't say what type of collection would be expected to be returned for Rules DSL, even though if JS might be more flexible regarding the incoming collections.

Maybe this is a bug in Rules DSL, maybe the type of collection of the persistence extension needs to be changed.

Regarding my code already found another solution to solve the issue; just wanted to report on this.

**Comment by J-N-K** [comment] 2024-08-31 15:09
Thanks for reporting, but I'm closing this since it's not a bug in in influxdb.

**Closed by J-N-K** 2024-08-31 15:09 UTC
