### ISSUE TITLE
[ipcamera] Channel "enableMotionAlarm" from type "Instar Camera with API" switches state back and forth

### ISSUE THREAD

**Issue by RudiOH** [openhab/openhab-addons#14363] opened 2023-02-08 11:16 UTC
I am using the ipcamera binding for five Instar cameras (9008HD and 6014HD) and one Foscam camera (FI9902P) since two years. For each Instara camera a thing of the type "Instar Camera with API" was created and a thing of the type "Foscam Camera with API" for the Foscam camera. After the update in December to 3.4.0 (and still in 3.4.1), the "enableMotionAlarm" channel no longer works correctly with the Instar cameras: the status of the switch item is not displayed correctly in the "ON" status. The status switches between " ON" and "OFF" back and forth. The "ON" status is displayed for approx. 8 seconds, after which the "OFF" status is usually displayed for more than 40 seconds.

In the settings of the camera's web interfaced, however, it can be seen that MotionAlarm is still switched on. Camera recordings are also generated. The "motionAlarm" channel continues to be triggered. So only the OFF state seems to be displayed incorrectly in the switch item.

This issue affects both Instar camera models but not the Foscam camera.
This problem only affects the display of the status but not the function of the switch: the switch can still be used to switch the camera's "enableMotionAlarm" on and off from Openhab.
I also use: motionAlarm, enablePirAlarm, pirAlarm, pollImage and image. The items of these channels work correctly.

**Comment by Skinah** [comment] 2023-05-24 02:55
At that point in time new channels were added to the binding for Instar thing type. Did you try removing and then re-adding the cameras/things? openHAB creates a cache of the thing at the time it is created and when new channels get added you need to delete and re-add the thing for this cache to be accurate. It is possible this is the cause, so can you try this and report if it still happens as I will then test and look into it further.

**Comment by Skinah** [comment] 2023-06-10 05:27
I can not reproduce this with a IN 8015 full HD POE
My guess is you just need to delete and re-add the things due to the recent changes made.

**Comment by Skinah** [comment] 2023-06-10 06:51
I did find an issue when using the cameras with the old API in them, but it only started occurring after I updated the firmware in the camera. The camera responds with a text message of an error 404 reply, but the http code is OK so it does not get filtered out. I will make a PR to fix this.

**Comment by RudiOH** [comment] 2023-06-10 07:58
Hi Matthew,

 

sorry for the missing reply. I was on vacation.

I deleted all camera things and re-added the things as well as the items. The main reason was the renaming of things/items and so I could also check the functionality.

The bug still exists and only affects Instar cameras and only the enableMotionAlarm channel.

 

How do I get the fix?

 

Best regards, Ralf

 

 

 

Von: Matthew Skinner ***@***.***> 
Gesendet: Samstag, 10. Juni 2023 08:52
An: openhab/openhab-addons ***@***.***>
Cc: RudiOH ***@***.***>; Author ***@***.***>
Betreff: Re: [openhab/openhab-addons] [ipcamera] Channel "enableMotionAlarm" from type "Instar Camera with API" switches state back and forth (Issue #14363)

 

I did find an issue when using the cameras with the old API in them, but it only started occurring after I updated the firmware in the camera. The camera responds with a text message of an error 404 reply, but the http code is OK so it does not get filtered out. I will make a PR to fix this.

**Comment by Skinah** [comment] 2023-06-10 10:32
You can try seeing if this jfrog link works.

This pull request will automatically be built and available under the following links if anyone wants to test:
https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/

https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.ipcamera/4.0.0-SNAPSHOT/org.openhab.binding.ipcamera-4.0.0-SNAPSHOT.jar

**Comment by BuddGit** [comment] 2023-07-02 10:21
Hello Skinah,

I have the same problem with version https://openhab.jfrog.io/ui/native/libs-pullrequest-local/org/openhab/addons/bundles/org.openhab.binding.ipcamera/4.0.0-SNAPSHOT/ org.openhab.binding.ipcamera-4.0.0-SNAPSHOT.jar
The only thing is that it switches back and forth more slowly.

**Comment by Skinah** [comment] 2023-07-02 23:41
I don't know how the jfrog server handles multiple PR and there are currently 3 for this binding waiting to be merged so your jar may be from a build without the changes. Best to compile your own or wait till it is merged as I was able to reproduce and prove the fix on mine here.

**Comment by BuddGit** [comment] 2023-07-15 15:31
Hello Skinah,

Thank you for your work, but I have tested with version 3.4.4 and 4.0.0.M4 with the included addon and with the org.openhab.binding.ipcamera-4.0.0-SNAPSHOT.jar from 14-07-23 16:36:57 and I get the same problem. The motion alarm changes the state between 30 seconds and minutes.

**Closed** 2023-07-16 11:32 UTC

**Comment by Skinah** [comment] 2023-07-18 07:25
Can you try 4.0mikestone 5 that was just released and contains the fix, V3 will not get the fix. Feel free to reopen this only if you have tried milestone  5.

**Comment by BuddGit** [comment] 2023-08-23 16:23
I tested it and it works great! 
Thank you
