### ISSUE TITLE
[somfymylink] Missing from Paper UI and Karaf Console

### ISSUE THREAD

**Issue by guallo** [openhab/openhab-addons#8009] opened 2020-06-24 21:24 UTC
## Expected Behavior

I should be able to list the [Somfy myLink Binding](https://www.openhab.org/addons/bindings/somfymylink/) using either of:

- [http://\<my-openhabian-ip\>:8080/paperui/index.html#/extensions?tab=binding](http://<my-openhabian-ip>:8080/paperui/index.html#/extensions?tab=binding)
- **openhab>** `feature:list`

## Current Behavior

I am unable to list the [Somfy myLink Binding](https://www.openhab.org/addons/bindings/somfymylink/) using either of above methods.

## Possible Solution

Add the following dependency to [bom/openhab-addons/pom.xml](https://github.com/openhab/openhab-addons/blob/2.5.x/bom/openhab-addons/pom.xml) as inferred from [this comment](https://community.openhab.org/t/somfy-mylink-binding-5652-omitted-in-upgrade-to-openhab-2-5-6/101285/2):

```xml
    <dependency>
      <groupId>org.openhab.addons.bundles</groupId>
      <artifactId>org.openhab.binding.somfymylink</artifactId>
      <version>${project.version}</version>
    </dependency>
```

## Steps to Reproduce

1. **openhabian@openhab:~$** `openhab-cli console`
2. **openhab>** `feature:list -s -b | grep somfymylink`

## Context

I want to install the [Somfy myLink Binding](https://www.openhab.org/addons/bindings/somfymylink/) without needing to manually compile it and resolve its dependencies (if any), etc., to avoid any human mistakes.

## Environment

* https://github.com/openhab/openhabian/releases/download/v1.5/openhabian-pi-raspbian-201908050414-gitca0976f-crc6a66b5a1.img.xz
* Raspbian GNU/Linux 10 (buster)
* openHAB 2.5.6-2 (Release Build)
* java -version: openjdk version "1.8.0_252"
* nodejs --version: v12.18.1
* Firefox 77.0.1 (64-bit)

**Comment by Hilbrand** [comment] 2020-06-25 06:47
Closing as it's a duplicate of #8008

**Closed by Hilbrand** 2020-06-25 06:47 UTC
Labels: duplicate
