### ISSUE TITLE
[Network] Binding: Wake On Lan broadcasting instead of using configured IP

### ISSUE THREAD

**Issue by J0nathan-S** [openhab/openhab-addons#11196] opened 2021-09-03 11:43 UTC
## Expected Behavior
I expect the Network Binding to send the Magic Request to the IP configured in the Network Binding Thing. This is not what happens. Instead it broadcasts the Magic Request within the docker Network only. 

## Current Behavior
It broadcasts the Magic Request within the docker Network only. 

`2021-09-03 13:27:29.795 [DEBUG] [twork.internal.WakeOnLanPacketSender] - Wake-on-LAN packet sent (MAC address: XX:XX:XX:XX:XX:XX, broadcast address: 172.23.255.255)
2021-09-03 13:27:29.796 [INFO ] [twork.internal.WakeOnLanPacketSender] - Wake-on-LAN packets sent (MAC address: XX:XX:XX:XX:XX:XX)`
Mac adress is blurred

## Possible Solution
A solution would be to use the IP adress configured in the Network Binding Thing, if set. Otherwise Broadcast.

## Steps to Reproduce (for Bugs)
1. Create a Networking Binding Thing with IP and Mac
2. Open Console via `docker exec -it <docker-id> /openhab/runtime/bin/client -p habopen`
2. Set the log level via (log:set debug org.openhab.binding.network)

## Context
For Security purposes I put my OpenHAB Server as well as all smart devices in its own network. But I still want to be able to startup my computer via WOL. 
I managed to do that from the Server OpenHAB is running on through ubuntus wakeonlan package.

## Your Environment
* Version used: OpenHAB 3.1.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Docker
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 20.04

**Comment by Rossko57** [comment] 2021-09-12 15:59
That's not a bug; ordinary WoL is supposed to target by MAC.  You're seeking an enhancement, and it should be optional.

**Comment by J0nathan-S** [comment] 2021-09-12 16:30
> That's not a bug; ordinary WoL is supposed to target by MAC.  You're seeking an enhancement, and it should be optional.
> 
> 

I didn't know that. Thanks for pointing that out.

**Comment by lsiepel** [comment] 2023-01-08 23:06
As this is an older issue and the PR seems to be merged, I assume it has been resolved. Please re-open if that is not the case or if there is anything else to add.

**Closed by lsiepel** 2023-01-08 23:06 UTC
