### ISSUE TITLE
[deCONZ] Can't control Items connected to Color Channels. Does not display Sliders or Colorpickers.

### ISSUE THREAD

**Issue by cablesandcoffee** [openhab/openhab-addons#10107] opened 2021-02-08 19:13 UTC
## Expected Behavior
When looking at an Item connected to a color channel in Model page, Items page or Main UI some sort of tool to control this item should be presented. 

## Current Behavior
No tool  (slider, color picker) is presented. Only the Item's state as integer. 

## Possible Solution
Don't know the cause of the problem but the color channels for deconz things look weird, no icon color wheel for example is shown, only the letter C. I've checked the behaviour with the same items connected to a Philips Hue thing instead and that works. That's why I think it's a deCONZ binding issue. 

Also if changing semantic property on Item connected to a Color channel the color picker pops up sometimes. If you view another item and go back to the one before the color picker is gone again. 

## Steps to Reproduce (for Bugs)
Picture of item connected to color channel showing only state as integer
![Screenshot from 2021-02-07 19-50-03](https://user-images.githubusercontent.com/63468500/107269110-65529580-6a49-11eb-94d8-6f16d12a2c95.png)

Picture after changing semantic property from light to something else. The color picker pops up. Disappears if you leave page and look at the item again.
![Screenshot from 2021-02-07 19-50-55](https://user-images.githubusercontent.com/63468500/107269120-684d8600-6a49-11eb-95f7-6873777ff611.png)

1.
2.

## Context
Cant control items connected to DeCONZ binding color channels

## Your Environment
Raspberry Pi 4
Openhabian latest release
Openhab 3.1.0M1

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by J-N-K** [comment] 2021-02-12 14:17
Probably solved with #10126

**Comment by broliyoung** [comment] 2021-02-22 19:14
I'm running the #294 snapshot and I can confirm my Philips Strip Led works again. 
However I have an Ikea bulbs:
TRADFRI bulb E14 WS 470lm with FW 2.3.050
that work only the brightness channel, the temperature is shown with a number.
![image](https://user-images.githubusercontent.com/7022596/108757705-7b348000-754a-11eb-8cd0-28ed1b597393.png)

**Comment by cweitkamp** [comment] 2021-02-22 19:51
The Color Channel is working. That is good. And we can close this issue.

wrt the Color Temperature Channel you should have a look int #8260. The Channel uses item type Number to let a user set the value in Kelvin. That is probably the reason why no Slider will be shown in the UI. Sliders are only shown by default for item type Dimmer. To see on you have to define the Default List Item Widget for you item similar to this

```
value: oh-slider-item
config:
  unit: " K"
  min: 2000
  scaleSteps: 9
  max: 6500
  icon: oh:slider
  scale: true
  step: 100
  label: true
  title: Farbtemperatur
  scaleSubSteps: 5
```

**Closed by cweitkamp** 2021-02-22 19:51 UTC
