### ISSUE TITLE
[telegram] sendTelegramPhoto is returning 401 when using basic auth

### ISSUE THREAD

**Issue by RobertHerter** [openhab/openhab-addons#9792] opened 2021-01-12 09:29 UTC
Using sendTelegramPhoto with:
val telegramAction = getActions("telegram","telegram:telegramBot:6e13b54c0d")
telegramAction.sendTelegramPhoto(1234L, "http://192.168.0.17/mjpeg/snap.cgi?chn=1", "Kinderzimmer", "user", "password")

always getting error:
[WARN ] [gram.internal.action.TelegramActions] - Download from http://192.168.0.17/mjpeg/snap.cgi?chn=1 failed with status: 401

same sendTelegramPhoto() was working on 2.5 without any problems.

Using Openhab 3.0.0 on ubuntu amd64 20.04

**Comment by czahorski** [comment] 2021-01-25 13:29
+1 

Same problem after upgrade to OH3 

val telegramAction = getActions("telegram","telegram:telegramBot:9755518a")
telegramAction.sendTelegramPhoto("http://192.168.4.110/cgi-bin/snapshot.cgi", null, "user", "password")

Error :
[gram.internal.action.TelegramActions] - Download from http://192.168.4.110/cgi-bin/snapshot.cgi failed with status: 401

Works if no auth is needed.
val telegramAction = getActions("telegram","telegram:telegramBot:9755518a")
telegramAction.sendTelegramPhoto("http://192.168.4.110/cgi-bin/snapshot.cgi", null)

**Comment by Skinah** [comment] 2021-02-20 10:50
Does your camera have BASIC or DIGEST auth? The url @czahorski gave is for Dahua and in newer firmwares they only support DIGEST and the telegram binding only supports BASIC. If you use the ipCamera binding that will allow it to work as it supports both methods and then can serve the file with no password needed.

**Comment by czahorski** [comment] 2021-02-20 11:11
I'm using Basic, I'm still on the old firmware. Did a curl on the URL I
provided and checked it is BASIC (actually my firmware doesn't support
Digest on that specific camera).

**Comment by Wikibear** [comment] 2021-03-08 15:30
Same issue here with 3.1.M2 and before. http://username:passwort@192.168.1.5/mjpeg/snap.cgi?chn=0 show my webcam picture and telegramPhoto gives me a 401.
telegramPhoto("http://username:passwort@192.168.1.5/mjpeg/snap.cgi?chn=0",null,"username","password")

**Comment by Wikibear** [comment] 2021-03-28 14:31
Are there no solutions? Month ago and no feedback...

**Comment by Wikibear** [comment] 2021-03-29 15:36
Build a php proxy, that running on my apache server as workaround.
`<?php
  header('Content-Type: image/jpeg');
  $user = "admin";
  $pass = "campass";
  $camUrl = "http://192.168.1.27/mjpeg/snap.cgi?chn=0";
  $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $camUrl); 
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_ANY | CURLAUTH_ANYSAFE );
    curl_setopt($ch, CURLOPT_USERPWD, "$user:$pass");
    $im = curl_exec($ch);
?>`

**Comment by Skinah** [comment] 2021-08-18 08:54
I took a look and the code was using StandardCharsets.ISO_8859_1 and the ipcamera binding is using UTF_8 and since I have never had a complaint about auths failing, I have made the change to the telegram binding so fingers crossed this fixes it for you.

**Comment by Skinah** [comment] 2021-09-06 08:39
Since the changes got merged, can someone test this when openHAB 3.2 Milestone 2 is released then post back here so we can close the issue if it is fixed or know if it is not and still needs looking into? thanks

**Comment by czahorski** [comment] 2022-01-06 15:45
Issue still happening on 3.2. Log output : "[gram.internal.action.TelegramActions] - Download from http://192.168.4.111/cgi-bin/snapshot.cgi failed with status: 401" 

Checked Username and Pass and are correct. Also checked on 3 other cameras.

**Comment by Skinah** [comment] 2022-03-05 02:53
How are you using the action? A person above used this:

```
telegramPhoto("http://username:passwort@192.168.1.5/mjpeg/snap.cgi?chn=0",null,"username","password")
```

I am not sure it the binding can handle that and you should try it like this instead. If this is the case then it would need the binding updated to remove the `username:passwort@` from the url if it exists. Perhaps this explains why people are having issues?

```
telegramPhoto("http://192.168.1.5/mjpeg/snap.cgi?chn=0",null,"username","password]")
```

**Comment by RobertHerter** [comment] 2022-04-19 06:50
Hello, even with Version 3.2 it still fails with error 401 using:
telegramPhoto("http://192.168.1.5/mjpeg/snap.cgi?chn=0",null,"username","password]")

**Comment by timtimsson** [comment] 2022-05-04 19:37
… same problem with Hikvision - 401
`telegramPhoto("http://ip/ISAPI/Streaming/channels/101/picture",null,"username","password")`

**Comment by Skinah** [comment] 2022-11-26 08:40
I am sorry but I can not reproduce this by using the following with my Hikvision and openHAB version 3.4 milestone 4:

```
getActions("telegram", "telegram:telegramBot:MyBotNameHere").sendTelegramPhoto("http://192.168.2.3/ISAPI/Streaming/channels/101/picture",null,"admin","password")
```

Both of you have posted version 3.2 but dont mention if it was 3.2 STABLE or a Milestone and which one.

In the case of HIKVISION you will need to make sure that you set the camera to use DIGEST/BASIC under SYSTEM>SECURITY>AUTHENTICATION> because if you have it set to DIGEST only, then the telegram binding cannot do digest method, which in this case you can use the IPCAMERA binding to talk to the camera with digest and then use the ipcamera url to supply the telegram binding with.

Unless you can provide a way to reproduce this here on one of my cameras, I cannot look into it as it appears that the code is correct. Since you are getting a 401 error it means the camera is replying that your user/pass is wrong or missing, so Perhaps look at changing your password to remove spaces or other weird characters that may cause a glitch. If you can post more details on how to reproduce it on my system then I will be happy to look at it in more detail.

**Comment by Skinah** [comment] 2022-11-26 08:58
Actually, there is something people can do to help narrow this down. Capture the HTTP traffic with wireshark when the binding asks the camera for the snapshot, then also capture the traffic of wget/curl asking for the snapshot and we can then compare what is different. Please note that the HTTP header will have your user/pass hashed in it that is easily reversed so change it enough if you wish without spoiling what the cause is. I would expect this to show what is wrong so that we can move forwards and fix the issue. You're welcome to PM me the info via the forum.

**Comment by tpham3783** [comment] 2022-11-30 17:41
@Skinah 

All of this used to work in OH2.5; but since I migrated to OH3.3 on Ubuntu-20.04 it stopped working, exactly like the issue described here.

Here is the trace log (with the hashed password changed to MYHASHEDPASS
Let me know what use you need.
```

12:35:42.676424 IP (tos 0x0, ttl 64, id 20010, offset 0, flags [DF], proto TCP (6), length 234)
    iot.oh3.54328 > 11.0.1.216.http: Flags [P.], cksum 0x1a19 (incorrect -> 0x3047), seq 1:183, ack 1, win 502, options [nop,nop,TS val 2918176418 ecr 2161993], length 182: HTTP, length: 182
	GET /cgi-bin/snapshot.cgi?channel=1&subtype=1 HTTP/1.1
	Accept-Encoding: gzip
	User-Agent: Jetty/9.4.46.v20220331
	Host: 11.0.1.216
	Authorization: Basic MYHASHEDPASS==
	
12:35:42.676684 IP (tos 0x0, ttl 64, id 57237, offset 0, flags [DF], proto TCP (6), length 52)
    11.0.1.216.http > iot.oh3.54328: Flags [.], cksum 0x676d (correct), seq 1, ack 183, win 972, options [nop,nop,TS val 2161993 ecr 2918176418], length 0
12:35:42.690776 IP (tos 0x0, ttl 64, id 57238, offset 0, flags [DF], proto TCP (6), length 264)
    11.0.1.216.http > iot.oh3.54328: Flags [P.], cksum 0xe205 (correct), seq 1:213, ack 183, win 972, options [nop,nop,TS val 2161994 ecr 2918176418], length 212: HTTP, length: 212
	HTTP/1.1 401 Unauthorized
	WWW-Authenticate: Digest realm="Login to AMC042F7DA1B31181A", qop="auth", nonce="1126273863", opaque="92fa3ebea7eb7770f95d1c92b7b1da0a74f923ad"
	Connection: close
	CONTENT-LENGTH: 0

```

**Comment by Skinah** [comment] 2022-11-30 20:45
My comment from 4 days ago was for hikvision cameras which allow both basic and digest auth, but can lock out and stop basic from working. They have a camera setting you can change. Newer Dahua firmwares only do digest.

I would have to dig back at the older code as I think the older binding was V1 format and has to get a full rewrite to work in V3 but I could be wrong.
How certain are you that it did work with digest in 2.5 and this is not caused by you upgrading the firmware for the camera at the same time you changed to V3?

This means it is not a bug but a feature request to add digest support.

You can use the ipcamera binding to get around this lacking feature and gain more features.

**Closed** 2023-07-12 22:14 UTC
