### ISSUE TITLE
[tapocontrol] ERROR Thing CONFIGURATION_ERROR

### ISSUE THREAD

**Issue by edemunari** [openhab/openhab-addons#11917] opened 2021-12-31 15:45 UTC
Can't Configure TP-Link 
 TapoControl Binding
CONFIGURATION_ERROR

 When trying to configure TP-Link L530E Series Color-Bulb I get configuration error.

CONFIGURATION_ERROR
found type:'L530' with mac:'B0-A7-B9-73-C7-06'. Check IP-Address

But the ip address and the mac address are of the TP-Link  L530 Series Color-Bulb I installed so what is the problem?

I use Tapo Cloud Login Bridge that is on line ad correctly working.

I'm on Openhab 3.2 on Raspberry PI Linux server.

I can't understand whats going on.

Any help appreciated, cheers, Eriberto

![Schermata 2021-12-31 alle 16 45 10](https://user-images.githubusercontent.com/96918650/147831076-83c968a0-0b28-48a6-8375-9e5cd1ebf325.png)
![Schermata 2021-12-31 alle 16 44 37](https://user-images.githubusercontent.com/96918650/147831080-df270b26-68c3-4f50-ab16-535fd40e61f3.png)

**Comment by edemunari** [comment] 2021-12-31 15:47
Sorry I forgot to telle that I'm on Openhab 3.2 on Raspberry PI Linux server.

**Comment by lindmayer** [comment] 2022-01-03 21:40
Same problem for me. Tried several things without success.

**Comment by sibbi77** [comment] 2022-02-17 20:19
I've a quick fix here: [jar](https://github.com/sibbi77/openhab2-addons/releases/tag/Tapo_L530)
The problem is, my L530 answers like this:
`20:49:18.117 [TRACE] [trol.internal.api.TapoDeviceConnector] - (tapocontrol:L530_Series:633c47336e:ab8edb24e0) received result: {"result":{"device_id":"8023BB2856C6646B919F0ED78DB7E6541F34B717","fw_ver":"1.0.5 Build 210928 Rel.180458","hw_ver":"2.0","type":"SMART.TAPOBULB","model":"L530","mac":"5C-A6-E6-6D-0A-D4","hw_id":"FDE1C68674D1535B12A042682B192E4E","fw_id":"7BECA9DC454565672FEC87D1104F9972","oem_id":"2241AD354FF56159AF1AC4A53B011A5D","overheated":false,"ip":"192.168.1.66","time_diff":60,"ssid":"","rssi":-56,"signal_level":2,"latitude":000000,"longitude":00000,"lang":"de_DE","avatar":"bulb","region":"Europe/Berlin","specs":"","nickname":"c21hcnRlIFdMQU4tR2zDvGhiaXJuZQ==","has_set_location_info":true,"device_on":true,"brightness":30,"hue":0,"saturation":0,"color_temp":4535,"default_states":{"type":"last_states","state":{"brightness":30,"hue":0,"saturation":0,"color_temp":4535}}},"error_code":0}`
model == "L530", but the binding expects "L530_Series".
I think it may be a newer firmware, but this is my first (and only) Tapo device, so I'm unsure about this.
The fix I made is only replacing the string "L530_Series" with "L530". This will not work with older devices and is therefore not a proper fix to the problem, but should work for the mean time.

@wildcs can you have a look at this?

**Comment by Bigdesaster** [comment] 2022-02-17 20:52
Hi,
with what version did you have the issue?
It should be fixed with 3.3 M1 or manual installing jar from [here](https://github.com/wildcs/oh3_tapocontrol)

**Comment by sibbi77** [comment] 2022-03-04 17:12
Hi @Bigdesaster you're right, the linked jar does find the LED, but needs a manual IP address entry. Color is not changeable and brightness, too. Swicthing it on and off does work. I'll file a new bug report for this.

**Closed by sibbi77** 2022-03-04 17:12 UTC
