### ISSUE TITLE
[mqtt] No reconnect after temporary disconnect

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#6438] opened 2019-11-23 07:05 UTC
If the MQTT broker connection is temporary disconnected, openHAB does not recover from it until a restart of OH. It looks like OH does a kind of 'soft restart' and it decides to do an UNSUBSCRIBE and DISCONNECT, followed by a CONNECT, but no SUBSCRIBE.

Environment:
- Debian 10 x64 (patched)
- OH 2.5.0.M5 (had the issue before in M4 as well)
- Mosquitto 1.6.7

The Mosquitto broker attempts to re-establish the connection as shown in the log below, but never gets a SUBSCRIBE from OH after the 'CONNACK'.
```
2019-11-23T07:39:18: Received PINGREQ from dsmrv4
2019-11-23T07:39:18: Sending PINGRESP to dsmrv4
2019-11-23T07:39:28: Received PINGREQ from 6549f45a-b990-4f2e-a523-8d180a5b987d
2019-11-23T07:39:28: Sending PINGRESP to 6549f45a-b990-4f2e-a523-8d180a5b987d
2019-11-23T07:39:33: Received UNSUBSCRIBE from 6549f45a-b990-4f2e-a523-8d180a5b987d
2019-11-23T07:39:33:    homeassistant/#
2019-11-23T07:39:33: Sending UNSUBACK to 6549f45a-b990-4f2e-a523-8d180a5b987d                                                                                                                                                  2019-11-23T07:39:33: Received UNSUBSCRIBE from 6549f45a-b990-4f2e-a523-8d180a5b987d
2019-11-23T07:39:33:    +/+/$homie                                                                                                                                                                                             2019-11-23T07:39:33: Sending UNSUBACK to 6549f45a-b990-4f2e-a523-8d180a5b987d                                                                                                                                                  2019-11-23T07:39:33: Received UNSUBSCRIBE from 6549f45a-b990-4f2e-a523-8d180a5b987d
2019-11-23T07:39:33:    sensor/dsmr                                                                                                                                                                                            2019-11-23T07:39:33: Sending UNSUBACK to 6549f45a-b990-4f2e-a523-8d180a5b987d
2019-11-23T07:39:33: Received DISCONNECT from 6549f45a-b990-4f2e-a523-8d180a5b987d                                                                                                                                             2019-11-23T07:39:33: Client 6549f45a-b990-4f2e-a523-8d180a5b987d disconnected.
2019-11-23T07:39:33: Received PINGREQ from dsmrv4
2019-11-23T07:39:33: Sending PINGRESP to dsmrv4
2019-11-23T07:39:33: New connection from 172.23.0.1 on port 1883.
2019-11-23T07:39:33: New client connected from 172.23.0.1 as b118990b-1a39-4835-ba59-6769065b5754 (p2, c1, k60, u'**REDACTED**').
2019-11-23T07:39:33: No will message specified.
2019-11-23T07:39:33: Sending CONNACK to b118990b-1a39-4835-ba59-6769065b5754 (0, 0)
2019-11-23T07:39:48: Received PINGREQ from dsmrv4
2019-11-23T07:39:48: Sending PINGRESP to dsmrv4
2019-11-23T07:40:03: Received PINGREQ from dsmrv4
2019-11-23T07:40:03: Sending PINGRESP to dsmrv4
2019-11-23T07:40:18: Received PINGREQ from dsmrv4
2019-11-23T07:40:18: Sending PINGRESP to dsmrv4
2019-11-23T07:40:33: Received PINGREQ from b118990b-1a39-4835-ba59-6769065b5754
2019-11-23T07:40:33: Sending PINGRESP to b118990b-1a39-4835-ba59-6769065b5754
2019-11-23T07:40:33: Received PINGREQ from dsmrv4
2019-11-23T07:40:33: Sending PINGRESP to dsmrv4
2019-11-23T07:40:39: Received PUBLISH from dsmrv4 (d0, q0, r1, m0, 'sensor/dsmr', ... (316 bytes))
2019-11-23T07:40:48: Received PINGREQ from dsmrv4
2019-11-23T07:40:48: Sending PINGRESP to dsmrv4
```
For the record: I have no `homie` or `homeassistant` topics, they are probably defaults from the binding?

The OH log shows the 'soft restart':
```
2019-11-23 07:39:33.485 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'unify.things'
2019-11-23 07:39:33.497 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'alexa.things'
2019-11-23 07:39:33.511 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'daikin.things'
2019-11-23 07:39:33.522 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'astro.things'
2019-11-23 07:39:33.533 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'system.things'
2019-11-23 07:39:33.549 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'mqtt.things'
2019-11-23 07:39:33.642 [INFO ] [.transport.mqtt.MqttBrokerConnection] - Starting MQTT broker connection to '192.168.2.2' with clientid b118990b-1a39-4835-ba59-6769065b5754
2019-11-23 07:39:33.662 [INFO ] [el.core.internal.ModelRepositoryImpl] - Refreshing model 'hue.things'
```

**Comment by J-N-K** [comment] 2019-11-23 11:41
What exactly is the problem? The connection is not coming online after a re-connect?

**Comment by justClouds** [comment] 2019-11-23 13:51
Not exactly, I should have stated it a bit more specific. The connection gets established again (as proven by the CONNACK), and should be followed by a SUBSCRIBE from the mqtt binding, like in this correct sequence:
````
2019-10-27T09:23:43: New connection from 172.18.0.1 on port 1883.
2019-10-27T09:23:43: New client connected from 172.18.0.1 as paho2512256097675 (p2, c1, k60000, u'**REDACTED**').
2019-10-27T09:23:43: No will message specified.
2019-10-27T09:23:43: Sending CONNACK to paho2512256097675 (0, 0)
2019-10-27T09:23:43: Received SUBSCRIBE from paho2512256097675
2019-10-27T09:23:43:    homeassistant/# (QoS 0)
2019-10-27T09:23:43: Sending SUBACK to paho2512256097675
2019-10-27T09:23:43: Received SUBSCRIBE from paho2512256097675
2019-10-27T09:23:43:    +/+/$homie (QoS 0)
2019-10-27T09:23:43: Sending SUBACK to paho2512256097675
2019-10-27T09:23:43: Received SUBSCRIBE from paho2512256097675
2019-10-27T09:23:43:    sensor/dsmr (QoS 0)
2019-10-27T09:23:43: Sending SUBACK to paho2512256097675
2019-10-27T09:23:43: Sending PUBLISH to paho2512256097675 (d0, q0, r1, m0, 'sensor/dsmr', ... (317 bytes))
2019-10-27T09:23:43: Received SUBSCRIBE from paho2512256097675
````

**Comment by J-N-K** [comment] 2019-11-24 22:34
Can you try to pin the client id by setting it to something?

**Comment by justClouds** [comment] 2019-11-25 19:08
> Can you try to pin the client id by setting it to something?

Sure, will report back with the result.

**Comment by rkoshak** [comment] 2019-11-26 18:54
To add to this issue, I too am seeing this problem with one but not both of my OH instances that are bridged by MQTT. When the connection to the broker is lost for what ever reason, the MQTT Broker Thing never seems to recognize that the connection is lost. The Thing remains ONLINE and there is nothing in the MQTT logs to indicate that the connection went away. On this OH instance I'm only using the publishMQTT Action and every time it tries to publish it logs an error.

In the mean time, the broker will have sent the LWT message.

MQTT logs:

```
26-Nov-2019 10:41:27.045 [TRACE] [inding.mqtt.internal.TopicSubscribeMultiConnection] - Found suitable bridge mqtt:broker:argus for listing to topic homeassistant/#
26-Nov-2019 10:41:27.084 [TRACE] [inding.mqtt.internal.TopicSubscribeMultiConnection] - Found suitable bridge mqtt:broker:argus for listing to topic +/+/$homie
26-Nov-2019 10:43:03.911 [DEBUG] [org.openhab.binding.mqtt.action.MQTTActions       ] - MQTT publish to dads-openhab/status performed
-------- 10:52 shut down Mosquitto -------------------
26-Nov-2019 10:53:00.211 [WARN ] [org.openhab.binding.mqtt.action.MQTTActions       ] - MQTT publish to dads-openhab/out/vDad_Heartbeat/command failed!
26-Nov-2019 10:53:00.242 [WARN ] [org.openhab.binding.mqtt.action.MQTTActions       ] - MQTT publish to dads-openhab/out/vDad_Heartbeat/state failed!
```

events.log
```
2019-11-26 10:41:23.407 [hingStatusInfoChangedEvent] - 'mqtt:broker:argus' changed from UNINITIALIZED to INITIALIZING
2019-11-26 10:41:23.561 [hingStatusInfoChangedEvent] - 'mqtt:broker:argus' changed from INITIALIZING to OFFLINE
2019-11-26 10:41:25.957 [hingStatusInfoChangedEvent] - 'mqtt:broker:argus' changed from OFFLINE to ONLINE
2019-11-26 10:42:00.139 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:42:00.186 [vent.ItemStateChangedEvent] - vDad_Heartbeat changed from NULL to ON
2019-11-26 10:42:00.189 [GroupItemStateChangedEvent] - PubItems changed from NULL to UNDEF through vDad_Heartbeat
2019-11-26 10:43:00.135 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:44:00.142 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:45:00.135 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:46:00.136 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:47:00.135 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:48:00.135 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:49:00.135 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:50:00.135 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:51:00.141 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:52:00.136 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
-------- 10:52 shut down Mosquitto -------------------
2019-11-26 10:53:00.138 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
2019-11-26 10:54:00.142 [ome.event.ItemCommandEvent] - Item 'vDad_Heartbeat' received command ON
```

There is nothing in openhab.log

Restarting the MQTT Broker Binding bundle appears to be sufficient to cause it to reconnect.

For me at least this is reproducible, just shut down Mosquitto for a bit then start it back up. 

I can't tell if it's time dependent or not because the OH instance that is on the same machine sometimes either reconnects, or when I just restart Mosquitto it comes back online soon enough that the connection can be retained or something like that. 

Both instances of OH have a fixed client ID. At least one other user is seeing the same behavior, as reported at https://community.openhab.org/t/2-5-milestone-5-issues/85680/152.

**Comment by J-N-K** [comment] 2019-12-01 13:09
@rkoshak's issue is a bug in core, which should be fixed by https://github.com/openhab/openhab-core/pull/1254

I think that the other one is different, I'll check that.

**Closed** 2019-12-02 21:40 UTC
