### ISSUE TITLE
[mqtt] Subscribe not working with whitespaces and/or parentheses

### ISSUE THREAD

**Issue by tomeng** [openhab/openhab-addons#5488] opened 2019-04-19 18:23 UTC
As requested by @davidgraeff on [How to debug MQTT2 Binding issues?](https://community.openhab.org/t/how-to-debug-mqtt2-binding-issues/70098/8)

It seems that MQTT subscribe is not working for topics that either contain whitespaces and/or parentheses.

In my example, debug log showed that the channel received an update
`2019-04-16 13:25:57.909 [DEBUG] [mqttv3.internal.wire.MqttInputStream] - null: Automatic Reconnect Successful: PUBLISH qos:0 retained:false dup:false topic:"Hugo2C/Roon/Arbeitszimmer (HQ)/now_playing/one_line/line1" payload:[hex:4261636b206f6e207468652044616e636520466c utf8:"Back on the Dance Fl" length:39]`

## Current Behavior
Update is not passed on to linked items.

## Expected Behavior
Pass update to items properly. :-)

## Workaround
Remove or replace whitespaces & parentheses from topic names.

## Your Environment

- rPi 3B+ running openhabian with OH 2.4 Release
- Virtual openhabian with OH 2.5.0#1571

**Comment by JohnBeton22** [comment] 2019-05-12 18:44
I can confirm this bug. The newly added Niko Home Control binding with support for Niko Home Control 2 suffers from this bug as well. The initial public mqtt message to gather a profiles.list from the connected controller fails already.

topic: public/authentication/cmd
message: {"Method":"profiles.list","ErrCode":"","ErrMessage":""}

@davidgraeff @mherwege

**Comment by davidgraeff** [comment] 2019-05-12 18:52
My next mqtt bug triage timeframe is next month. If someone else finds time in the meantime, that'd be great. I have updated the paho mqtt library the last days in core, maybe that helps already.

**Comment by JohnBeton22** [comment] 2019-05-12 18:57
Hi, latest snapshots are still broken unfortunately. 2.5.0~S1589-1

**Comment by davidgraeff** [comment] 2019-05-12 21:13
Just to be sure: other clients can send whitespace topics? Can someone test with the paho java library as well? 

Need to know if it's openhab or the paho library or the Mqtt broker

**Comment by mherwege** [comment] 2019-05-13 11:29
@JohnBeton22 @davidgraeff This is not the same issue. I believe it started happening with the Paho client upgrade. See [#815](https://github.com/openhab/openhab-core/issues/815).

**Comment by nanosonde** [comment] 2019-07-17 08:48
The binding has issues with certain topic names.
For example, I am using this project here: https://bitbucket.org/tobylorenz/sml2mqtt
It creates topics in these formats: 
stromzaehler/1-0:1.8.1*255
stromzaehler/1-0:1.8.2*255/$unit
stromzaehler/129-129:199.130.3*255

I cannot get those topics working with OpenHAB. 
My current workaround is to modify the sml2mqtt source code to use only [a-z] characters in the topic name. This way I got it working.

**Comment by davidgraeff** [comment] 2019-07-17 18:00
Yes the current code tries to map topic names to openHAB channel names and those have a very restricted allowed character set. A base48 conversion method has been added to the core to be used by mqtt but the mqtt binding hasn't been adopted yet.

**Comment by J-N-K** [comment] 2019-08-04 21:19
I think I found the problem. The `TopicSubscribers` class produces a regex-matcher from the topic but is not properly escaping all characters, whitespace is workimng for me but '*', '.' and '()' are a problem. This is core, not binding.

**Comment by wborn** [comment] 2019-08-05 20:28
Closing this issue because the fix by @J-N-K is now merged in OHC. :+1:

**Closed by wborn** 2019-08-05 20:28 UTC
Labels: ohc bug
