### ISSUE TITLE
[dbquery] Thing status unknown since openhab 4.2

### ISSUE THREAD

**Issue by rpsmonkey** [openhab/openhab-addons#17064] opened 2024-07-15 11:30 UTC
Hi all,

it's about add-on dbquery.

The status for the Bridge-Thing stays at "unknown" and queries are not working anymore.  
The dbquery thing query says, that the belonging bridge is offline. 

Problem exists since update to openhab version 4.2.0.
openhab version: 4.2.0
dbquery addon version: 4.2.0

I tried to reinstall add-on, delete and add again the Bridge Thing and deleted openhab cache with openhab-cli clean-cache.

On influxdb site nothing was changed (like updates, config, user, password, tokens, etc)

Kind Regards
Robert

Here some lines from openhab.log:
```
2024-07-15 09:42:16.827 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : ServiceFactory.ungetService()
2024-07-15 09:42:16.828 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : DependencyManager: osgi.ds.satisfying.condition close component unbinding from org.apache.felix.scr.impl.manager.ComponentContextImpl@43291c33 at tracking count 1 refpairs: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-15 09:42:17.439 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : ServiceFactory.getService()
2024-07-15 09:42:17.441 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : This thread collected dependencies
2024-07-15 09:42:17.442 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : getService (ServiceFactory) dependencies collected.
2024-07-15 09:42:17.442 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Querying state active
2024-07-15 09:42:17.443 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-15 09:42:17.443 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Changed state from active to active```

**Comment by lsiepel** [comment] 2024-07-21 11:48
What was the last known version for you that seemed to work?

From 4.1.0 to 4.2.0 there is only one PR: https://github.com/openhab/openhab-addons/pull/16458

**Comment by curro81** [comment] 2024-07-21 19:45
Hi, i have also the same Problem.
I upgraded vom 4.1.3 to 4.2.0

Here is my Bridge Code
```
UID: dbquery:influxdb2:XXXXXX
label: InfluxDB2 Bridge Growatt
thingTypeUID: dbquery:influxdb2
configuration:
  bucket: Growatt
  user: home
  url: http://10.1.1.5:8087
  organization: openHAB
  token: XXXXXXXXXXXXXX
```


When i enable the bridge, i see  this log.
Except for the 1st part the log repeats itself.
```

2024-07-21 21:32:16.410 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : ServiceFactory.getService()
2024-07-21 21:32:16.410 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : This thread collected dependencies
2024-07-21 21:32:16.410 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : getService (ServiceFactory) dependencies collected.
2024-07-21 21:32:16.410 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Querying state active
2024-07-21 21:32:16.410 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-21 21:32:16.410 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Changed state from active to active
2024-07-21 21:32:16.413 [DEBUG] [query.internal.DatabaseBridgeHandler] - connectDatabase Influx2Database{config=InfluxDB2BridgeConfiguration[url='http://10.1.1.5:8087', user='home', token='****************************************************************************************', organization='openHAB', bucket='Growatt']}
2024-07-21 21:32:16.414 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : ServiceFactory.getService()
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : This thread collected dependencies
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : getService (ServiceFactory) dependencies collected.
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Querying state active
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Changed state from active to active
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : ServiceFactory.getService()
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : This thread collected dependencies
2024-07-21 21:32:16.415 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : getService (ServiceFactory) dependencies collected.
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Querying state active
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Changed state from active to active
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : ServiceFactory.getService()
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : This thread collected dependencies
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : getService (ServiceFactory) dependencies collected.
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : Querying state active
2024-07-21 21:32:16.416 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (296)[org.openhab.binding.dbquery.action.DBQueryActions(349)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
```
The influxdb2 is working well. All values are saved as expected.

if you need more let me know.
THX for your help.

**Comment by lsiepel** [comment] 2024-07-21 20:34
Gentle ping @Skinah do you have any clue why this is not working? We mnight have to revert changes for dbquery.

**Comment by rpsmonkey** [comment] 2024-07-22 08:58
Last known version for me was 4.1.3.

This my debug log when enabling dbquery Thing.

`2024-07-22 10:50:08.187 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : ServiceFactory.getService()
2024-07-22 10:50:08.188 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : This thread collected dependencies
2024-07-22 10:50:08.188 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : getService (ServiceFactory) dependencies collected.
2024-07-22 10:50:08.188 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Querying state satisfied
2024-07-22 10:50:08.189 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-22 10:50:08.189 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Changed state from satisfied to active
2024-07-22 10:50:08.192 [DEBUG] [query.internal.DatabaseBridgeHandler] - connectDatabase Influx2Database{config=InfluxDB2BridgeConfiguration[url='http://192.168.1.23:8086', user='admin', token='****************************************************************************************', organization='daheim', bucket='pvforecast']}
2024-07-22 10:50:08.193 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : ServiceFactory.getService()
2024-07-22 10:50:08.194 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : This thread collected dependencies
2024-07-22 10:50:08.194 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : getService (ServiceFactory) dependencies collected.
2024-07-22 10:50:08.195 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Querying state active
2024-07-22 10:50:08.195 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-22 10:50:08.196 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Changed state from active to active
2024-07-22 10:50:08.196 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : ServiceFactory.getService()
2024-07-22 10:50:08.196 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : This thread collected dependencies
2024-07-22 10:50:08.197 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : getService (ServiceFactory) dependencies collected.
2024-07-22 10:50:08.197 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Querying state active
2024-07-22 10:50:08.198 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-22 10:50:08.198 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Changed state from active to active
2024-07-22 10:50:08.198 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : ServiceFactory.getService()
2024-07-22 10:50:08.199 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : This thread collected dependencies
2024-07-22 10:50:08.200 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : getService (ServiceFactory) dependencies collected.
2024-07-22 10:50:08.200 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Querying state active
2024-07-22 10:50:08.200 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : For dependency osgi.ds.satisfying.condition, optional: false; to bind: [[RefPair: ref: [{org.osgi.service.condition.Condition}={service.id=6, service.bundleid=0, service.scope=singleton, service.pid=0.org.osgi.service.condition.ConditionImpl, osgi.condition.id=true}] service: [null]]]
2024-07-22 10:50:08.200 [DEBUG] [inding.dbquery.action.DBQueryActions] - bundle org.openhab.binding.dbquery:4.2.0 (327)[org.openhab.binding.dbquery.action.DBQueryActions(447)] : Changed state from active to active`

My dbquery bridge thing config:
`UID: dbquery:influxdb2:6bee5ac6c4
label: InfluxDB2 Bridge Local
thingTypeUID: dbquery:influxdb2
configuration:
  bucket: pvforecast
  user: admin
  url: http://192.168.1.23:8086
  organization: daheim
  token: ***`

**Comment by Skinah** [comment] 2024-07-23 10:39
@lsiepel I have no idea why. I would recommend people install the InfluxDB binding even if they do not want/need it as it may install some missing dependencies when you install that binding. I had a huge pain getting that influxdb binding to work as it also uses the okio library. influxdb binding was building fine and then having issues during runtime, so it may be the same cause. If installing influxDB solves the issue for dbquery, then the fix should be easier to track down, so if a user can try and report back that would be great.

If there is an issue, then I would try dropping only okio back to 3.6 or 3.8 for just the one dbquery binding and leaving everything else as merged.
https://square.github.io/okio/changelog/

In the meantime I am currently installing a test server onto a pi3 to run a test to see if I can reproduce it here.

**Comment by rpsmonkey** [comment] 2024-07-23 11:12
Hi @Skinah, thanks a lot for debugging.

I have installed InfluxDB Persistence add-on and that is working fine, but still the same issue with dbquery. (for openhab version 4.2.0)

**Comment by Skinah** [comment] 2024-07-27 04:14
Can someone try this new jar please? Uninstall the merged copy first, then UNZIP this into your addons folder. A number of dependencies have changed in this build but its basically a copy of what fixed the influxdb bundle.

http://pcmus.com/openhab/org.openhab.binding.dbquery-4.3.0-SNAPSHOT.zip

**Comment by speham** [comment] 2024-07-27 09:48
> Can someone try this new jar please? Uninstall the merged copy first, then UNZIP this into your addons folder. A number of dependencies have changed in this build but its basically a copy of what fixed the influxdb bundle.
> 
> http://pcmus.com/openhab/org.openhab.binding.dbquery-4.3.0-SNAPSHOT.zip

Great thank you very much, you´re fix works.

**Comment by curro81** [comment] 2024-07-27 12:49
> Can someone try this new jar please? Uninstall the merged copy first, then UNZIP this into your addons folder. A number of dependencies have changed in this build but its basically a copy of what fixed the influxdb bundle.
> 
> http://pcmus.com/openhab/org.openhab.binding.dbquery-4.3.0-SNAPSHOT.zip

Works for me :-)
THX

**Comment by Skinah** [comment] 2024-07-28 01:05
Thanks for the testing and reporting back as openhabian only installs influx V1.8 and the binding needs v2 minimum, if what I read is correct. I could reproduce the issue, but can not test further without wasting a lot of time learning about influxDB2 and setting it up. Glad that it is fixed.

**Comment by rpsmonkey** [comment] 2024-07-28 09:39
Thanks a lot @Skinah! Also works for me.

**Closed** 2024-07-30 10:49 UTC
