### ISSUE TITLE
OH3 Daikin Binding : Setpoint for Temp Control not showing it's Control Card

### ISSUE THREAD

**Issue by jmone1** [openhab/openhab-addons#9659] opened 2021-01-02 20:53 UTC
When adding the Setpoint of a Dakin Air Con to the Semantic Model, it only displays the Analyse Graph instead of a Control Card (eg you can not change the Temp, just look at a graph of it).  More details and pics are in this thread - https://community.openhab.org/t/oh3-setpoint-issues-with-basicui/112431

**Comment by Hilbrand** [comment] 2021-01-02 21:08
If it works in the Android app it's not a bug in the binding, but very likely a problem with the new ui. Because for the binding there is no differences between Android app an ui. Please open an issue in the ui repository and explain the problem.

**Comment by psmedley** [comment] 2021-01-02 22:05
I also have issues relating to Setpoint - I can usually change the setpoint via the Android App, but when the same sitemap is rendered in the browser, the up and down controls do nothing.

**Comment by jmone1** [comment] 2021-01-03 01:37
The issue is that out of the Box, the binding does not allow for control of the Temp Set Point at all (in either OH3 UI or the Android App), it just graphs the value.  For testing, I've tried to change the associated metadata in OH3 UI to Default Standalone Widget --> oh-slider-card and that sort of works (works in OH3 GUI, but not in Android App)

**Comment by jimtng** [comment] 2021-01-15 05:02
> I also have issues relating to Setpoint - I can usually change the setpoint via the Android App, but when the same sitemap is rendered in the browser, the up and down controls do nothing.

I also experience this issue. Temporary solution: change the item definition from `Number:Temperature` to `Number`

**Comment by andrewfg** [comment] 2021-01-29 16:43
FYI I also see the issue with Tado thermostats and NeoHub thermostats, so I can confirm that **_this is not a binding issue_**, but rather a UI issue.

**Comment by andrewfg** [comment] 2021-03-31 14:20
Closed via https://github.com/openhab/openhab-core/pull/2165

**Closed by andrewfg** 2021-03-31 14:20 UTC
