### ISSUE TITLE
[keba] Unable to establish connection to wallbox

### ISSUE THREAD

**Issue by Orifahrer** [openhab/openhab-addons#6347] opened 2019-11-06 23:11 UTC
## Expected Behavior
Binding should connect to configured wallbox and do its job.

## Current Behavior
The binding tries to check for the existence of the configured wallbox in class KeContactHandler.pollingRunnable using InetAddress.isReachable

            if (!InetAddress.getByName(((String) getConfig().get(IP_ADDRESS))).isReachable(PING_TIME_OUT)) {

Unfortunately this check fails and the whole binding is not activated.
As far as I understand, the isReachable() method tries to perform a ping to the configured IP address (which works fine from the Raspi command line). For this ping to succeed from the Java code, openhab would require to be started as root user (which of course is not recommended at all). For testing I installed the 2.4.0 binding and started openhab as root user. The trace logging indicated a successful existence of the wallbox (but failed with some other exceptions later). So I assume the missing access rights cause the failure.

## Possible Solution
Instead of running openhab as root, I added a fallback check to the http port. It first performs the current isReachable check. In case of failure (which is true for my system all the time), it tries to open a socket to the http port (80). This works like a charm in my environment (I run my modified 2.3.0 keba binding for over a year now).

    private boolean checkKeba() throws IOException {
        boolean isReachable = InetAddress.getByName(((String) getConfig().get(IP_ADDRESS))).isReachable(PING_TIME_OUT);

        if (!isReachable) {
            logger.debug("InetAddress.isReachable failed, trying http port");

            SocketAddress sockAddr = new InetSocketAddress((String) getConfig().get(IP_ADDRESS),
                    REMOTE_CHECK_PORT_NUMBER);
            Socket socket = new Socket();

            try {
                socket.connect(sockAddr, PING_TIME_OUT);
                isReachable = true;
            } finally {
                socket.close();
            }

        }
        logger.debug("checkKeba returns {}", isReachable);
        return isReachable;
    }

I am not so familiar with forking and creating a pull request. Maybe somebody else could add that to the master branch, so I don't have to modify the code for each new version of the binding. :-) 

## Your Environment
Version used: openhab 2.4.0 stable, keba binding 2.4.0
Operating System and version: openHABianPi 4.19.66 on Raspberry Pi 3 B+
Keba Wallbox P30 x-series with firmware 3.9.10 connected via lan

**Comment by tiptick** [comment] 2019-11-14 14:27
please check if you entered your Keba via a hostname (e.g. mykeba.lan) vs a IP address (e.g. 192.168.0.100) please always enter a IP address. on my P30c it works fine with IP address.

**Comment by Orifahrer** [comment] 2019-11-14 14:34
> please check if you entered your Keba via a hostname (e.g. mykeba.lan) vs a IP address (e.g. 192.168.0.100) please always enter a IP address. on my P30c it works fine with IP address.

I am already using the IP address, as with a DNS name it is not working properly for me.
Are you running OH on a Raspi as well?

**Comment by tiptick** [comment] 2019-11-14 15:48
> Are you running OH on a Raspi as well?
yes, openhabian installation. 

how is your keba connected? Cable? wifi? Do you have package loss on the line?

Althou i will test your code and see if it works for me, by enforcing isreachable() to fail.

**Comment by Orifahrer** [comment] 2019-11-14 15:58
> > Are you running OH on a Raspi as well?
> > yes, openhabian installation.
> 
> how is your keba connected? Cable? wifi? Do you have package loss on the line?
> 
> Althou i will test your code and see if it works for me, by enforcing isreachable() to fail.

Last year it was connected via powerlan (unstable), but a month ago I connected it via cable. Since then it appears stable to me.

What confuses me is, that OH seems to be able to find the wallbox,  if I run it as root user. Maybe this indicates missing access rights?
Another difference might be, that I have a P30X, which is able to run as a master and therefore runs a different firmware. Maybe it reacts in a different way to those requests compared to a P30C.

**Comment by tiptick** [comment] 2019-11-14 21:10
can you try to give a higher value to PING_TIME_OUT , initial it is 3000 which should be enought, but try it with 10000 for testing maybe the timeout is not enougth for your setup. The access rights i think is not a issue as i would also have it.

**Comment by Raketenschnitzel** [comment] 2019-11-26 14:57
Well somehow i got pretty much the same issue with my setup. I configure the right IP adress but the KEBA P30 Wallbox values are not coming. Actually i tried two devices independently. 

# Your Environment
Version used: openhab 2.4.0 stable, keba binding 2.4.0
Operating System and version: Package Installation on Ubuntu 18.04.3 LTS
2 x Keba Wallbox P30 x-series with firmware 3.9.24 connected via Cable

**Comment by Orifahrer** [comment] 2019-11-27 16:01
No, I first need to set up a compilable environment again.
But I really doubt that a longer timeout will solve the issue. The command line responds immediately. According to several posts I read about the isReachable method, it might not be reliable in some environments.

@Raketenschnitzel: why do you run two x models of the Keba (vs. one x and one c Modell as master/slave)?

**Comment by tiptick** [comment] 2019-11-30 19:48
@Orifahrer @Raketenschnitzel 
please test this:
[org.openhab.binding.keba-2.5.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab2-addons/files/3907478/org.openhab.binding.keba-2.5.0-SNAPSHOT.jar.zip)

**Comment by tiptick** [comment] 2019-12-08 14:48
after testing the above change, with intentionally failing the ping (isreachable), also the binding connects over the http port80 method. so from my side we are all good.

**Comment by Raketenschnitzel** [comment] 2019-12-09 11:45
@Orifahrer: we simply have two devices in the Lab and i was checking if both are not responding. 
@tiptick: sry i ve overseen your demand. 

The port80 is a bad workaround in my oppion. The ping is even worse. Since we wan't to talk over udp port 7090 we shoul'd check the connectivity over that port, right?

I'am working on autodiscovery for the keba binding as well as an improvement of code quality in general. I hope to contribute this soon, but for now it's not official.

**Comment by Orifahrer** [comment] 2019-12-09 16:46
@Raketenschnitzel I agree the http check can be regarded as a workaround. At least it helped me to get my Keba connected. I appreciate other solutions as long as they solve the problem.

**Comment by Orifahrer** [comment] 2019-12-23 15:01
> after testing the above change, with intentionally failing the ping (isreachable), also the binding connects over the http port80 method. so from my side we are all good.

@tiptick
Today I finally found the time to update OH to 2.5 stable and added your snapshot jar. Works for me as well. Thanks a lot!
I would appreciate to have this in the next stable version. Could you issue a pull request please?
Due to the no longer existent Keba firmware check in the 2.5 Keba binding code, I can now start to update my Keba's firmware to the latest version. YES!

**Comment by tiptick** [comment] 2019-12-26 09:57
@Orifahrer 
welcome, but i also agree to @Raketenschnitzel : the port 80 method is not a good solution, as it is not really used by the addon to communicate with Keba, so udp 7090 should be the real one, let me check what we can do here.

**Comment by tiptick** [comment] 2019-12-31 15:25
ok seems to be little more complicated in the code than i initially thought. Mayor problem is the answer on udp from keba is received while the transceiver is still in init state, but already aquired the port in a different thread. 

so this will definitely takes more effort,

**Comment by Raketenschnitzel** [comment] 2020-01-06 22:48
So we solved that issue and added autodiscovery as well with a pretty good code quality. Its a complete rework. I have to talk with my colleagues about contribution but we probably do so soon. Maybe in some weeks.

**Comment by tiptick** [comment] 2020-02-01 11:10
@Raketenschnitzel any update that you can share with us?

**Comment by kaikreuzer** [comment] 2020-04-10 08:59
> So we solved that issue and added autodiscovery as well with a pretty good code quality. 

@Raketenschnitzel Sounds awesome and I would very much welcome a PR for it!

**Comment by MikeTheTux** [comment] 2021-02-13 19:59
I merged the changes from @Raketenschnitzel into OH3 trunk. You may want to give the resulting binding a try:
[org.openhab.binding.keba-3.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/5976367/org.openhab.binding.keba-3.1.0-SNAPSHOT.zip) (tested with OH3.0.1)

While debugging I figured out the following:
- There is a DIP Switch 1.3 on the Keba Box, where the required UDP interface can be enabled/disabled
- My Keba P30 X has an `E` in the identifier. As a workaround I extended `KebaSeries` as follows
```
        E('0'),
        B('1'),
        C('2', '3'),
        X('A', 'B', 'C', 'D', 'E');
```
- Merged the implementation of `isKebaReachable` from @Raketenschnitzel

**Comment by MikeTheTux** [comment] 2021-02-14 06:52
It seems that further versions of the X-series have been missing:
![grafik](https://user-images.githubusercontent.com/44850211/107870415-7ca1e080-6e98-11eb-8d86-b10cdc9827fc.png)

Added the missing ones and triggered a re-build:
```
        E('0'),
        B('1'),
        C('2', '3'),
        X('A', 'B', 'C', 'D', 'E', 'G', 'H');
```
[org.openhab.binding.keba-3.1.0-SNAPSHOT.zip](https://github.com/openhab/openhab-addons/files/5977106/org.openhab.binding.keba-3.1.0-SNAPSHOT.zip)

**Comment by kaikreuzer** [comment] 2021-02-14 15:55
> I merged the changes from @Raketenschnitzel into OH3 trunk.

@MikeTheTux Where can those be found? Is there an open PR with that?

**Comment by Chaosmax007** [comment] 2021-02-14 18:40
I have  upgraded to 3.1.0 as I had issues with 3.0 and now I get those msg every 10 to 20 seconds in my log

> 2021-02-14 19:32:15.428 [INFO ] [ba.internal.handler.KeContactHandler] - Running pollingRunnable to connect Keba wallbox
2021-02-14 19:32:36.834 [INFO ] [ba.internal.handler.KeContactHandler] - Running pollingRunnable to connect Keba wallbox
2021-02-14 19:32:58.390 [INFO ] [ba.internal.handler.KeContactHandler] - Running pollingRunnable to connect Keba wallbox

any chance to avoid thoe?

**Comment by MikeTheTux** [comment] 2021-02-14 18:46
> 
> 
> > I merged the changes from @Raketenschnitzel into OH3 trunk.
> 
> @MikeTheTux Where can those be found? Is there an open PR with that?

I guess here it is: https://github.com/openhab/openhab-addons/pull/10151
It's my first PR. Please provide direct feedback if something more is required.

**Comment by MikeTheTux** [comment] 2021-02-14 18:52
> Running pollingRunnable to connect

Thanks for reporting this finding. I will change the log-level of this message from `info` to `debug`.

**Comment by MikeTheTux** [comment] 2021-02-14 19:23
Here you can find the update without the info log:
[org.openhab.binding.keba-3.1.0-SNAPSHOT-20210214.zip](https://github.com/openhab/openhab-addons/files/5978332/org.openhab.binding.keba-3.1.0-SNAPSHOT-20210214.zip)

**Comment by Chaosmax007** [comment] 2021-02-14 19:39
thx for the quick fix. works for me.

**Comment by Orifahrer** [comment] 2021-02-15 20:51
The latest snapshot works for me as well. Now I can see some Keba numbers in OH3. Thanks!

**Comment by JanTTTTT** [comment] 2021-02-18 09:21
Dear community, I am new to OH3. Running on Synology docker container. Working super fine.. But: My new KEBA P30x (B) will not deliver data via the binding (as mentioned in this thread). It seems that the new snapshot (3.1.0) might work also for me... but how do I get my OH3 to update the KEBA binding to the new snapshot? When this snap will be available in a general update of OH3? Is there a how to for stupids/newbies regarding this issue? sorry for asking beginners questions in this threat..

**Comment by MikeTheTux** [comment] 2021-02-18 09:37
I fear that the KEBA P30 B-series does not provide the required UDP interface at all:
![image](https://user-images.githubusercontent.com/44850211/108336909-d37b2300-71d4-11eb-8637-5002c53752ee.png)
Therefore the binding will not work for E and B-series - C and X only.

If you own an C- or X-series, you can replace the official OH3.0.x binding with the one shared above.
- Uninstall official OH3.0.x binding
- Copy unzipped OH3.1.0 snapshot into addons-folder of your OH3 installation instead

**Comment by JanTTTTT** [comment] 2021-02-18 09:49
Hi Mike,
thanx for the quick response. Sorry for my misunderstanding description of my KEBA. Of course I have a fully fletched KEBA p30 series X (the “B” stands for the Wifi Option)..:-)

In my docker container installation I can find only the files in folders which are created during KEBA binding installation. Whenever I install KEBA binding it creates a new folder with the 3.01 Keba binding. Where do I find the folders with the repository of all addons/ bindings?

My actual path is: docker/openhab/userdata/tmp/mvn/org/openhab/addons/bundles/org,openhab.binding.keba

But this path leads only to the “installed” binding..

Sorry for asking stupid questions..
Best
Jan

Von: MikeTheTux <notifications@github.com>
Antworten an: openhab/openhab-addons <reply@reply.github.com>
Datum: Donnerstag, 18. Februar 2021 um 10:38
An: openhab/openhab-addons <openhab-addons@noreply.github.com>
Cc: Jan Traenckner <jt@venturecheck.com>, Comment <comment@noreply.github.com>
Betreff: Re: [openhab/openhab-addons] [keba] Unable to establish connection to wallbox (#6347)


I fear that the KEBA P30 B-series does not provide the required UDP interface at all:
[Das Bild wurde vom Absender entfernt. image]<https://user-images.githubusercontent.com/44850211/108336909-d37b2300-71d4-11eb-8637-5002c53752ee.png>
Therefore the binding will not work for E and B-series - C and X only.

If you own an C- or X-series, you can replace the official OH3.0.x binding with the one shared above.

  *   Uninstall official OH3.0.x binding
  *   Copy unzipped OH3.1.0 snapshot into addons-folder of your OH3 installation instead

**Comment by MikeTheTux** [comment] 2021-02-18 09:57
Don't care about the files in `userdata/tmp...`
De-install the official binding via the OH3 web interface. It will disappear from the path you mentioned above.
Copy the snapshot binding to `docker/openhab/addons` - it will be automatically loaded from this place.

**Comment by JanTTTTT** [comment] 2021-02-18 10:45
thanx for this advice.. unfortunately OH3 is still installing the 3.0.1:
docker/openhab/addons folder is completely empty. When I copy the snapshot .jar file there, OH3 is still installing the 3.01
![grafik](https://user-images.githubusercontent.com/79252023/108345559-b51a2500-71de-11eb-8f38-9210395bd9a0.png)

**Comment by MikeTheTux** [comment] 2021-02-18 11:01
once you copy it into the `docker/openhab/addons` it is already installed and loaded. You do not need to go back to A`dd binding add-ons`.

**Comment by JanTTTTT** [comment] 2021-02-18 11:13
got it! workink! thanx a lot.. genious!!

**Comment by shaselb** [comment] 2021-04-29 14:34
Hi guys,

i receive a error during installation in my docker (OH3.1.0.M3-debian)

2021-04-29 14:08:24.835 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/openhab/addons/org.openhab.binding.keba-3.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.keba [242]
  Unresolved requirement: Import-Package: org.apache.commons.lang; version="[2.6.0,3.0.0)"

Any idea how i can fix this issue?

King regards

Sascha

**Comment by MikeTheTux** [comment] 2021-04-30 16:08
Please give this one a try, when using latest OH3.1.0 versions.
- [org.openhab.binding.keba-3.1.0-SNAPSHOT-20210410.zip](https://github.com/openhab/openhab-addons/files/6290411/org.openhab.binding.keba-3.1.0-SNAPSHOT-20210410.zip)

There are some incompatible changes betwen OH3.0 and 3.1, that are already considered in this build.

**Comment by Chaosmax007** [comment] 2021-07-08 06:25
@MikeTheTux  thanks for updating the binding. Unfortunatley it does not work for me. 

`Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.keba-3.1.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.keba [305]
  Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"
	at org.eclipse.osgi.container.Module.start(Module.java:463) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:440) ~[org.eclipse.osgi-3.16.200.jar:?]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.8]`


I'm on OH 3.1.0
The keba binding which I could install via the UI works but I cannot set the "maxpresetcurrent" anymore. That worked fine while being on 3.0.x and using your binding dd Feb. 14th.

**Comment by MikeTheTux** [comment] 2021-07-10 06:20
> nresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"

This seems to be caused by a change in the OH3.1 environment. Re-Build of the add-on with the latest version might help. I might be able to do so within the next days. @Chaosmax007 I will share the new uip so that you can give it a try.

**Comment by shaselb** [comment] 2021-07-10 08:39
Hi Chaos,

may be declared the variable as Number:ElectricCurrent and forgot to set the units within your command. I have made the same mistake:

Have a look at this post:
https://community.openhab.org/t/keba-binding-resets-maxpresetcurrent-no-matter/118735/3

I am using the inetgrated version of the Keba Binding of M4 and it works fine.

Hope it helps

Sascha

**Comment by MikeTheTux** [comment] 2021-07-11 11:26
Hi @Chaosmax007,

I created a new version of the binding, adding a dependency to `javax.measure`:

- [org.openhab.binding.keba-3.2.0-SNAPSHOT-20210711.zip](https://github.com/openhab/openhab-addons/files/6796826/org.openhab.binding.keba-3.2.0-SNAPSHOT-20210711.zip)

Can you please check if your problem is gone when using the attached snapshot?

If not, please also give the proposal from @shaselb a try.
Please provide feedback.
mike

**Comment by Chaosmax007** [comment] 2021-07-12 08:06
@MikeTheTux thanks. I was able to load it without issues. I will check later if it works proper. 

@shaselb thanks for the link. I did some testing over the weekend and the integrated Keba Binding works on a fresh OH 3.1. installation but as soon I restore my configuration the binding doesn't work proper anymore. Not yet sure what the reason is and I hope this binding will solvemy issue.

**Comment by MikeTheTux** [comment] 2021-07-12 08:24
According to https://github.com/openhab/openhab-distro/releases there are some incompatible changes in the [keba] binding of OH3.1.0:

> Introduced Units of Measurements and the channel 'pwmpilotcurrent' was replaced by 'maxpilotcurrentdutycyle'. Items must be adapted and things created through the UI must be recreated.

I guess you need to re-integrate the binding from scratch in order to make it working after the incompatible update (i.e. UoM in some channels). @shaselb is pointing already into the same direction.

**Comment by Chaosmax007** [comment] 2021-07-17 15:55
new binding works now. Thanks for the update!

**Comment by MikeTheTux** [comment] 2021-07-18 06:12
Hi @Chaosmax007, I'm still struggling to commit these changes, because it might be that the problem is caused by the way how you are using the binding.

Can you please share how you declared the variable for the channel `maxpresetcurrent` and how you are sending the command?

**Comment by Chaosmax007** [comment] 2021-08-03 09:15
@MikeTheTux sorry for late reply I was on holidays. Unfortunatley openhab crashed during that time (not relatedt to the Keba Binding)  and now I'm back at 3.0.1
Anyways, following the asked details:

`Number KebaCurrent (gKeba) {channel="keba:kecontact:XXXXXXX:maxpresetcurrent"}
KebaCurrent.sendCommand(16 | A) `

Need to figure out why openhab crashed and set it up again.

**Comment by MikeTheTux** [comment] 2021-08-03 09:29
In order to use QuantityTypes `KebaCurrent` shall be defined as `Number:ElectricCurrent` instead of `Number` only.

**Comment by hmerk** [comment] 2022-04-29 06:37
Closed due to inactivity

**Closed by hmerk** 2022-04-29 06:37 UTC
