### ISSUE TITLE
[chromecast] Things go offline when sending stop command while "no application is running"

### ISSUE THREAD

**Issue by andiwirs** [openhab/openhab-addons#9591] opened 2020-12-30 09:20 UTC
## Expected Behavior
Chromecast Binding should ignore the stop command when no application is running

## Current Behavior
I have my google home minis setup with the Chromecast Binding. When sending a stop command when no application is running the follwing happens:

```
2020-12-30 10:10:40.831 [ome.event.ItemCommandEvent] - Item 'Sw_Sp_Stop_Lr' received command ON
2020-12-30 10:10:40.913 [nt.ItemStatePredictedEvent] - Sw_Sp_Stop_Lr predicted to become ON
2020-12-30 10:10:40.979 [hingStatusInfoChangedEvent] - 'chromecast:audio:GHM_LR' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): No application is running in ChromeCast
2020-12-30 10:10:42.851 [hingStatusInfoChangedEvent] - 'chromecast:audio:GHM_LR' changed from OFFLINE (COMMUNICATION_ERROR): No application is running in ChromeCast to ONLINE
```

## Context
I have made a group of all Chromecast STOP switches so that i can stop them all for example when i leave the house.
Of course not all Chromecast devices are running at all times, leading to these errors. Writing an extra rule that checks if something is running before sending the STOP is not elegant. IMO the binding should handle that.

## Your Environment
openHAB 2.5.11, on an up-to-date Raspbian, running on a NanoPi M4.

**Comment by lsiepel** [comment] 2023-01-01 18:52
As this issue is two years old, it might allready been fixed as there are several PR's merged since. Could you verify if this is still happening with 3.4.0? Last week there was also some PR merged to the (yet) unreleased 3.4.1 branch that solved some connection issues.

If this issue is still active, could you provide a debug log from the 3.4.0 version of the binding?

**Comment by andiwirs** [comment] 2023-01-02 09:23
I am on OH 3.4 now and the problem persists:

`2023-01-02 10:21:57.412 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Sw_Sp_Stop_Ki' received command ON
2023-01-02 10:21:57.414 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Sw_Sp_Stop_Ki' predicted to become ON
2023-01-02 10:21:57.473 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'chromecast:audio:GHM_KI' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): No application is running in ChromeCast
2023-01-02 10:21:59.483 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'chromecast:audio:GHM_KI' changed from OFFLINE (COMMUNICATION_ERROR): No application is running in ChromeCast to ONLINE

2023-01-02 10:22:07.195 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Sw_Sp_Stop_Br' received command ON
2023-01-02 10:22:07.196 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Sw_Sp_Stop_Br' predicted to become ON
2023-01-02 10:22:07.246 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'chromecast:audio:GHM_BR' changed from ONLINE to OFFLINE (COMMUNICATION_ERROR): No application is running in ChromeCast
2023-01-02 10:22:11.440 [INFO ] [ab.event.ThingStatusInfoChangedEvent] - Thing 'chromecast:audio:GHM_BR' changed from OFFLINE (COMMUNICATION_ERROR): No application is running in ChromeCast to ONLINE`

**Comment by lsiepel** [comment] 2023-01-03 09:53
Tried to reproduce the problem but i'm unable to get your results. When the stop button is pressed i see it is changed perfectly fine. I also noticed the running app changes to 'backdrop' while your setup logs that no app is runing. I guess this behaviour is changed in some firmware update.
What device do you use? revision and firmware? Can you also share your thing and item definition? If there is a firmware update, could you save the current version and update it? If that is the cause, we might need to update the documentation about compatibility.
```
2023-01-03 10:43:35.770 [INFO ] [openhab.event.ItemCommandEvent      ] - Item 'Chromecast_Audio_Stop' received command ON
2023-01-03 10:43:35.773 [INFO ] [penhab.event.ItemStatePredictedEvent] - Item 'Chromecast_Audio_Stop' predicted to become ON
2023-01-03 10:43:35.775 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Chromecast_Audio_Stop' changed from OFF to ON
2023-01-03 10:43:35.936 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'Huiskamer_App' changed from YouTube to Backdrop
```

**Comment by lsiepel** [comment] 2023-01-04 22:02
@andiwirs I might have a solution for 3.4.x branch here: https://1drv.ms/u/s!AnMcxmvEeupwjp4ILqWfPxAy7qJh4g?e=43fQde 
Changed the close app logic to check for the running app first. If it still shows an error could you show some debug logging?

You can place the jar from the link in your addons folder. Also you can enable debug logging from the karaf console `log:set debug org.openhab.binding.chromecast`

**Comment by andiwirs** [comment] 2023-01-05 07:08
Thanks your fix works. Errors are gone.

FYI: Because you asked, my devices that produced these errors where: 
1) Home mini 1. gen
2) Lenovo Smart Clock 2
3) Onkyo Smart Speaker G3

**Closed** 2023-01-07 08:51 UTC
