### ISSUE TITLE
[modbus] modbus binding identifies as HeliosEasyControls Binding

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#11256] opened 2021-09-17 15:30 UTC
Consistently in MainUI when I manually click "+" to add a new thing, in the presented list of all installed binding it's always named like this instead of 'Modbus' or other. I see this on several box with various OH versions incl. 3.1, 3.2M2.

On a sidenote, there's a typo ("reseting") in this error message please also fix
```
Try 2 out of 3 failed when executing request (ModbusReadRequestBlueprint [slaveId=1, functionCode=READ_INPUT_REGISTERS, start=12999, length=44, maxTries=3]). Will try again soon. Error was I/O error, so reseting the connection. Error details: net.wimpi.modbus.ModbusIOException I/O exception: SocketException Connection reset [operation ID 363322a7-d699-426b-8bb8-d4a3edaf2863]
```

**Comment by Rossko57** [comment] 2021-09-17 17:04
Duplicate of https://github.com/openhab/openhab-addons/issues/8973

**Closed** 2021-09-18 06:48 UTC
