### ISSUE TITLE
Hi, is there plan to support Matter devices?

### ISSUE THREAD

**Issue by chenliuyang1989** [openhab/openhab-addons#12908] opened 2022-06-08 15:11 UTC
## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by digitaldan** [comment] 2022-06-08 18:23
Duplicate of #10761

**Closed by digitaldan** 2022-06-08 18:23 UTC
Labels: enhancement
