### ISSUE TITLE
[openhabcloud] Appears offline but still able to send notifications

### ISSUE THREAD

**Issue by MikeJMajor** [openhab/openhab-addons#3031] opened 2017-12-27 00:04 UTC
I've had a couple of occasions when myopenhab reports my OH as offline and requires a stop/start of the cloud connector bundle or a restart of OH to get it back online. However, while it's offline my OH instance appears to be running ok and I'm still able to receive OH notifications in the android app.

I'm running OH 2.1 on a RPI 2 and the problem usually occurs around the same time as the monitoring website reporting problems.

**Comment by Flole998** [comment] 2018-01-11 23:53
The notifications are sent by http requests, probably to an external server. Definitely it's not the nodejs that's handling myopenhab reverse connections. So this is not an issue, it's just the server being overloaded.

**Comment by MikeJMajor** [comment] 2018-01-12 00:40
The issue I had was that myopenhab said I was offline for almost 23 hours and either it didn't reconnect or it did reconnect but myopenhab had the state confused. During those 23 hours I was still receiving notifications so I was connected to the internet ok.

The connection eventually came back following further server overload issues which I suspect resulted in the connection dropping causing a reconnect.

**Comment by Flole998** [comment] 2018-01-12 00:42
As i said, server overload and not an issue. Happened to me quite often, should be fixed once that server stuff is fixed. This is not an issue with the addon, if you think it is, you're more than welcome to provide a fix for it.

**Comment by MikeJMajor** [comment] 2018-03-12 07:17
This is still a problem. Last night my OH server disconnected and reconnected to myopenHAB. 

However, this morning Alexa was unable to control any lights and I could not access paperUI remotely. Restarting the cloud connector bundle immediately resolved both these issues.

**Comment by wborn** [comment] 2019-03-25 20:40
Looks like a duplicate of https://github.com/openhab/openhab-cloud/issues/134. Your instance it connected to the Cloud because you can send notifications. However the Cloud doesn't always seem to properly keep track of online/offline instances.

**Comment by hmerk** [comment] 2021-07-26 16:49
closed due to inactivity

**Closed by hmerk** 2021-07-26 16:49 UTC
