### ISSUE TITLE
[jellyfin] binding is *very* noisy

### ISSUE THREAD

**Issue by peterhoeg** [openhab/openhab-addons#12936] opened 2022-06-14 05:11 UTC
## Expected Behavior
I would imagine that the jellyfin binding logs recurring information with the `DEBUG` level.

## Current Behavior
The jellyfin binding uses the `INFO` level for regular updates every 30 seconds and thus filling up the log with:

```
Jun 12 08:29:58 hod openhab[131954]: [INFO ] [g.jellyfin.sdk.api.client.KtorClient] - GET http://jellyfin:8096/System/Ping
Jun 12 08:29:58 hod openhab[131954]: [INFO ] [g.jellyfin.sdk.api.client.KtorClient] - GET http://jellyfin:8096/Sessions?controllableByUserId=a-uuid&activeWithinSeconds=10
```

## Possible Solution
Change the default log level to `DEBUG`

## Steps to Reproduce (for Bugs)
1. Enable the jellyfin binding
2. Add a jellyfin Thing
3. Observe the log filling up

## Context
I typically run openhab with `INFO` as the debug level and jellyfin is currently adding a LOT of noise.

## Your Environment

* Version used: 3.2 and jellyfin binding 3.2
* OpenJDK 14
* Operating System and version: NixOS 22.05

**Comment by peterhoeg** [comment] 2022-06-14 05:18
Cc: @GiviMAD

**Comment by GiviMAD** [comment] 2022-06-14 14:27
The SDK seems to emit this as an info message.
We can try to always set the SDK log level to warning from the binding.

**Comment by peterhoeg** [comment] 2022-06-24 03:24
I'd argue that these 2 specific messages should be at `DEBUG` level rather than raising the default. That's assuming that is at all possible of course.

**Comment by lsiepel** [comment] 2023-08-12 18:24
External issue: https://github.com/jellyfin/jellyfin/issues/578 is closed due to inactivity, but more users seem to have this problem.

It might be usefull to raise the log level to max warning. As the sdk uses serilog, it might be done by a logging.json file:
https://jellyfin.org/docs/general/administration/configuration/#main-configuration

I can create the json, but i really don't know where to place it as i'm not familair with the dependency's and their folder structure etc. Is there another binding using such config file for a dependency ?

**Comment by GiviMAD** [comment] 2023-08-13 11:18
I think that issue is not related, as the issue is for the Jellyfin server, what we were talking here was about the jellyfin sdk logs. I'm not sure whetter this already has been solved, because the dependency has been updated since the issue was raised.

@peterhoeg are you still seeing those logs? I don't remember to see those recently.

**Comment by peterhoeg** [comment] 2023-08-14 07:47
I haven’t been using jellyfin for ages so I don’t have an immediate way to check, sorry.

**Comment by GiviMAD** [comment] 2023-08-14 14:34
> I haven’t been using jellyfin for ages so I don’t have an immediate way to check, sorry.

Thank you for the quick answer, I don't see them in my log so I will close this for now. I will check carefully next time I update the addon dependencies.

BR

**Closed by GiviMAD** 2023-08-14 14:34 UTC
