### ISSUE TITLE
[rrd4j] Persistence warnings

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#15220] opened 2023-07-10 08:47 UTC
Since recent persistence optimization by @J-N-K I'm seeing a lot of messages like the one below and so do several others on the forum. Running S3515.

I think it happens when I update(+persist) an item multiple times in one second.
To be clear, it's okay that this will only persist one value per second.
But the remaining updates should not result in WARN level output so at least the log level should be lowered to DEBUG.

```
2023-07-10 10:41:07.473 [WARN ] [org.openhab.persistence.rrd4j.internal.RRD4jPersistenceService   ] - RRD4J does not sup                                               port adding past value this=1688978467, last update=1688978468. Discarding Netzeinspeisung - -8.0
```

**Comment by J-N-K** [comment] 2023-07-10 18:02
What persistence strategy do you have?

**Comment by rkoshak** [comment] 2023-07-10 19:11
Yes.

```
Strategies {
        everyMinute  : "0 */1 * * * ?"
        default = everyChange
}
Items {
        * : strategy = everyMinute, everyChange
}
```

I use MapDB for restoreOnStartup so I created a .persist file. Based on the docs everyMinute/everyChange matches the default saving strategies which is why I used both. I wanted the default and to just disable restoreOnStartup.

**Comment by J-N-K** [comment] 2023-07-10 19:15
I guess that might be the issue (and I have no good idea how to solve that). When "everyChange" is triggered at second 0 of a minute, they may be scheduled with the same timestamp.

**Comment by rkoshak** [comment] 2023-07-10 19:30
> they may be scheduled with the same timestamp.

Does rrd4j save the everyMinute as a single transaction? It kind of looks like that might be the case and it makes sense that it would but it's hard to tell. 

If so, would it make sense to adjust the timestamp on events that come in during that transaction so it's not before the most recently saved record? At least with my warning entries and watching the debug logs it's looking like new events are blocked from being saved while the everyMinute is running. By the time the everyMinute is done the timestamp for the new event is now in the past. 

I'm sure it's worthy of a debate, but it seems like it would be less wrong to save the value with an off by one or two seconds timestamp than it is to throw away the value entirely meaning it won't actually be saved to the database (assuming it doesn't change in the mean time) until one minute later.

**Comment by J-N-K** [comment] 2023-07-10 19:41
Behind the scenes there is a scheduled job in core that calls the persistence service for each item that has the time-based strategy defined. This happens very quickly (probably faster than the persistence service is able to store them, because that happens sequentially) and if a large number of items is persisted, each of them is scheduled for storage as a single job. If an update occurs, it is also scheduled for storage, most likely after all time-based. That may explain the difference in the timestamps, opening 100 files, checking them, writing the new data and closing them might take quite some time.

**Comment by rkoshak** [comment] 2023-07-10 20:42
> That may explain the difference in the timestamps, opening 100 files, checking them, writing the new data and closing them might take quite some time.

Based on the logs, I can confirm that it takes about 2.5 seconds on my system to complete the everyMinute. It seems to take between 2 to 20 msec per Item. I've about 300 Items that gets saved to rrd4j. There are some 100+ msec gaps here and there too.

**Comment by J-N-K** [comment] 2023-07-10 21:13
This has always been the case, but the event handler was blocked until a write completed. This is why there were less (or no) collisions.

**Comment by J-N-K** [comment] 2023-07-10 21:16
One solution would be to use the timestamp when the data is really written to the file instead of the timestamp when `.store` is called. That may create times that are a few seconds off, but I believe for RRDs this is not such a great issue as data is usually binned on larger scales.

**Comment by rkoshak** [comment] 2023-07-10 21:20
I personally would be happy with that. A few seconds this way or that is better than just short of a whole minute.

**Closed** 2023-07-13 20:11 UTC
