### ISSUE TITLE
[mqtt] support availability transformation in generic mqtt thing

### ISSUE THREAD

**Issue by mdeanda** [openhab/openhab-addons#10226] opened 2021-02-24 23:07 UTC
i have a few devices that send availability messages to some topic `/status` that are json and include a little bit of extra metadata:

ONLINE:

{"status":"ONLINE", "timestamp": .... }

OFFLINE:
{"status":"OFFLINE", ...}

oh3 doesn't let me extract the "status" field from the json so the thing always shows up as offline

**Comment by jochen314** [comment] 2021-03-06 09:11
The availability is thought of to be used with and LWT message from the device.
Ithe the device can still send messages, then it is still available.

**Comment by mdeanda** [comment] 2021-03-07 05:18
@jochen314 yeah its how i'm using it, but in my device, (an esp32 using autoconnect) i have the device auto-restart if it detects the network dropped and it actually reconnects (and sends the "online") before the LWT message gets to the oh3 client. for example:

```
time   normal flow                                  after device restart
-------------------------------------------------------------------------
   1   online
   2   online
   3   online
   4   online
... [network is detected as down somewhere in here]
  10                                                online
  11   offline (lwt)
  12                                                online
  13                                                online

```

so my solution for this situation was to just send `online` messages every few minutes. all my messages from the app i made are as json and include timestamps for potential tracking/logging use. by sending the messages every few minutes, it prevents a restarted device from getting stuck in `offline` because of a slow-to-arrive LWT message.

**Comment by jochen314** [comment] 2021-03-07 16:12
There should not be an out-of-order of messages in a single topic.
When the device

1. Sends an 'Online' message on topic 'state' (QoS: 2, retained: true) once online.
2. Sets an LWT 'Offline' on topic 'state' (QoS: 2, retained: true)

Then openhab will get the messages in the correct order.

**Comment by jimtng** [comment] 2022-01-30 02:19
This is a duplicate of https://github.com/openhab/openhab-addons/issues/10632

**Closed** 2022-02-06 09:30 UTC
