### ISSUE TITLE
[openwebnet] Receiving messages from the bus as far as alarm control (WHO=5 and WHO=9)

### ISSUE THREAD

**Issue by fabgio** [openhab/openhab-addons#12639] opened 2022-04-22 13:49 UTC
[openwebnet] Aux commands can be used ONLY to send messages to the BTcino alarm unit with the consequence  that there is no feedback from the bus (ON/OFF status etc..) .  Therefore,  the present issue has the aim to implement WHO=5 to get such    return messages from the bus

**Comment by mvalla** [comment] 2022-04-24 09:27
> [openwebnet] Aux commands can be used ONLY to send messages to the BTcino alarm unit 

Actually AUX (WHO=9) messages can be received from the BUS as other users have shown and as it's documented in the official specs. 
However support to receive AUX messages as events from BUS is not currently offered by the binding.

Regarding support for WHO=5 messages, this is already requested/reported in #12569, so this issue here is a partial duplicate of that issue.

**Closed** 2022-04-24 09:39 UTC
Labels: duplicate, invalid
