### ISSUE TITLE
[boschindego] Bosch Indego binding not working anymore. Possible API change.

### ISSUE THREAD

**Issue by BillGOH** [openhab/openhab-addons#12720] opened 2022-05-11 14:32 UTC
Bosch seems to have changed the API access recently. That means that the binding can no longer log into the Bosch server. Error: "The login credentials are wrong or another client connected to your Indego account"

I posted the problem [here ](https://community.openhab.org/t/boschindego-bosch-indego-binding-not-working-any-more/135825)an it got confirmed. Possible solution [here](https://forum.iobroker.net/topic/9915/adapter-f%C3%BCr-bosch-indego-connect/198?lang=en-GB&page=10).

My system: openHAB 3.2 with openHABian.

Thanks for help!

**Comment by BillGOH** [comment] 2022-05-12 17:47
The binding relies on https://github.com/zazaz-de/iot-device-bosch-indego-controller. Changes need to be made there, issue is already open.

**Comment by real-easy** [comment] 2022-05-19 18:31
bosch say´s, you can use IFTTT (paid, only stop, start, no status) Alexa or Google, other systems will not supported.

this ioBroker mod actualy works.

https://forum.iobroker.net/topic/9915/adapter-f%C3%BCr-bosch-indego-connect/198?lang=en-GB&page=10

so i changed from indego->mqtt->openhab   to    indego->iobroker->mqtt->openhab.

**Comment by jlaur** [comment] 2022-05-23 15:35
Summary:
- `accept_tc_id: '202012'` needs to be added to the request.
- The binding is dependent on **bosch-indego-controller-lib**.

Solutions:
- We can wait for the library to be updated: zazaz-de/iot-device-bosch-indego-controller#22 fixes the issue.
- We can implement the protocol in openHAB and remove the dependency.

Since PR towards the library is already created, let's hope for the mentioned PR being merged soon, so we can quick-fix the issue without a major rewrite.

See also: https://github.com/withstu/ioBroker.boschindego/commit/acd628409c9a4a37486bbfa6bd82be6a548ed41c

**Comment by real-easy** [comment] 2022-05-23 15:37
ok i try...

on my openhab pc is also running the mosqitto MQTT server.
i think we all have an MQTT server already.

install iobroker somewhere (my runs on an windows 10 virtual machine)
in iobroker install the MQTT adapter. (and connect with your MQTT server)
in iobroker install the indego adapter with manual install from this github: (search for the litte github kitten)
https://github.com/withstu/ioBroker.boschindego

after this configure the indego, fill in your mail and password.
then this adapter connects to indego and get the data.
you can check this under objects in the left panel.
here you see all states from and to the indego, great for monitoring.

in iobroker at the configuration of the MQTT adapter is an error, here is missing the entry for publication.
so we have to export the settings with the down arrow in the top right corner.
then edit the file.

change the line with the publisch statement.
`"publish": "boschindego.*",`

then save this file and import over the up arrow (in the top right corner)
after this uncheck and check some other setting to enable the save button.

dont forget to check the "publisch by change" and the "send states" options.
(my are german, i dont know the right labels)

if all works, then every change of the indego will publisch to the MQTT.
now you can change your OH items and things to get the states and commands to OH.

my indego is offline since this weekend. 
also the android APP say offline.
so also this iobroker workaround cant work at this time.

**Comment by jlaur** [comment] 2022-06-06 12:51
I recently purchased an Indego M+ 700 which I installed yesterday. Today I have created a draft implementation of the protocol based on the **bosch-indego-controller-lib**. I have it running now using Jetty HTTP client and GSON.

**Comment by jlaur** [comment] 2022-06-06 21:49
@BillGOH - I have progressed further during the day, and now have a beta version ready for testing:
https://drive.google.com/file/d/1bTr2sfFaZus-xrTaZ3g4qZrmju0Hhvy0/view?usp=sharing

Any feedback would be much appreciated. I expect to create a pull request soon.

**Comment by BillGOH** [comment] 2022-06-07 17:33
@jlaur Thank you very much for your help. Looks good so far.

However, the bosch-indego-controller-lib seems to be somewhat outdated, e.g. textual state says "Unknown status code 64513". 

Is there a chance to integrate some more features in the binding like getting the next mow time and the finish time of the last mowing?

**Comment by BillGOH** [comment] 2022-06-07 18:06
There seems to be an issue: After the the refresh intrervall (180 sec) I get several error messages:
`[WARN ] [.core.thing.binding.BaseThingHandler] - Handler BoschIndegoHandler tried updating the thing status although the handler was already disposed.`

**Comment by real-easy** [comment] 2022-06-07 18:35
status-code 64513 means stoped from user (with API) and docked.

**Comment by jlaur** [comment] 2022-06-07 19:52
@BillGOH - don't worry, I'm also having the "handler was already disposed" issue so I'm looking into it, that's also why I haven't created a pull request just yet. :-) Since I've rewritten the indego library from scratch natively within the binding, we can also easily add new features. Additional status codes can be added now, other new features I'll probably do in subsequent pull requests. That way we'll have a new baseline just bringing back the existing feature set before extending it.

@real-easy - can you provide the actual text displayed on the mower while having the 64513 status code? I'm not sure how the original texts were obtained, but I'd like some kind of verification of the meaning, so if displayed on the device, that could be one way to do it.

**Comment by real-easy** [comment] 2022-06-07 20:17
there is no text on the mover display, the mover is in the docking station.

the status 64513 may be new. i have this since the change to iobroker. 
may be this is new from bosch, after the login change.

if the mower stops self after mowing, the status will be 258 (docked).
if the mower get the stop signal over the api (... i send it by rain ...) then the mower have the 64513 state in the docking station.

the display on the mower dit not show thie difference.
also in the app is this difference not shown

**Comment by jlaur** [comment] 2022-06-07 20:26
I've found the "handler was already disposed" bug now and fixed it - and also added 64513 as "Docked". New JAR available using same link.

**Comment by jlaur** [comment] 2022-06-07 22:08
@BillGOH and @real-easy, please fetch latest JAR (from same link) and retest. I nailed all problems I could find and also published the pull request (as draft). When you have tested it and any possible regressions have been addressed, I will publish the pull request to hopefully get the fix included with openHAB 3.3.

**Comment by real-easy** [comment] 2022-06-08 08:26
tanks for your work, since the login-change-trouble i changed over to ioBroker.
i changed a lot of items, my rules and my sitemap. (also becuase the 64513)
meanwhile it works realy well an i see also the mower-map on my sitemap.

dont be angry to me, but i have not the time to test your work and change back.
may be at the next change i am the first do contact you...

i am sure the next change will happen.

in the last 4 years, bosch changes every year.
over the last 2 years i must have an virtual android with tasker and the indego-app to hold open the login-state.
in the year bevore i have startet the indego-mqtt-lib every hour to hold open this state.

i think bosch will reduce the users of the api wich will always be connectet to the server.
at this time they changes the login and cut many users.
if all users are back i think they will go the next step.

here are two answers from bosch to me, after i ask for documentation an suportet systems.
becuase the IFTTT suport is only a joke... (only send the 3 commands and get nothing back)

```
Zu Systemen, die offiziell nicht von uns unterstützt werden, können wir keine Auskunft geben.
Die aktuelle API wird nicht veröffentlicht.
Wenn Sie uns eine genauere Problembeschreibung schicken, werden wir es uns gern ansehen und versuchen, Ihnen behilflich zu sein.
```

```
Wir danken Ihnen für Ihre interessanten Bemerkungen und Vorschläge. Ich habe diese an unser App-Team weitergeleitet, damit diese in Erwägung genommen werden können.
Unser Indego lässt sich auch mit Alexa und Google Home verbinden als Teil der Hausautomatisation. Eventuell kann eines dieser Geräte von Interesse sein.
```

i will and can not test google or amazon, but i can image that here is also no status back to our systems. 

i tell them that if i must use a cloud, then only the bosch-api-cloud and not google or amazon.

my next mower has only local wifi, or i modify my indego to an ardumower... 
if bosch dont want users... then i dont will be an user....

**Comment by BillGOH** [comment] 2022-06-08 16:39
@jlaur Again, thanks for your work. I can test it at the weekend!

**Comment by jlaur** [comment] 2022-06-08 17:18
@real-easy - thanks for your feedback, and no worries at all. Since I purchased an Indego myself, I will probably play "catch up" with ioBroker and see if I can add some missing features supported by the API. If I'm successful you will return to the openHAB binding. :-)

@BillGOH - thanks for volunteering to test. I have done some basic testing myself, although my Indego currently cannot cut ("# 1160 Cutter stopped/Sensor error"). I will mark the pull request ready for review now. In case it will be merged before the weekend, I'll do follow-up PR's. I also want it merged as baseline before I start adding new features.

**Comment by jlaur** [comment] 2022-06-09 20:11
New version uploaded with improved session handling avoiding re-authorization for each polling (or command).

**Comment by gafk** [comment] 2022-06-12 09:04
Just tried the latest .jar file  and all seems fine 👍 

What I did:
- Disable mower thing via UI
- Uninstall original binding
- Shutdown OH
- Delete Cache & Temp
- Copy .jar to addon folder
- Start OH
- Enable thing again

Thanks for the fix!

**Comment by BillGOH** [comment] 2022-06-12 15:17
@jlaur Tests look good so far. Many thanks for your efforts. I could send the "mow" command to the mower successfully, "pause", however, did not work (could be a problem of my UI). I will test further.

**Closed** 2022-06-14 20:51 UTC
