### ISSUE TITLE
[icalendar] doesn't handle all exceptions to recurring events

### ISSUE THREAD

**Issue by rolandmas** [openhab/openhab-addons#9735] opened 2021-01-07 16:20 UTC
It seems to me that when I define a recurring event, the icalendar binding doesn't understand all the exceptions. Namely, if one of the occurrences is simply deleted, then the binding does see it as such and doesn't trigger an event; hovewer, for occurrences that are modified (such as moved in time), the binding doesn't see that change and keeps the appointment at the initial (recurring) time.

For instance, I'm attaching an example .ics file with one event starting on Jan 1st 2022 at noon, recurring every year. I deleted the 2022 occurrence, and moved the 2023 occurrence to 2pm instead of noon. While doing this, I kept an eye on the "next_start" item.

## Expected Behavior
Creation of the event: next_start is 2022-01-01 12:00
Make it recurrent yearly: next_start is 2022-01-01 12:00
Delete the 2022 occurrence: next_start is 2023-01-01 12:00
Edit the 2023 occurrence: next_start is 2023-01-01 14:00

## Current Behavior
Creation of the event: next_start is 2022-01-01 12:00
Make it recurrent yearly: next_start is 2022-01-01 12:00
Delete the 2022 occurrence: next_start is 2023-01-01 12:00
Edit the 2023 occurrence: next_start is 2023-01-01 12:00 (here's the bug)

## Steps to Reproduce (for Bugs)
* Use the [test.ics.txt](https://github.com/openhab/openhab-addons/files/5782741/test.ics.txt) file as an icalendar source
* Define the appropriate items (at least ...:next_start)
* Check the ...:next_start item

## Context
This issue is a problem because I'm using the calendar to control lighting in a waiting room based on appointments stored in a CalDAV calendar. It works when people cancel their appointments, but when the appointments are moved, the lighting gets out of sync.

## Your Environment
* Version used: up-to-date OpenHAB 2.5.11, installed from http://dl.bintray.com/openhab/apt-repo2 stable/main
* Environment name and version: calendar stored on Nextcloud 20
* Operating System and version: Raspbian Buster on Raspberry Pi3

**Comment by daMihe** [comment] 2021-01-09 21:36
Duplicate of #9647. Fixed in snapshot.

**Closed by daMihe** 2021-01-09 21:36 UTC
