### ISSUE TITLE
[DSMR] Serial Library connection lost

### ISSUE THREAD

**Issue by Jordo-o** [openhab/openhab-addons#10381] opened 2021-03-23 10:31 UTC
## Story
After running for a few days (4 to 7) the binding states an error: “No data received from Smart Meter” and after restarting the DSMR binding “Serial port does not exist”.

Only a restart of OpenHAB or the device fixes the problem. And then it can run for like 4 to 7 days.
I already checked my logging and searched for problems with serial communication, but unfortunately I couldn’t find anything usefull.

Already discussed the problem with the [community](https://community.openhab.org/t/serial-communication-stops-working-oh3/117203).

## Expected Behavior
It would be nice if the binding kept running for longer then a few days.
A restart now and then isn't a problem, but multiple times a week is a bit annoying.

## Current Behavior
After running for a few days (4 to 7) the binding states an error: “No data received from Smart Meter” and after restarting the DSMR binding “Serial port does not exist”. Reinstalling the binding and re-adding the device didn't work.

## Config
The smart meter is connected on the serial interface of the Raspberry Pi 3B+ GPIO.
The signal is enverted with a logic inverter to make the signal readable for the Serial library.

```
thingTypeUID: dsmr:dsmrBridge
configuration:
  receivedTimeout: 30
  serialPort: /dev/ttyS0
```

## Context
The data is used to be logged in via the OpenHAB MySQL connection.
When the binding stops, useless data is logged into the database (eg. NULL).

## Environment
* OpenHAB 3.1.0.M2 - Milestone Build
* Raspberry Pi 3B+
* Linux raspberrypi 5.10.17-v7+ (Debian Armv71)
* OpenJDK Client VM Zulu11.41+75-CA (build 11.0.8+10-LTS, mixed mode)

**Comment by Hilbrand** [comment] 2021-03-24 18:47
The binding should be very resilient against connection problems. So even with connection.problems it tries to restart.Therfor I doubt the problem is with the binding or something that can be fixed in the binding. It could be a problem with the library or a combination of the library with hardware issues.. I remember having a similar problem that was caused by an unstable converter hardware. If you have this problem can you check if you can connect to the meter from the command line and see if you receive any data.

**Comment by fwolter** [comment] 2021-03-28 21:40
This problem can be caused by openhab/openhab-core#1842.

**Comment by Jordo-o** [comment] 2021-03-30 07:44
>  I remember having a similar problem that was caused by an unstable converter hardware. If you have this problem can you check if you can connect to the meter from the command line and see if you receive any data.

I now opened the serial port via the command line with "cat /dev/ttyS0".
And now the output is comming out correctly, although I had to change the default BAUD rate of the serial port before I could read anything. So I think it is not in the hardware.

Also, now OpenHAB states that the serial port does not exist:
`Serial port does not exist.`.

I looks like the Serial port gets locked or something.

**Comment by Jordo-o** [comment] 2021-04-09 14:18
Looked into the logging after the connection has stopped and found this:
```
2021-04-02 04:19:18.090 [WARN ] [device.connector.DSMRSerialConnector] - RuntimeException during handling serial event: 1
java.lang.StringIndexOutOfBoundsException: begin 0, end 1, length 0
        at java.lang.String.checkBoundsBeginEnd(String.java:3319) ~[?:?]
        at java.lang.String.substring(String.java:1874) ~[?:?]
        at java.lang.String.subSequence(String.java:1913) ~[?:?]
        at tec.uom.se.format.DefaultQuantityFormat.parse(DefaultQuantityFormat.java:79) ~[bundleFile:?]
        at tec.uom.se.quantity.Quantities.getQuantity(Quantities.java:78) ~[bundleFile:?]
        at org.openhab.core.library.types.QuantityType.<init>(QuantityType.java:100) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.cosem.CosemQuantity.getStateValue(CosemQuantity.java:103) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.cosem.CosemQuantity.getStateValue(CosemQuantity.java:1) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.cosem.CosemObject.parseCosemValues(CosemObject.java:127) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.cosem.CosemObjectFactory.getCosemObjectInternal(CosemObjectFactory.java:169) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.cosem.CosemObjectFactory.getCosemObject(CosemObjectFactory.java:129) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.p1telegram.P1TelegramParser.storeCurrentCosemObject(P1TelegramParser.java:382) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.p1telegram.P1TelegramParser.setState(P1TelegramParser.java:414) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.p1telegram.P1TelegramParser.parse(P1TelegramParser.java:224) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.DSMRTelegramListener.handleData(DSMRTelegramListener.java:74) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.connector.DSMRBaseConnector.handleDataAvailable(DSMRBaseConnector.java:116) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.connector.DSMRSerialConnector.handleDataAvailable(DSMRSerialConnector.java:317) ~[bundleFile:?]
        at org.openhab.binding.dsmr.internal.device.connector.DSMRSerialConnector.serialEvent(DSMRSerialConnector.java:276) [bundleFile:?]
        at org.openhab.core.io.transport.serial.rxtx.RxTxSerialPort$1.serialEvent(RxTxSerialPort.java:82) [bundleFile:?]
        at gnu.io.RXTXPort.sendEvent(RXTXPort.java:834) [bundleFile:5.2.1]
        at gnu.io.RXTXPort.eventLoop(Native Method) [bundleFile:5.2.1]
        at gnu.io.RXTXPort$MonitorThread.run(RXTXPort.java:108) [bundleFile:5.2.1]

```

It is only a warning, so I doubt if this is the cause of the problem.

I also see the binding starting up, after restarting openhab. 
And then this is the first message about DSMR and also for serial.

**Comment by Jordo-o** [comment] 2021-04-28 18:07
Recently I edited some settings for the connection to the smart meter:
```
thingTypeUID: dsmr:dsmrBridge
configuration:
  receivedTimeout: 10
  serialPort: /dev/ttyS0
```

And removed an device from the 5V output from the GPIO (on which the serial connection to the smart meter is also connected). And the connection is now working for more then 2 weeks. 

Looks like a power shortage on the communication logic for the pi to the smart meter.

**Closed** 2021-05-18 10:14 UTC

**Comment by hansbogert** [comment] 2023-07-08 17:56
I got the 'serial port does not exist' when there was a lingering lock file in `/var/lock/`. After removing that, everything worked like a charm again. A sudden powercut was the cause of the issue.
