### ISSUE TITLE
[NEATO] OH3.RC1 Scan for robot item fails with Exception

### ISSUE THREAD

**Issue by jensflorian** [openhab/openhab-addons#9392] opened 2020-12-15 19:17 UTC
## Expected Behavior
After starting "Scan" a neato:vacuumcleaner (in my case a BotVac D7) should be added to the inbox.
## Current Behavior
No item is created by scan although item can be created manually.

## Possible Solution

Add Vacuumcleaner manually, this however requires a secret key (not implemented so far, see: https://github.com/openhab/openhab-addons/issues/4185 so you have to use external scripts such as pybotvac). 

## Steps to Reproduce (for Bugs)

1. Set up your cleaner with the neato app and have a working account at neatorobotics.com
2. Install neato binding and set up neato account and wait until account is online.
3. Set log to TRACE
4. Start search. In the UI nothing is added.

`2020-12-15 20:05:51.575 [DEBUG] [internal.handler.NeatoAccountHandler] - Attempting to find robots tied to account
2020-12-15 20:06:06.582 [DEBUG] [internal.handler.NeatoAccountHandler] - Error when sending Authentication request to Neato.
java.io.IOException: java.lang.InterruptedException
	at org.openhab.core.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:260) ~[bundleFile:?]
	at org.openhab.core.io.net.http.HttpUtil.executeUrl(HttpUtil.java:156) ~[bundleFile:?]
	at org.openhab.core.io.net.http.HttpUtil.executeUrl(HttpUtil.java:131) ~[bundleFile:?]
	at org.openhab.binding.neato.internal.handler.NeatoAccountHandler.sendAuthRequestToNeato(NeatoAccountHandler.java:125) ~[bundleFile:?]
	at org.openhab.binding.neato.internal.handler.NeatoAccountHandler.authenticate(NeatoAccountHandler.java:109) [bundleFile:?]
	at org.openhab.binding.neato.internal.handler.NeatoAccountHandler.getRobotsFromNeato(NeatoAccountHandler.java:92) [bundleFile:?]
	at org.openhab.binding.neato.internal.discovery.NeatoAccountDiscoveryService.findRobots(NeatoAccountDiscoveryService.java:56) [bundleFile:?]
	at org.openhab.binding.neato.internal.discovery.NeatoAccountDiscoveryService.lambda$0(NeatoAccountDiscoveryService.java:73) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345) ~[?:?]
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232) ~[?:?]
	at org.eclipse.jetty.client.util.FutureResponseListener.get(FutureResponseListener.java:100) ~[bundleFile:9.4.20.v20190813]
	at org.eclipse.jetty.client.HttpRequest.send(HttpRequest.java:685) ~[bundleFile:9.4.20.v20190813]
	at org.openhab.core.io.net.http.HttpUtil.executeUrlAndGetReponse(HttpUtil.java:251) ~[bundleFile:?]
	... 13 more`

## Your Environment

* OH3 RC1
* Safari
* OSX Catalina

**Comment by jjlauterbach** [comment] 2020-12-28 18:41
I'm not able to reproduce this same issue.  I just tried on a brand new OH3 instance.

**Comment by jjlauterbach** [comment] 2021-06-11 00:39
Is this still reproducible?  If not - I think it can be closed

**Comment by lsiepel** [comment] 2023-01-08 21:21
As two years have passed, the issue could not be reproduced and there was no repsonse to the request for information, i close this issue. Please re-open if there is anything to add.

**Closed by lsiepel** 2023-01-08 21:21 UTC
