### ISSUE TITLE
[astro] Sun phase name incorrect - NIGHT when it should be DAYLIGHT

### ISSUE THREAD

**Issue by Dopeyr** [openhab/openhab-addons#7642] opened 2020-05-14 19:21 UTC
## Expected Behavior

The "Sun Phase Name" to always be correct.

## Current Behavior

The "Sun Phase Name" can be incorrect on certain days, at certain times.

On 13th May 2020 I found that at 05:17 the phase name switched to DAYLIGHT, then a few seconds later to NIGHT. 

* A openhab restart at 09:23 still showed the phase as NIGHT. 
* A openhab restart at 12:12 showed the phase correctly as DAYLIGHT.

This is the events.log filtered by phase name:

```
2020-05-12 13:07:09.285 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from DAYLIGHT to NOON
2020-05-12 13:12:09.284 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NOON to DAYLIGHT
2020-05-12 20:56:00.010 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from DAYLIGHT to SUN_SET
2020-05-12 21:00:00.008 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from SUN_SET to CIVIL_DUSK
2020-05-12 21:44:00.006 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from CIVIL_DUSK to NAUTIC_DUSK
2020-05-12 22:45:00.009 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NAUTIC_DUSK to ASTRO_DUSK
2020-05-13 00:00:30.396 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from ASTRO_DUSK to ASTRO_DAWN
2020-05-13 03:27:00.007 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from ASTRO_DAWN to NAUTIC_DAWN
2020-05-13 03:27:09.284 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NAUTIC_DAWN to NIGHT
2020-05-13 04:29:00.006 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NIGHT to CIVIL_DAWN
2020-05-13 04:32:09.288 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from CIVIL_DAWN to NIGHT
2020-05-13 05:13:00.006 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NIGHT to SUN_RISE
2020-05-13 05:17:00.004 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from SUN_RISE to DAYLIGHT
2020-05-13 05:17:09.288 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from DAYLIGHT to NIGHT
```

And all astro changes after the restart at 09:23 (phase incorrect):

```
2020-05-13 09:43:33.576 [hingStatusInfoChangedEvent] - 'astro:sun:9fe96e5d' changed from UNINITIALIZED to INITIALIZING
2020-05-13 09:43:33.754 [hingStatusInfoChangedEvent] - 'astro:sun:9fe96e5d' changed from INITIALIZING to ONLINE
2020-05-13 09:43:34.826 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_duration changed from NULL to 4
2020-05-13 09:43:34.920 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_end changed from NULL to 2020-05-13T13:08:00.000+0100
2020-05-13 09:43:34.993 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_end changed from NULL to 2020-05-13T03:27:00.000+0100
2020-05-13 09:43:35.024 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_duration changed from NULL to 44
2020-05-13 09:43:35.026 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_duration changed from NULL to 1
2020-05-13 09:43:35.027 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_end changed from NULL to UNDEF
2020-05-13 09:43:35.027 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_end changed from NULL to 2020-05-13T22:48:00.000+0100
2020-05-13 09:43:35.029 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eclipse_total changed from NULL to 2020-12-14T16:15:00.000+0000
2020-05-13 09:43:35.051 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_end changed from NULL to 2020-05-13T05:17:00.000+0100
2020-05-13 09:43:35.056 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_start changed from NULL to UNDEF
2020-05-13 09:43:35.098 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_start changed from NULL to 2020-05-13T20:57:00.000+0100
2020-05-13 09:43:35.123 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_end changed from NULL to 2020-05-13T21:46:00.000+0100
2020-05-13 09:43:35.128 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_start changed from NULL to 2020-05-13T03:27:00.000+0100
2020-05-13 09:43:35.134 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eveningNight_start changed from NULL to UNDEF
2020-05-13 09:43:35.177 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_duration changed from NULL to 62
2020-05-13 09:43:35.178 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_start changed from NULL to 2020-05-13T05:17:00.000+0100
2020-05-13 09:43:35.196 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_duration changed from NULL to 5
2020-05-13 09:43:35.231 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_start changed from NULL to 2020-05-13T04:29:00.000+0100
2020-05-13 09:43:35.237 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_end changed from NULL to 2020-05-13T05:13:00.000+0100
2020-05-13 09:43:35.238 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_start changed from NULL to UNDEF
2020-05-13 09:43:35.248 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_spring changed from NULL to 2020-03-20T03:51:00.000+0000
2020-05-13 09:43:35.256 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eclipse_ring changed from NULL to 2020-06-21T07:41:00.000+0100
2020-05-13 09:43:35.257 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_end changed from NULL to 2020-05-13T21:02:00.000+0100
2020-05-13 09:43:35.260 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_start changed from NULL to 2020-05-13T21:46:00.000+0100
2020-05-13 09:43:35.263 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_duration changed from NULL to 62
2020-05-13 09:43:35.287 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_start changed from NULL to 2020-05-13T21:02:00.000+0100
2020-05-13 09:43:35.289 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_duration changed from NULL to 940
2020-05-13 09:43:35.291 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_end changed from NULL to UNDEF
2020-05-13 09:43:35.294 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_duration changed from NULL to UNDEF
2020-05-13 09:43:35.303 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_duration changed from NULL to UNDEF
2020-05-13 09:43:35.313 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_end changed from NULL to 2020-05-13T20:57:00.000+0100
2020-05-13 09:43:35.320 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_winter changed from NULL to 2020-12-21T10:04:00.000+0000
2020-05-13 09:43:35.486 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_end changed from NULL to 2020-05-13T04:29:00.000+0100
2020-05-13 09:43:35.487 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eclipse_partial changed from NULL to 2022-04-30T21:42:00.000+0100
2020-05-13 09:43:35.487 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_summer changed from NULL to 2020-06-20T22:45:00.000+0100
2020-05-13 09:43:35.488 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_start changed from NULL to 2020-05-13T22:48:00.000+0100
2020-05-13 09:43:35.488 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NULL to NIGHT
2020-05-13 09:43:35.489 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_start changed from NULL to 2020-05-13T05:13:00.000+0100
2020-05-13 09:43:35.489 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_duration changed from NULL to 44
2020-05-13 09:43:35.490 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_start changed from NULL to 2020-05-13T00:41:00.000+0100
2020-05-13 09:43:35.490 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_name changed from NULL to SPRING
2020-05-13 09:43:35.491 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eveningNight_end changed from NULL to UNDEF
2020-05-13 09:43:35.492 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_end changed from NULL to UNDEF
2020-05-13 09:43:35.493 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_duration changed from NULL to UNDEF
2020-05-13 09:43:35.493 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_autumn changed from NULL to 2020-09-22T14:32:00.000+0100
2020-05-13 09:43:35.494 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eveningNight_duration changed from NULL to UNDEF
2020-05-13 09:43:35.500 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_start changed from NULL to 2020-05-13T13:07:00.000+0100
2020-05-13 09:43:35.501 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_duration changed from NULL to UNDEF
```

and the restart at 12:23 (when the phase name was ok):

```
2020-05-13 12:12:22.071 [hingStatusInfoChangedEvent] - 'astro:sun:9fe96e5d' changed from UNINITIALIZED to INITIALIZING
2020-05-13 12:12:22.235 [hingStatusInfoChangedEvent] - 'astro:sun:9fe96e5d' changed from INITIALIZING to ONLINE
2020-05-13 12:12:23.221 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_duration changed from NULL to 4
2020-05-13 12:12:23.234 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_end changed from NULL to 2020-05-13T13:08:00.000+0100
2020-05-13 12:12:23.278 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_end changed from NULL to 2020-05-13T03:27:00.000+0100
2020-05-13 12:12:23.318 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eclipse_total changed from NULL to 2020-12-14T16:15:00.000+0000
2020-05-13 12:12:23.329 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_end changed from NULL to 2020-05-13T05:17:00.000+0100
2020-05-13 12:12:23.330 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_start changed from NULL to UNDEF
2020-05-13 12:12:23.331 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_end changed from NULL to 2020-05-13T22:48:00.000+0100
2020-05-13 12:12:23.331 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_end changed from NULL to UNDEF
2020-05-13 12:12:23.343 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_duration changed from NULL to 1
2020-05-13 12:12:23.349 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_duration changed from NULL to 44
2020-05-13 12:12:23.367 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_start changed from NULL to 2020-05-13T20:57:00.000+0100
2020-05-13 12:12:23.373 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_end changed from NULL to 2020-05-13T21:46:00.000+0100
2020-05-13 12:12:23.406 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_start changed from NULL to 2020-05-13T03:27:00.000+0100
2020-05-13 12:12:23.407 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eveningNight_start changed from NULL to UNDEF
2020-05-13 12:12:23.438 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_duration changed from NULL to 62
2020-05-13 12:12:23.455 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_start changed from NULL to 2020-05-13T05:17:00.000+0100
2020-05-13 12:12:23.470 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_duration changed from NULL to 5
2020-05-13 12:12:23.515 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_start changed from NULL to 2020-05-13T04:29:00.000+0100
2020-05-13 12:12:23.575 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_end changed from NULL to 2020-05-13T05:13:00.000+0100
2020-05-13 12:12:23.599 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_start changed from NULL to UNDEF
2020-05-13 12:12:23.612 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_spring changed from NULL to 2020-03-20T03:51:00.000+0000
2020-05-13 12:12:23.647 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eclipse_ring changed from NULL to 2020-06-21T07:41:00.000+0100
2020-05-13 12:12:23.693 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_end changed from NULL to 2020-05-13T21:02:00.000+0100
2020-05-13 12:12:23.781 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_start changed from NULL to 2020-05-13T21:46:00.000+0100
2020-05-13 12:12:23.781 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_duration changed from NULL to 62
2020-05-13 12:12:23.839 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_start changed from NULL to 2020-05-13T21:02:00.000+0100
2020-05-13 12:12:23.842 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_duration changed from NULL to 940
2020-05-13 12:12:23.850 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_end changed from NULL to UNDEF
2020-05-13 12:12:23.869 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_duration changed from NULL to UNDEF
2020-05-13 12:12:23.881 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_duration changed from NULL to UNDEF
2020-05-13 12:12:23.883 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_end changed from NULL to 2020-05-13T20:57:00.000+0100
2020-05-13 12:12:23.901 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_winter changed from NULL to 2020-12-21T10:04:00.000+0000
2020-05-13 12:12:24.138 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_end changed from NULL to 2020-05-13T04:29:00.000+0100
2020-05-13 12:12:24.139 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eclipse_partial changed from NULL to 2022-04-30T21:42:00.000+0100
2020-05-13 12:12:24.139 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_summer changed from NULL to 2020-06-20T22:45:00.000+0100
2020-05-13 12:12:24.140 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_start changed from NULL to 2020-05-13T22:48:00.000+0100
2020-05-13 12:12:24.150 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from NULL to DAYLIGHT
2020-05-13 12:12:24.150 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_start changed from NULL to 2020-05-13T05:13:00.000+0100
2020-05-13 12:12:24.151 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_duration changed from NULL to 44
2020-05-13 12:12:24.152 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_start changed from NULL to 2020-05-13T00:41:00.000+0100
2020-05-13 12:12:24.152 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_name changed from NULL to SPRING
2020-05-13 12:12:24.153 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eveningNight_end changed from NULL to UNDEF
2020-05-13 12:12:24.153 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_end changed from NULL to UNDEF
2020-05-13 12:12:24.154 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_duration changed from NULL to UNDEF
2020-05-13 12:12:24.154 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_duration changed from NULL to UNDEF
2020-05-13 12:12:24.162 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_start changed from NULL to 2020-05-13T13:07:00.000+0100
2020-05-13 12:12:24.174 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_season_autumn changed from NULL to 2020-09-22T14:32:00.000+0100
2020-05-13 12:12:24.189 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_eveningNight_duration changed from NULL to UNDEF
```

There were no issues the following day (14th May) 

The 13th May 2020 coincides with the last day of astronomical night for my lattitude, 53.524695. The 14th onwards has no night (Ref: https://www.timeanddate.com/sun/@53.524695,-2.4)

Another user had the same issue, at lattitude 53.47092 and the same issue at 53.989512 on May 12th.

The related forum topic is: https://community.openhab.org/t/astro-binding-phase-name-is-incorrect-night-when-it-should-be-daylight/98718

## Possible Solution

Unknown, but it seems tied to the last day of astronomical night and lattitude.

## Steps to Reproduce (for Bugs)

I've not attempted to reproduce this, but I want to see if I can reproduce it on a separate instance whilst adjusting the date / time.

## Context

I use the phase name for night / day transitions. I don't use the events, as IIRC these only trigger when openhab is running. A restart of openhab in the middle of the day would not set my "Night State" to OFF. I use phase name + a system started rule.

The impact was that lights were coming on in the middle of the day :)

## Your Environment

Hardware: Intel
OS: 18.04.4 LTS (Bionic Beaver)

Java Runtime Environment:
  openjdk version “1.8.0_232”
  OpenJDK Runtime Environment (Zulu 8.42.0.21-CA-linux32) (build 1.8.0_232-b18)
  OpenJDK Client VM (Zulu 8.42.0.21-CA-linux32) (build 25.232-b18, mixed mode)

  openHAB version: 2.5.4-1

**Comment by Dopeyr** [comment] 2020-05-14 19:33
As an addition, these are the full logs at 00:00:30 on 13th May, which is when I believe it sets all the times / event schedules for the current day:

```
2020-05-13 00:00:30.347 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_start changed from 2020-05-12T05:15:00.000+0100 to 2020-05-13T05:13:00.000+0100
2020-05-13 00:00:30.350 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_rise_end changed from 2020-05-12T05:19:00.000+0100 to 2020-05-13T05:17:00.000+0100
2020-05-13 00:00:30.352 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_start changed from 2020-05-12T20:56:00.000+0100 to 2020-05-13T20:57:00.000+0100
2020-05-13 00:00:30.356 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_end changed from 2020-05-12T21:00:00.000+0100 to 2020-05-13T21:02:00.000+0100
2020-05-13 00:00:30.358 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_set_duration changed from 4 to 5
2020-05-13 00:00:30.360 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_start changed from 2020-05-12T13:07:00.000+0100 to 2020-05-13T13:07:00.000+0100
2020-05-13 00:00:30.361 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_noon_end changed from 2020-05-12T13:08:00.000+0100 to 2020-05-13T13:08:00.000+0100
2020-05-13 00:00:30.364 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_night_start changed from 2020-05-13T00:41:00.000+0100 to UNDEF
2020-05-13 00:00:30.367 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_start changed from 2020-05-12T00:29:00.000+0100 to 2020-05-13T00:41:00.000+0100
2020-05-13 00:00:30.367 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_end changed from 2020-05-12T01:34:00.000+0100 to UNDEF
2020-05-13 00:00:30.369 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_morningNight_duration changed from 65 to UNDEF
2020-05-13 00:00:30.369 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_start changed from 2020-05-12T01:34:00.000+0100 to UNDEF
2020-05-13 00:00:30.370 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_end changed from 2020-05-12T03:29:00.000+0100 to 2020-05-13T03:27:00.000+0100
2020-05-13 00:00:30.370 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDawn_duration changed from 115 to UNDEF
2020-05-13 00:00:30.371 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_start changed from 2020-05-12T03:29:00.000+0100 to 2020-05-13T03:27:00.000+0100
2020-05-13 00:00:30.371 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDawn_end changed from 2020-05-12T04:31:00.000+0100 to 2020-05-13T04:29:00.000+0100
2020-05-13 00:00:30.373 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_start changed from 2020-05-12T04:31:00.000+0100 to 2020-05-13T04:29:00.000+0100
2020-05-13 00:00:30.377 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDawn_end changed from 2020-05-12T05:15:00.000+0100 to 2020-05-13T05:13:00.000+0100
2020-05-13 00:00:30.378 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_start changed from 2020-05-12T22:45:00.000+0100 to 2020-05-13T22:48:00.000+0100
2020-05-13 00:00:30.378 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_end changed from 2020-05-13T00:41:00.000+0100 to UNDEF
2020-05-13 00:00:30.379 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_astroDusk_duration changed from 116 to UNDEF
2020-05-13 00:00:30.380 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_start changed from 2020-05-12T21:44:00.000+0100 to 2020-05-13T21:46:00.000+0100
2020-05-13 00:00:30.380 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_end changed from 2020-05-12T22:45:00.000+0100 to 2020-05-13T22:48:00.000+0100
2020-05-13 00:00:30.381 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_nauticDusk_duration changed from 61 to 62
2020-05-13 00:00:30.382 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_start changed from 2020-05-12T21:00:00.000+0100 to 2020-05-13T21:02:00.000+0100
2020-05-13 00:00:30.382 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_civilDusk_end changed from 2020-05-12T21:44:00.000+0100 to 2020-05-13T21:46:00.000+0100
2020-05-13 00:00:30.384 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_start changed from 2020-05-12T05:19:00.000+0100 to 2020-05-13T05:17:00.000+0100
2020-05-13 00:00:30.385 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_end changed from 2020-05-12T20:56:00.000+0100 to 2020-05-13T20:57:00.000+0100
2020-05-13 00:00:30.387 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_daylight_duration changed from 937 to 940
2020-05-13 00:00:30.396 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from ASTRO_DUSK to ASTRO_DAWN
```

**Comment by lsiepel** [comment] 2022-12-23 18:11
This issue may have been fixed in the mean time as 19 PR's have been merged since may 146th 2020.
https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+in%3Atitle+astro+created%3A%3E2020-05-14+is%3Amerged+

Can you confirm if this is still an issue in 3.4.0 stable that was just released last week?

**Comment by Dopeyr** [comment] 2022-12-27 11:08
Hi, it happened again this year, but I was only on OH3.2 at the time, not OH3.3. 

I'm running on OH3.4 now, so I'll know in May, I still haven't been back to reproduce it artifically by adjusting the time :(

**Comment by lsiepel** [comment] 2022-12-27 19:25
> 00.004


I added a test. 
 ```
    @Test
    public void testIssue7642() {
        TimeZone tZone = TimeZone.getTimeZone("Europe/London");
        Calendar tDate = SunCalcTest.newCalendar(2020, Calendar.MAY, 13, 5, 17, 2,
                tZone);
        Calendar tDate2 = SunCalcTest.newCalendar(2020, Calendar.MAY, 13, 5, 17, 12, 
                tZone);

        Sun sun = sunCalc.getSunInfo(tDate, 53.47092, -2.4, 0.0, true);  
        Sun sun2 = sunCalc.getSunInfo(tDate2, 53.47092, -2.4, 0.0, true);

        assertEquals(SunPhaseName.NIGHT, sun.getPhase().getName());
        assertEquals(SunPhaseName.NIGHT, sun2.getPhase().getName());
    }
```

The first log from the OP shows:
```
2020-05-13 05:17:00.004 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from SUN_RISE to DAYLIGHT
2020-05-13 05:17:09.288 [vent.ItemStateChangedEvent] - astro_sun_9fe96e5d_phase_name changed from DAYLIGHT to NIGHT
```

So i set the dates to 2020-05-13 05:17:02 (i assume Europe/Londen timezone here) and 2020-05-13 05:17:12 for the second test.
I grabbed the lat/long from the link. (53.47092, -2.4) and assumed the height to 0.0.

Both tests succeed. So i cannot reproduce this. Or i might have the wrong parameters.

**Comment by lsiepel** [comment] 2022-12-27 22:15
Did find a test related bug, made some extra tests and a PR. But i cannot reproduce the problem you describe. Please check with me:

All tests in
Timezone: Europe/London
Lat/Lon/Alt: 53.47092, -2.4, 0.0
2020-05-13 05:12 => CIVIL_DAWN
2020-05-13 05:13 => SUN_RISE
2020-05-13 05:18 => DAYLIGHT

**Comment by Dopeyr** [comment] 2022-12-28 10:04
Hi @lsiepel, thanks for looking into this. This is what I have for the astro setings:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/5502915/209793892-dd44a190-c359-4f63-8088-8e9a04434953.png">

My lattitude is 53.524695 - I think things may have been confused when I mentioned 53.47092, as that is from a different user on the forum who had a similar problem on 12th of May. The problem I saw/see is at 53.524695 on the 13th of May.

Interestingly I don't have anything set under regional settings re: timezone, or any location settings, in case that makes a difference:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/5502915/209794715-c6488caf-820b-4d0f-8d5f-4c0d007e6a77.png">

The system timezone is set to Europe/London though.

Thanks, Andy.

**Comment by lsiepel** [comment] 2022-12-29 12:52
I can confirm something is wrong here.
Two files have been generated fopr 2020-05-12 and 2020-05-13
https://1drv.ms/u/s!AnMcxmvEeupwjp4B0Ny3WuBF82_8zA?e=vunLCa

The values seem weird. I also don;t understand the first 29 minutes of the 12th are null values.

**Comment by lsiepel** [comment] 2022-12-29 22:42
Note to self: test-case for the 12th of may is having a `null` value on the `Night` phase range end. To determine this end date, it looks to the `ASTRO_DAWN` of the next day (13th) and that is also null. That is possibly the root cause.

Also noticed that the binding is looking a day forward to check ranges that are overlapping the next dat. It does not do that for a day earlier, checking for a phase that has started the day before. This is i.m.h.o opinion a bug and is atleast causing the `null` values for the 12th of may between 00:00 and 00:29, will look at that later on.

**Comment by lsiepel** [comment] 2022-12-30 11:07
Narrowed it down to a call to `double w4 = getHourAngle(H3, phi, d);`  where d > H3 (constant 0.3141592653589793) and that should never happen. this returns a `NaN` and then other calculations go wrong.

**Comment by lsiepel** [comment] 2022-12-30 23:14
Pff. that was a tough one. Just fixed it. There were some different results between normal and debug test runs causing a lot of fuzz. Anyway, it came down to a sorting issue. 
Tests with the parameters you give failed earlier, but after the sort fix, they succeed.

**Closed** 2022-12-31 14:04 UTC

**Comment by Dopeyr** [comment] 2022-12-31 16:28
Thanks @lsiepel for your hard work on this :)
