### ISSUE TITLE
[wemo] Add support for Wemo Dimmers

### ISSUE THREAD

**Issue by MrFusion42** [openhab/openhab-addons#4808] opened 2019-02-05 12:07 UTC
## Expected Behavior
[Wemo dimmers](https://www.belkin.com/us/p/P-F7C059/) should be discoverable by the Wemo binding.

## Current Behavior
Wemo dimmers are not discovered, while other wemo devices are discovered correctly.

## Context
The dimmers can be turned on/off, brightness adjusted, and have a long-press action

## Your Environment
* Version used: openhab 2.4.0 with latest Wemo binding
* Operating System: OpenHABian 2.4.0-1 on a Raspberry Pi 3 B+

**Comment by hmerk** [comment] 2019-02-10 21:22
This is a duplicate of 
https://github.com/eclipse/smarthome/issues/3632
There is already a test version but I did not find time to finish it
https://community.openhab.org/t/wemo-dimmer-switch-not-auto-detected/29690/37

**Closed** 2019-11-19 16:28 UTC
Labels: duplicate
